### ISSUE TITLE
I can't do nothing in kali linux 

### ISSUE THREAD

**Issue by EinsteinJr9** [rapid7/metasploit-framework#10075]
Firstly i dont know how github works, i just know that it is a good site. But ok

I have installed kali linux by a virtual box. 
And i dont know where to start.. I HAVE A LOT OF ISSUES
i dont have metasploit, PostgreSQL etc, or im too dumb that i cant even find them
But lets start -> **"How can i install metasploit?"**

**Comment by bcoles** [comment]
Metasploit should come pre-installed on Kali. You can run `msfconsole` to start Metasploit.

**Comment by EinsteinJr9** [comment]
Was the first thing that I did but " bash: msfconsole: command not found" apears

**Comment by bcoles** [comment]
That's strange. Perhaps check `/usr/bin/msfconsole` or `/usr/share/metasploit-framework`.

Regardless, this isn't the right place to ask. It would best to ask Kali support as your issue is with the Kali environment and/or Kali packages. Alternatively, drop by #metasploit on Freenode IRC, or the Metasploit Slack channel.
