### ISSUE TITLE
Feature request: IOS < 10.3.3 webkit exploit

### ISSUE THREAD

**Issue by TheBrokenWasp** [rapid7/metasploit-framework#10214]
There is already a PoC on github: https://github.com/MTJailed/MSF-Webkit-10.3
I can't get it to actually give me a meterpreter session but it does give me the "pwned" message.

**Comment by bcoles** [comment]
It is a denial of service exploit. It will not give you a meterpreter session.

**Comment by TheBrokenWasp** [comment]
oh... well, I guess that sucks but it can still be added as an exploit, right?

**Comment by timwr** [comment]
It's non-obvious (to me anyway) how to turn the proof of concept crash in https://github.com/MTJailed/MSF-Webkit-10.3 into a read/write memory primitive or shellcode execution.
I'd love to be proven otherwise if you have more links/writeups/pocs for it.
You're more than welcome to open a pull request with an auxiliary/dos module based on it though.
