### ISSUE TITLE
Feature Request - In-memory elf execution

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#10301]
Found this a few weeks ago and thought that it would be some cool additions to Metasploit's functionality 

- https://magisterquis.github.io/2018/03/31/in-memory-only-elf-execution.html

It's written in perl but not perl dependent. I'm probably not the best to try to attempt integrating this but I bet there are Nix people out there that would jump at this.

**Comment by mubix** [comment]
I see this being really useful for local exploit execution where compiling might not be possible or steal is something that would be nice to have. As well as maybe a lazy loader for web_delivery, or a shell script generator that would write linux/meterpreter into memory from a `.sh` like we have for `sct` and powershell files.

**Comment by wvu-r7** [comment]
This has been on my want-to-do list for a bit! I'm sure @busterb and @acammack-r7 would love to work on it, too.

**Comment by wvu-r7** [comment]
Here's another: https://0x00sec.org/t/super-stealthy-droppers/3715. Also have been toying with https://github.com/XiphosResearch/netelf.

**Comment by acammack-r7** [comment]
It also just occurred to me while talking with @wvu-r7 that since the libc on Linux boxes is also going to be static and PIE, we can invoke it directly and pass in the executable we want to run (possibly with modified shellcode to set up a more plausible initial stack). In fact, if my reading of the `musl` source is right[1], we can even load our own remote binaries in memory to pass them to `ld-linux.so` in addition to being able to pass a file name.

[1] Other implementations on Linux presumable have the same capabilities since they all work, `musl` is just easier to read. https://git.musl-libc.org/cgit/musl/tree/ldso/dynlink.c#n1498

**Comment by fsacer** [comment]
something dropped for this https://github.com/fbkcs/msf-elf-in-memory-execution

**Comment by bcoles** [comment]
Blog post associated with the above repo: https://blog.fbkcs.ru/en/elf-in-memory-execution/

**Comment by acammack-r7** [comment]
`mettle` uses `libreflect` now to work correctly with `execute -m` now, so I think this can be closed. The results of my research can be seen in https://blog.rapid7.com/2019/01/03/santas-elfs-running-linux-executables-without-execve/. Thanks for the push @mubix!
