### ISSUE TITLE
ms17_010_eternalblue_win8 problems

### ISSUE THREAD

**Issue by chick0n** [rapid7/metasploit-framework#10310]
I get this error:

```
[*] Started bind handler
[*] shellcode size: 1255
[*] numGroomConn: 13
[-] Exploit aborted due to failure: unknown: Module exited abnormally
[*] Exploit completed, but no session was created.
```

framework.log says:
`socket.error: [Errno Connection error (*.*.*.*:445)] [Errno 110] Connection timed out`

I use socks5 proxy in metasploit.

other modules connect flawlessly to port 445 over socks5.

thanks

**Comment by acammack-r7** [comment]
@chick0n if Metasploit is giving you that error, there should be a Python traceback in `framework.log` (maybe split up over several log messages) with messages starting `Unexpected output running <PATH TO MODULE>` . Can you post it? Also, how are you connecting the module to the proxy?

**Comment by 3tternp** [comment]
I too got this issue here is my output 
[*] Started reverse TCP handler on xx.xx.xx.xx:4444 
[*] shellcode size: 1221
[*] numGroomConn: 13
[*] Target OS: Windows 10 Pro 10240
[-] Exploit aborted due to failure: unknown: Module exited abnormally
[*] Exploit completed, but no session was created.

**Comment by acammack-r7** [comment]
@wvu-r7 looks like we'll have to add an `except:` block to the module since people keep running into this.

@3tternp can you paste more of the traceback in `framework.log` (it might be split up) so we can be sure we handle the error in the right place? I think I know where this is happening, but I would like to check.

**Comment by wvu-r7** [comment]
I've gotten other connection errors, too. Might be a good idea to wrap everything until we pin down what we need. I'm also noticing that `RPORT` does nothing. I've fixed this in the upcoming PR.

**Comment by rootz491** [comment]
i'm stucked with same problem and is it deadend, means is there's no solution till date ?

[*] Started reverse TCP handler on 192.168.43.48:4444 
[-] Module dependencies (impacket) missing, cannot continue
[-] Exploit aborted due to failure: unknown: Module exited abnormally
[*] Exploit completed, but no session was created.

if  there any solution to this please refer me there!

Before this, i had one more error that said 

msf5 > info exploit/windows/smb/ms17_010_eternalblue_win8
[-] Invalid module: exploit/windows/smb/ms17_010_eternalblue_win8

but then i found fix by @kal1s post, that is , replacing the exploit by his python2 edited version.
after doing that, i was atleast responding like "info exploit/windows/smb/ms17_010_eternalblue_win8" 
and "use exploit/windows/smb/ms17_010_eternalblue_win8 "

but by the time i ran it, it didn't woked :-1: 

please community help ASAP 


SYSTEM 
Linux parrot 4.14.0-parrot13-amd64 #1 SMP Parrot 4.14.13-1parrot13 (2018-01-21) x86_64 GNU/Linux


msfconsole -v
Framework Version: 5.0.98-dev

**Comment by daweedkob** [comment]
[-] Module dependencies (impacket) missing, cannot continue
[-] Exploit aborted due to failure: unknown: Module exited abnormally
I am having the same error while exploiting (exploit/windows/smb/ms17_010_eternalblue_win8).
I changed Dockerfile but error still remains.
I installed metasploit from package on Mac OS. What Can I do to fix it? Help me please.
