### ISSUE TITLE
AUTORUNSCRIPT multi_console_command doesn't work anymore after update

### ISSUE THREAD

**Issue by meiraxx** [rapid7/metasploit-framework#10408]
I built a .rc file with normal instructions such as "run killav" and other commands and it used to work when I did set AUTORUNSCRIPT multi_console_command -rc /root/autoruncommands.rc

It doesn't work anymore. The file has 1 command per line, the usual syntax. Can someone verify this?

Error: 
[-] Unknown command: /root/autoruncommands.rc.

**Comment by wvu-r7** [comment]
Show us some screenshots or console output.

**Comment by sn0wfa11** [comment]
There was a change a while back where switches for meterpreter scripts could only contain one character after the "-". The usage of this script was changed from `-rc` to just `-r` in PR #8802. Try it this way:

`set AUTORUNSCRIPT multi_console_command -r /root/autoruncommands.rc`

However, it is better to use post/multi/manage/multi_post instead of multi_console_command as such:

`set AutoRunScript post/multi/manage/multi_post MACRO=/root/autoruncommands.rc`
