### ISSUE TITLE
Writing post module.

### ISSUE THREAD

**Issue by Roganced** [rapid7/metasploit-framework#10445]
I trying to write a simple module for metasploit, and i have questions for this.
Above all i need to prevent run this module again. I decided to copy hwid in text document on my computer (at the end of the first run) And check later: if hwid exists on txt? - Do nothing. Otherwise - continue.

How i get hwid? I try use machine_id['Machine ID'] but it isn't work. And what libraries should i load for this?

**Comment by jmartin-r7** [comment]
When using a module preventing the user for executing the same module twice for a single target is not really a common.  However to support this you could store a note or loot about on the host and check for that before executing.

Are you looking to ensure it does not run multiple times on the same session or on the same target?  If just the session then consider basing on the session guid, if for the host the machineId is likely unique enough.  In most cases the module that stored the value is tagged to the data so you should be able to check for the value stored in data model.  I would also suggest instead of preventing execution you validate state when running the module and add an option to override so the user can decide if a module needs to be run again on a host/session.

**Comment by Roganced** [comment]
Thanks for you answer. But i can't follow your advice, because i don't plan create any files on hdd. It must be a resident module. I want upload lazagne with dll injections, into memory, without touching the hdd.
So, to prevent starting twice i can use note only on my machine. Since it should be in automatic method - i decided use machine id, for verification.

**Comment by jmartin-r7** [comment]
My recommendation is to store as a note to loot, these are retained in the database on the console, not in the target.  By `on the host` I am referring the to the database `host` object that metasploit tracks and reports on when you call the `hosts` command in the `msfconsole`.  

https://github.com/rapid7/metasploit-framework/blob/943629b3548933a1ffa772765526e991169191ed/lib/msf/core/db_manager/note.rb#L52-L77

**Comment by Roganced** [comment]
Can I make it easier?
I want to use:
`hwid = ::File.read(::File.join(Msf::Config.data_directory, 'hwidlists','hwidlist.txt')).strip`  
(If hwid is not found in this list, continue working. If found, terminate)

How i get hwid from session and put it into hwidlist.txt? (To store hwid at the first run)
