### ISSUE TITLE
Necessity of OS detection of reverse shell session

### ISSUE THREAD

**Issue by WangYihang** [rapid7/metasploit-framework#10513]
#### Idea
As is known to all metasploit users, reverse shell session just provide a bare tcp/udp communication
I think it would be more convience in pentesting if metasploit can detect the OS version of remote machine
I open this issue to ask if it's necessary to add a command to detect remote os version

#### Goals
1. add a meta shell command like `detect_os`
2. the `detect_os` command is able to detect the remote os version, it's `linux` `macos` or `windows`, even the destribution name of `linux` os

#### How
I think the input of reverse shell is idempotent, so we can execute commands a lot of times, that allows we to run a wrong command(like: `uname -a` on windows machine, the command execution will failed, but it won't crash the reverse shell session)
so, we can run commands on the reverse shell session and analysis the output of these command, then we can know the specific os version.

#### References
#10382 #10389 #10146

**Comment by sempervictus** [comment]
This is a deeper hole than it may seem:
A shell session is a printable char IO stream atop a transport like TCP. The source of these is often a runtime like php or java, and that is the platform assigned to the payload/session handler which is inferred by MSF. Since those runtimes can be and are isolated quite often you end up with a lot less common surface. You could check for the existence of /sys and guess you're probably on windows if its missing, but enumeration of sysfs is a mess and noisy as all hell. This is where higher level payloads with native bindings to the runtime come in - sigar and meterp do a pretty good job with this in native bindings.
Its all noise however, all visible on HIDS if they're looking...

**Comment by wvu-r7** [comment]
#10146 is also related. Remember our discussion there? :)

**Comment by ccondon-r7** [comment]
Closing this for now because it's been so long since it was active and #10146 seems like a better forum for discussing usability fixes. That said, we can reopen if needed!
