### ISSUE TITLE
Shellcode cannot find kernel32 because of AVG 

### ISSUE THREAD

**Issue by PhantomCloak** [rapid7/metasploit-framework#10839]
reverse tcp shellcode gets kernel32 address through peb so method gets  3 rd module's base address but in this situation AVG uses a simpel trick to avoid shellcodes situation is avast puts aswhookx.dll to 3 rd entry 
question is only way is modify shellcode manualy ?

-AVG Enabled
FullDllName is C:\Users\USER\Desktop\LoadLibShellCode.exe
BaseAddress is 190000
FullDllName is C:\Windows\SYSTEM32\ntdll.dll
BaseAddress is 77420000
FullDllName is C:\Program Files\AVG\Antivirus\aswhookx.dll <-- 3rd Entry shellcode gets aswhookx.dll addres instead of kernel32.dll
BaseAddress is 6b9f0000
FullDllName is C:\Windows\system32\kernel32.dll 
BaseAddress is 75800000
FullDllName is C:\Windows\system32\KERNELBASE.dll
BaseAddress is 755e0000

-AVG Disabled
FullDllName is C:\Users\USER\Desktop\LoadLibShellCode.exe
BaseAddress is b50000
FullDllName is C:\Windows\SYSTEM32\ntdll.dll
BaseAddress is 77420000
FullDllName is C:\Windows\system32\kernel32.dll <-- 3rd Entry in normal conditions
BaseAddress is 75800000
FullDllName is C:\Windows\system32\KERNELBASE.dll
BaseAddress is 755e0000

**Comment by bwatters-r7** [comment]
That's pretty tricky...  I like it.
To answer your question, no; I do not think there's another way to edit the shellcode other than manually.  I'd be curious to know if this breaks anything that is legitimate....

**Comment by OJ** [comment]
So it's worth mentioning here that the order of DLL loading isn't what's significant. The windows-based stagers, including [reverse_tcp](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/reverse_tcp.rb) makes use of the Block API (written by Stephen Fewer, included as both [x86](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/block_api.rb) and [x64](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/x64/block_api.rb) versions in MSF).

As you can see from the [code](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/block_api.rb#L59-L75), the block API doesn't rely on the order of the DLL loading. In order to invoke the functions that are required, a simple has is used to identify the combination of dll name/function name (this avoids the use of strings in stagers, for obvious reasons). The hash is passed to the block API, and at runtime, the code iterates over all the DLLs that are loaded, and all the exported functions, looking for a dll name/function name combination that matches the hash that was given to it.

So without really diving in any further, my guess is that the `aswhookx.dll` may just contain one or more functions that have names specifically designed to clash with important things like `GetProcAddress` and `LoadLibrary`. Given how simple the hashing scheme is in the block API, it's not really hard to generate a colliding string. I would think that AVG is inserting the DLL there so that its own functions get checked before the real ones in the other libraries do, resulting in the block API invoking functions in the wrong DLL.

Cute problem though! Off the top of my head I'm not sure how you'd get around that. Need to put some thought into it.
