### ISSUE TITLE
Obfuscation an Executable

### ISSUE THREAD

**Issue by ibrahimsadek** [rapid7/metasploit-framework#10849]
## Steps to reproduce

I am trying to obfuscate a simple executable file generated by a c++ script as described below:

#include <iostream>    // Needed to perform IO operations
using namespace std;
 
int main() {                        // Program entry point
   cout << "hello, world" << endl;  // Say Hello
   return 0;                        // Terminate main()
}

- To generate an executable I run following command:

> g++ -Wall -W script.cpp -lm -o script.elf

- To obfuscate the executable I use following command:

> msfvenom -p - -x script.elf -a x64 --platform linux -k -e x86/shikata_ga_nai -i 10 -f elf -o scriptEncoded.elf

When I display the assembler contents of the formal executable and the obfuscated one I don't see any change;

- To display the assembler contents I run following commands:

> objdump -d script.elf >> script.txt

> objdump -d scriptEncoded.elf >> scriptEncoded.txt 

To check the difference between the two contents:

> diffuse script.txt scriptEncoded.txt

Can you assist me to see where is the problem ? or how can I get an obfuscated executable where the assembler contents is different from the formal executable ? In a different way, How can I check that both executable files are not the same ?

### Metasploit version

Framework: 4.17.18-dev-
Console  : 4.17.18-dev-

### I installed Metasploit with:

- Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS

What OS are you running Metasploit on?

Kali Linux

**Comment by wchen-r7** [comment]
Hi,

You may want to consider using the Metasploit::Framework::Compiler API in order to generate a randomized executable for Windows. This API is based on Metasm and supports EXE and DLL. To use it, it's really simple:

```
Metasploit::Framework::Compiler::Windows.compile_c_to_file('/tmp/test.exe', c_template)
```

In your Metasploit repository, there is also a tool called `random_compile_c.rb`. You can use that to compile source, too.

To check how unique the randomness is, either you can diff the checksums, or you can open IDA Pro and manually inspect the binaries. Every time it compiles, it should look very different.
