### ISSUE TITLE
Meterpreter, windows, hide from ids.

### ISSUE THREAD

**Issue by Koraman** [rapid7/metasploit-framework#11122]
Hello, i need to hide meterpreter traffic from ids. 
1) What will be better: meterpreter/reverse_https (with my certificate) or meterpreter/reverse_tcp_rc4?
2) If ids have a certificate, сan it decrypt meterpreter_https?
3) Reverse_tcp_rc4 encrypts traffic or only stager?

Thank you!

**Comment by pussinboots1992** [comment]
A reverse HTTPS payload will evade IDS if it isn't doing any SSL interception. You will probably have more issues evading the proxy though. A custom encoder/encryptor or chaining encoders is a good way to avoid IDS / proxies / AV.

**Comment by Sonya2010** [comment]
> A reverse HTTPS payload will evade IDS if it isn't doing any SSL interception. 
If we assume the worst case scenerio, so that IDS/IPS will intercept SSL traffic, then which way do have to follow in order to avoid that.  It would be very good and I really will be very grateful if you share any real life example or point out to the source of it.

**Comment by pussinboots1992** [comment]
Try chaining encoders for the stager and second stage or using a custom encoder is the best way. The hardest thing to bypass from my experience is the Anti-virus, not the IDS. If your payload isn't being caught by a good AV I doubt an IDS will catch it...try modifying the decoder stubs too.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by OJ** [comment]
Best option here is to use stageless payloads if you can.

**Comment by Sonya2010** [comment]
@pussinboots1992 Oppositely and interestingly the hardest thing on my side, judging by experience, is evading IPS/IDS rather than AV. The thing I do to bypass AV(Namely NOrton 360) is generate the encoded raw shellcode(stageless windows/meterpreter_reverse_tcp) embed it into simple C program and let it run, doing it that way Norton360 deep sonar can not detect it for hours that its a malicious file and let it run, on the other hand since shellcode is synchronous IDS/IPS of norton immediately catches the connection and blocks it, it even specifies that its Meterpreter Reverse Tcp connection.  

> Best option here is to use stageless payloads if you can.
@OJ Sure I can use the stageless payload and this what I have done, I also find this tentatively because it made me think that, the less you communicate with meterpreter client/server the less are the chances you are being spotted by IPS/IDS. But no matter what I do I still get busted, Can you point me out to what I have delve into to resolve it?

**Comment by Sonya2010** [comment]
@pussinboots1992 thanks for the shared information, I generally use stageless payload , so I don't bother with encoding the stages, I encode it once and its in final *.exe, *.hta etc.. 

>You can also try to recompile the metsrv.dll, modify it slightly. Make sure to add useragents, add cookies.

Can you give more detailed information on that one, what is the purpose of adding cookies and user agents, you mentioned that to make it more realistic, but how am I supposed to make that?  Can we do it with MSF intrinsic methods, auxiliary modules ? 

>If a stageless payload if getting busted, I doubt it's the IDS. Can you at least run sysinfo before it dies ?

No I can not run sysinfo, it doesn't even executed, I'm pretty much confused here but it seems and yields that you are right, it is not IDS probably.

**Comment by pussinboots1992** [comment]
Modifying the metsrv.dll will not help with stageless payloads...So you can scrap that one if you plan on only using stageless payloads. The cookies and user-agents are important at the proxy level. If your handler is listening externaly and the payload has to get out of the corporate network via the IDS/Proxy etc...The proxy might be setup in a way which requires authentication, or it might filter on user-agents or require specific cookies to allow the traffic out. You will also need to get the reputation right on your handler, check it on symantecs/bluecoats site, proxies might reject connection to your handler because it is not classified. As explained if the sysinfo command isn't getting through, I really doubt it is the IDS. You can set cookies, user-agents and much more in the advanced options. Both on the msfvenom and handler side.
