### ISSUE TITLE
Stageless dll.

### ISSUE THREAD

**Issue by Koraman** [rapid7/metasploit-framework#11170]
Please, add stageless dll.

**Comment by jmartin-r7** [comment]
A `dll` is often not executable without a wrapper to provide the process space.  A `stageless payload` is one that can execute without another provided stage making a `dll` somewhat difficult to consider stageless. Here is a fairly detailed explanation of what stageless payloads need to consist of.

https://blog.rapid7.com/2015/03/25/stageless-meterpreter-payloads/

How would you envision a `stageless dll` to structured?  What scenarios might it be used for specifically for?

**Comment by Koraman** [comment]
I can create a dropper, which puts my dll and load it with rundll.exe or LoadLibrary api. It can be useful if we or target have a bad connection.
The theoretical principle of exploatation may be similar to stager dll.

**Comment by OJ** [comment]
I initially thought that this wouldn't be too hard to quickly whip up, but I'm going to have to spend a bit more time on it.

@Koraman the reason that it's not as easy for DLLs compared to EXEs is the fact that with DLLs you can't do excessive amounts of work in `DllMain`. `DllMain` needs to remain lean so that when the DLL loads things work as expected. One of two approaches are used when complexity is required on startup:

1. In `DLL_PROCESS_ATTACH` a thread is created to do the complex stuff.
1. After `DLL_PROCESS_ATTACH` an exported function is invoked directly (which may or may not run stuff on another thread).

The current DLL templates we have in place have a pre-determined amount of space to write the payload to which avoids the problem for us, and the patching of the DLL is done by replacing a pattern with the payload we have (assuming it's small enough to fit). However, this obviously puts a limitation on the space.

To solve this problem properly we'd need to make some changes that would allow us to do what we do with EXE files (ie. on the fly add a new section that's big enough to fit the payload regardless of its size) but avoid patching the entry point. This would mean the template would need to be updated so that it's smart enough to locate an execute the payload when required (either via `CreateThread` or via an exported function).

I hope that makes sense. I intend to fix this very soon, as a stageless DLL is something I have wanted for a while as well.

**Comment by Koraman** [comment]
@OJ Thank you for your answer. Good luck!
