### ISSUE TITLE
How to build meterpreter which inludes only the screenshot functioning 

### ISSUE THREAD

**Issue by Sonya2010** [rapid7/metasploit-framework#11323]
As the topic title depicts, how can achhieve such a goal as to create meterpreter which only takes screenshot? Even it is better, if it performs ascynchronous sending of images back to attacker. 

The premise behind of that is that: most of the AVs are metasploit - phobic anything or any subtle hint of metsrv.dll , stdapi.dll etc.. constants causes the AVs to block the activity of executable, with that way I'll try to strip down to minimalistic executable which servers that purpose. Your guidance will be appreciated.

**Comment by busterb** [comment]
That is a tricky question, because the way that Meterpreter makes a screenshot requires a lot of the infrastructure that you're trying to avoid. It starts by looking for a process that is actually connected to the desktop, and injects code into that process. The screenshot is taken, then the 'child' process sends data back to meterpreter, which then sends it back to metasploit framework.

For reference, the code that handles the high-level logic is here: https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/extensions/stdapi/server/ui/desktop.c

The actual screenshot code that gets injected is here: https://github.com/rapid7/metasploit-payloads/tree/master/c/meterpreter/source/screenshot

If you can live without the automatic injection logic and just want to build a standalone payload that tries to take a screenshot (but might fail depending on where it lands), the second link will probably be your best bet. Thanks.
