### ISSUE TITLE
Msfconsole  could not find...

### ISSUE THREAD

**Issue by wr3nch3** [rapid7/metasploit-framework#11391]
Metasploit framework ./msfconsole error pls help 
Could not find cookiejar-0.3.3 in any of the sources          Run `bundle install` to install missing gems.

**Comment by busterb** [comment]
Hi, if you are setting up a development environment, make sure you follow the instructions here: https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

Otherwise if you just want to use Metasploit, it's usually easier to simply use one of our installers: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
