### ISSUE TITLE
why meterpreter session has died everytime ?

### ISSUE THREAD

**Issue by AntaressX** [rapid7/metasploit-framework#11428]
Hi, there

OS - KALI
VER - new

I'm clueless on this issue, why meterpreter session has died everytime?

when i start run payload nothing happens, and I'm checking if my port is open and yes its open, when i check my port meterpreter says ; 

[*] Sending stage (70653 bytes) to 88.198.46.51
[*]  - Meterpreter session 1 closed.  Reason: Died
[*] Meterpreter session 1 opened (127.0.0.1 -> 127.0.0.1) at 2019-02-17 15:06:07 -0500

after all any commands is not working

i used fatrat for android and i tried it android ver:6.0.1 and 9 pie same problem everytime but its working on my local network

Appreciate your help. ^_^

**Comment by h00die** [comment]
You have given us zero details to help with this.
1) you didn't say what version of metasploit you are using
2) you didn't show us how your listener was set up
3) you didn't show us how your payload was created
4) you didn't sanitize your German victim's IP, which I'd assume you are authorized to pentest.................
5) you're most likely using some kind of port forwarding based on the 3rd line, but didn't give us any details on how that was set up.
6) If you find a BUG in metasploit, post here. If you find a bug with fatrat try here: https://github.com/Screetsec/TheFatRat
7) if you are looking for help because you are learning, aren't sure what you are doing, or anything else other than you clearly identified a bug, you should ask in the appropriate place like IRC, or slack with details on getting connect to those here: https://metasploit.help.rapid7.com/docs/getting-support
