### ISSUE TITLE
Errors from exploit: exploit/unix/webapp/wp_total_cache_exec.rb

### ISSUE THREAD

**Issue by dsx12** [rapid7/metasploit-framework#11739]
After attempting to run this exploit on my website running wordpress msf5 outputs this error:

[*] Started reverse TCP handler on 10.0.0.21:8080
[-] Exploit aborted due to failure: no-target: /wp-login.php does not seeem to be Wordpress site
[*] Exploit completed, but no session was created.

Wondering why it is giving me this error? I've tried using strings containing different  directories in the targeturi variable and still to no avail. Does anyone have any idea what's going wrong here?

**Comment by bcoles** [comment]
Metasploit expects `TARGETURI` to be `The base path to the wordpress application`, ie, `/path/to/wordpress/`, rather than a file path, ie `/wp-login.php`.

>  does not seem to be Wordpress site

This means that Metasploit could not detect WordPress using the various fingerprinting techniques in the `wordpress_and_online?` method in the WordPress mixin.

It is possible that the target website may have modified HTML and/or modified HTML template.

If you're certain that you've specified the correct `TARGETURI`, and you're certain that the remote host is WordPress, you can disable the check with:

```
set WPCHECK false
```

If this doesn't work, I suggest debugging with:

```
set HttpTrace true
```

This will allow you to see the raw HTTP requests and responses, which may offer some insight.

**Comment by dsx12** [comment]
set WPCHECK false worked!

Thanks so much this taught me a fair amount of knowledge @bcoles !

**Comment by dsx12** [comment]
[*] Started reverse TCP handler on 99.120.34.76:443 [*] Trying unauthenticated exploitation... [*] Trying to get posts from feed... [*] Nothing found. Trying to brute force a valid POST ID...

I recieve this output above^ is there anyway to get around this? by setting the posts manually without authentication ?

**Comment by bcoles** [comment]
Have you tried `set POSTID` ?

**Comment by wvu-r7** [comment]
Original question answered. Hope you found your post ID.
