### ISSUE TITLE
oats_weblogic_console exploit module

### ISSUE THREAD

**Issue by syriusbughunt** [rapid7/metasploit-framework#11849]
I am very happy to see this exploit module; This one will be very useful on some of our pentesting duties :) I am always getting the same error message while trying to run this exploit module:

msf5 exploit(multi/http/oats_weblogic_console) > run

[*] Started reverse TCP handler on 192.168.1.103:4444
[+] Logged in as weblogic:weblogic
[*] Ready for war. Codename "heather" at 6256 bytes
[-] Exploit aborted due to failure: unknown: Unable to find recordLink
[+] Successfully undeployed heather.war
[*] Exploit completed, but no session was created.

Any help would be very appreciated,

Thanks

**Comment by bcoles** [comment]
The `oats_weblogic_console` module has not yet been merged. It probably has not been tested thoroughly.

It would be best to post on the open PR: #11846 - I'm sure @wchen-r7 would be happy to know of any bugs before the module is merged into Metasploit.

---

The `Unable to find recordLink` error is throw in the following code block from the `get_deploy_frsc` method:

```
    html = res.get_html_document
    record_link = html.at('a[@id="recordLink"]')
    fail_with(Failure::Unknown, 'Unable to find recordLink') unless record_link
```

This implies that a HTML anchor `a` with `id=recordLink` was not found.

Prior to running the module, if you `set VERBOSE true` and `set HttpTrace true`, Metasploit will print the HTTP response from the server. You can then manually inspect the HTTP response in an attempt to locate the `recordLink`. This might offer some insight into the issue. ie, is the appropriate anchor present? Is the `id` case sensitive? Did something go horribly wrong (HTTP 500) ?

**Comment by wchen-r7** [comment]
What @bcoles said is exactly what I need to debug the problem. Thank you. Also, could you please provide more information about your environment? Version of software for example. I actually built this module specifically for Oracle Application Testing Suite. Not sure if that is related.

**Comment by wchen-r7** [comment]
I made some changes to the code. Instead of checking the `recordLink` tag for the value I need (which extracts the JS code from the `onClick` attribute), I'm grabbing it from a hidden input, which makes parsing less complicated. Let me know if that works better. Honestly I kind of suspect you're hitting a different page, but if you could provide the HTML response, maybe that would help. Thanks.

**Comment by syriusbughunt** [comment]
Just added the updated module and now I am getting the following output:

[*] Started reverse TCP handler on 192.168.1.103:4444
[+] Logged in as weblogic:weblogic
[*] Ready for war. Codename "tina" at 6253 bytes
[-] Exploit failed: NoMethodError undefined method `attributes' for nil:NilClass
[*] Exploit completed, but no session was created.

The Weblogic version is 10.3.0.0. Let me know if you need any more information.

Thanks

**Comment by wchen-r7** [comment]
Hmm ok. So that looks like you're really hitting a completely different page. I'll try to set up a weblogic server (and not something that integrates weblogic), and then see if I can reproduce it. But for now, you can only treat the module as an exploit that targets Oracle Application Testing Suite. Sorry for the limited capabilities.

**Comment by syriusbughunt** [comment]
Awesome, thanks @wchen-r7, very appreciated for your support :)

**Comment by wvu-r7** [comment]
Carry on conversation there! Thanks!
