### ISSUE TITLE
Capturing unicode characters inside meterpreter

### ISSUE THREAD

**Issue by ahm3dhany** [rapid7/metasploit-framework#11994]
Is there a way to capture Unicode characters (e.g. arabic, hebrew) using keystrokes capturing inside a gained meterpreter other than mapping these keystrokes to the pre-known  language after dumping the keystrokes?

**Comment by timwr** [comment]
Just a guess, perhaps it's because the keylogger (assuming you're talking about Windows meterpreter) is unaware of the keyboard layout:
https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/extensions/stdapi/server/ui/keyboard.c#L560
Perhaps we can do something like this:
https://github.com/SherifEldeeb/UniLogger
