### ISSUE TITLE
Opening browser fails 

### ISSUE THREAD

**Issue by hkerma** [rapid7/metasploit-framework#12113]
Hi, 
I'm completly new at contributing to Metasploit, but I'd like to help. I run Firefox as a default browser, and I'm trying to open some markdown documentation on specific modules (with `info -d`).

When I'm using a root account, it fails and tells `Running root without --no-sandbox is unsupported.` and I understand that, as it tries to open the doc with Chromium.

So, I wanted to modify the browser-opening code, in order to open the documentation with my default browser which is Firefox.

My issue is that I can't find the /lib/rex/compat.rb which is supposed to contain the function `open_webrtc_browser()`. I can't find it either on the Git and on my installation, I really don't understand :/

Thanks a lot for your help !

## Steps to reproduce

1. Open msfconsole as root
2. Reach a module (i.e `use auxiliary/scanners/ftp/ftp_login`)
3. Try `info -d`.

## Expected behavior

I don't know the real expected behavior, but I'd like to open with my default browser, and not with Chromium (which causes issue in this case).

## Current behavior

Got an error `Running root without --no-sandbox is unsupported.`

### Metasploit version

Version 5.0.37-dev
 
### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Running the last Kali Linux amd64 architecture.

**Comment by bcoles** [comment]
Rex is a Ruby library (gem); `Compat` is a module within the gem:

* https://github.com/rapid7/rex/blob/master/lib/rex/compat.rb

**Comment by PingouinRF** [comment]
OK now that makes sense, thanks a lot.

After taking a look at the code, I wonder why does the documentation tries to open with Chromium, because my sensible browser is Firefox, and xdg-open *.html also opens with Firefox :/

I've read that the way Kali installs packages causes troubles with RubyGems installations, could it be linked with my issue ?

Thx for your quick reply !

**Comment by bcoles** [comment]
> I've read that the way Kali installs packages causes troubles with RubyGems installations, could it be linked with my issue ?

That causes a lot of problems, but I doubt it is related.

> After taking a look at the code, I wonder why does the documentation tries to open with Chromium, because my sensible browser is Firefox, and xdg-open *.html also opens with Firefox :/

The `open_webrtc_browser` method opens programs in the following order. You're correct in that `firefox` should be executed first. Perhaps the `firefox` executable is not in your `$PATH` ?

```ruby
    if defined? ENV['PATH']
      ['firefox', 'google-chrome', 'chrome', 'chromium', 'firefox', 'opera'].each do |browser|
        ENV['PATH'].split(':').each do |path|
          browser_path = "#{path}/#{browser}"
          if File.exists?(browser_path)
            args = (browser_path =~ /Chrome/) ? "--allow-file-access-from-files" : ""
            system("#{browser_path} #{args} #{url} &")
            found_browser = true
            break
          end
        end
      end
    end
```

**Comment by PingouinRF** [comment]
`which firefox`returns `/usr/bin/firefox` and `/usr/bin` is in PATH. I tried to figure out which one of the `compat.rb` is called, as I have two installs of this RubyGem (one in `/var/lib/gems` and another in `/usr/lib/ruby`).

I tried to run your code, it opens firefox but keep on telling me that "Running root without -no-sandbox is unsupported" which is a Chromium error o.o

I'll investigate and hopefully come back with answers. Thx for your help anyway !

**Comment by PingouinRF** [comment]
Hi again,
Now I really don't understand

I tried `gem uninstall rex` and deleted the rex directory in `/usr/lib/ruby/vendor_ruby`. I expected msf not to be able to run `info -d` as it wouldn't find compat.rb anymore. 
But it ran anyway, and still opens the doc with Chromium.

Does someone knows where does msfconsole get the rex module, and therefore compat.rb script (because compat.rb isn't in the msf/rex directory) ?

If i could find the script from where msfconsole run the `Rex::Compat.open_webrtc_browser()` it would be a huge step :(

**Comment by h00die** [comment]
Being tracked in `rex-core`, but no PR was ever submitted :(
