### ISSUE TITLE
Wrong OS detected: Windows Server 2016 instead of 2019

### ISSUE THREAD

**Issue by phra** [rapid7/metasploit-framework#12112]
## Steps to reproduce

How'd you do it?

1. `c:\users\public>systeminfo`
```
systeminfo

...
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
```

2. `sysinfo`
```
meterpreter > sysinfo
Computer        : ...
OS              : Windows 2016 (Build 17763).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
```

## Expected behavior

Windows 2019 is detected

## Current behavior

Windows 2016 is detected

### Metasploit version

5.0.37-dev

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

**Comment by bwatters-r7** [comment]
Well, crud.  
At first check this appears to be  a bug in meterpreter's `add_windows_os_version` contained in the file `c/meterpreter/source/extensions/stdapi/server/sys/config/config.c` (in the windows c meterpreter).

I think the offending snippet is:
```
		else if (v.dwMajorVersion == 10)
		{
			if (v.dwMinorVersion == 0)
			{
				osName = v.wProductType == VER_NT_WORKSTATION ? "Windows 10" : "Windows 2016";
			}
		}
```
That assumes any major version of a server release is 2016....  I am sure this worked great a few years ago, so I can't fault them.  Usually the major version coordinates with a "named" release, but that's not how they do it, anymore.

Unfortunately, I am not entirely sure the best way to go about fixing this.....  We'll be doing whack-a-mole if we start using build numbers as code, and even more, Windows has stopped using the year as the delineation, but rather the release code.  Let me dig into this today and see if I can come up with something.  I also want to check the way the over meterpreters figure out the OS.

**Comment by bwatters-r7** [comment]
OK, so after some digging, this is because historically Windows changes product names in association with a bump to the major or minor version number.  Windows 2016 _and_ 2019 both have 10.0 as the major.minor release values.  I think the best option is to just change the OS name for server releases to "Windows 2016 or above" and give the major/minor release in addition to the build number like we do now.

This is probably the best bet, as Microsoft seems to be Transitioning from named server releases, anyway.   I have a Windows 2019 Server with the same build version as a Windows Server 1809, so we can see Microsoft is not particularly attached to the server names meaning anything, anymore.

**Comment by phra** [comment]
it would be nice to replicate the output of `sysinfo`.

**Comment by bwatters-r7** [comment]
I do not know where that string lives.  I do not see it in any of the documented system information functions here https://docs.microsoft.com/en-us/windows/win32/sysinfo/system-information-functions.
