### ISSUE TITLE
android.intent.action.VIEW problem

### ISSUE THREAD

**Issue by X1nto** [rapid7/metasploit-framework#12163]
## Steps to reproduce

1. I opened a session in meterpreter
2. While downloading files from a "hacked" device, i.e i do webcam_snap, it should prompt me to choose how to open a file (via gallery app or file explorer) it doesn't, instead it gives me this error:

Starting: Intent { act=android.intent.action.VIEW dat=/data/data/com.termux/files/home/OZHXPeSz.jpeg } Error: Activity not started, unknown error code -1

I have tested two "hacked" devices, one was running android 4.4.4 and the other android 7.1.2

## Expected behavior

I've seen that for others it opens a "open with" window on android, so i think my should too.

## Current behavior

Instead i got error message, and i should move files directly from termux's directory to /sdcard

### Metasploit version

5.0.37-dev

### I installed Metasploit with:

I used Tool-X for termux, also tested with git download and pkg install but problem still presists

### OS

Android 7.1.2

**Comment by bcoles** [comment]
If I understand the issue correctly, the bug is that captured data (screenshot, webcam snap) is correctly downloaded, but cannot be viewed via Metasploit.

The downloaded file is saved as `<rand>.jpeg`.

https://github.com/rapid7/metasploit-framework/blob/e29711661b6cc8e7ef229b8d34476f7c8477b661/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/webcam.rb#L75

The android library uses the same `Rex::Compat.open_file` functionality as used elsewhere in the framework to open files.

https://github.com/rapid7/metasploit-framework/blob/e29711661b6cc8e7ef229b8d34476f7c8477b661/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/webcam.rb#L117-L126

`Rex::Compat.open_file` simply calls `open_browser` to handle all files, with the file name as a URL:

```ruby
def self.open_file(url='')
  case RUBY_PLATFORM
  when /cygwin/
    path = self.cygwin_to_win32(url)
    system(["cmd", "cmd"], "/c", "explorer", path)
  else
    self.open_browser(url)
  end
end
```

`open_browser` contains platform independent code to launch the specified file URL:

```ruby
def self.open_browser(url='http://google.com/')
  case RUBY_PLATFORM
  when /cygwin/
    if(url[0,1] == "/")
      self.open_file(url)
    end
    return if not @@loaded_win32api
    Win32API.new("shell32.dll", "ShellExecute", ["PPPPPL"], "L").call(nil, "open", url, nil, nil, 0)
  when /mswin32|mingw/
    return if not @@loaded_win32api
    Win32API.new("shell32.dll", "ShellExecute", ["PPPPPL"], "L").call(nil, "open", url, nil, nil, 0)
  when /darwin/
    system("open #{url}")
  when /android/
    system("am start --user 0 -a android.intent.action.VIEW -d #{url}")
  else
    # Search through the PATH variable (if it exists) and chose a browser
    # We are making an assumption about the nature of "PATH" so tread lightly
    if defined? ENV['PATH']
      # "xdg-open" is more general than "sensible-browser" and can be useful for lots of
      # file types -- text files, pcaps, or URLs. It's nearly always
      # going to use the application the user is expecting. If we're not
      # on something Debian-based, fall back to likely browsers.
      ['xdg-open', 'sensible-browser', 'firefox', 'firefox-bin', 'opera', 'konqueror', 'chromium-browser'].each do |browser|
        ENV['PATH'].split(':').each do |path|
          # Does the browser exists?
          if File.exist?("#{path}/#{browser}")
            system("#{browser} #{url} &")
            return
          end
        end
      end
    end
  end
end
```

The relevant code for Android is:

```ruby
system("am start --user 0 -a android.intent.action.VIEW -d #{url}")
```


* I'm not sure why `--user 0` is specified.
* Perhaps there's no default handler for `.jpeg` file URLs (seems unlikely, but maybe it can only handle `.jpg` ?).
* Perhaps file urls need a `file:///` scheme (this seems more likely).

For what it is worth, there are only two Google results for `"am start" "-a android.intent.action.VIEW -d file:///data"`. And both of these are false positives matches, matching "data" on `<data that you want to pass>`.

There are significantly more Google results for `"am start" "-a android.intent.action.VIEW -d file:///data"`. This strongly implies that `file:///` is the correct approach for opening local files.

This is probably a bug (especially as the `confirmed` label has been applied). However, Termux is not a supported platform and this issue has been open for over 30 months with no details / follow up / logs. It is unlikely that anyone is going to look into this.

I've submitted a simple patch (https://github.com/rapid7/rex-core/pull/26) to `lib/rex/compat.rb` based on this assumption that gets the job done:

```ruby
  when /android/
    url = "file://#{url}" if url.to_s.start_with?('/')
    system("am start --user 0 -a android.intent.action.VIEW -d #{url}")
```

While Android is not a supported platform for Metasploit, technically the Rex libraries are supposed to be cross-platform.
