### ISSUE TITLE
Remote Data Services / WebServices (services command) errors out

### ISSUE THREAD

**Issue by cathedrall** [rapid7/metasploit-framework#12184]
It appears that when you have two msf instances communicating over a remote data service, the `services` command bombs out. 

On the client (which performed `db_nmap -A -O -v scanme.nmap.org`):
```
msf5 > hosts

Hosts
=====

address       mac  name             os_name  os_flavor  os_sp  purpose  info  comments
-------       ---  ----             -------  ---------  -----  -------  ----  --------
45.33.32.156       scanme.nmap.org  Linux                      server         

msf5 > services
[-] Error while running command services: undefined method `address' for nil:NilClass

Call stack:
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:786:in `block (2 levels) in cmd_services'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:770:in `each'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:770:in `block in cmd_services'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2130:in `block in each_host_range_chunk'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each_host_range_chunk'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:765:in `cmd_services'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'
/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/local/bin/msfconsole:49:in `<main>'
msf5 > version
Framework: 5.0.40-dev-cbe4771d29
Console  : 5.0.40-dev-cbe4771d29
msf5 > ruby -v
[*] exec: ruby -v

ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
msf5 > db_status
[*] Connected to remote_data_service: (https://team:5443). Connection type: http. Connection name: JaUbUVQ1.
msf5 > 
```
On the server, which received the scan results from the client over the remote data session:
```
msf5 > hosts

Hosts
=====

address       mac  name             os_name  os_flavor  os_sp  purpose  info  comments
-------       ---  ----             -------  ---------  -----  -------  ----  --------
45.33.32.156       scanme.nmap.org  Linux                      server         

msf5 > services
Services
========

host          port   proto  name        state  info
----          ----   -----  ----        -----  ----
45.33.32.156  22     tcp    ssh         open   OpenSSH 6.6.1p1 Ubuntu 2ubuntu2.13 Ubuntu Linux; protocol 2.0
45.33.32.156  80     tcp    http        open   Apache httpd 2.4.7 (Ubuntu)
45.33.32.156  9929   tcp    nping-echo  open   Nping echo
45.33.32.156  31337  tcp    tcpwrapped  open   

msf5 > version 
Framework: 5.0.40-dev-
Console  : 5.0.40-dev-
msf5 > ruby -v
[*] exec: ruby -v

ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
msf5 > db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
msf5 > 
```
This happens regardless of which system does the scanning. 

## Expected behavior

`services` command returns scanned services for particular host. 

## Current behavior

`services` errors out with:
```
[-] Error while running command services: undefined method `address' for nil:NilClass

Call stack:
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:786:in `block (2 levels) in cmd_services'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:770:in `each'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:770:in `block in cmd_services'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2130:in `block in each_host_range_chunk'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each_host_range_chunk'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:765:in `cmd_services'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'
/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/local/bin/msfconsole:49:in `<main>'
```

I should add that if I disconnect the client system from the webservice and scan again, everything works as expected. Only when I'm using the remote data service does the `services` command bomb out. 

There's nothing related in either systems `~/.msf4/logs/framework.log`

### Metasploit version
Client:
```
Framework: 5.0.40-dev-cbe4771d29
Console  : 5.0.40-dev-cbe4771d29
msf5 > ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
```

Server:
```
Framework: 5.0.40-dev-
Console  : 5.0.40-dev-
msf5 > ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
```
### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (please specify ruby version)

### OS
Client: Archlinux - `5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux`
Server: Ubuntu 16.04 LTS - `4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jgor** [comment]
I'm experiencing the same issue with a shared remote data service. I reproduced it in the latest master yesterday and tried tracking it down a bit but I'm out of my depth with irb so it's slow going. I appear to be seeing similar data objects returned for the service for the client connected to localhost:5443 (which succeeds) and the client connected remotely to another service via hostname:5443 (which gets the above stack trace) when querying services, but by the time it gets to lib/msf/ui/console/command_dispatcher/db.rb:788 the host attribute of service is nil in the latter.

My first problem is I'm not sure if I'm using this correctly since it's my first attempt at it. Is it the case that two clients with their own local postgres connection but connected to the same webservice on 5443 should be able to share services results? Or are both clients additionally supposed to share the same postgres connection?

If the webservice is supposed to be enough, what I'm seeing is json_to_mdm_object() in lib/metasploit/framework/data_service/remote/http/response_data_helper.rb is calling to_ar() twice per service requested: once for a Mdm::Service object and once for a Mdm::Host object, processing json objects e.g.:

Client connected to remote webservice, crashes:
`[09/14/2020 21:55:06] [d(0)] core: {:id=>1488, :host_id=>66, :created_at=>"2020-09-11T17:14:56.000Z", :port=>81, :proto=>"tcp", :state=>"open", :name=>"", :updated_at=>"2020-09-11T17:14:56.000Z", :info=>"", :host=>{:id=>66, :created_at=>"2020-09-11T16:50:55.000Z", :address=>"10.10.10.42", :mac=>"", :comm=>"", :name=>"10.10.10.42", :state=>"alive", :os_name=>"Unknown", :os_flavor=>"", :os_sp=>"", :os_lang=>"", :arch=>nil, :workspace_id=>1, :updated_at=>"2020-09-11T17:47:51.121Z", :purpose=>"device", :info=>nil, :comments=>nil, :scope=>nil, :virtual_host=>nil, :note_count=>2, :vuln_count=>0, :service_count=>647, :host_detail_count=>0, :exploit_attempt_count=>0, :cred_count=>0, :detected_arch=>nil, :os_family=>nil}}`
`[09/14/2020 21:55:06] [d(0)] core: {:id=>66, :created_at=>"2020-09-11T16:50:55.000Z", :address=>"10.10.10.42", :mac=>"", :comm=>"", :name=>"10.10.10.42", :state=>"alive", :os_name=>"Unknown", :os_flavor=>"", :os_sp=>"", :os_lang=>"", :arch=>nil, :workspace_id=>1, :updated_at=>"2020-09-11T17:47:51.121Z", :purpose=>"device", :info=>nil, :comments=>nil, :scope=>nil, :virtual_host=>nil, :note_count=>2, :vuln_count=>0, :service_count=>647, :host_detail_count=>0, :exploit_attempt_count=>0, :cred_count=>0, :detected_arch=>nil, :os_family=>nil}`

Client connected to local webservice, succeeds:
`[09/14/2020 21:55:45] [d(0)] core: {:id=>1, :host_id=>1, :created_at=>"2020-09-15T02:46:30.317Z", :port=>81, :proto=>"tcp", :state=>"open", :name=>nil, :updated_at=>"2020-09-15T02:46:30.317Z", :info=>"", :host=>{:id=>1, :created_at=>"2020-09-15T02:46:00.833Z", :address=>"10.10.10.42", :mac=>nil, :comm=>"", :name=>nil, :state=>"alive", :os_name=>"Unknown", :os_flavor=>nil, :os_sp=>nil, :os_lang=>nil, :arch=>nil, :workspace_id=>1, :updated_at=>"2020-09-15T02:46:30.329Z", :purpose=>"device", :info=>nil, :comments=>nil, :scope=>nil, :virtual_host=>nil, :note_count=>0, :vuln_count=>0, :service_count=>1, :host_detail_count=>0, :exploit_attempt_count=>0, :cred_count=>0, :detected_arch=>nil, :os_family=>nil}}`
`[09/14/2020 21:55:45] [d(0)] core: {:id=>1, :created_at=>"2020-09-15T02:46:00.833Z", :address=>"10.10.10.42", :mac=>nil, :comm=>"", :name=>nil, :state=>"alive", :os_name=>"Unknown", :os_flavor=>nil, :os_sp=>nil, :os_lang=>nil, :arch=>nil, :workspace_id=>1, :updated_at=>"2020-09-15T02:46:30.329Z", :purpose=>"device", :info=>nil, :comments=>nil, :scope=>nil, :virtual_host=>nil, :note_count=>0, :vuln_count=>0, :service_count=>1, :host_detail_count=>0, :exploit_attempt_count=>0, :cred_count=>0, :detected_arch=>nil, :os_family=>nil}`

Those are results from two different databases that I just added the same ip and port to, but they look to be comparable. I'm just throwing debug logs in various places in the code hoping to spot discrepancies. I'll keep plugging away at it but if someone with more familiarity wants to jump in it might be quick to at least spot the discrepancy in what's being returned.
