### ISSUE TITLE
Errno::ECONNRESET Connection reset by peer

### ISSUE THREAD

**Issue by Huan2gao** [rapid7/metasploit-framework#12298]
hello, im testing this exploit locally on my system on window Server 2008. Don't know why it giving such error. Pls help me out
thanks
![Screenshot from 2019-09-09 05-25-26](https://user-images.githubusercontent.com/48352033/64519866-f48ed300-d2c2-11e9-9200-a558b7c12986.png)

**Comment by keisentraut** [comment]
The hardcoded value of GROOMBASE for VirtualBox value was wrong for me, too when eploiting Win7 SP1 Build 7601 on Virtualbox 6.0 with Win10 host. I didn't understand the exploit in detail, but I think GROOMBASE simply needs to be the start address of the NonPagedPool. I found this address by dumping the memory with ```VBoxManage``` and then running ```rekall``` as suggested by [KevTheHermit on Twitter](https://twitter.com/KevTheHermit/status/1170399843841388549). Please see [my blog](https://klaus.hohenpoelz.de/playing-with-the-bluekeep-metasploit-module.html) for details how I did it.

I had to reduce GROOMSIZE from the default of 250 to 50, too. I think the reason was that my VM had kind of limited RAM (2GB) assigned and 250 MB of grooming is too much, therefore the connection is reset before the actual exploit is triggered.

**Comment by OJ** [comment]
@keisentraut Please don't spray your message across multiple issues. Thanks.

**Comment by OJ** [comment]
@Huan2gao please refer to the original bluekeep PR for discussion.

**Comment by AoG22** [comment]
you solved it ?
