### ISSUE TITLE
I Can't Run ./msfconsole  

### ISSUE THREAD

**Issue by CoolCyclo** [rapid7/metasploit-framework#12319]
## Steps to reproduce

I Run ./msfconsole at the terminal but doesn't work. it says zsh: no such file or directory: ./msfconsole

## Expected behavior

What should happen?

## Current behavior

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:

- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS
OSX High Sierra

**Comment by busterb** [comment]
Running './msfconsole' would only work if the command was in your current working directory. This is basic Linux stuff. If you type `which msfconsole` you should be able to see where it is installed. Since you're using `zsh` you may need to modify your PATH to include `/usr/local/bin`, if you're using the commercial installed based on what you checked above.
