### ISSUE TITLE
about server/smb !

### ISSUE THREAD

**Issue by youssrii** [rapid7/metasploit-framework#12335]
lets say that i have a meterpreter session up and running on a windows server out of my local network.. how can i capture those hashes !
in the srvhost should i put the windows server internal ip or just left it on 0.0.0.0?

**Comment by h00die** [comment]
If you are unable to do something like `hashdump` or the associated module, you would set the srvhost to the the metasploit box. Once the server is running, you then need to initiate a connection from the meterpretered box to the metasploit box via smb.
When I get around to making docs, or someone else does, I'll make sure this use case is included.

**Comment by youssrii** [comment]
you then need to initiate a connection from the meterpretered box to the metasploit box via smb.
how can that be done?
thanks in advance

**Comment by h00die** [comment]
Try googling how to create an smb connection. Here is one of the first results I got.
https://superuser.com/questions/52220/how-do-i-connect-to-a-network-share-via-the-windows-command-prompt

Socket error is most likely due to permissions or the port being in use already.

I don't believe this is a Metasploit issue, just a 'how to metasploit', so ticket will be closed. Any further questions please join the slack group, or use it.

**Comment by youssrii** [comment]
just like that ! u confused me lmao 
and about the error i think the auxiliary crash.. the port is not in use
thanks anyway

**Comment by bcoles** [comment]
#12341
