### ISSUE TITLE
capture/smb

### ISSUE THREAD

**Issue by youssrii** [rapid7/metasploit-framework#12341]
lets say that i have a meterpreter session up and running on a windows server **out of my local network**.. how can i capture those hashes using capture/smb !

**Comment by h00die** [comment]
The basic way to do it is you would start the capture/smb aux module on the metasploit box. Then you'd set a tunnel for 445 from the meterpreter box back to your own box.

However, since Windows is undoubtedly already listening on port 445, you would need to stop it from doing so.  This, I've never tried (either killing SMB, which i'd think would reboot the box... or setting SMB to listen on one interface like localhost so you can set the forward through on the main interface... which seems like it may have VERY adverse effects in a corporate environment).

I'm upgrading infrastructure in my lab, but once that is done I plan to make some capture/smb docs.  I'll see what I can come up with for this.

**Comment by youssrii** [comment]
u told me that i have to set a initial connection between the meterpretred box and my kali machine.
so what i did.. i set a route to that server machine from my metasploit session then i set a sock4a server  and i was able to set a connection via proxychains and smbclient from my kali box to the windows server .
but i couldnt capture thoes hashes :confused:

**Comment by youssrii** [comment]
u told me that i have to set a initial connection between the meterpretred box and my kali machine.
so what i did.. i set a route to that server machine from my meterpreter session then i set a sock4a server and i was able to set a connection via proxychains and smbclient from my kali box to the windows server .
but i couldnt capture thoes hashes ;/

**Comment by youssrii** [comment]
i also tried to connect u on slack.. i left couple of msg

**Comment by h00die** [comment]
While the docs are not finished (haven't done the website vector, or running a fake server through a meterpreter), the VERY BASICS have been documented in my repo. 
https://github.com/h00die/metasploit-framework/blob/smb_docs/documentation/modules/auxiliary/server/capture/smb.md

Once I get some more time to add in additional scenarios and documentation, I'll put up a PR to the framework, but in the meantime, this should answer some of your questions.

**Comment by youssrii** [comment]
i'will see what i can do.. thanks

**Comment by youssrii** [comment]
u can do a hashdump through the meterpreter session on windows xp machine and u get those hashes easily. (like u said before)
let me explain the scenario again..like i said i have a meterpreter session up and running on domain admin account on windows server 2008 which happened to be the domain controller (the windows server is not on my local network) that's the problem.
and for some reasons when i dump those hashes and try to login to this machines via auxiliary smb_login it did'nt work for some of them. (windows 10 machines).
so what i wanna do is capture those specific hashes of those specific users on those specific machines via auxiliary capture/smb when they join the server shares; so i can pivot to those machines too using psexe or winrm if its enabled.
did i miss something?

**Comment by h00die** [comment]
`smb_login` may only be SMBv1 (untested), and windows 10 by default has smbv1 turned off.  Could be your issue.
Maybe you should try a tool like bloodhound to see if the creds you have are valid vice a protocol issue.

**Comment by h00die** [comment]
Other than that, your problem is that you don't have code execution on those win10 boxes, thus you can't make them connect to your `capture/smb`.  *IF* they are on the domain, you could make a new login script to map a drive to your server from those hosts.  When the user logs in again, it would propagate and force their connection to you.   However, as noted, Win10 has SMBv1 turned OFF by default, and `capture/smb` only works on SMBv1.

The only other way I can think would be to kill smb on the interface, and tunnel the connections through meterp back to `capture/smb`.  This is reckless as hell and will undoubtedly cause network issues.  Plus anything w/o SMBv1 would just fail anyways.

**Comment by youssrii** [comment]
actually there is one win 10 box i can login into.. so automaticlly the smbv1 is enabled on this box! BUT when i try to pivot to this box using psexe with creds i get access denied!! one more thing i wanna ask about, when i use psexe exploit did it inject the payload in memory or disk? because defender is up and running by default on win 10.
if not, any idea !

**Comment by youssrii** [comment]
thank you for your time and effort in advance
