### ISSUE TITLE
I get an error on synflood run.

### ISSUE THREAD

**Issue by onurMarkY** [rapid7/metasploit-framework#12346]
I get an error on synflood run.
Error:
[-] Auxiliary failed: RuntimeError Pcarub error : eth0 : no IPv4 address assigned.

When I run ifconfig on my Metasploitable 2. It sows me IP 192.168.56.105.
I am using virtula box

_Originally posted by @Souvika in https://github.com/rapid7/metasploit-framework/issues/7264#issuecomment-533562836_

**Comment by h00die** [comment]
can you do a `show options` and post it, this will help.

**Comment by Souvika** [comment]
This issue was fixed by setting the INTERFACE to eth1. But there is another issue. I am running synflood from my Kali to Metasploitable2 (both are on host only network) but Kali is unable to sending packets to Metasploitable. 

![image](https://user-images.githubusercontent.com/55590431/65401505-1772ba00-dd8e-11e9-82e0-4fe5b073f0a7.png)
