### ISSUE TITLE
msfconsole: Operation failed:740

### ISSUE THREAD

**Issue by komron01** [rapid7/metasploit-framework#12383]
## Steps to reproduce

How'd you do it?

using exploit/psexec

I actually can connect to the target via Administator privileges and there is a meterpreter session with the target. So I just uploaded few files and expect to run them on the target machine. 
msf>Upload /sdcard/1/myfile.exe
msf>pwd
C:\1
msf>ls
myfile.exe
msf>execute -s 1 -f myfile.exe
Operation failed: 740

**Comment by bwatters-r7** [comment]
Interesting.  What user are you?  You said that you're administrator, but MSDN cites Windows error code 740 as:
```
ERROR_ELEVATION_REQUIRED

740 (0x2E4)

The requested operation requires elevation.

```
https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-

Please double check the permissions you have.  It may be you are an "administrator" but still are getting trapped because you are not system.  Try elevating with `getsystem` first.

If that does not work, I'd love to know more about what that file is doing, if you are willing to share.
