### ISSUE TITLE
Inheriting Faraday error

### ISSUE THREAD

**Issue by karelbyte** [rapid7/metasploit-framework#12645]
Hello friends, when I start the ms console, I get this error, can you give me some suggestion that it could be?
**NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.**

**Comment by francisuk1989** [comment]
I have the same error message from upgrading from 5.0.60-dev  to 5.0.63-dev using msfupdate methord
I am currently using ubuntu 18.04.3 lts (bionic beaver) x64

> turkey@stuffingxps ~ $ msfconsole
> NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
> Faraday::Error::ClientError.inherited called from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
> [-] Error while running command db_connect: Failed to connect to the HTTP data service: Data Service does not appear to be responding
> 
> Call stack:
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2067:in `rescue in db_connect_http'
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2062:in `db_connect_http'
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1832:in `cmd_db_connect'
> /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
> /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
> /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
> /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:252:in `block in load_db_config'
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:239:in `each_pair'
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:239:in `load_db_config'
> /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:133:in `initialize'
> /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
> /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
> /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
> /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
> /opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'
> Traceback (most recent call last):ork console...-
>         28: from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'
>         27: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
>         26: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
>         25: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
>         24: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
>         23: from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:161:in `initialize'
>         22: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
>         21: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
>         20: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
>         19: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
>         18: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
>         17: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
>         16: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:133:in `load_modules'
>         15: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:133:in `each'
>         14: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:135:in `block in load_modules'
>         13: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:256:in `load_modules'
>         12: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:256:in `each'
>         11: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:259:in `block in load_modules'
>         10: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:109:in `recalculate'
>          9: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:109:in `each_pair'
>          8: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:122:in `block in recalculate'
>          7: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:122:in `each_pair'
>          6: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:186:in `block (2 levels) in recalculate'
>          5: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload.rb:212:in `size'
>          4: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload/windows/encrypted_reverse_tcp.rb:66:in `generate'
>          3: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload/windows/encrypted_reverse_tcp.rb:177:in `get_compiled_shellcode'
>          2: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/compiler/mingw.rb:15:in `compile_c'
>          1: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/compiler/mingw.rb:27:in `build_cmd'
> /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/compiler/mingw.rb:27:in `write': Permission denied @ rb_sysopen - /opt/metasploit-framework/embedded/framework/reverse_pic_stager.c (Errno::EACCES)

**Comment by bcoles** [comment]
> NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0

This is a warning, rather than an error. For now, it can be safely ignored. Eventually, it should be resolved by the Metasploit team, before migrating Faraday to version 1.0.

**Comment by Moron-bit** [comment]
dont know how much this would help but i was messing around today with the "msfdb init" command to start the msf web service on my android

i ended up with "bundle update"(which updated faraday to 0.17.0) by mistake 

and also did "bundle clean --force"(which removed faraday 0.15.4) 

it also removed "rack 2.0.7" gem for it to work and it acutally did worked 
but it screwed other stuff as "bundle clean --force" removed system gems 

and messed up my beef installation hehe, 

after that i tried to minimize damages, and when i tried msfconsole this came up:

NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
[-] Error while running command db_connect: Failed to connect to the HTTP data service: Data Service does not appear to be responding

so i only did "apt uninstall metasploit" which doesnt remove all of metasploit, after that did "apt install metasploit" with out removing the new faraday 0.17.0 gem, the faraday note was gone but i still had that: 

"[-] Error while running command db_connect: Failed to connect to the HTTP data service: Data Service does not appear to be responding" 

so i tried "msfdb delete" and it did delete the msf web service files but the :

"[-] Error while running command db_connect: Failed to connect to the HTTP data service: Data Service does not appear to be responding"

was still there after a little digging i ended up with doing this:

i ran "msfconsole" with the error and did "db_connect -l" to view the databases and services

i immediately noticed the "HTTP data service"

and deleted it with "db_delete HTTP data service"

exited the console and started it again and there were no erros :]

i hope this helps because i know termux isnt the same as linux.... good luck.

**Comment by bwatters-r7** [comment]
I believe this was fixed by https://github.com/rapid7/metasploit-framework/pull/12658
