### ISSUE TITLE
Install location issues

### ISSUE THREAD

**Issue by aloswoya** [rapid7/metasploit-framework#12716]
## Steps to reproduce
1. I get the .msi file to install
2. chage the install way，I change the default location C:\ to D:\
3.  However ,the metasploit homepath not in D:\，it's in F:\
and in cmd run:
F:\>msfconsole
F:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-core-0.1.13/lib/rex/compat.rb:376: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[-] ***
[-] * WARNING: No database support: No database YAML file
[-] ***

### I installed Metasploit with:
use windows  installer ：https://windows.metasploit.com/metasploitframework-latest.msi
### OS
Windows 10 17763

**Comment by TannerFilip** [comment]
I'm seeing this as well. I set the install path to C:\metasploit and it installed in D:\metasploit-framework. 

metasploit v5.0.67-dev-cd566846dd13143f283f1f1b713debd30d31d761

Version	10.0.19536 Build 19536

**Comment by Vishnu8808appu** [comment]
how to solve tis os : windows 10
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- expect (LoadError)

**Comment by Jack-ban** [comment]
I have same issus! @Vishnu8808appu

**Comment by eddyndumia** [comment]
Try reinstalling with admin rights @Vishnu8808appu

**Comment by k3d4ns** [comment]
Same issue here ,any news?

**Comment by eddyndumia** [comment]
@k3d4ns  Not yet. I instaled Linux instead.It comes with Metasploit Pre-installed!😊😊😁

**Comment by k3d4ns** [comment]
# Solved this way :
It's a warning line in file (Win32API.rb)

Open your metasploit install directory and search for the file (Win32API.rb) 
*i'm writing from my phone so i can't give you the full file path*

Now edit the file with any editor (np++, vscode..) and you'll fine a warning command before the require command 
Like this:
warn "Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead", uplevel: 2
Put # before (warn) to turn it into a comment line instead of a warning command line
So it'll be like that : 
#warn "Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead", uplevel: 2
 Save and try again 
The file is here :
https://github.com/ruby/ruby/blob/master/ext/win32/lib/Win32API.rb

**Comment by Reelix** [comment]
@k3d4ns Commenting out an issue instead of fixing it is terrible practice...

**Comment by Scrambled-Egg** [comment]
Just comment out the line: warn "Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead", uplevel: 2 in Win32API.rb file

**Comment by aloswoya** [comment]
Scrambled-Egg <notifications@github.com>于2020年10月6日 周二14:33写道：

**Comment by gumara** [comment]
I solving by disable windows defender

**Comment by Faokun1** [comment]
FUCK

**Comment by Reelix** [comment]
> FUCK

I take it by this response that this is still an issue 4 years later? :p

**Comment by LiNuX-Mallu** [comment]
Found any solution guys?
