### ISSUE TITLE
Metasploit is not detecting newly imported perl exploit

### ISSUE THREAD

**Issue by rowname** [rapid7/metasploit-framework#12825]
Metasploit is not detecting newly imported perl exploit

 I download a exploit 1244.pl 

 have placed it under the directory /.msf4/modules/exploits/webapp/php and made it executable. Then I ran the command updatedb.

In my locally placed exploit-database it was under the directory exploits/webapp/php 

Before adding and after adding the new one it should have got increased, but it remained the same. It does not detect the new one.

I have also tried running msfupdate, I thought updating the whole framework could change something. But its all the same.

Version 

I'm running metasploit v5.0.68-dev

I have installed with kali linux

VM

Thanks for help.

**Comment by h00die** [comment]
Metasploit accepts several module languages, Ruby, python and golang coMe to mind. Perl, is not one of them (although msf was originally written in Perl...)
Next, you'd need to tell us where that Perl file came from, assuming it's from edb, that is simply an exploit and not written as a metasploit module. Even if it was the right language, because it wasn't written as a metasploit module, msf would have no idea what to do with it.
Lastly, just try to use the exploit? There is no msf equivalent, although nmap does have a script to exploit this.

**Comment by rowname** [comment]
Thanks for your comment h00die

Yes, the file is from edb and nmap show me the vulnerability by phpMyAdmin grab_globals.lib.php (1244.pl)

I really don't know how to use it alone or how to use it with nmap. I am totally new, but eager to learn

If you can help me I thank you

**Comment by bcoles** [comment]
> 
> 
> Thanks for your comment h00die
> 
> Yes, the file is from edb and nmap show me the vulnerability by phpMyAdmin grab_globals.lib.php (1244.pl)
> 
> I really don't know how to use it alone or how to use it with nmap. I am totally new, but eager to learn
> 
> If you can help me I thank you

Exploit [1244](https://www.exploit-db.com/exploits/1244) is a Perl script. Perl scripts can be executed using the Perl interpreter. On most UNIX systems, the Perl interpreter is `perl`.

It will not work with Metasploit. It will not work with Nmap.

**Comment by rowname** [comment]
Thanks for your comment bcoles...

So I can use the exploit whit perl. 

Can you recommend a tutorial on how to do it?

Thanks.

**Comment by bcoles** [comment]
> 
> 
> Thanks for your comment bcoles...
> 
> So I can use the exploit whit perl.
> 
> Can you recommend a tutorial on how to do it?
> 
> Thanks.

no
