### ISSUE TITLE
Add UUID support for osx/*/meterpreter/reverse_tcp

### ISSUE THREAD

**Issue by phra** [rapid7/metasploit-framework#12837]
At the moment, the Mac OS X `reverse_tcp` stager seems to miss support for UUIDs. It would be nice to have this support when exposing the handler on the internet.

**Comment by timwr** [comment]
This shouldn't be too hard to add because it's already implemented on linux:
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/linux/send_uuid.rb

I suspect the only thing that needs changing is the syscall number.

For now you could just use the stageless meterpreter (osx/x64/meterpreter_reverse_tcp) and stage it via web_delivery.

**Comment by phra** [comment]
I was using the reverse_tcp because is the only one with raw shellcode since the AV doesn't like the macho generated with msfvenom :)
