### ISSUE TITLE
Homebrew Cask Installation broken

### ISSUE THREAD

**Issue by manzke** [rapid7/metasploit-framework#12936]
## Steps to reproduce

How'd you do it?

1. brew update
2. brew search metasploit
3. brew cask install metasploit

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior

brew should download the pkg and install it

## Current behavior

What happens instead?

user$ brew cask install metasploit
Updating Homebrew...

==> Downloading https://osx.metasploit.com/metasploit-framework-5.0.72+20200130113516-1rapid7-1.pkg
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-5.0.72+20200130113516-1rapid7-1.pkg

### OS

Mac OSX Catalina 10.15.1 (19B88)

**Comment by adamgalway-r7** [comment]
This is an issue with Brew's cask file rather than our own web server. https://osx.metasploit.com/ only supports the 10 most recent builds builds of Metasploit and at the time of this issue being raised the `.pkg` the Cask file pointed to was no longer supported. The cask file is now updated but if this happens again you'd get faster turn around if you raised an issue on the [brew github](https://github.com/Homebrew/brew/issues/new?template=bug.md), as it's a simple one line fix for them.
