### ISSUE TITLE
   Status: package is invalid (checksum did not verify)

### ISSUE THREAD

**Issue by Curioo** [rapid7/metasploit-framework#13058]
when executing `curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall`
i get this error: 

curl: (18) transfer closed with 200675381 bytes remaining to read
Checking signature...
Package "metasploitframework-latest.pkg":
   Status: package is invalid (checksum did not verify)
Cleaning up...
metasploitframework-latest.pkg

any way to fix this? I installed metasploit before, but then deleted it.

**Comment by nsa** [comment]
It seems like the connection has been closed, while the file has been downloading. It might be connection issue between your machine and the firewall.

**Comment by MaxSecurity** [comment]
My mac also has this problem. How can I solve it?

**Comment by h00die** [comment]
The line: `curl: (18) transfer closed with 200675381 bytes remaining to read` says that curl was unable to download the entire file because the connection dropped.
Solutions:
1. try again
2. get a more consistent connection (stronger wifi, move closer to the cell tower, use Ethernet etc).
3. instead of curl, use a browser and download the file then save it as `msfinstall`?

**Comment by MaxSecurity** [comment]
I am using msfupdate this command is not curl

> 该行：`curl: (18) transfer closed with 200675381 bytes remaining to read`表示curl由于连接断开而无法下载整个文件。
> 解决方案：
> 
> 1. 再试一次
> 2. 获得更一致的连接（更强的wifi，靠近蜂窝塔，使用以太网等）。
> 3. 使用浏览器下载文件，然后将其另存为，而不是curl `msfinstall`。

I am using msfupdate this command is not curl
