### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by chuck234** [rapid7/metasploit-framework#13120]
I know this is old but I have the same issue I have everything working right I’m using zirikatu when I type exploit it just says “handler failed to bind to (ip address)”
“Ip is already in use or unavailable” 
“Exploit complete but no session was created” 
Then I cannot conned to my target system.
I’m running kali Linux on my raspberry pi 3
Thanks

**Comment by h00die** [comment]
You could start by giving us some more information.  Maybe a `show options`, then the output of `run`.  Since its mentioning IP Address, maybe `ifconfig` as well.

**Comment by chuck234** [comment]
![529F3EFC-57D5-4134-9AFB-E56253CCC2CB](https://user-images.githubusercontent.com/62567836/77358462-460f2480-6d20-11ea-8477-26e84369bcf7.png)

**Comment by h00die** [comment]
so, you started a listener on port 4545 and ran it as a background job (can't see the IP though).  Then you started a 2nd listener and ALSO set it to listen on port 4545.  This failed because job 0 is already listening on that port. When you tried to run it a 3rd time (manually), it **still** couldn't start start because job 0 is still running and listening on port 4545.

solutions:
1. switch ports of your various listeners
2. kill the first job before trying the 2nd job, or starting it manually.

**Comment by chuck234** [comment]
How do you kill the jobs

**Comment by h00die** [comment]
https://www.offensive-security.com/metasploit-unleashed/msfconsole-commands/
