### ISSUE TITLE
migrate to a recent "rails"

### ISSUE THREAD

**Issue by blshkv** [rapid7/metasploit-framework#13175]
https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/rails_version_constraint.rb

Rails 4.2 is old, outdated, dead, unsupported, has known security issues and should not be used in short. Not by a security tool anyway. 
https://guides.rubyonrails.org/maintenance_policy.html

The biggest problem that Rails 4.2 was already removed by many Linux distributions
Please consider migrating to something more decent.

Thank you

**Comment by bcoles** [comment]
Rails 4.2.6 was released over four years ago and has since been replaced by 90 newer releases across three major versions (4.x, 5.x, 6.x), although the 4.2 branch was updated as recently as 14 months ago with the release of version `4.2.11.1`.

I've created a PR to bump the minimum Rails version constraint to enforce `'~> 4.2.11'`. This is mildly less terrible than `'~> 4.2.6'`, but obviously doesn't resolve the issue.

**Comment by jmartin-r7** [comment]
Rails 5.2 upgrade work is in progress (likely landing in next 60 days).  Jump to Rails 6.0 may come quickly after.

**Comment by hlein** [comment]
See also https://github.com/rapid7/metasploit-framework/pull/13831

**Comment by blshkv** [comment]
I noticed that the pull request has been merged apparently but nobody bothered to update it here. The latest release 6.x supports rail 5 too. So closing it. 

@rapid7 you need to learn how take care reported issues better.
