### ISSUE TITLE
Can't open a session.

### ISSUE THREAD

**Issue by xyz87** [rapid7/metasploit-framework#13239]
Guys i'm new here.
can any one help me with this error?
Started reverse TCP handler on 10.0.2.15:4444 
[*] 10.0.2.1:1099 - Using URL: http://10.0.2.15:8080/rV9Q87RPZx
[*] 10.0.2.1:1099 - Server started.
[-] 10.0.2.1:1099 - Exploit failed [unreachable]: RuntimeError The connection was refused by the remote host (10.0.2.1:1099).
[*] 10.0.2.1:1099 - Server stopped.
[*] Exploit completed, but no session was created. 
Trying to exploit windows 7 using the exploit (multi/misc/java_rmi_server) in kali machine
with metasploit v5.0.2
The Kali and windows 7 both were running in virtual box 
The host is connected to internet

**Comment by bcoles** [comment]
The target is unreachable. Ensure you can route traffic to 10.0.2.1 port 1099 from your host 10.0.2.15.

Are you sure `10.0.2.1` is the correct IP address? You suggest that both the Windows and Kali host are running on VirtualBox. It is unlikely that a VirtualBox host will be allocated a `.1` address.

On VMware, you'll need to ensure your network adapters are not set to `host only`, in order to route traffic between hosts. I believe VirtualBox has a similar setting. NAT or Bridged are fine, although I'd recommend using NAT so as to not expose your test VMs to the local network.

You can debug your netcat issues with netcat.

```
nc 10.0.2.1 1099 -v
```

If you cannot connect with netcat, you cannot connect with Metasploit.

**Comment by gwillcox-r7** [comment]
Closing this as the solution for @xyz87's problem has already been posted.

**Comment by gabriel27660211** [comment]
> address

Hello world!

I am system engineering student, and I'm attending a course named data security. One of the subjects is exploit a cloud vm (created by the profesor) connect the vm, set a shell and later gain root access. Te problem is the vm is outside my lan. Besides, the vm is a zimbra mail server executed in a nginx server, other students turn a web site, other P2P apps.

I used the comand ncat -C 200225(Ipv4 adress) -ssl and his output was: ncat connected to 200.*.225. Which means that is accessible. But the problem is when I execute the shell, fails. Do you know how can gain the root acess in the host that is outside of my lan? Please, give me some examples.
