### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by scripkid** [rapid7/metasploit-framework#13270]
Help how to fix

msfconsole
CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so" not found
Aborted

Ps: I have checked "/data/data/com.termux/files/usr/lib/ruby" by running cd and what I see is 2.7.0 . Does it mean I have to downgrade ruby to run metasploit? If so, how do I downgrade my ruby to 2.6.0? I'm not sure if I'm right so please correct me if I'm wrong. Hope you could help me out. I actually made this word last time with the same error. I looked alot of things at google and made it work. It seems now that I could not find that solution.

**Comment by gwillcox-r7** [comment]
@scripkid Currently Ruby 2.7 is not supported but Ruby 2.6 is, so your issue is likely related to this. As for how to downgrade etc on Termux, I am not sure and as mentioned above this is not a supported platform. Please reference the links above or your local Termux support group if you need additional assistance.

Closing as this is not a supported platform.
