### ISSUE TITLE
Stuck on browser 

### ISSUE THREAD

**Issue by LuckySagittarius** [rapid7/metasploit-framework#13323]
I created windows/meterpreter/reverse_tcp payload and injected.. And using msfconsole connected to the victim.. When i start webcam stream.. The browser opens and says playing.. But its jst stuck and no video is seen
 Please help me

**Comment by gwillcox-r7** [comment]
@LuckySagittarius Closing this as you did not follow the issue template. Please ensure that you follow the issue template when submitting your issue; there are several questions in there that we need answered in order to assist with your case, otherwise we tend to have to spend a lot of time chasing people for details about their setup and use case. Refer to #13294 for an example of how an issue submission should look like once you have filled out the appropriate details.
