### ISSUE TITLE
--no-sandbox

### ISSUE THREAD

**Issue by agrd2086** [rapid7/metasploit-framework#13387]
im new to metasploit and im trying to stream my android camera to the pc and every time i try webcam_stream -i 2 its saying "Running as root without --no-sandbox is not supported" and closes the ssesion and says that it died other commands like webcam_snap work just not this
if there is anything else you need from the code just say ill send you

**Comment by gwillcox-r7** [comment]
@agrd2086 So normally `--no-sandbox` means that the command will only work if you are not running within a browser's sandbox. Given that output it seems that you might be running inside of a browser's sandbox and therefore `webcam_stream` is throwing an error to let you know that it cannot operate inside of the browser's sandbox. 

With that being said, I'm surprised `webcam_snap` is working for you as this should be blocked from the sandbox.

We will need a lot more detail from you. In future please use the template we provide when creating issues as this prevents the back and forth that is about to happen where I try and get more details from you so we can work this issue out more.

It will help me a lot if you can provide the following:
1. Browser you are targeting and its version
2. OS the browser is running on and its version.
3. Output from Metasploit in full showing you trying other commands and it succeeding and also showing `webcam_stream` failing.
4. `show options` should be run before executing `exploit` or `run` for each module shown in your testing so that we can see if there are any options that might be causing issues.

Its just curious as I can't see any code in the framework minus some Chrome exploits that reference `--no-sandbox` so I'm not sure where that line is coming from atm.

**Comment by bcoles** [comment]
> Its just curious as I can't see any code in the framework minus some Chrome exploits that reference `--no-sandbox` so I'm not sure where that line is coming from atm.

This might be related the browser on the Metasploit side. See:

* https://github.com/rapid7/metasploit-framework/issues/12113
* https://github.com/rapid7/rex-core/issues/9

If i had to guess, the session dying was unrelated, unless there's some dumb code in the session handling that relies on the browser on the Metasploit side to open correctly.... which seems unlikely.

**Comment by nomaddude1978** [comment]
A html file is created in the root folder, open that with firefox browser, issue solved !
