### ISSUE TITLE
nasm_shell cant find Ascii85

### ISSUE THREAD

**Issue by benjaminholloway** [rapid7/metasploit-framework#13440]
I am trying to run nasm_shell

## Steps to reproduce

[root@kali:~]# locate nasm_shell
/opt/metasploit-framework/embedded/framework/tools/exploit/nasm_shell.rb
[root@kali:~]# /opt/metasploit-framework/embedded/framework/tools/exploit/nasm_shell.rb
Could not find Ascii85-1.0.3 in any of the sources
Run `bundle install` to install missing gems.

## Expected behavior
it to run nasm and accept input
nasm >

### OS & versions
running kali, updated and upgraded as of 12/05/2020
ruby ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
msf Framework Version: 5.0.89-dev-

Would appreciate help on how I can fault find a little bit more independently if possible as these little hiccups are wasting a lot of my time,

**Comment by bcoles** [comment]
I ran into this a while ago with Metasploit `msfconsole`.

I had to `gem install Ascii85` and ensure to run `msfconsole` with `ruby2.5`, ie:

```
ruby2.5 ./msfconsole
```

It appears my install has a similar issue with `tools/exploit/nasm_shell.rb`. Likewise, it was resolved by using:

```
ruby2.5 ./tools/exploit/nasm_shell.rb
```

**Comment by benjaminholloway** [comment]
Hey thanks for that, seems to have made some progress. It is now throwing another error up.

So first I did the gem install.

#gem install Ascii85
Fetching Ascii85-1.0.3.gem
Successfully installed Ascii85-1.0.3
Parsing documentation for Ascii85-1.0.3
Installing ri documentation for Ascii85-1.0.3
Done installing documentation for Ascii85 after 0 seconds
1 gem installed

Then 

#ruby2.7 /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-bin_tools-0.1.6/lib/rex/assembly/nasm.rb
Traceback (most recent call last):
        2: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-bin_tools-0.1.6/lib/rex/assembly/nasm.rb:4:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rex/file (LoadError)


Alittle bit of digging around people are saying that i need to run the bundle command, but apparently this will not work in kali because kali store the repository differently?? 
Not realy too sure how to interpenetrate it.

**Comment by bcoles** [comment]
Kali recently updated the Ruby environment. Both Ruby 2.5 and Ruby 2.7 are installed.

Metasploit does not yet fully support Ruby 2.7.

`bundle` is probably aliased to the default system Ruby which is likely to be Ruby 2.7.

You can use `bundle` for the Ruby 2.5 environment by using `bundle2.5`; ie:

```
$ bundle2.5 install
```

Also I noticed in the command above you're using Ruby 2.7. Until Metasploit fully supports Ruby 2.7, you'll want to use Ruby 2.5. You can do this by prefacing commands with `ruby2.5`, ie:

```
$ ruby2.5 ./msfconsole
```

**Comment by benjaminholloway** [comment]
Thanks for the comment, I have done another apt update, things have changed slightly.
If I run now; i get "not found"

#ruby2.5  nasm.rb
bash: ruby2.5: command not found

Now more interestingly  when I run:


# ruby2.7 nasm.rb
Traceback (most recent call last):
        2: from nasm.rb:4:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rex/file (LoadError)


I can locate a rex/file.rb ?and it is in another directory:
/opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-core-0.1.13/lib/rex/file.rb

However this is a rex/file.rb   I do not know if this is relevant.  I have tried running ruby2.7 from this directory and still get the error.

Do I  need to install ruby 2.5 and then run this command with ruby2.5?

 Am I missing something?
Is there a way that I can better fault find this? I do not like wasting peoples time.

**Comment by bcoles** [comment]
It looks like you might have Ruby 2.6 and 2.7 installed.

You're still encountering Ruby environment issues. It appears the appropriate dependencies have not been installed for Ruby 2.7. The path you've provided above shows that the problematic gem is installed for Ruby 2.6 but not installed for 2.7. Maybe you have Ruby 2.6 installed? In which case, use `ruby2.6` prefix.

Technically, this is probably more of a Kali issue than a Metasploit issue, as the issue exists within the Kali package and/or Ruby environment.

![ruby](https://user-images.githubusercontent.com/434827/81784978-09ea8a00-9541-11ea-93a4-86a549a1c992.png)

> Is there a way that I can better fault find this?

Here's some ramblings which might get you on the right track.

Unfortunately I ~can't~ won't offer accurate guidance as I'm not familiar with the package on Kali. My fully up-to-date Kali environment still has Ruby 2.5, and I use Metasploit from the git repo master branch, rather than the Kali package. I also have no idea as to the state of Ruby 2.7 support, but I'm fairly certain it is not yet supported.

If you want to try using Ruby 2.7, you can try changing directory to the Metasploit directory (where `Gemfile` exists) and running `bundle2.7 install`, or alternatively, install each dependency as `nasm_shell` complains. ie:

```
$ ruby2.7 ./nasm_shell
< Error: i need gem asdf
$ gem2.7 install asdf
$ ruby2.7 ./nasm_shell
< Error: i need gem zxcv
$ gem2.7 install zxcv
... repeat ...
```

The even lazier option is to clone Metasploit from the git repo, rather than use the Kali package. This way you'll get patches and new modules faster, but run the usual risks of using bleeding edge software. ie, more bugs.
