### ISSUE TITLE
 Exploit completed, but no session was created.

### ISSUE THREAD

**Issue by hothefa1998** [rapid7/metasploit-framework#13501]
Hey, I hope you are all doing well.
I am using this exploit to test a web. I found a chance to use pureftpd exploit, but it seems like it is working, but no sessions is created. Is it the exploit or the msf 5?!

msf5 exploit(multi/ftp/pureftpd_bash_env_exec) > run

[*] Started reverse TCP handler on 192.168.1.11:4444 
[*] ***.***.***.**:21 - Command Stager progress -  59.81% done (497/831 bytes)
[*] ***.***.***.**:21  - Command Stager progress - 100.60% done (836/831 bytes)
[*] Exploit completed, but no session was created.

**Comment by h00die** [comment]
Unfortunately you haven't given us enough detail to help. Please use the template provided when creating an issue. Next time please include more details such as your metasploit version, the actual input and output, and more details about the target.

**Comment by hothefa1998** [comment]
@h00die 
Thanks for your reply. 
 I am sorry, but this was my first time.
msf 5.0.89 --> the version
Module options (exploit/multi/ftp/pureftpd_bash_env_exec):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOSTS   160.153.205.99   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPATH    /bin             yes       Target PATH for binaries used by the CmdStager
   RPORT    21               yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSL      false            no        Negotiate SSL for incoming connections
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)


Exploit target:

   Id  Name
   --  ----
   0   Linux x86
---------
please try it. 
this is the 160.153.205.99

**Comment by h00die** [comment]
so there are a lot of issues here:

1. It is unwise to post your target's true IP on the internet since now everyone in the world knows to try this exploit on that IP
2. Exploitation (even attempts) are illegal in most countries for IPs you don't own, or have written consent to exploit.
3. According to your first post you are using an `lhost` of a private IP.  Have you configured port forwarding? Unless you're target is dual homed, and you're on the internal network, there is no way that your host will be able to connect to you.  You also didn't set a `srvhost`, and not knowing your network configuration, it can be assumed it grabbed the `192` addresses as well, which is not accessible to the target.
4. This is for bugs within the code, not a 'how do I use an exploit' type tutorial, try either slack or irc for that.
5. Checking shodan for that host, It looks like every port and service is open that would be juicy.  I'd be extremely concerned that it is a honeypot.

I'm going to go ahead and close this, since it is most likely a bug in the code, but a 'how do i use this exploit`.  Please seek help on IRC or slack.

**Comment by hothefa1998** [comment]
Thanks for your help.
@h00die 
It is that they offered a reward for the person who can hack it.

**Comment by bingo1199** [comment]
i am trying to hack my virtual window in the same network

for the trojan
lhost=10.0.2.6
lport=2525

msfconsole =use exploit/multi/handler

set payload windows/meterpreter/reverse_tcp
set lhost=10.0.2.6
lport=2525
set target=0

after downloading the trojan in virtual window
exploit , exploit -j -z , run

exploit completed but no session was created.. what can i do
