### ISSUE TITLE
mssql_exec -->how to set password [NULL]

### ISSUE THREAD

**Issue by 947612227** [rapid7/metasploit-framework#13532]
1. i want to use 'admin/mssql/mssql_exec' plug.
2. now. the sqlserver password is null
3. how to set password [null] in msf "admin/mssql/mssql_exec"

my system is macOSX 10.15.5,MSF5
Thanks~~~

**Comment by gwillcox-r7** [comment]
@947612227 I believe you should just be able to leave this field blank? On my host if I leave it blank it will still attempt to connect.

Otherwise you could always do `set PASSWORD ""` but this won't really change anything as this is the default anyway.

If you could output your attempts (redacted if needed) after trying this, it would help us diagnose any issues.
