### ISSUE TITLE
Error: Unable to find hook point on APK

### ISSUE THREAD

**Issue by NNodero** [rapid7/metasploit-framework#13533]
Using msfvenom with the apk as an input file and the payload being android/meterpreter/reverse_tcp
I'm trying to inject a payload into netflix apk. This is where i got the netflix apk from the official website https://help.netflix.com/en/node/57688
![Screenshot 2020-05-28 23:26:24](https://user-images.githubusercontent.com/65863676/83174880-06323800-a0e9-11ea-9b60-820accb9deee.png)

while injecting it says it can't find a hook point
to be specific :
Error: Unable to find hook point in /tmp/d20200528-6757-196qgfp/original/smali*//NetflixApplication.smali
![Screenshot 2020-05-28 23:46:15](https://user-images.githubusercontent.com/65863676/83178041-fc5f0380-a0ed-11ea-8596-48fc8e4ea91f.png)
LHOST= my public ip

But when i try biniding payload into simple apps and games like flappy bird it works
HOW CAN I FIX THIS?

**Comment by Nisar0** [comment]
Could you fix this?

**Comment by busterb** [comment]
It's possible that Netflix intentionally has engineered and obfuscated their app so that common methods of payload injection would not work. This is similar for other high-visibility and commercial apps. You'll probably need to take a look at what the decompiled output of apktool is (look at lib/msf/core/payload/apk.rb) and determine how your app of interest might be structured in order to find the .smali file.

**Comment by cocomoman** [comment]
hi, im still having this issue. if someone can help me ill really appreciate it

**Comment by Droid1x** [comment]
تعلم الهاكر الأخلاقي واختبار الإختراق من الصفر الي الاحتراف باللغة العربية، السعر مجاني
اللينك : https://user167956.pics.ee/3vhutr

**Comment by bcoles** [comment]
@NNodero @cocomoman @Nisar0 do you have any example APK files which encounter this issue other than netflix?

I have a simple patch for this issue.

The hookable class name is extracted without the full path `"/NetflixApplication.smali"` which causes globbing to fail, preventing finding the correct smali class file.

Easily fixed, but rebuilding the netflix APK later fails due to #16338. I'd prefer to test a valid APK file before proceeding with submitting the patch to insure that the injection still worked correctly.
