### ISSUE TITLE
Autoscript

### ISSUE THREAD

**Issue by ampf27** [rapid7/metasploit-framework#13568]
Hi

Im trying to run the following autoscript

use exploit/multi/handler
set payload …
set lhost
set lport
set autorunccript multi_console_command -r /root/script.rc
set exitonsession false
exploit -j
shell
powershell command

it happens that when it opens a session it runs shell but after that it doesn't run the powershell commands

there are post modules that allow run powershell scripts but I would like to know how to automate run powershell commands through a shell or other way without using scripts

Thanks

**Comment by gwillcox-r7** [comment]
Hello there @ampf27! Upon initial inspection it looks like you could have typo'd this? You typed `autorunccript` rather than `autorunscript` which means that you may have been setting an item in the `datastore[]` array that is never used by the module itself. Can you check if you perhaps typo'd this?

If this doesn't work, please provide the following to allow us to better diagnose your issue:

- Metasploit version
- Ruby version
- Screenshots of what is going on or MsfConsole output

As you haven't provided this info, and the only info that I have right now is simply "its not working", I don't really have all that much to use to assist you in fixing your issue beyond the typo that I noticed, so this should allow me to determine the root cause of your issue better.

**Comment by ampf27** [comment]
Hi

Indeed on this issue I mistyped autorunscrypt however on the console I typed correctly

The ruby version is 2.5.7p206 (2019-10-01 revision 67816)

The metasploit version is v5.0.71-dev

the error given

![Autorunscript Error](https://user-images.githubusercontent.com/42299613/83978366-e677ec80-a8fe-11ea-8ddf-774300960367.png)

on the resource the commands are

shell
powershell command

**Comment by gwillcox-r7** [comment]
Oh I think I know whats going on here. `shell` is executing and its waiting for its task to finish. However since you still have a shell open from the `shell` command, its not executing that powershell command cause its still waiting for `shell` to finish executing.

You can see this in the output above as it notes `Running command shell` but it doesn't show it running that other command. Have you tried exiting the shell and seeing if the other command runs at all?

**Comment by ampf27** [comment]
I have tried powershell withouth the Shell command first but I get the error "Unkown command: powershell"

I have also tried execute -f cmd.exe -i -H powershell -command "" but get the error
"Error running command execute: Errno::ENOENT No such file or directory @rb_sysopen - cmd.exe"

I have tried also a resource with

load powershell
powershell_execute "command"

It managed to run the exe file but it droped on the disk and have run this command sevseral times on the target. I have tried to add exit to the resource but without success

This is a screenhot of the time I got some limited success

![Powershell Load](https://user-images.githubusercontent.com/42299613/83980800-783c2580-a910-11ea-8405-0362724b120d.png)

**Comment by gwillcox-r7** [comment]
@ampf27 Sorry for the delay! I think you could do `powershell_import` to import a PowerShell script or DLL onto the target and then use `powershell_execute` to execute commands now that that PowerShell script has been loaded into the context of the current session. This would prevent you having to drop a file to disk and would still allow you to run the payload from memory.
