### ISSUE TITLE
cannot copy extracted data for './usr/share/metasploit-framework/vendor/bundle/ruby/2.7.....

### ISSUE THREAD

**Issue by srsamuka** [rapid7/metasploit-framework#13941]
Hi there, how are you guys? I hope you're fine...

well see my log while upgrading metasploit:

cannot copy extracted data for './usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/ext/nokogiri/nokogiri.so' to '/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/ext/nokogiri/nokogiri.so.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:

My system:

Running on virtualbox...

Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux

Thanks in advance for the help. :)

**Comment by busterb** [comment]
Howdy! This sounds like an issue for the Kali linux bug tracker, since we don't maintain that package: https://www.kali.org/docs/community/submitting-issues-kali-bug-tracker/

Offhand, I'd check to make sure you had proper disk space available, or try to redownload the package in case it was truncated earlier (apt-get update; apt-get install metasploit-framework) . Good luck!
