### ISSUE TITLE
To integrate a metasploit payload in an official .apk it's easy... but how to integrate a payload from another application ?

### ISSUE THREAD

**Issue by blinko1** [rapid7/metasploit-framework#14069]
Hello, I'm looking to integrate a payload from a Remote Administration Tool on an apk on my own smartphone.

But here it is, all the tutorials I found are made from a metasploit payload. The payload.smali is then in /smali/com/metasploit/stage/Payload.smali

With the Spynote payload I can't find a "Payload.smali", so how do I find the right .smali file?
![Smali](https://user-images.githubusercontent.com/70415263/91621796-b0458880-e994-11ea-81ad-47f2a040c1af.PNG)

**Comment by GetRektBoy724** [comment]
waitt
so you literally want to inject msf payload into an .apk file ??

**Comment by GetRektBoy724** [comment]
or 
you want to make your own tool to inject msf payload into other .apk ???

**Comment by timwr** [comment]
@blinko1 fyi you can find the source for Payload.smali here:
https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/app/src/com/metasploit/stage/Payload.java
if you need the smali code instead of the java just generate an apk with msfvenom and run apktool on it.

You can also automatically inject it into an existing apk:
https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/payload/android/meterpreter/injection.md
