### ISSUE TITLE
MSF6 download failed

### ISSUE THREAD

**Issue by meterp** [rapid7/metasploit-framework#14087]
## Steps to reproduce

How'd you do it?

1. ...set payload android/meterpreter/reverse_tcp
2. ...set lhost localhost
3.... Use multi/handler
4... Exploit

5. download filePath my path

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Were you following a specific guide/tutorial or reading documentation?
No

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.

## Expected behavior

What should happen?

It should begin downloading files from target device and uploading to my device

## Current behavior

What happens instead?

It gives an error of 'download failed'. This download method worked days ago before I updated to MSF6

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version
6.0.2

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Parrot 4.1.0

**Comment by gwillcox-r7** [comment]
@meterp I can't tell what your issue is from this output, other than that you are running Parrot OS and that your getting a download error when trying to update Metasploit. However as you have not told me how you are trying to download Metasploit I am not sure how to help you with this. I am also not sure what commands you were running to trigger the error either, since you didn't update the default template with the required information.

In future, please follow the template and actually fill out the sections, its very hard to distinguish the parts of your issue that are boilerplate parts that you should have removed and replaced with your own responses, and the parts that are your actual responses.

In the meantime, if you can please update the issue with the steps you took to trigger the issue and the output that was shown after running all the commands leading up to that error, then it will be more likely I can assist you with your error.
