### ISSUE TITLE
Fedora/Linux installer deleting all symlinks while package update

### ISSUE THREAD

**Issue by 53c70r** [rapid7/metasploit-framework#14086]
Using the Linux installer from https://docs.rapid7.com/metasploit/installing-the-metasploit-framework/ i noticed after updating the package all symlinks are gone leaving all binaries in place without any references to the environment.
Symlinks are placed correctly only after installation.

Fedora 32

**Comment by VainlyStrain** [comment]
+1
had this for quite some time now (since first installation on Fedora 29). I solved it by uninstalling, then installing again (NOT reinstall):

msfvpdate.sh
```
sudo dnf remove metasploit-framework
sudo dnf install metasploit-framework
```

**Comment by 53c70r** [comment]
This should be fixed within the .spec file while rpm building.

**Comment by 53c70r** [comment]
Setting reference to
https://github.com/rapid7/metasploit-omnibus/issues/133

**Comment by 53c70r** [comment]
Bump.

**Comment by VainlyStrain** [comment]
I have looked into it. There is a script [here](https://github.com/rapid7/metasploit-omnibus/blob/master/package-scripts/metasploit-framework/postinst) (responsible for the shortcuts) that is executed correctly every time the package is freshly installed. However, it is not triggered when there is a package update.

In the [Fedora documentation](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax), it says that the scriplets are called with a different argument when upgrading than when installing. Maybe this is the issue here? As I am unfamiliar with packaging, I can't fix the issue myself and submit a pull request, sorry :/

But hopefully this reply was able to help a person able to fix it.

**Comment by dwelch-r7** [comment]
We're going to just keep track of this issue in the omnibus repo here: https://github.com/rapid7/metasploit-omnibus/issues/133
