### ISSUE TITLE
Feature Request - Meterpreter Debug Mode

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#14232]
## Summary

It would be nice to have the Meterpreter stagers support a "Debug" mode where the remote binary would start writing debug strings out to STDOUT or in the case of Windows Meterpreter to Windows Debug

### Basic example

- In Python meterpreter after the stage it could write to STDOUT so that you could see the functions and actions that it was being asked to perform and extensions loads etc
- In Windows meterpreter after the stage it could write to Windows Debug the functions and actions that it was being asked to perform, as well as extension loads or migrates etc.

### Motivation

For debugging Meterpreter when it's fails to function

**Comment by mubix** [comment]
*cough* *cough* @OJ

**Comment by OJ** [comment]
Well, funny you should say that .. because if you lookie [over here](https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/common/common.h#L8):
``` c
/*! @brief Set to 0 for "normal", and 1 to "verbose", comment out to disable completely. */
//#define DEBUGTRACE 0
```
Just uncomment that `#define`, rebuild the binaries, and have DbgView running on the target box ... you'll see more information than you can handle!

If you want MOOOOAR than set `DEBUGTRACE` to `1` and build again.
