### ISSUE TITLE
During penetration testing while using VPN or proxy it affects outgoing and incoming connections on metasploit?
For some reasons also it is important to forward 4444 IP on my router?

### ISSUE THREAD

**Issue by im-sec** [rapid7/metasploit-framework#14284]

**Comment by smcintyre-r7** [comment]
> During penetration testing while using VPN or proxy it affects outgoing and incoming connections on metasploit?

Yes, a VPN and proxy will affect the connections to Metasploit. Metasploit uses the network provided by the host operating system so if your system is connected to a VPN then Metasploit will use that for it's connections. Whether or not the incoming connections to Metasploit travel over the VPN is a bit more complicated and depends on the network configuration of the remote system establishing the connection. If you want to be 100% certain that it's all going over the VPN then use a bind payload instead of a reverse payload so Metasploit establishes all connections instead of listening for any from the target.

> For some reasons also it is important to forward 4444 IP on my router?

That completely depends on your configuration. If you're trying to port forward from your public address then yes youll need to forward 4444 on your router to your system that is running Metasploit.
