### ISSUE TITLE
stucked at meterpreter session opened and the closed and enter meterpreter and perform commands

### ISSUE THREAD

**Issue by vpnfreefree** [rapid7/metasploit-framework#14550]
Started reverse TCP handler on x.x.x.x:8765 
[*] Sending stage (76756 bytes) to xxx.x.x.x(ip)
[*] Meterpreter session 1 opened (xxx.x.x.1:8765 -> xxx.x.x.1:58336) at 2020-12-25 05:25:01 -0500
[*] Sending stage (76756 bytes) to xxx.x.x.1
[*] Meterpreter session 2 opened (xxx.x.x.1:8765 -> xxx.x.x.1:58572) at 2020-12-25 05:26:49 -0500
[*] xxx.x.x.1 - Meterpreter session 1 closed.  Reason: Died
[*] xxx.x.x.1 - Meterpreter session 2 closed.  Reason: Died
[*] Sending stage (76756 bytes) to xxx.x.x.1
[*] Meterpreter session 3 opened (xxx.x.x.1:8765 -> xxx.x.x.1:58780) at 2020-12-25 05:31:53 -0500
[*] 127.0.0.1 - Meterpreter session 3 closed.  Reason: Died

i am stucked here as i am not going ahead and cannot write and commands 
how long should i wait here to enter in meterpreter and write commands like dump_sms
please provide me with a solution
my ngrok is running fine and is online and also i have ping the ip and there is no error
please please provide me with a solution

**Comment by loneicewolf** [comment]
Hello, have you tried `CTRL + Z` to background it, and then type `sessions` to interact with the specific one, ?
sometimes, in my case this would, in some cases solve that.

Please reply if the problem persists.

**Comment by vpnfreefree** [comment]
@loneicewolf still facing the same issue and this time a new issue also occured-
Failed to load extension: No module of the name android found
[-] Failed to load extension: No module of the name appapi found
after it i retried also
I WANT TO KNOW IS THERE AN LTERNATIVE TO LOCALHOST-127.0.0.1
AS I DON'T KNOW MUCH BUT I AM USING NGROK (FREE) FOR PORT FORWARDING
IS THERE ANY WAY TO GET PERMANENT ACCESS AND SOMETHING BETTER THAN NGROK

**Comment by loneicewolf** [comment]
I - uh it depends on what you mean by Permanent access - if you mean permanent access to a system (I assume and hope) is authorized ( - we're talking about authorized access here right? ) Is it a system you need to connect to that you cannot physically can get to? 
An alternative to Local host or 127.0.0.1 - I am not sure,  the ipv4 address/host name displayed in the output of the command (In Linux)  "ifconfig" and "hostname" - But since I am a bit unsure about exactly what you are after, I cannot really determine what to write,

lastly,  something better than Ngrok? - I have not used it, so I cannot accurately answer that, but You sure your router/firewall is port-forward too (NOTE: If that is needed, if it should not be needed, Do not port forward) I am not into the ngrok topic, so Do not take my words for this, I can just speculate what the problem might  be.

#### Sorry if this answer wasn't the answer you hoped for, it probably isn't - But if this reply is downright wrong,  I would appreciate it if someone pointed it out.

**Comment by fardeen-ahmed** [comment]
@vpnfreefree the reasons might be :

1) Network issues.
2) Target Machine is down, so user is log out.
3) Ports that are being tested are running services
4) Or any anti-virus that are running kills shells.

***Solutions (These might work) 👍*** 

1) Check for Network Issues.
2) For shell creation, you need to see if target is Up or Down.
3) Ports, that are running should be shut-down in order to create a meter-preter shell.
4) Antivirus generally kills shell. If Windows Defender is running, that can be easily bypassed, but If anti-virus is running of private companies, like McAfee or Quick-heal, then it's near to impossible.

Hope this solution works.

**Comment by cgranleese-r7** [comment]
Hey @vpnfreefree, just wondering if you could give some more information, in terms of the the setup you're using for this?

If you could also please run the debug command and attach the output please.

Thanks
