### ISSUE TITLE
SOCKS5 SUCKS !

### ISSUE THREAD

**Issue by youssrii** [rapid7/metasploit-framework#14554]
i'm trying to reach a VNCServer over meterpreter using proxychains (Socks5) and it is very slow..slower even from Socks4a.. so whats the problem !

> kali@kali:~$ cat /etc/proxychains.conf | grep socks5
#socks5	192.168.67.78	1080	
#proxy types: http, socks4, socks5
socks5  127.0.0.1 9090

**Comment by vpnfreefree** [comment]
BETTER DON'T USE PROXYCHAINS
TRY TO USE IT NORMALLY

**Comment by youssrii** [comment]
it's over wan... i'm limited using it with proxychains

**Comment by zenware** [comment]
This doesn't seem to be an issue with the metasploit-framework, and there is no diagnostic information presented. I'm afraid the only one who can help you in this case is yourself.

If you wanted, you could try this program instead of proxychains https://github.com/rofl0r/proxychains-ng
Or if you think there is an issue with the proxychains software you could bring it up here: https://github.com/haad/proxychains

I would first recommend doing some research and attempting to understand what is to be expected of each protocol given your specific network conditions, my suspicion is that this is related to the network, not the software.

I also recommend this issue be closed as irrelevant to the metasploit-framework project.

**Comment by gwillcox-r7** [comment]
Closing this issue due to it not being an issue with Metasploit itself and due to @zenware's answer which should provide enough info to answer the original question.
