### ISSUE TITLE
I get this when I run Metasploit

### ISSUE THREAD

**Issue by rnvtwri** [rapid7/metasploit-framework#14575]
When I run Metasploit

Executing “sudo msfdb init && msfconsole”
[i] Database already started
[i] The database appears to be already configured, skipping initialization
Could not find reline-0.1.5 in any of the sources
Run bundle install to install missing gems.

When i run bundle install
root@arnav:~# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application
for all non-root users on this machine.
Could not locate Gemfile

I also cannot run Armitage

**Comment by h00die** [comment]
You need to run `bundle install` from the folder where metasploit-framework is installed so it can find the `Gemfile`

**Comment by gwillcox-r7** [comment]
Closing this issue as this is not an issue with Metasploit and @h00die has already provided answer. Please follow @h00die's advice for installing the gems.

**Comment by Dorabotmaster** [comment]
I cloned the GitHub metasploit and tried installing but when I installed both msf dosnent work

**Comment by bcoles** [comment]
> I cloned the GitHub metasploit and tried installing but when I installed both msf dosnent work

This issue is closed.

If you have an issue, [create a new issue](https://github.com/rapid7/metasploit-framework/issues/new/choose) and ensure you complete the issue template. "both msf dosnent work" is an insufficient description to diagnose the issue.

Installation should be as easy as installing operating system packages, cloning the repository, and installing Ruby dependencies. Refer to:

* https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

**Comment by gwillcox-r7** [comment]
Locking issue. Please follow @bcoles's advice if you wish to raise a new issue and be sure to follow the template provided and fill in the required details.
