### ISSUE TITLE
Typo on CVE link

### ISSUE THREAD

**Issue by PastNullInfinity** [rapid7/metasploit-framework#14706]
https://github.com/rapid7/metasploit-framework/blob/59aa6eab8575910bdef53ce97dfb43c653fe95d7/modules/exploits/solaris/ssh/pam_username_bof.rb#L39

This should be *cve-2020-14871*

**Comment by adfoster-r7** [comment]
Thanks for raising an issue. From what I can see this is a typo with a third party site that we don't control, using the suggested URL https://hacker.house/lab/cve-2020-14871/ results in a 404 for me

**Comment by PastNullInfinity** [comment]
> Thanks for raising an issue. From what I can see this is a typo with a third party site that we don't control, using the suggested URL https://hacker.house/lab/cve-2020-14871/ results in a 404 for me

yeah, that site seems to not have the CVE indexed, but NIST has it: [CVE-2020-14871](https://nvd.nist.gov/vuln/detail/CVE-2020-14871)

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/blob/21d734d576757a905f1dda43e655010cd20c7bc0/modules/exploits/solaris/ssh/pam_username_bof.rb#L36-L39

The correct CVE is already referenced in the module. I have no control over @HackerFantastic. 😂

**Comment by wvu-r7** [comment]
Speaking of that module, I still need to PR the 10u10 and 11.0 targets. :|

**Comment by gwillcox-r7** [comment]
Closing this issue as this is the correct URL, and the typo is out of our control. If @HackerFantastic wishes to edit his website to fix this typo, we will happily update this, however as it stands right now this is not something that makes sense to change given that `https://hacker.house/lab/cve-2020-18471/` links to the right web page, and this is the URL currently used by the module.

TLDR: If HackerHouse does update their URL to fix the typo, then we will update it at that time. Otherwise for now I'll have to close this issue as we do not own nor have any control over HackerHouse and therefore cannot fix this issue.
