### ISSUE TITLE
metasploit framewaork modules could not be loaded

### ISSUE THREAD

**Issue by praveen190** [rapid7/metasploit-framework#14891]
# msfconsole -q

[!] The following modules could not be loaded!
[!]     /usr/share/metasploit-framework/modules/auxiliary/gather/office365userenum.py
[!] Please see /root/.msf4/logs/framework.log for details.

Then tried msf>reload_all

msf6 > reload_all
[*] Reloading modules from all module paths...
[-] WARNING! The following modules could not be loaded!
[-]     /usr/share/metasploit-framework/modules/auxiliary/gather/office365userenum.py
[-]     /usr/share/metasploit-framework/modules/auxiliary/dos/http/slowloris.py
[-]     /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go
[-]     /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go
[-]     /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go
[-]     /usr/share/metasploit-framework/modules/auxiliary/scanner/ssl/bleichenbacher_oracle.py
[-] Please see /root/.msf4/logs/framework.log for details.

 Can anyone please help out to fix the issue

**Comment by bcoles** [comment]
You haven't provided the log (`framework.log`), but it is highly likely that the `*.py` modules aren't loading because Python wasn't found. The `*.go` modules aren't loaded because Go wasn't found.

These module are external modules and those are not always available because they have dependencies that are external to Metasploit. If you want to run the Python modules, you'll need to install Python and then it's dependencies (at minimum, the `requests` package will be required). If you want to run the Go modules, you'll need to install Go.

**Comment by yogeshyogi-cloud** [comment]
you can try the comment metasploit b errror can slove 
100% working  

- 

- 

> sudo apt install gccgo-go

**Comment by putabones** [comment]
The install from @yogeshyogi-cloud fixed it

**Comment by hackeranonymousd** [comment]
nlkmn
