### ISSUE TITLE
why dont have windows/meterpreter/reverse_tcp

### ISSUE THREAD

**Issue by ox1234** [rapid7/metasploit-framework#14916]
why my msf6 dont have windows/meterpreter/reverse_tcp module

**Comment by bcoles** [comment]
it do

```
msf6 > use exploit/multi/handler 
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf6 exploit(multi/handler) > 
```

**Comment by ox1234** [comment]
![image](https://user-images.githubusercontent.com/32171650/111588573-b438db00-87fe-11eb-8426-68196c2fb655.png)
my msf dont have this module, does it broken?

**Comment by ox1234** [comment]
[framework.log](https://github.com/rapid7/metasploit-framework/files/6162135/framework.log)
this is the error log，what's wrong with my msf?

**Comment by gwillcox-r7** [comment]
@ox1234 What is the version of Metasploit that you have installed, what is your Ruby version, and do you have AV installed on the system you have installed Metasploit on?

I'm seeing a bunch of Zeitwerk related errors here, but without knowing your Metasploit version and setup environment its hard to tell if this is a new issue or if its due to your configuration.
