### ISSUE TITLE
Suggestion Feature : `sysinfo` command to shell sessions 

### ISSUE THREAD

**Issue by pingport80** [rapid7/metasploit-framework#15027]
## Summary

It will be good to have a `sysinfo` command to shell sessions to query common system information.

### Basic example
```
sysinfo 

IP Address   : 192.168.29.149
OS           : Debian  (Linux 2.4-kali3-amd64)
Architecture : x64
hostname     : kali
username     : pingport80
```

Something like this, doesn't need to be exactly like this.

**Comment by sempervictus** [comment]
To make a cliche Matrix reference - the MSF world has constant dejavu going on.
Many moons ago, a wise man by the name of @kernelsmith worked on an effort to enable shell sessions to behave similarly to meterpreter ones by **fronting** them with a CLI middleware which would translate things like `upload` and `sysinfo` to the shell's native interpretation... or there's meterssh and other such "goodness" out there in the hackerverse.
The PITA:benefit ratio here has been proven repeatedly to be only worth it in the case of newcomers coming to learn the _framework_ and how to implement functions in it (rather than just using it to make modules/run stuff). Not disagreeing about the notion of convenience methods, but `uname -a` should serve you all the same and not require l33t h4x0rs to dive ragged `cmd_` or god forbid `Session` code paths for the function. Just my $0.02, though you're more than welcome to stub the functionality you want and make a pull request to get some contributor review and assistance in refinement.

**Comment by pingport80** [comment]
Totally Agreed :+1: , I too was trying to make it to move closer to meterpreter but wanted to fetch some other useful info too. But yeah, Hackers can actually use simple commands to achieve that. Will wait for some time in case someone else has some suggestions on this. :) otherwise close this. Also thanks for explaining it so well :slightly_smiling_face:
