### ISSUE TITLE
eternalblue exploit not working on vulnerable computer

### ISSUE THREAD

**Issue by The-ML-Hero** [rapid7/metasploit-framework#15148]
![image](https://user-images.githubusercontent.com/67855775/117012326-763f3a00-ad0c-11eb-8951-67a80f551e6f.png)

## Summary
so I tried it on kali linux as well as windows double checked everything my ip the rhost everything please reply as soon as possible
## Relevant information
so the target is running a windows 8 pro my other computer and the attacker is running a windows 10 pro with kali linux
please reply as soon as possible

**Comment by bcoles** [comment]
The exploit has `NormalRanking`. It is not 100% reliable.

**Comment by adfoster-r7** [comment]
The issue template hasn't been filled out so it's not entirely clear what module options you're running with etc. But at glance, if you're targeting windows 8 machines, you should use `exploits/windows/smb/ms17_010_eternalblue_win8.py` instead of ` modules/exploits/windows/smb/ms17_010_eternalblue.rb`
