### ISSUE TITLE
Installation problems on windows

### ISSUE THREAD

**Issue by samokosik** [rapid7/metasploit-framework#15188]
## Summary
After a "successful" installation, metasploit cannot load due to a PATH error

## Relevant information
I installed the metasploit on windoes 10 Enterprise LTSC and it said that the installation is successful - no errors occured.
However, when I tried running metasploit, it started complaining about path which is very weird because it was said that the installer created needed path variables for you.
Here is the message I get:
![image](https://user-images.githubusercontent.com/73645764/117967344-363c1080-b325-11eb-8068-8f8827ad8ae9.png)

Does anyone get the same message?
Does anyone know how to solve this issue?
Thank you

**Comment by adfoster-r7** [comment]
Looks like this is an issue caused by being on a domain PC?
https://stackoverflow.com/questions/39179377/windows-bundle-install-home-environment-variable-or-homedrive-and-homepath-mu

Let me know if that workaround works for you. Alternatively, I can recommend using Metasploit with a Kali VM if you're new to security. You can download a VM here which will have everything pre-installed which you can use to hit the ground running:
https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-image-download/
