### ISSUE TITLE
How to make Metasploit payload FUD?

### ISSUE THREAD

**Issue by Korto9** [rapid7/metasploit-framework#15195]
Hi,

I have read many forum about it and It seems that all of them are old metho. I would like ot knwo the most efficient way of making a FUD payload. (windows/meterpreter/reverse_tcp.

Thank you in advance

**Comment by whichbuffer** [comment]
meterpreter is public tool so public means AV or EDR systems detects easily , you need to write a custom shellcode loader or packer in order to bypass this systems but bigger issue was C2 server of MSF it will still detected by many EDRs or firewalls due to deafult profiles of connection, good news MSF it's open source and well documented you can able to create your own payload if you can , good luck

**Comment by Korto9** [comment]
Do you have any recommandation from where should I start?

Thank you

**Comment by Korto9** [comment]
And is it difficult or its achieveble by a beginner like me?

**Comment by whichbuffer** [comment]
My recommendation for you, learn GO or C++ then write a simple Client (EXE,DLL) and Server (Python)  (Get Reverse Shell from victim machine) that way you can learn malware development , painful way to learn but it should great experience for you also your malware now can able to bypass Microsoft Defender but not EDR solutions that's another problem to achieve , google is your friend use it

**Comment by Korto9** [comment]
Do you recommend me to learn python or C++? I want to learn to write malware.

Thank you

**Comment by whichbuffer** [comment]
C++ for client side and Python for server side.

**Comment by OJ** [comment]
Please can you take this discussion to Slack. Github is for bug reports and issues. Thanks.

metasploit.slack.com
