### ISSUE TITLE
Unable to take a screenshot in meterpreter

### ISSUE THREAD

**Issue by Kayx23** [rapid7/metasploit-framework#15208]
### Issue
Cannot take a screenshot in meterpreter: 
```
meterpreter > screenshot
[-] stdapi_ui_desktop_screenshot: Operation failed: The program issued a command but the command length is incorrect.
```

I have also tried
```
meterpreter > use espia
Loading extension espia...Success.

meterpreter > screengrab
[-] espia_image_get_dev_screen: Operation failed: The handle is invalid.
```
Anyone know what's going on? Thanks in advance! 

### Process
Exploited a box with `windows/shell/reverse_tcp` payload and migrated my process to `explorer.exe`

### Other Info
```
meterpreter > sysinfo
Computer        : ELS-WINXP
OS              : Windows XP (5.1 Build 2600, Service Pack 3).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x86/windows
```

**Comment by krishnadevpmelevila** [comment]
This error is not with the meterpreter . Try the same exploit with another target. Then if screenshot command worked, you can confirm that some of the files are missing on the target pc. may be it is because of recent updates or incorrect registry values on target pc,
so i advice you to try the same attack on other target device, and tell me the status.
