### ISSUE TITLE
How do I run Metasploit on Windows?

### ISSUE THREAD

**Issue by ololoe** [rapid7/metasploit-framework#15201]
Windows installer is broken AGAIN!
https://github.com/rapid7/metasploit-framework/issues/12600

**Comment by bcoles** [comment]
For reference, OP's issue was described here: https://github.com/rapid7/metasploit-framework/issues/12600#issuecomment-841573291

It's been a while since I've looked at Metasploit on Windows. The command line interface can be run with `msfconsole.bat`.

**Comment by ololoe** [comment]
Why do you install to drive root regardless of selected folder? Only idiots install to drive root. Windows 9x is dead more that 20 years.
Why do you provide an installer that does not work? Why not simply a zip file?

@bcoles I know that. How to start web interface?

**Comment by bcoles** [comment]
Issues with the installer are tracked on the https://github.com/rapid7/metasploit-omnibus/ repository.

> Why do you install to drive root regardless of selected folder?

This is a bug. This issue is tracked here: https://github.com/rapid7/metasploit-omnibus/issues/115

> Why do you provide an installer that does not work? Why not simply a zip file?

If I had to guess, I'd presume that it's because users want fancy functionality like a web interface and database. These must be installed and cannot simply be unzipped, especially if any functionality needs to be run at system startup.

> How to start web interface?

Are you using Metasploit Framework or Metasploit Pro?

The web interface runs on `https://localhost:3790` and is only available in Metasploit Pro:

* https://docs.rapid7.com/metasploit/getting-started/
* https://docs.rapid7.com/metasploit/metasploit-web-interface-overview/

**Comment by ololoe** [comment]
> This is a bug. 

Why isn't it fixed? Is the installer mantained at all?

>If I had to guess, I'd presume that it's because users want fancy functionality like a web interface and database. These must be installed and cannot simply be unzipped, especially if any functionality needs to be run at system startup.

But your installer doesn't work and this since ages.


What is Metasploit Community? Where can it be downloaded?

**Comment by Nikhil9938** [comment]
How to unhide the app icon in metasploit lol pls help
