### ISSUE TITLE
Git status

### ISSUE THREAD

**Issue by GitHubNeko** [rapid7/metasploit-framework#15232]
bundle install 
git status
![Screenshot_20210522_135017](https://user-images.githubusercontent.com/83487691/119216174-a9533d00-bb04-11eb-8c88-641e8b85051f.jpg)

**Comment by bcoles** [comment]
what is your question

**Comment by GitHubNeko** [comment]
> 你的问题是什么

Why does this prompt appear

**Comment by bcoles** [comment]
> 
> 
> > 你的问题是什么
> 
> Why does this prompt appear

`Gemfile.lock` is created by `bundler` automatically. This file lists the installed versions of each gem dependency.

https://rubyinrails.com/2013/12/10/what-is-gemfile-lock/

This file appears in `git status` because it is not part of the repository. It is a new file created by `bundler` on your system. It is also not ignored by `.gitignore`.

**Comment by GitHubNeko** [comment]
> 你的问题是什么



> > > 你的问题是什么
> > 
> > 
> > 为什么出现此提示
> 
> `Gemfile.lock`由`bundler`自动创建。该文件列出了每个gem依赖项的安装版本。
> 
> https://rubyinrails.com/2013/12/10/what-is-gemfile-lock/
> 
> 出现此文件是`git status`因为它不是存储库的一部分。这是`bundler`在您的系统上创建的新文件。也不会被忽略`.gitignore`。

Can I ignore it?

**Comment by bcoles** [comment]
> Can I ignore it?

Yes.
