### ISSUE TITLE
Bundler failed to load and returned this error

### ISSUE THREAD

**Issue by alexanderajju** [rapid7/metasploit-framework#15258]
┌──(thantos㉿ParrotSec)-[/usr/share/metasploit-framework]
└─$ msfconsole
[*] Bundler failed to load and returned this error:

   'You have already activated bundler 2.1.4, but your Gemfile requires bundler 2.2.17. Since bundler is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports bundler as a default gem.'

[*] You may need to uninstall or upgrade bundler

i already installed bundler 2.2.17

**Comment by gwillcox-r7** [comment]
@alexanderajju I have had this issue before. Usually the best solution is to uninstall all current versions of bundler on your system and then install a later version of bundler, or do `gem update bundler`. If that still doesn't work, try `gem update --system`, followed by `gem update bundler` and that should fix the issue.

**Comment by alexanderajju** [comment]
> @alexanderajju I have had this issue before. Usually the best solution is to uninstall all current versions of bundler on your system and then install a later version of bundler, or do `gem update bundler`. If that still doesn't work, try `gem update --system`, followed by `gem update bundler` and that should fix the issue.

I tried all the method but i didn't worked .then i reinstall the machine and update it

**Comment by Gargeeshar19** [comment]
# msfconsole 
Metasploit requires the Bundler gem to be installed
# bundle install
# bundle update nokogiri
Be patient..
After the successful completion of the above commands, try running msfconsole again.

Hope this solves the error.

**Comment by gwillcox-r7** [comment]
@Gargeeshar19 The user in this case already had `bundler` installed, and mentioned that he solved the issue by reinstalling the machine, so this issue should be considered closed and no new comments should be added to avoid polluting old issues that are already resolved. If users encounter issues in the future in a new open issue feel free to comment on them and try to assist but in general closed issues should be considered closed and should not be commented on unless you have reason to believe the issue discussed in the issue is not truly resolved.
