### ISSUE TITLE
scanner/snmp/snmp_login does not obey selected snmp version

### ISSUE THREAD

**Issue by usd-markus** [rapid7/metasploit-framework#15922]
metasploit module scanner/snmp/snmp_login does not use Version 1 at all, not when selecting "all", nor when directly selecting "1". I had issues with this module in the past. I just tested it, when setting "Version 1" as the option, the UDP package is send with v2c. Checked this with wireshark, added the screenshots.

Metasploit version 6.1.14-dev

Did you install Metasploit with...

* [X] Kali package via apt ()
* [ ] Omnibus installer (nightly)
* [ ] Commercial installer (from https://www.rapid7.com/products/metasploit/download/)
* [ ] Source install (please specify Ruby version)

![2021-11-02_12-05](https://user-images.githubusercontent.com/47627831/144200878-243b152b-4c24-4de1-ac6a-6d14310f066b.png)

**Comment by h00die** [comment]
Confirmed.

This is caused by a string comparison when building the packet [here](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/snmp.rb#L263) and [here](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/snmp.rb#L283).  However the string is being replaced by a symbol [here](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/snmp.rb#L52) before being thrown to those functions [here](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/snmp.rb#L101).

Fix inbound.

**Comment by usd-markus** [comment]
everything working as expected now, thanks for looking into this :)
