### ISSUE TITLE
Windows 11 - Metasploit not installing in C:\metasploit-framework

### ISSUE THREAD

**Issue by Qardruss** [rapid7/metasploit-framework#15942]
## Steps to reproduce

(Prepare Windows 11 Computer/VM)
1. Install Metasploit from the MSI package
2. Check C:\metasploit-framework

## Were you following a specific guide/tutorial or reading documentation?
- I was using the Github Wiki for Metasploit to install it
- https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers#installing-metasploit-on-windows

## Expected behavior
- Metasploit installs perfectly and is ready for pwning some CTFs

## Current behavior
- C:\metasploit-framework doesn't exist and msfconsole command doesn't exist either

### Metasploit version
- Doesn't even work

## Additional Information
- Doesn't even work

**Comment by gwillcox-r7** [comment]
This is likely your AV catching the files, or when you ran the installer you specified a different directory. Have you ensured that Windows Defender has been disabled and that Real Time Scanning has been disabled? You will also need to add an exception for that directory to your AV program otherwise Windows Defender or whatever AV program you are using will continue to detect it.

**Comment by Arkapravo-Ghosh** [comment]
Try disabling Microsoft Defender

**Comment by Qardruss** [comment]
I don't use it, and my AV is whitelisted
