### ISSUE TITLE
Python Meterpreter

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#15996]
I found this branch https://github.com/rapid7/metasploit-payloads/tree/master/python/meterpreter
This is supposed to upgrade my python/meterpreter session with all functions including screenshot, keyscan and all functions, right?
If yes, How can I manually implements these scripts?

Help please

**Comment by gwillcox-r7** [comment]
@czonta96 Explain what you mean by manually implement? The code spans multiple languages and is quite complex so I imagine implementing small parts as needed would likely be best approach; if your looking to reimplement the whole system though, @OJ has a lot more experience on this than I do and might be able to guide you more if that is what you are interested in.

As for screenshot, keyscan, and related functions, I think some of the code is implemented there but if you look at https://github.com/rapid7/metasploit-payloads/blob/master/python/meterpreter/meterpreter.py#L330 you can see that it implements `stdapi_ui_desktop_screenshot`. Looking for `desktop_screenshot` we can see the code is implemented at https://github.com/rapid7/metasploit-payloads/blob/6e08d1f9812aa4d7a76b451fd5e0bae03975bb91/c/meterpreter/source/extensions/stdapi/server/ui/desktop.c#L400 in C code.

Hope that helps 👍

**Comment by smcintyre-r7** [comment]
> I found this branch https://github.com/rapid7/metasploit-payloads/tree/master/python/meterpreter

That's actually not a branch, but rather the directory in which the source for the Python Meterpreter is stored.

> This is supposed to upgrade my python/meterpreter session with all functions including screenshot, keyscan and all functions, right?

No, it's just the Python Meterpreter, which like the others implements a subset of the overall functionality. It doesn't look like the Python Meterpreter implements keyscan, or screenshot functionality because it hasn't be implemented.

If you try to run the `screenshot` Meterpreter command on a `python/meterpreter` session, you'll receive the following error message stating that it's not supported:

```
meterpreter > screenshot
[-] The "screenshot" command is not supported by this Meterpreter type (python/linux)
meterpreter > 
```

What @gwillcox-r7 is referring to [on meterpreter.py#L330](https://github.com/rapid7/metasploit-payloads/blob/c3b9bbc18889f952b65d1905cc07424141dc86f3/python/meterpreter/meterpreter.py#L330) is actually a constant definition. The individual functions are actually "registered" using the `register_function` decorator and use the same name as their command (for example: [`stdapi_sys_process_execute`](https://github.com/rapid7/metasploit-payloads/blob/c3b9bbc18889f952b65d1905cc07424141dc86f3/python/meterpreter/ext_server_stdapi.py#L1154)) but there is none for `stdapi_ui_desktop_screenshot` in the Python Meterpreter.
