### ISSUE TITLE
how to uninstall app on android with meterpreter forcefully

### ISSUE THREAD

**Issue by QinnStar** [rapid7/metasploit-framework#15995]
when i run "app_uninstall com.package"

it shows the uninstall window in my android....Is there any way to uninstall the app forcefully without letting the victim known..?

by using shell or any other command?

can anyone help with it?

**Comment by timwr** [comment]
You need to be root, or su.
`# pm uninstall com.package` I think

**Comment by QinnStar** [comment]
> You need to be root, or su. `# pm uninstall com.package` I think

i tried it..but it shows "unknown command : pm"

**Comment by gwillcox-r7** [comment]
Are you doing this from `meterpreter` shell or from the actual ADB shell itself? You will need to execute this from the ADB shell itself. A quick google of your issue turned up https://programmer.help/blogs/android-silent-install-app-and-silent-uninstall-app.html which seems to suggest @timwr's suggestion would be the proper way to do this as the code they provide just is a wrapper around the `pm install` and `pm uninstall` commands.

Another quick Google also shows https://coderedirect.com/questions/158064/uninstall-app-silently-with-system-privileges however this requires the manifest file shipped with your APK also has the `<uses-permission android:name="android.permission.DELETE_PACKAGES"/>` line added to it, after which you can use the `installPackage` and `deletePackage` methods.
