### ISSUE TITLE
How to use client.fs.file.expand_path() in a module?

### ISSUE THREAD

**Issue by Biaogo** [rapid7/metasploit-framework#15993]
I customized a module, but I don’t know how to make the client run normally?

**Comment by smcintyre-r7** [comment]
If you're writing a post module, what you want to do is `include Msf::Post::File` and then call `expand_path`. This has the advantage of checking what the session type is instead of always assuming it's the Meterpreter function.

[post/windows/gather/credentials/gpp.rb](https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/credentials/gpp.rb) would be a good example of this. You can see [here](https://github.com/rapid7/metasploit-framework/blob/647a73fd47b3f85d1e6d3a0af1583f4dc42cf65d/modules/post/windows/gather/credentials/gpp.rb#L8) it includes the mixin, and then [here](https://github.com/rapid7/metasploit-framework/blob/647a73fd47b3f85d1e6d3a0af1583f4dc42cf65d/modules/post/windows/gather/credentials/gpp.rb#L93) it calls the function.
