### ISSUE TITLE
Elevated msi file downloads something?

### ISSUE THREAD

**Issue by Idlefase** [rapid7/metasploit-framework#16149]
## Summary

When i run the nightly msi installer from this repo it spawns a elevated msi ( after summary and is signed). Does it downloads files? Like libs? And is this method secured or signed in any way?

## Relevant information

Ive recoverd the msi file and whitelisted its file ID, Path ( C:/metasploit, the correct way.) and disabled the av Just in case. 

File insight stated that it had indicators of network attacks and the firewall was turned on.

**Comment by gwillcox-r7** [comment]
@Idlefase File Insight will likely detect it since many things in Metasploit will trigger AV. It is a exploit development framework after all 😄 We don't recommend installing it on any systems where you might need to have an active AV for this reason, and strongly encourage you to use a separate VM or similar that is dedicated to your testing environment.

As for downloading additional files, I don't believe the MSI installer does this and everything to install that version of Metasploit that the installer correlates to should already be within the MSI, however @adfoster-r7  might know more about the specifics of this. Note however that if you do something like `msfupdate` or similar then yes it would reach out to Git or similar and try pull the files needed to update itself which could also be part of what File Insight is detecting.

Hope that answers your questions :)

**Comment by Idlefase** [comment]
@gwillcox-r7 thanks in advance for your anwser.  It solved my problem.

**Comment by gwillcox-r7** [comment]
No problem @Idlefase, will close this issue now that you seem to have found a solution, glad to hear you got things solved 🥳
