### ISSUE TITLE
I have some thoughts

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#16333]
![424c11c936cfce5b9c9a1712f31b662b](https://user-images.githubusercontent.com/83517202/158030216-a4083938-9c50-4c8e-b60d-53b5ed8422ad.jpg)

**Comment by bcoles** [comment]
Metasploit projects welcomes pull requests.

* https://github.com/rapid7/metasploit-framework/wiki/Contributing-to-Metasploit
* https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

**Comment by smcintyre-r7** [comment]
So I may better understand the value proposition of this proposal, how is the current lack of compatibility with modern Android devices affecting your ability to use Metasploit to test and demonstrate vulnerabilities and attack paths?

Are there a bunch of exploits that can't be exploited because we don't have payloads that are compatible for instance?

We have a couple of spots where are payloads are a bit behind. Our efforts would be best invested where those payloads are most likely to be used which is why I'm trying to understand the current limitations. Some gaps in our ARM support come to mind.

**Comment by czonta96** [comment]
According to tests performed against an Android 11 (non-rooted), basic MP commands (which are meant to work even if device is un unrooted) are bugged. And I'm talking about basic commands:
-> Webcam_snap: using this will just cause main_activity to crash;
-> App_run/install/uninstall: not giving an output request in the target screen due to permission error (no output despite permissions are granted);
-> Send_SMS: permission error again despite it's all granted during the app installation.

This should not even be labeled as 'new-features', cuz it's morerly like about fixing. These commands are bugged 'cuz they're meant to work even if device is unrooted.

**Comment by smcintyre-r7** [comment]
Would you mind then reorganizing these thoughts into tickets for the individual bugs if they don't already exist? Including the steps to reproduce, the current errors and the Android details would be pretty helpful.

**Comment by czonta96** [comment]
Already did, it were ignored ---> https://github.com/rapid7/metasploit-framework/issues/16313
In the link u have the verbose output, there is no screenshot, becouse simply nothing happens on the target screen.
The apk used was just the basic vanilla payload made with msfvenom. I already tried all stagers, verbose result never change. Perfect tunnel relay through Portmap.io was used, so it's not even a matter of connectivity, they are just bugs. Hope they will be patched in some way.

**Comment by smcintyre-r7** [comment]
Alright, thanks! Since it's a duplicate ticket, then I'll go ahead and close this one.
