### ISSUE TITLE
How can I add if I can? : TLV_TYPE to sysinfo.rb 

### ISSUE THREAD

**Issue by ALLERRORr** [rapid7/metasploit-framework#16392]
I would like to add 6 APIs for sysinfo to get more information from the victim's computer.
Here is the API But I don't know if ruby would behave well with more API in the system type if there would be a conflict in the code.

TLV_TYPE_BIOS_INFO

TLV_TYPE_CPU_INFO

TLV_TYPE_GPU_INFO

TLV_TYPE_DRIVER_INFO

TLV_TYPE_WEBCAM_INFO_ON_LED_OFF_LED

TLV_WAN_LOCAL_INFO

would have a chance?

sysinfo would look like this
![1Sysinfo](https://user-images.githubusercontent.com/43153257/160690267-42b0bb71-48e6-4847-9792-78a1f0536484.PNG)

**Comment by timwr** [comment]
I'd be wary of modifying sysinfo, mostly because it's invoked automatically when the session is established. This means if it goes wrong (e.g crashes, takes too long or triggers AV) you're potentially breaking the session for users that don't care about this information.  Instead why not add or modify one of the existing post/gather modules to lookup this information? I bet there are some that do similar lookups you could extend.

**Comment by ALLERRORr** [comment]
thanks man for giving this tip I didn't really think about the post/windows/gather. I'm in doubt under 'msf/core' I see some code using this lib. stdapi gives a lot of errors and loses connection you're right. so thank you very much have a nice day.
