### ISSUE TITLE
Unable to install Metasploit on Windows 11

### ISSUE THREAD

**Issue by JamesR404v2** [rapid7/metasploit-framework#16463]
## Steps to reproduce

Download Nightly Build of Metasploit for Windows. Attempt to install.

## Expected behavior

Installation should complete successfully.

## Current behavior

Installation fails with error:

"Setup Wizard ended prematurely because of an error", Windows event Viewer application log shows:

Windows Installer installed the product. Product Name: Metasploit-framework v6.1.39. Product Version: 6.1.39.1. Product Language: 1033. Manufacturer: Rapid7 Release Engineering <r7_re@rapid7.com>. Installation success or error status: 1603.

### Metasploit version

v6.1.39 the installer says.

Nightly build downloaded on 2022-04-16 and again on 2022-04-17. 

### Windows version

Windows 11 Version 22H2 (OS Build 22598.1)

**Comment by bcoles** [comment]
Run the installer with elevated privileges.

**Comment by JamesR404v2** [comment]
Yes, thank you. That fixed the issue.

I had to use an elevated command prompt. It was interesting, because the
windows account I used was already an Administrator, but that wasn't
sufficient.

**Comment by GetRektBoy724** [comment]
Just a small tip, it's not recommended to install the Metasploit Framework on Windows directly, since Windows AVs will probably fucked up the framework files and messes things up generally. It's more recommended to install Kali WSL2 and install the Metasploit Framework in it. Btw if your issues are resolved, please consider closing it :)
