### ISSUE TITLE
The The ngx_http_parse_chunked for ubuntu 13.04

### ISSUE THREAD

**Issue by gabriel27660211** [rapid7/metasploit-framework#16568]
Hello world!

I wanna to have access to my computer(I manage a e-comerce glasses online store) which are located in other place.I tried to control it with Citrix Metaframe but I dont Know to configure it. Thus I decided to take advantage of a vulnerabilitie on nginx(The ngx_http_parse_chunked) server to gain control. Despite I have all the credential the exploit didn't work. I think is because the exploit only works for a Ubuntu 13.04 and I have Ubuntu 16.04. I an not software engineer, only I follow the advice that my expert on computers provide me(but he didn't know!). So I need someone explain me how to code the default exploit(https://www.exploit-db.com/exploits/25775) in order to programe it to catch Ubuntu 16.04 machines in step Ubuntu 13.04.

**Comment by smcintyre-r7** [comment]
Switching this from bug to module suggestion since you're asking for a new target to be added to the exploit.

So the vulnerability ([CVE_2013-2028](https://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2013-2028)) affects nginx versions 1.3.9 through 1.4.0. [Ubuntu 16.04 (Xenial)](https://launchpad.net/ubuntu/xenial/+source/nginx) appears to have been released with nginx 1.9.3 as the oldest build I can reference. Based on this I would say it is safe to assume that Ubuntu 16.04 is not affected. If it were affected, the user would have installed a vulnerable version of nginx from source. Given that's the case, it's very possible that the compilation environment and arguments would affect the values necessary to know for exploiting this vulnerability due to it being memory corruption. That is to say, that I'm not confident that if we even installed a vulnerable version of nginx, the exploit on our test system would work on your server.

You're better off using a different solution to configure and manage your server.

**Comment by gabriel27660211** [comment]
> Switching this from bug to module suggestion since you're asking for a new target to be added to the exploit.
> 
> So the vulnerability ([CVE_2013-2028](https://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2013-2028)) affects nginx versions 1.3.9 through 1.4.0. [Ubuntu 16.04 (Xenial)](https://launchpad.net/ubuntu/xenial/+source/nginx) appears to have been released with nginx 1.9.3 as the oldest build I can reference. Based on this I would say it is safe to assume that Ubuntu 16.04 is not affected. If it were affected, the user would have installed a vulnerable version of nginx from source. Given that's the case, it's very possible that the compilation environment and arguments would affect the values necessary to know for exploiting this vulnerability due to it being memory corruption. That is to say, that I'm not confident that if we even installed a vulnerable version of nginx, the exploit on our test system would work on your server.
> 
> You're better off using a different solution to configure and manage your server.

When I want to exploit, says "exploit unreachable" all te previous step was sucedeed but return me the message in the end. What's the solution then?

**Comment by gabriel27660211** [comment]
> Switching this from bug to module suggestion since you're asking for a new target to be added to the exploit.
> 
> So the vulnerability ([CVE_2013-2028](https://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2013-2028)) affects nginx versions 1.3.9 through 1.4.0. [Ubuntu 16.04 (Xenial)](https://launchpad.net/ubuntu/xenial/+source/nginx) appears to have been released with nginx 1.9.3 as the oldest build I can reference. Based on this I would say it is safe to assume that Ubuntu 16.04 is not affected. If it were affected, the user would have installed a vulnerable version of nginx from source. Given that's the case, it's very possible that the compilation environment and arguments would affect the values necessary to know for exploiting this vulnerability due to it being memory corruption. That is to say, that I'm not confident that if we even installed a vulnerable version of nginx, the exploit on our test system would work on your server.
> 
> You're better off using a different solution to configure and manage your server.

Besides, the nmap vulnscan show me this vuln. Ir is strange because is my computer.

**Comment by bcoles** [comment]
This module only has targets for:

* Ubuntu 13.04 32bit - nginx 1.4.0
* Debian Squeeze 32bit - nginx 1.4.0

> So I need someone explain me how to code the default exploit

A lot of exploit development discussion occurred in the associated pull request. #1834

> Besides, the nmap vulnscan show me this vuln.

Which nmap script are you using? What output did you get?

If you're referring to [vulscan](https://github.com/scipag/vulscan), this tool uses version matching rather than testing for vulnerabilities. It likely saw the nginx version string and pattern matched it against known vulnerabilities in this version. This doesn't mean the service is vulnerable.

> When I want to exploit, says "exploit unreachable" all te previous step was sucedeed but return me the message in the end. What's the solution then?

"exploit unreachable" is not something that Metasploit says. It might have said something like "Exploit failed: unreachable" which means the remote port on the remote host was not reachable.

**Comment by bcoles** [comment]
Closing as dupe of #16637.
