### ISSUE TITLE
Mozilla Firefox Bootstrapped Addon Social Engineering Code Execution - Metasploit

### ISSUE THREAD

**Issue by guest2921** [rapid7/metasploit-framework#16799]
[BUG REPORT]
leaving the default options on the msfconsole unchanged for testing purposes (testing on lan against myself)
once I open the browser to install the add-on I just get "error: the addon is corrupted" with no verbose error log on the console.

Tested against Firefox ESR (current version)

**Comment by bcoles** [comment]
I've updated the module documentation in PR #16983 to describe the scenarios in which this modules is expected to work correctly.

The Firefox extension format changed in ~2017 (see reference URLs in #16983). The `firefox_xpi_bootstrapped_addon` module uses the `Exploit::Remote::FirefoxAddonGenerator` library to generate a Firefox extension. This library has not been updated in many years and generates extensions in a "legacy" format which is no longer supported.

Firefox now requires extensions to be signed (see reference URLs and description in #16983). While it is still possible to install unsigned extensions on some non-mainline builds of Firefox in a non-default configuration, this is an extremely limited use case.

Personally, I'm not interested in updating the library to support new extension formats due to limited usefulness. Given that Firefox stopped supporting legacy extensions more than 5 years ago and no-one has since stepped up to update the `Exploit::Remote::FirefoxAddonGenerator` library, it is fairly safe to say that this issue won't be fixed any time soon.

Unfortunately this is a WontFix for now, unless someone volunteers to step up and add support for the new extension format.

Pull requests are welcome should someone take an interest in submitting a well-written update to the `Exploit::Remote::FirefoxAddonGenerator` library which supports new and legacy extension formats. Note that existing modules which depend on this library will also need to be updated to support generating legacy extensions.

```
# grep -rn FirefoxAddonGenerator modules/
modules/exploits/multi/browser/firefox_xpi_bootstrapped_addon.rb:12:  include Msf::Exploit::Remote::FirefoxAddonGenerator
modules/exploits/multi/browser/firefox_proto_crmfrequest.rb:11:  include Msf::Exploit::Remote::FirefoxAddonGenerator
```
