### ISSUE TITLE
Describe yourself as a Metasploit user

### ISSUE THREAD

**Issue by jharris-r7** [rapid7/metasploit-framework#16804]
Hello folks! Made a new poll because the other got deleted. If you could answer this one, we would so appreciate it!

Poll here: https://github.com/rapid7/metasploit-framework/discussions/16803

**Comment by loneicewolf** [comment]
I am not using it very much; I am mostly using it if I absolutely must; like, if there is no other choice; if it is impossible(or need considerable effort) to re-create anything I need metasploit to do;  
I am not saying MSF is bad! it's GORGEOUS, but - in my kind of 'do it yourself' view, (as I always have) I re create stuff in C or Python; mostly. Like shell codes n stuff. no real reason to **every time** go to msfvenom to *JUST* `make a shellcode that will, say, pop a reverse shell. ` it is detected too, extremely much.. (`not saying this is a problem!`)

I am just answering the question @jharris-r7  wrote; :) And as said; MSF is brilliant, but if I can make it myself, why not :)
And as I am the slowest when it comes to code/reversing, this is for me extra important, it takes time - of course, more time than anyone else (because I am **so slow**) but I get there eventually

I guess that `describes me as a Metasploit user`?

**Comment by loneicewolf** [comment]
just to not make any mistake or something;
### Metasploit & Rapid7 is BRILLIANT.
**no two ways about that; it's 100% true. `More than 100%`.**

**Comment by jharris-r7** [comment]
Thanks so much for your input and for taking the time to respond! :)

**Comment by loneicewolf** [comment]
> Thanks so much for your input and for taking the time to respond! :)
Heh.. no worries! nothing great about me but all greatness is MetaSploit and Rapid7. here we talk about being totally Pure brilliant. 

# Rapid7 is **GOLD**.


Will likely not be any more active on this thread/string soo.. 
contact info is located on my profile (in github). anyway; have it great!

**Comment by francoataffarel** [comment]
Atualmente sou estudante do OSEP, e utilizo muito o MSF contudo a inicialização é muito lenta. Isso é normal.? CErca de 20 min

**Comment by archuser555** [comment]
I like it, it's free and open source, i think someone should make a web interface for it

**Comment by loneicewolf** [comment]
> I like it, it's free and open source, i think someone should make a web interface for it
isn't there one? I am sure it is but I don't know the name..
anyway have it great!

**Comment by h00die-gr3y** [comment]
I can not agree more with @loneicewolf. 

It is a great tool with excellent support.
A must have for every hacker...

I am using it a lot in my engagements and it also fun to write your own modules if you have time left...

Keep up the good work, folks !

**Comment by gwillcox-r7** [comment]
> I am currently a student of OSEP, and I use MSF a lot, however the initialization is very slow. This is normal.? about 20 min

Hmm this shouldn't be happening, should only take a few seconds to start up. What version of Metasploit are you running and how did you install it? If you have some replication steps we can look into this more and see if we can reproduce it so that we can investigate a fix if appropriate.

**Comment by gwillcox-r7** [comment]
> I like it, it's free and open source, i think someone should make a web interface for it

Unfortunately there are no plans for us to develop for a web interface for Metasploit Framework at the moment 😅 There is however Armitage which can be thought of as a GUI interface similar to Cobalt Strike. Its no longer maintained by its original developers but has been forked and now appears to be community maintained given https://www.kali.org/tools/armitage/ links to https://github.com/r00t0v3rr1d3/armitage. That might fit the bill for what you are after.

The only other web interface I am aware of is our Metasploit Pro offering which is the paid version of Metasploit Framework and which comes with some extra features related to automation as well as a web interface to help make some features easier to use.

**Comment by loneicewolf** [comment]
# RAPID7 is still GOLD. Keep up the good work guys.
`// will over n out.`
