### ISSUE TITLE
Is there a reason we don't use systeminfo for Windows ID

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-framework#16993]
Just noticed that on my Windows 2003 VM, I get the following values for `systeminfo`:
```
Computer        : WIN2K3X64-SP1
OS              : Windows .NET Server (5.2 Build 3790, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : EXAMPLE
Logged On Users : 2
Meterpreter     : x64/windows
```

Our fingerprinting for friendly OS names is not great.  My guess is that historically, we did not use `systeminfo` because it was not supported until Windows XP, but I think pre-XP hosts are getting pretty scarce at this point, and we could do a much better job enumerating OS names by querying `systeminfo` at this point, rather than guessing the value based on the kernel version.

**Comment by bcoles** [comment]
At a guess, execution time may be one reason. `systeminfo` takes ~5 seconds on a mostly clean Windows XP SP3 system (2 CPU cores; 2GB RAM; no user processes running). Execution time increases with sysyem age as patches are enumerated. Retrieving network info might also impact execution time.

Also, this approach requires executing the `systeminfo` program, rather than a library call.
