### ISSUE TITLE
Add tests for #17072 (shell command tokens w/echo)

### ISSUE THREAD

**Issue by smcintyre-r7** [rapid7/metasploit-framework#17080]
Add a test to https://github.com/rapid7/metasploit-framework/blob/master/test/modules/post/test/cmd_exec.rb for testing the fix/ functionality provided by #17072.

**Comment by hamax97** [comment]
I'm trying to find out now how to test #17072. Can you please assign this to me?

**Comment by hamax97** [comment]
@smcintyre-r7 As discussed 3 weeks ago in Slack this can be closed. This is quote from you:

`"The post/test/file module calls file_rm among other things so I don't think we need to duplicate that. I don't quite remember what I was hoping to get out of that ticket, someone probably asked me to open it for them. We can probably just close it"`

Maybe this can be closed so that people won't keep trying to work on this.
