### ISSUE TITLE
Meterpreter caught by AV when migrating into explorer.exe

### ISSUE THREAD

**Issue by Reversing26** [rapid7/metasploit-framework#17120]
How to fix?

**Comment by Xm-ploit** [comment]
If you are running your own PC , you can close
antivirus to test.

"Metasploit" is one of the most popular pentesting framework,so the techniques and payloads it use are flagged by every AV.

If you want to test exploit and see the way that a malware works,you can use the function embdded in metasploit.
However,if you want to test exploit and run malware under AVs,the metasploit is not enough.

You need to have basic skills on computer science,paticularly c,assembly language ,operating system......

Then you can use those knowledges to cooperate with metasploit framework and you will find every AV is blind
(You wont trust AVs anymore)

**Comment by Reversing26** [comment]
I was able to bypass AV, the detection happens just when I try to migrate to explorer.exe
It won't get detected however if I try to migrate in different proc, it is happening just if migration is performed against explorer.exe

**Comment by Slavfucious** [comment]
easy fix for win defender, for others, idk
#ANTIVIRUS EXCLUSIONS
powershell -Command Add-MpPreference -ExclusionPath "C:\Windows\"
powershell -Command Add-MpPreference -ExclusionProcess "java.exe"
powershell -Command Add-MpPreference -ExclusionExtension ".exe"

**Comment by gwillcox-r7** [comment]
> I was able to bypass AV, the detection happens just when I try to migrate to explorer.exe It won't get detected however if I try to migrate in different proc, it is happening just if migration is performed against explorer.exe

Certain processes may be more heavily monitored than others by AV which may explain this difference. For instance SAM related processes tend to be heavily monitored by AV due to their sensitivity, whereas other processes may not be as heavily monitored.

Without knowing the internals of the AV though is hard to say. Every AV has its own set of rules and on way of dealing with things.

Closing this out as this is more of a speculative question at this point and now turns more into the specifics of the AV itself vs anything to do with Metasploit, hopefully this answer helps though.
