### ISSUE TITLE
Payloads - This app can't run on your PC

### ISSUE THREAD

**Issue by delightfuldallas** [rapid7/metasploit-framework#17137]
Hello guys, i tried to access my PC from my kali laptop but when i generate an exe payload and try to run it on my windows pc says it cant run on this pc. AV id disabled. Am i doing smth wrong or payload files are outdated ? Im using Windows 10

**Comment by bcoles** [comment]
> i generate an exe payload

How did you generate the payload?

> my windows pc says it cant run on this pc

Microsoft is a multi-billion dollar company. I find it hard to believe their operating system says "it cant run on this pc".

**Comment by gwillcox-r7** [comment]
@bcoles It could be that the payload was generated using the wrong architecture or was simply formatted incorrectly (example trying to stuff a android binary into a Windows EXE will result in a valid EXE however you would get that "this can't run on this PC" error"). 

Similar errors may also be encountered for instance if you try to make a ARM64 binary run on a x64 platform.

I would check that the payload you are using is correct, the architecture you are specifying is correct, and that you are outputting to an EXE.

If you can send the actual command your using as I see you didn't fill out the template as we suggested, then we might be able to help you further with this. Otherwise this is as far as we can assist you on this issue without you providing more detailed info on steps provided and output encountered.

**Comment by bcoles** [comment]
> @bcoles It could be that the payload was generated using the wrong architecture or was simply formatted incorrectly (example trying to stuff a android binary into a Windows EXE will result in a valid EXE however you would get that "this can't run on this PC" error").

Microsoft is a multi-billion dollar company. I find it hard to believe their operating system says "it cant run on this pc".

There is insufficient information to reproduce this issue. OP wants us to play guessing games. Closing.
