### ISSUE TITLE
apache common-texts: cve-2022-42889

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#17159]
https://securityboulevard.com/2022/10/new-text2shell-rce-vulnerability-in-apache-common-texts-cve-2022-42889/

**Comment by pwnb0y** [comment]
I would like to work on this issue

**Comment by h00die** [comment]
go for it!

**Comment by gwillcox-r7** [comment]
Looks like there is a potential PoC and Docker container over at https://github.com/Dima2021/cve-2022-42889-text4shell and some writeups at https://sysdig.com/blog/cve-2022-42889-text4shell/. Going to see if I can't grab this and make a module.

**Comment by gwillcox-r7** [comment]
After looking into this further I think it will be hard to make a module for this that is generic enough to be used in a wide variety of scenarios. Combined with the fact that the target needs to be using the vulnerable component in a way where malicious input is passed to the vulnerable component, which is not common, makes this less valuable of a module to add.

I don't forsee this becoming more valuable in the future. For our stance on this vulnerability see https://attackerkb.com/topics/98L4lvgOD1/cve-2022-42889 and our assessment there; I think that summarizes a lot of the feeling atm surrounding this bug and its limits.

Given these limitations I'm going to close this out for now. I doubt we will reopen this in the future but if some information does surface which would convince us otherwise, we can examine this again at that point.

**Comment by h00die** [comment]
I spoke with @catc0n about this and she had agreed with @gwillcox-r7
