### ISSUE TITLE
ProxyShell exploit maxing out at 100 email addresses

### ISSUE THREAD

**Issue by digininja** [rapid7/metasploit-framework#17206]
I think this is a limitation with the module, I'm trying to work through it but figured I'd ask as it is slow going.

I'm  using `windows/http/exchange_proxyshell_rce` against a fairly large client. It does the enumeration call to `autodiscover/autodiscover.xml` and says it got 100 addresses back, it then goes through and tries to find a vulnerable one. The list it runs through starts with addresses starting with 'a' and ends in the middle of the 'c's which suggests that there is some pagination going on and all I'm getting is the first 100 hits back.

For some reason I can't reproduce the request in Burp so I can't fiddle with it to see exactly what is going on even though I've put debugging in to see exactly what is being called.

My xml skills are limited so it may be as easy as adding a new field to the request for a million records, but I've had a dig through the schemas and can't see anything obvious.

Is it a limitation of the module or the server? Can anything be done? Am I just stuck with 100 results?

**Comment by smcintyre-r7** [comment]
Alright, I was able to reproduce this and I think you're right it's probably a paging issue because there isn't any paging.

I used [davidprowe/BadBlood](https://github.com/davidprowe/BadBlood) to populate my AD instance with 2,500 users (the default number) and then created mailboxes for each of them using `Get-User | Enable-Mailbox` from the Exchange Powershell console.

**Comment by digininja** [comment]
My client upgraded their server so I can't help in any further testing, but it would be good to have it fixed in case I ever come across it again.
