### ISSUE TITLE
add CVE-2022-41352

### ISSUE THREAD

**Issue by julirc** [rapid7/metasploit-framework#17201]
Dear Team,

I have not been able to test and check CVE-2022-41352 in zimbra.

**Comment by bcoles** [comment]
If you run the module with `set HttpTrace true` you can see the HTTP requests and responses generated during `check` and `exploit`. This may help with debugging.

**Comment by gwillcox-r7** [comment]
Removing suggestion-module label since we already have a module for this CVE in Metasploit and that tag is designed to be used to request new modules for inclusion in Metasploit. Since this is more of a question I've added the appropriate question label.

**Comment by gwillcox-r7** [comment]
Without further details or output @julirc I'm not sure we are going to be able to help you much here. Try @bcoles advice, otherwise I'd recommend opening a new issue with more details and following the issue template to be sure you provide the appropriate level of detail r.e your setup, what steps you tried, the output you got, and what your issue is.

Closing this issue due to insufficient information provided to replicate the issue.
