### ISSUE TITLE
kali linux exploit problem

### ISSUE THREAD

**Issue by nfxtr** [rapid7/metasploit-framework#17510]
Im trying to generate a trojan with using veil and try to download it with virtual machine. But when I start to exploit and download the trojan with windows there is no any changes in exploit. I started apache2 also and did everything but I couldnt fix ythe problem. Please help.
![Ekran Alıntısı](https://user-images.githubusercontent.com/113991747/213556377-5b680355-d0c4-46ca-b8a7-d27994f14bcb.PNG)

**Comment by gwillcox-r7** [comment]
This is a question for `veil` not for Metasploit Framework specifically. Additionally, even if it were a problem with Metasploit, which it doesn't seem to be, we would need more details on what you actually did to debug this.

Closing this as it doesn't seem to be a Metasploit related problem and also due to lack of info.
