### ISSUE TITLE
 rvm/gems/ruby-3.1.3/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2

### ISSUE THREAD

**Issue by Vineeta2000** [rapid7/metasploit-framework#17627]
I am facing  this issue when i am upgrading my rails project from rails version 5 to 6.1.7.2 . Can anyone help me to resolve my issue

**Comment by bcoles** [comment]
This warning is due to using an outdated version of bundler: 1.17.3

Version 2.4.6 is the latest https://rubygems.org/gems/bundler

Update your bundler gem.

```
bundle update --bundler
```

Metasploit is bundled using 2.1.4:

https://github.com/rapid7/metasploit-framework/blob/86fc6172591616dccedbe9bb4c8abbcc27fdcd4f/Gemfile.lock#L526-L527

**Comment by gwillcox-r7** [comment]
Closing this issue to resolved comment above and this being a question that appears to be unrelated to Metasploit Framework itself.
