### ISSUE TITLE
Warning: metasploit-framework/apt/dists/lucid/InRelease Key is stored in legacy trusted.gpg

### ISSUE THREAD

**Issue by DruidicBearClan** [rapid7/metasploit-framework#17636]
## how to reproduce

command:
apt update 

## Problem description
updating system on ubuntu causes warnings about the key being stored in legacy trusted.pgp keyring (deprecated)

## Metasploit and Ubuntu version
metasploit v6.3.3-dev
OS: ubuntu 22.04
uname -a: 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## Expected behavior
for the key to be stored in /usr/share/keyrings instead

## Current behavior

Key is stored in legacy /etc/apt/trusted.gpg instead.  

How to resolve this issue for myself in the correct manner?

**Comment by gwillcox-r7** [comment]
This issue seems to be specific to the Omnibus installers of which the `apt` installers are a part of. It is likely more appropriate for you to raise your issue over at https://github.com/rapid7/metasploit-omnibus. I'm going to close out this issue here since this is for issues in Metasploit Framework itself, not how it is packaged, which is Omnibus's reponsibility.

Please reraise this ticket over at https://github.com/rapid7/metasploit-omnibus and I'm sure one of the team members will be able to help you out 👍
