### ISSUE TITLE
 Exploit failed [no-access]: RubySMB::Error::UnexpectedStatusCode The server responded with an unexpected status code: STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by abid000007** [rapid7/metasploit-framework#17703]

**Comment by abid000007** [comment]
![image](https://user-images.githubusercontent.com/123622419/221400254-c26af9ea-6283-4da3-9a97-02be1f94a7d2.png)

**Comment by bcoles** [comment]
Does the user have admin permissions?

https://github.com/rapid7/metasploit-framework/blob/47652e3b19b92636fdb9184a892290514fa845b6/modules/exploits/windows/smb/psexec.rb#L29-L33

Does the target system have Remote UAC disabled? Refer to:

* https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/windows/smb/psexec.md#disabling-remote-uac

**Comment by gwillcox-r7** [comment]
Lack of sufficient information here and didn't follow the template. @bcoles also added an explanation above for possible things to check. Closing this out due to lack of information available to replicate. Once sufficient information is available and the information requested within the issue template has been supplied we can look into this further.
