### ISSUE TITLE
Database Service command sorting not retained on output to CSV 

### ISSUE THREAD

**Issue by stephenbond** [rapid7/metasploit-framework#17714]
## Steps to reproduce

How'd you do it?

msf6 > services -u -O 1 -o int-services.csv

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

The data in the CSV file is sorted via 'host' column 1.

## Current behavior

Data in CSV is sorted via port
If you omit '-o' the data is sorted as expected. 

### Metasploit version

6.3.5-dev-

## Additional Information

n/a

**Comment by manishkumarr1017** [comment]
I want to contribute on this issue. This issue caused by one of the gems that metasploit is using to display and store the table information.
`Rex::Text::Table` is not sorting the data when getting saved into a csv file.

**Comment by gwillcox-r7** [comment]
@manishkumarr1017 Will assign you to this issue so long, let us know if you need any info to assist 👍

**Comment by manishkumarr1017** [comment]
I was able to find the root cause of this issue. This issue is coming from the gem rex-text.
In the file `lib/msf/ui/console/command_dispatcher/db.rb` on line number 895.
```
# the `tbl` is an object of class `Rex::Text::Table`
# tbl.to_csv is not sorting the rows where tbl.to_s does sort the rows.
::File.open(output_file, "wb") { |f| f.write(tbl.to_csv) }
```
As we can check from the code of https://github.com/rapid7/rex-text/blob/master/lib/rex/text/wrapped_table.rb
It is clear that in the file `lib/rex/text/wrapped_table.rb`

```
  def to_s
    sort_rows
```
But in to_csv we are not sorting the rows. So shall I keep a PR for this repo https://github.com/rapid7/rex-text to solve this issue?

**Comment by gwillcox-r7** [comment]
@manishkumarr1017 Sounds like you have it right and should be putting up a PR to https://github.com/rapid7/rex-text as you suspected 👍

**Comment by stephenbond** [comment]
Hi @manishkumarr1017, thanks for looking into this!
