### ISSUE TITLE
do i need to connect my phone to the same rooter to hack it or not ?

### ISSUE THREAD

**Issue by jcole2244** [rapid7/metasploit-framework#17815]
hey guys i have to routers at home 1 and 2
can i hack my phone if it is connect to router 1 and my on router 2 ?
or my phone must connect to the same router that my pc is connected to hack the phone or not ?

**Comment by bcoles** [comment]
If you can establish a TCP connection between the two networks then you can get a session.

**Comment by Rutu83** [comment]
Learn about port  Forwarding where you get all of your answers.

**Comment by shaurya1026** [comment]
If your phone is connected to Router 1 and your computer is connected to Router 2, it is unlikely that you can hack your phone straight from your computer. Because the IP addresses and networks of the two routers are different, devices connected to one router cannot communicate directly with devices on the other router's network.

But, you can still hack your phone using other methods such as phishing attempts, social engineering, or software vulnerabilities.

**Comment by bcoles** [comment]
Dupe of #17814.

It is possible with tunneling and port forwarding, but the easiest solution is to put both devices on the same network subnet.
