### ISSUE TITLE
CVE-2023-28252: Windows CLFS Privilege Escalation. 

### ISSUE THREAD

**Issue by jheysel-r7** [rapid7/metasploit-framework#17880]
# Summary 
Windows privilege escalation vulnerability via `clfs.sys` said to work on:  "supporting different versions and builds of Windows, including Windows 11"

No PoC as of now however more details are to be added to this blog post 9 days after April's patch Tuesday: https://securelist.com/nokoyawa-ransomware-attacks-with-windows-zero-day/109483/

**Comment by gwillcox-r7** [comment]
Not sure how readily exploitable this one is going to be, seems like CLFS bugs in the past have been rather difficult due to us needing to implement a lot of undocumented stuff to make them work; Also SecureList in the past has historically tried to redact certain details from their publications to prevent exploitation; I'm not sure they will be as easy to parse for details 🤔

**Comment by gwillcox-r7** [comment]
PoC for this now available at https://github.com/fortra/CVE-2023-28252

**Comment by jheysel-r7** [comment]
https://github.com/rapid7/metasploit-framework/pull/18250
