### ISSUE TITLE
Exploit for CVE-2023-25135

### ISSUE THREAD

**Issue by jvoisin** [rapid7/metasploit-framework#17894]
With a poc in python here: https://github.com/ambionics/vbulletin-exploits/blob/main/vbulletin-rce-cve-2023-25135.py

**Comment by gwillcox-r7** [comment]
Writeup at https://www.ambionics.io/blog/vbulletin-unserializable-but-unreachable for reference. Looks like a good candidate @jvoisin, going to need to look at where to set up a target though 🤔

**Comment by gwillcox-r7** [comment]
@jvoisin Out of curiosity would you happen to have a target for this available for testing or know someone who would be willing to lend theirs for testing? Looks like a new license for this product runs in the range of $256 or so, and I'm not sure they allow you to download older versions which will be needed to test this bug.

**Comment by gwillcox-r7** [comment]
@jvoisin Understandable, thanks for getting back to me on this. I'd be happy to accept a contribution with a PCAP showing it working against your lab target if that is something that would help move this forwards and you can't share your lab environment? Would that work for you? Otherwise this will likely need to wait until we can set up some way to verify the exploit either via PCAP or via us getting access to a lab to test this out in.
