### ISSUE TITLE
[?] Would you like to init the webservice? (Not Required) [no]: keep prompting user after each restart

### ISSUE THREAD

**Issue by danyk20** [rapid7/metasploit-framework#17922]
## Steps to reproduce

How'd you do it?

1. $ msfdb delete
    [?] Would you like to delete your existing data and configurations? []: yes
2. $ msdfdb init
     [?] Would you like to init the webservice? (Not Required) [no]: no
     ...
     Database initialization successful
4. $ msfdb stop
5. $ msdfdb start
     [?] Would you like to init the webservice? (Not Required) [no]: no

Why db always (after restart) ask me whether init the webservice? I have set it once when I initialise db (step 2.) and I don't want this :       
[?] Would you like to init the webservice? (Not Required) [no]:
to show every single time that I start DB.

## Were you following a specific guide/tutorial or reading documentation?
I was not able to find any way how to suppress this optional prompt in any tutorial or documentation.

## Expected behavior

1. $ msfdb delete
    [?] Would you like to delete your existing data and configurations? []: yes
2. $ msdfdb init
     [?] Would you like to init the webservice? (Not Required) [no]: no
     ...
     Database initialization successful
4. $ msfdb stop
5. $ msdfdb start
     not showing this prompt -> [?] Would you like to init the webservice? (Not Required) [no]:

What should happen?

Start db with initial settings or add some option to continue with default no without prompting the user.

## Current behavior

1. $ msfdb delete
    [?] Would you like to delete your existing data and configurations? []: yes
2. $ msdfdb init
     [?] Would you like to init the webservice? (Not Required) [no]: no
     ...
     Database initialization successful
4. $ msfdb stop
5. $ msdfdb start
     [?] Would you like to init the webservice? (Not Required) [no]: no

What happens instead?

Optional prompt shows after each restart (step 5.). 

### Metasploit version

Get this with the `6.3.13` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

## Additional Information
I am running macOS Ventura 13.3.1 (22E261)

**Comment by saurabhmj11** [comment]
It seems like the Metasploit Framework is designed to prompt the user for whether they would like to initialize the webservice or not after each restart. Unfortunately, there is no built-in option to disable this prompt in the Metasploit Framework. However, you may be able to work around this issue by modifying the Metasploit source code.

To do this, you can locate the source code file where this prompt is being displayed and comment out or remove the relevant lines of code. Alternatively, you can modify the source code to default to "no" instead of prompting the user each time.

Keep in mind that modifying the source code of the Metasploit Framework may have unintended consequences and may require some level of technical expertise. Additionally, any modifications made to the source code may be overwritten during future updates to the framework. Therefore, it is important to carefully consider the implications of modifying the source code and to keep a backup of the original files.

Alternatively, you can automate the process of starting the Metasploit Framework and supplying the "no" response to the prompt by creating a script or alias that automatically runs the necessary commands with the appropriate options. This will allow you to bypass the prompt entirely and streamline your workflow.

**Comment by cgranleese-r7** [comment]
Hi @danyk20, there was a recent PR that update some functionality around the `--use-defaults`. This flag will now allow users to skip the the web service prompt when initialising the database with that flag. See [here](https://github.com/rapid7/metasploit-framework/pull/18009) for more information.

Going to close this issue for now, but feel free to reopen if the PR's solution wasn't what you were after 👍
