### ISSUE TITLE
Avoiding loader lock on DLL payload

### ISSUE THREAD

**Issue by cookpoo78** [rapid7/metasploit-framework#18640]
Hey guys,
In the framework the main payload is being executed within DllMain PROCESS_ATTACH, for example [here](https://github.com/rapid7/metasploit-framework/blob/94a4a6173f22f2abda0bf35f46e09544ab09fc74/data/templates/src/pe/dll/template.c#L25) (I guess there are more examples here where the main payload is executed in the context of the current process rather than injection to another).
I'm very curious to understand how is that possible with the [loader lock](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices) held.
MSDN really discourages from doing actions like creating processes and so, so how we bypass that limitation and everything is running smoothly from Dllmain?

**Comment by cookpoo78** [comment]
still relevant

**Comment by smcintyre-r7** [comment]
It works because we inject the payload into a new process where it runs for an arbitrary amount of time. This technique is a combination of [Process Hollowing](https://github.com/rapid7/metasploit-framework/issues/18751) in the sense that we create a process in a suspended state and [Thread Execution Hijacking](https://attack.mitre.org/techniques/T1055/003/) due to how we update the process's main thread. It would be more traditional Process Hollowing if we bothered to unmap the existing executable sections memory and replaced it rather than allocating our own.

As for the load lock, those are just guidelines put forth by MSDN. It would be a larger problem for us if the functions we used required more DLLs to be loaded than those provided by kernel32. Kernel32 is pretty much always available in a target process, along with NTDLL. There are only a few rare exceptions.
