### ISSUE TITLE
Sync RubyReadline with vendor upstream and allow for 2.x compatibility

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#3791]
We currently vendor a modified version of ruby readline from 2011, however active development is still occurring in this gem, and the current rbreadline.rb code is preventing us from moving to Ruby 2.x.
* https://rubygems.org/gems/rb-readline

**Comment by todb-r7** [comment]
#4128 and #4574 are also related to readline bugs. I'm tired of seeing them and telling people to use `msfconsole -L`. Talked with @jlee-r7 this morning, and I'd rather see that `msfconsole` do the Right Thing when it comes to readline/rbreadline. Basically, msfconsole should detect that readline is present. If not, it should fall back to rbreadline, with a warning.

I expect detection methods will need to account for:

- [ ] Linux installations
- [ ] Windows installations
- [ ] Kali installations
- [ ] Source installations

Assuming such detection is possible (and really, it should be) @jlee-r7 and I seem to agree that this is reasonable, barring any tribal knowledge on readline from @bturner-r7 and @hmoore-r7. Once this happens, the `-L` option needs to be deprecated. I see that as:

- [ ] `-L` becomes a nop with a message that it's deprecated in order to untrain people.
- [ ] `-L` is removed as an option (6 months later?)

Also, b02dc7a seems to have nothing to do with this bug, @trosen-r7

**Comment by todb-r7** [comment]
BTW I don't see anything here that says that rbreadline is no longer a 2.1 blocker, so marking as such. Also, that screed should really be its own bug. Copy-pasting.

**Comment by jlee-r7** [comment]
See 867329d4b32a5414aea663063ebdd01420347c6e, 7b77bbedaa112427c4c47b8e7409dde47df7eaa3, and 667f1ca876f8d3ef1e09f7a168b7314e3b6b8907, all from #4084

**Comment by todb-r7** [comment]
Unlabelling as Ruby-2.1 per #4084.

**Comment by hmoore-r7** [comment]
#4128 is still a blocker (we need them to cut a new gem, or we should fork it).

**Comment by todb-r7** [comment]
Is #4128 a blocker for 2.1? I can see where it's a bug, what with the crashing, but I've been on 2.1 for a long while, tab completing, nearly always under msfconsole -L. Doesn't feel like a blocker (given the workaround) to me, @hmoore-r7 .

That said, will comment on #4128 about affirming a fork and gem build.

**Comment by todb-r7** [comment]
This is resolved with the new `rb-readline-r7` gem. Hopefully we won't have to maintain that forever.
