### ISSUE TITLE
deprecate msfcli and msfd

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#3802]
msfcli, msfd, msfencode, and msfpayload should be gone.

Replacements
* msfencode & msfpayload should be replaced by msfvenom completely
* msfcli should be replaced by msfconsole completely

**Comment by todb-r7** [comment]
The deprecation warning was added, so I believe this ticket should be closed? Will want to delete the deprecated utilities eventually of course, but I don't see the need for the ticket to stay open for that.

**Comment by qgrosperrin** [comment]
I'm running into some issues using the `msfconsole -x` alternative to `msfcli` and was hoping to get some directions here on how to use it properly. In my opinion, it appears:
- 1. slower than msfcli  
- 2. too verbose  
- 3. the command line doesn't look very clean

Below are some details about these comments.

1. 
I have noted that the `msfconsole` alternative to `msfcli` is at least two times slower on my machine. I'm guessing this is because `msfconsole` tries to load everything, not taking into account it runs as a command line utility (as opposed to interactive mode) and may not need everything. Is there a way to use `msfconsole -x/-r` and not have it load everything ?

Sample exec times from my machine
```
time msfcli auxiliary/scanner/finger/finger_users USERS_FILE=/usr/share/wordlis
ts/metasploit/unix_users.txt RHOSTS=192.168.231.145 E
[...]
real    0m4.412s
user    0m3.288s
sys     0m1.080s
```

```
time msfconsole -x "use auxiliary/scanner/finger/finger_users; set USERS_FILE /
usr/share/wordlists/metasploit/unix_users.txt; set RHOSTS 192.168.231.145; exploit; exit"
[...]
real    0m11.185s
user    0m5.860s
sys     0m5.244s
```

2. `msfconsole` prints the metasploit framework welcome message and logo which is a lot more verbose than `msfcli` but this does not provide additional technical details. Is there a way to have `msfconsole` not print all that information and instead just output the essential information that `msfcli` was exclusively returning ?

You might think this is not really important but I usually have `msfcli` run inside a wrapper function (BASH, Python or else) so having unnecessary verbose output can sometimes be a problem.

3. Is there any ways to have the command below executed in one go (not using ";" separated stacked commands), similar to msfcli ? 
`msfconsole -x "use auxiliary/scanner/finger/finger_users; set USERS_FILE /usr/share/wordlists/metasploit/unix_users.txt; set RHOSTS 192.168.231.145; exploit; exit"`

Something like the following would look cleaner imo, for instance:
`msfconsole -x "use auxiliary/scanner/finger/finger_users USERS_FILE=/usr/share/wordlists/metasploit/unix_users.txt RHOSTS=192.168.231.145"`

__Note__: I am not particularly attached to keeping `msfcli`. I just think the usability of `msfconsole -x/-r` is not as good at the moment. Hopefully this will be received as constructive criticism and help others if any documentation is provided here.
Thanks

**Comment by hmoore-r7** [comment]
It might be worth adding a command line flag to make this easier (```--msfcli```). Load times should have drastically improved if you are using master with Ruby 2.1.5.

**Comment by wchen-r7** [comment]
The load times will be improved when @limhoff-r7 (or somebody) adds more improvements on autoload.

For the too verbose issue, you can do: ```msfconsole -q -x "your commands"```

A better way to do less typing is probably creating bash aliases or functions, maybe some resource scripts.

**Comment by kernelsmith** [comment]
I actually have a sweet solution to this (well not the verbosity part). It's not %100 ready for everyone to try, but I may have some time this week to finish it up. Would you like to helps beta test it?

**Comment by qgrosperrin** [comment]
The `-q` option is exactly what I needed in terms of verbosity. Thanks. I should have picked that up from the help menu..

As for the execution speed, you were right suggesting the use of the latest Ruby version as I now get exec times twice as fast as before (good job on that !). However, `msfcli` is still consistently two times faster than `msfconsole`. 

Is the `autoload` module part of `msfconsole` but not included in `msfcli` ? If that's the case, maybe a `--msfcli` flag or similar would indeed make sense so that when used, less modules are loaded.

Below are some more examples of quick and dirty benchmarks to compare to times posted earlier.

__Version information__
```
root@kali:~# ruby -v 
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
[...]
metasploit v4.11.0-dev [core:4.11.0.pre.dev api:1.0.0]
```

1. `time ./msfcli auxiliary/scanner/finger/finger_users USERS_FILE=/usr/share/wordlists/metasploit/unix_users.txt RHOSTS=192.168.231.145 E`
```
real    0m3.449s
user    0m2.920s
sys     0m0.460s

real    0m3.345s
user    0m2.868s
sys     0m0.428s

real    0m3.410s
user    0m2.944s
sys     0m0.400s
```
2. `time ./msfconsole -x "use auxiliary/scanner/finger/finger_users; set USERS_FILE /usr/share/wordlists/metasploit/unix_users.txt; set RHOSTS 192.168.231.145; exploit; exit"`
```
real    0m6.981s
user    0m2.796s
sys     0m4.188s

real    0m7.135s
user    0m2.916s
sys     0m4.220s

real    0m7.135s
user    0m2.916s
sys     0m4.220s
```
Note: using `msfconsole` with `-q` appears to be slightly faster (200ms on average) than its verbose counterpart.

**Comment by estarlinhk** [comment]
como resuelvo esto que me sale en el kali linux algien expliqueme eso porfa [!] **********************************************************************
[!] *               The utility msfcli is deprecated!                      *
[!] *            It will be removed on or about 2015-06-18                 *
[!] *              Please use msfconsole -r or -x instead                  *
[!] *  Details: https://github.com/rapid7/metasploit-framework/pull/3802   *
[!] ************************************

**Comment by estarlinhk** [comment]
as I solve this that I get in the kali linux algien Explain that porfa [!] ********************************* *************************************
[!] * The utility msfcli is deprecated! *
[!] * It will be removed on or acerca 18.06.2015 *
[!] * Please use msfconsole Instead -r or -x *
[!] * Details: https://github.com/rapid7/metasploit-framework/pull/3802 *
[!] ************************************

**Comment by RealPariah** [comment]
WOW, JUST WOW, I have not needed metasploit in some time and then I come back to find forced registration with too much personal info, CLI is GONE (this thing emulates but is not true CLI).  No wonder your stock has taken huge hits.  A security company asking for my personal details to download Open Source software; I just find that so ironic it KILLS me.

**Comment by bcook-r7** [comment]
Nice troll. If you want just the CLI / open source, go ahead and install it: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

Or grab Kali or any of the other security distributions that come with it pre-packaged.

**Comment by hdm** [comment]
If only it killed him

**Comment by OJ** [comment]
1. Locate source code of open source project.
1. Post ignorant & incorrect ranty comment on an unrelated issue.
1. Fail to notice the irony of posting rant in said location.
1. Look stupid.
1. Profit?
