### ISSUE TITLE
print_debug

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#3816]
Currently `print_debug` output is shown if the `VERBOSE` option is enabled. To be consistent, I think this output should only be shown if `DEBUG=true` (which automatically implies `VERBOSE=true`).

vprint_debug: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/module.rb#L244

**Comment by todb-r7** [comment]
I will pull this trigger; it still annoys me every time when I see `print_debug` in production.

So, my plan now:

  - [ ] Find all print_debug's
  - [ ] Convert them to print_verbose OR drop them entirely
  - [ ] Add a msftidy check to look for print_debug in production.

Thereby outlawing it forever.

**Comment by FireFart** [comment]
:+1:

**Comment by bcook-r7** [comment]
Also:

- [ ] remove print_debug

**Comment by jvazquez-r7** [comment]
After today's discussion, some new points to have into account:

- [ ] Left ```DEBUG``` as unregistered option. So only if you know about it, you use it.
- [ ] Don't allow modules to register the ```DEBUG``` option neither, since ```rand_text``` methods behavior changes, add msftidy check.
- [ ] Review modules registering ```DEBUG``` option and take care of them.
- [ ] Warn pro ppl once there is PR ready, because probably they can take care better than me of ```print_debug``` usage on pro.
