### ISSUE TITLE
Add progress indicator for large payload stages

### ISSUE THREAD

**Issue by cbdraconus** [rapid7/metasploit-framework#4059]
I was wondering, would it be possible to add into the framework, a percentage counters, for items like staged handlers, to see how long it's taking for the handler to run?

**Comment by 7043mcgeep** [comment]
Reviving this old feature request.
@cbdraconus Do you remember what payload you were trying to generate that was taking so long to justify progress output? I have not come across a payload large enough to take more than a few seconds.

To my understanding of how payloads are (usually) built in Metasploit modules, there's some assembly code (specific to the module) that is assembled by `metasm` (an open-source assembler written in Ruby).

For example, line 58 of `lib/msf/core/payload/linux/x64/reverse_tcp.rb`:
```
 54   # Generate and compile the stager
 55   #
 56   def generate_reverse_tcp(opts={})
 57     asm = asm_reverse_tcp(opts)
 58     buf = Metasm::Shellcode.assemble(Metasm::X64.new, asm).encode_string
 59     apply_prepends(buf)
 60   end
```
The asm (assembly code defined within this module) is passed through a call to a metasm routine `assemble` which creates the payload buffer.

If progress is going to be included in payload generation steps, it make most sense to me to output progress as the actual buffer is being built (is that what you meant?). But since this is done outside of MSF, it doesn't seem intuitive. Like I said, I have not seen payload creation take longer than a few seconds. In my experience, it takes much longer for `msfconsole` to output the payload at the end of `generate` (I guess `msfvenom` is a different story since I don't remember it outputting the payload...)

Anyway, there are other progress elements that are more general and easier to implement than "percentage generated". For instance, implementing a `-v` option to `generate` could output the steps before and after various function calls, so the user knows what it's doing. I think this could be sufficient for progress and I could get working on it if there's a demand for it (and if my understanding of the use of metasm is correct).

**Comment by cbdraconus** [comment]
I don't remember exactly what it was I was working on, or even the choice I was trying to utilize. But it isn't so much the assembly of the payload, but rather an indicator of how much of the payload has been sent to the target. In example, I've already assembled my code, and I am using a staged handler to transmit it to my target, while it's being transmitted I would like to know how much of the code has been sent,  i.e. 10%-------->100%

**Comment by 7043mcgeep** [comment]
9 minute reply; impressive for a 5-year-old issue.

Ah thanks. I misunderstood before. I understand now. Progress indicators make way more sense when we bring over-the-network sending into the ring. I think the current output during payload transmission to a target machine is this something like:
`Sending stage (x bytes) to y`

And that's pretty much it. It would be nice to have progress indication (or at least a `-v` or `--progress` option for it). As a fan of progress indicators, I'm interested in this issue, and I'll look into this.

**Comment by cbdraconus** [comment]
I can agree with the -v or --progress options, as I too am a fan of progress indicators.

**Comment by ccondon-r7** [comment]
Hey @7043mcgeep, you still looking to implement this somehow?

**Comment by 7043mcgeep** [comment]
@ccondon-r7 I've pretty much abandoned it as I haven't had much time to think about this issue. Last time I checked, it might require changing the function that sends the payload so the bytes are viewable to the framework and can display stats. That seemed a bit intimidating at the time so I picked up a few other issues instead. Best regards.

**Comment by ccondon-r7** [comment]
Sounds good! I'm going to put this in the attic, then.
