### ISSUE TITLE
SegmentInjector does not work against warbird (license verification) windows binaries

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4380]
I noticed this while fixing another bug so I didn't focus too much on it.

You can trigger the SegmentInjector class by using the -k flag in msfvenom. ~~Technically speaking this flag is currently ignored because this is what exe.rb does~~:

```ruby
    if opts[:inject]
      injector = Msf::Exe::SegmentInjector.new({
          :payload  => code,
          :template => opts[:template],
          :arch     => :x86
      })
      injector.generate_pe
    end
```

But it should be ```return injector.generate_pe```. I already have this fix in my #4377 PR so no need to submit a PR for this.

But anyways, if you do that, it seems the executable only works for Windows XP. If against a newer machine such as Windows 7, sometimes it looks like the malicious process terminates right away, or it actually crashes.

I don't have any more info at this point.

**Comment by scriptjunkie** [comment]
Ok, I just ran the exe version against a test exe on win7 and it worked as expected for me. The biggest thing you need to watch out for usually is in the EXITFUNC; by default, say you run
`ruby msfvenom -p windows/exec -f exe -e generic/none -i 0 -x deleteme.exe -k -o deletemecalc.exe CMD=calc`
When you run deletemecalc.exe, it will spawn calc, but then immediately kill the delteme process. (So it appears to crash or die) This is because the default EXITFUNC is ExitProcess. You need to run `ruby msfvenom -p windows/exec -f exe -e generic/none -i 0 -x deleteme.exe -k -o deletemecalc.exe CMD=calc EXITFUNC=thread`
Then your generated payload is more likely to succeed. It's possible there could be some other unexpected failures. I originally wrote this inject-payload-as-new-thread-so-the-original-exe-still-runs about 5 years ago https://dev.metasploit.com/redmine/issues/1244#note-1 and the biggest issues were in stuff like UPX'd executables or other executables that messed with the PE format. Some of those can still break it I'd assume.

**Comment by wchen-r7** [comment]
Thanks @scriptjunkie, I will try again!

**Comment by wchen-r7** [comment]
Ok so I just tried it again, still not working for. Here's what I did:

1. I have a Windows 7 SP1 box (32-bit)
2. I copy the Win7's calc.exe in order to use it as a template
3. I generate my payload like this: ```ruby msfvenom -p windows/exec -f exe -e generic/none -i 0 -x /tmp/calc.exe -k -o /tmp/new_fake_calc.exe CMD=calc EXITFUNC=thread```
4. I copy new_fake_calc.exe to my Windows 7 box, and I double click on it
5. No calc pops up

If I copy Windows XP's calc.exe and use that as a template, then it will work.

**Comment by hmoore-r7** [comment]
The inject mode flag doesn't work with certain binaries, for what its worth.

**Comment by scriptjunkie** [comment]
Don't use win7 calc. It has weird DRM stuff in it. Try this as an experiment. Copy Win7's calc from system32 to the desktop (No changes). Double-click it. It won't run.

**Comment by scriptjunkie** [comment]
I don't know for sure if calc's weird behavior is related to warbird, but that's what I'm assuming. http://thisissecurity.net/2014/10/15/warbird-operation/

**Comment by wchen-r7** [comment]
@scriptjunkie I looked at the Win 7 calc.exe binary and the same loader access code doesn't seem to exist in WinMain, and no matching functions with the pattern ```x calc!*warbird*``` either. They do exist in the Win 8.1 calc so I added a check for it.
