### ISSUE TITLE
Target process Notepad.exe should be a configurable datastore option

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4569]
We should find replace all notepad.exe target process executions and make them a configurable datastore option.

**Comment by kernelsmith** [comment]
That datastore opt should default to RANDOM or similar and we should implement a spawn(path) and/or spawn_and_inject(path, dll) method(s) which, when path is "RANDOM" it chooses randomly from a list of common things like notepad.exe, calc.exe, wordpad etc and continues picking them if the first fails, then returns the pid of the one that works, otherwise nil.  If the process needs to be something hard coded, caller can just always pass "notepad.exe" or filter/adjust what's coming from the datastore

Something like
```
pid = spawn(datastore["SPAWN"])
# or
pid = spawn_and_inject(datastore["SPAWN"], dll_to_inject)
```

-Josh

**Comment by wchen-r7** [comment]
I think if you want to choose randomly from a list, you probably need a new datastore option. OptTargetProcess or something like that. But I also think that's unlikely to happen. A weird way around that is create a new mixin specifically for this, I guess.

**Comment by wchen-r7** [comment]
Or actually, you can just have a new datastore option in Msf::Payload::Windows::ReflectiveDllInject?

**Comment by OJ** [comment]
Is that where is really belongs? Surely the payload should be agnostic of where it's being injected. I'd prefer a new mixin personally.

**Comment by wchen-r7** [comment]
> Is that where is really belongs? Surely the payload should be agnostic of where it's being injected. I'd prefer a new mixin personally.

Nah, I was just mumbling all the possible ways to implement this.

A new mixin works, but every time I find ourselves not being able to implement another Opt*, I wonder if we should just deprecate option_container.rb and create something that allows us to make new Opts when needed.
