### ISSUE TITLE
Add "LURI" to reverse_http(s) payloads?

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#4623]
This isn't so much an issue as a potential feature request that I am interested in hearing thoughts on.

There's been discussion in the past about the _uberhandler_ idea, where a single handler is able to determine if an incoming session is TCP, HTTP or HTTPS, and that ultimately would be super awesome. However, in the short term, what do you guys thing to having the ability to set an `LURI` on a HTTP or HTTPS payload and have a single listener be able to handle different requests on the same port based on that URI?

So for example, you could spin up one listener on `/metwin32` which handles `windows/meterpreter/reverse_http` and have it do its thing. Then after, create another listener which listens _on the same port_, but on `/py` which accepts `python/meterpreter/reverse_http`. When launched, it doesn't actually create a whole new listener, but reusing the existing listener but binds to a separate URI.

This would mean that you could have a single listener for a number of different http(s) payloads all bound to the same port.

Is this a stupid idea? Thoughts?

**Comment by hmoore-r7** [comment]
+1 here. We should look into it as a broader effort around tracking specific payloads (which payload it came from, etc).

**Comment by hmoore-r7** [comment]
Marking as delayed while we do some design work.

**Comment by bcook-r7** [comment]
Are folks happy with how LURI turned out? It seems like a decent stepping stone at least. I think @egypt had some concerns about user misconfiguration in getting the URIs to line up. I'm going to close this issue but feel free to continue commenting.

**Comment by egypt** [comment]
Yes, I have concerns, but I don't have a better way to do it. As long as the default is `/` it should be ok. 

I'm more concerned with the way this gets displayed in `jobs` output. Reusing the `URIPATH` column is problematic for a couple reasons.
* `URIPATH` is for the exploit, not the handler, so semantics are different
* Every browser exploit will have both, so `URIPATH` will override and `LURI` will be invisible
* There's no way to tell at a glance that the above has happened

I'm not too keen to add more columns because that table is already pretty wide. Perhaps we could combine LHOST/LPORT/LURI into a single "callback uri" column and start using `shortname` instead of `refname` in the first column?

**Comment by bcook-r7** [comment]
Thanks! I usually use the 'sessions' view, which didn't have much of a change other than -x showing it as an option. I'll submit a PR to try to shorten the info overload in the jobs view.

**Comment by OJ** [comment]
+1 to the "callback URI" option for jobs.
