### ISSUE TITLE
set LogLevel and setg LogLevel mean different things

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#4641]
This doesn't seem very intuitive. Feels like a bug in `set` vs `setg`, but maybe it's just a documentation issue.

See [this comment](https://github.com/rapid7/metasploit-framework/pull/4632#issuecomment-71517145).

## Reproduction Steps

- [ ] Start msfconsole.
- [ ] Use any module.
- [ ] Edit that module to include a method not found error: `edit` and add `foobar_whatever` as the first line under `def exploit`.
- [ ] `tail -f $HOME/.msf4/framework.log` in another terminal.
- [ ] `unset LogLevel 3`
- [ ] `unsetg LogLevel 3`
- [ ] `set LogLevel 3`
- [ ] `run`
- [ ] Notice the lack of a backtrace in the `framework.log` file.
- [ ] `setg LogLevel 3`
- [ ] Now see the backtrace.

**Comment by wchen-r7** [comment]
I'm not sure if this is a bug, I mean I never looked at it as a bug.

So first off, LogLevel is a global option. Not that I made that up, but when you look at lib/msf/ui/console/command_dispatcher/core.rb, that's how it wants you to look at it.

Now, the purpose of our set command is to "set a variable to a value". And then there is setg, which is meant for "setting a global variable to a value." Since LogLevel is a global option, it makes sense to use setg command instead of set.

What's really confusing about this "set" is done under the scope of whatever the prompt is pointing at. So for example, when I load a module first, my prompt is pointing at that module, so when I use the set command, only that module will get that setting (but will not be seen globally). For example:

```
msf > use exploit/multi/handler 
msf exploit(handler) > set LogLevel 3
LogLevel => 3
msf exploit(handler) > set

Global
======

No entries in data store.

Module: multi/handler
=====================

  Name                   Value
  ----                   -----
  DisablePayloadHandler  false
  EnableContextEncoding  false
  ExitOnSession          true
  ListenerTimeout        0
  LogLevel               3
  VERBOSE                false
  WfsDelay               0

msf exploit(handler) > back
msf > set

Global
======

No entries in data store.

msf >
```

As you can see, my multi/handler module knows about the LogLevel setting, but at the global level nobody else knows.

The thing is you CAN actually use the set command to set LogLevel and being able to log stuff. Like I said before, your prompt must be pointing at the right place. Watch this:

```
msf > use exploit/multi/handler 
msf exploit(handler) > back
msf > set LogLevel 3
LogLevel => 3
msf > set

Global
======

  Name      Value
  ----      -----
  LogLevel  3

msf >
```

As you can see, this works just like setg.

So this is why I never looked at this as a bug.

Is this a documentation issue? Eh, well, it's not like I didn't talk about this you know:
https://github.com/rapid7/metasploit-framework/wiki/How-to-use-datastore-options

Here's what I said:

> "On the user's side, datastore options are seen as global or module-level: Global means all the modules can use that option, which can be set by using the setg command. Module-level means only that particular module you're using remembers that datastore option, no other components will know about it."

I didn't specifically talk about set LogLevel vs setg LogLevel, but that should explain about the scope difference between set and setg. Maybe I should explain this differently?

**Comment by wvu-r7** [comment]
Yeah, this has been normal behavior to me...? What further compounds the problem, though, is that there's ```set -g```, too, which operates exactly the same as ```setg``` or ```set``` under the global datastore.

I favor a documentation change as suggested by @wchen-r7. Command help, too.

**Comment by wchen-r7** [comment]
We can try to phrase it a little better in the help menu, yeah. Especially the set command. Right now it's like this:

```
set           Sets a variable to a value
```

I feel like the word "scope" or "context" should squeeze in there.

**Comment by wchen-r7** [comment]
Oh wait, when you do: ```set -h```, it says in there too:


> If run from a module context, this will set the value in the module's
> datastore.  Use -g to operate on the global datastore
