### ISSUE TITLE
redesign the snmp scanner to be efficient and asynchronous

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4718]
This module is mostly unusable unless scanning a large range of hosts. I reckon it will be taking 12 seconds to scan each community string if it is invalid...

Issues:

* Default timeout set to 2 seconds, unable to override. 
* Default retries set to 2, unable to override
* Scans both v1 and v2c without ability to override, doubling the above issues
* Unable to spin up multiple threads for a single host, the only way to increase efficiency is via multiple batches. This is of no use if just trying to scan a single host.  This is due to the underlying Batch Mode design.
* Uses SNMP library, which doesn't allow a timeout value of < 1 second.

**Comment by Meatballs1** [comment]
Hmm if a scanner uses batch mode then threads are only effective for running multiple batches. Within each batch (ie if only 1 host), the number of threads will not be increased to meet THREADS :(

**Comment by Meatballs1** [comment]
The LoginScanner base connection_timeout only appears to accept Integer values?  :( 

```
 37           validates :connection_timeout,
 38                     presence: true,
 39                     numericality: {
 40                       only_integer:             true,
 41                       greater_than_or_equal_to: 1
 42                     }
```

**Comment by hmoore-r7** [comment]
One thread per batch is the design model, multiple batches require setting THREADS > 1.

**Comment by Meatballs1** [comment]
Yeah but how do you blat out 28 threads against 1 host? :)

**Comment by Meatballs1** [comment]
Looks like timeout settings are forced to be seconds in the snmp library. Could reduce the retries though.

**Comment by hmoore-r7** [comment]
Change from batch mode to per-host mode then increase thread count, or set the batch size to 1.

**Comment by Meatballs1** [comment]
Oh and it also doubles up the attempts by scanning SNMPv1 and SNMPv2 simultaneously. :(

**Comment by hmoore-r7** [comment]
Oh, per-host, intentionally not supported at the moment. The only way to get faster per-host performance is to scan more hosts at once. This would make more sense as an RFE to add module-level thread splitting, but in this particular case it could be rewritten using a raw UDP based module instead of depending on the snmp gem.

**Comment by Meatballs1** [comment]
@hmoore-r7 How do you disable batch mode? Set BATCHSIZE to 0?

**Comment by hmoore-r7** [comment]
After thinking about this a bit: 

 * SNMP v1/v2 is kind of pointless today (internet-wide scans of each showed negligible differences in support between the two protocols, with some devices ignoring v1, but responding to v2, and almost none the other way).

 * The current implementation is bad for a bunch of reasons. This could be better implemented as a fast send of UDP probes for each community and a regular receive and process hook to determine if any of those communities succeeded. Instead of 2s/community this could be 10+ communities/s while still remaining reliable. It would require rewriting this code to not use SNMP::Manager.

**Comment by Meatballs1** [comment]
Current PR makes module much more customizable in the meantime. I doubt I'd ever get around to re-writing SNMP scanner :)

**Comment by hmoore-r7** [comment]
Thinking on this some more, the solution will require a full rewrite if we want to get past the ~2s/community timeout.

**Comment by todb-r7** [comment]
This is also reported in MSP-11853

**Comment by bcook-r7** [comment]
There is a lot of work to redesign this scanner, so switching from bug to feature.

**Comment by jsherwood0** [comment]
This module was many orders of magnitude faster before it was "refactored."  The problem is that it was not refactored but rewritten entirely, losing some of the efficiency provided by the original design.  That said, perhaps it should be reverted to its functional state from before commit c553fcac73edb15be250a791e48aac7dcae28a96, and then refactored from that point.  That way the design that worked efficiently in the first place would be there and it wouldn't need to be redesigned (again), taking a lot of work.

I'd also like to recommend that a complete rewrite of a functioning module be examined more carefully before merging it into the master.  A simple test against a class C network using a list of community strings of reasonable size (e.g., around 50 strings) would have exposed how every slow this rewritten module is compared to the original.

Thirdly, I'd strongly advocate for reclassifying this issue back to "bug" status.  When assessing networks consisting of several CIDR blocks, the module is unusable in its current state.

-John

**Comment by hmoore-r7** [comment]
@jsherwood0 Thank you for the feedback. I appreciate your concerns, I agree with your assessment of the current speed of this module. It needs a refactor that uses bulk requests before checking each response.There are other tools that do a much better job of fast brute forcing (thc-hydra, medusa, etc). Metasploit is not one of those (yet), but it is on our radar of things to improve.

**Comment by hmoore-r7** [comment]
See #5459

**Comment by jsherwood0** [comment]
Thanks for the reply.  If I may ask, what was the problem with the module
before the refactor?  I found it to work well (other than a minor problem
with the progress indicators).  In fact, I often got my best results with
it.  Maybe I can retool the original to meet the needs that prompted the
refactor.

Regards,

-John

**Comment by hmoore-r7** [comment]
The module before the refactor had many of the same problems as the current implement (use of SNMP::Manager vs raw packets). The increased delay is the result of porting the module to the new LoginScanner model, which assumes a new connection for each login attempt. This doesn't work well for UDP services.
