### ISSUE TITLE
LoginScanner refactor missing many advanced/evasion options

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#4803]
When the login modules were ported to use LoginScanner classes, many of the advanced and evasion options present in their mixins are not implemented in the LoginScanner code. For example, the http_login module registers a number of options that are now ignored (UserAgent, DigestAuthIIS, and dozens of evasion options). The modules and LoginScanner classes need to be updated to implement the options defined by each module (typically via mixin).

**Comment by hmoore-r7** [comment]
cc @dmaloney-r7

**Comment by hmoore-r7** [comment]
In the case of HTTP-derived LoginScanners, we can add new options to the base HTTP class, but all of the HTTP modules now need to be aware of and explicitly pass the HTTP mixin options (dozens!) unless we put the LoginScanner login into the mixin. Tricky to solve without making this even harder to maintain in the future.

**Comment by wchen-r7** [comment]
Yeah I reported some of them, too. It's like you have these components that used to be wired together, but now you have to DIY without documentations.

**Comment by dmaloney-r7** [comment]
@wchen-r7 They are not more technical. They are pruposely built to be more atomic now so that they can be individually used and tested outside of the crisscrossing mixin context. Ideally we would have converted a lot of the existing mixin functionality into proper class constructs when we made the LoginScanners but were up against deadlines and so the decision was made to do the best we can on the first pass by copying mixin functionality.  

The existing mixin setup is interwoven in cross-refferences and are entirely dependent upon being included in an Msf Module for most of the methods to even work. This makes Unit testing of this code almost impossible to achieve.  Every part of the LoginScanners is documented with YARD docs that show how the API works. 

We do need to continue to work on integrating this features, but the long term solution is to get away from having these module dependent mixins doing all of the work as they have become nearly unmaintainable and worse, untested. A lot of the functionality need to be split into other classes, so that rather than passing all the datastore options into the LoginScanner directly, you for example configure an actual HTTP client object with those options and simply pass the client to the LoginScanner, because the LoginScanner does not actually care about those options. They have nothing to do with the LoginScanner functionality but rather the functionality of our HTTP Client behaviour. Proper OOP thus dictates that these should be seperate objects responsible for each thing that communicate with each other.

**Comment by dmaloney-r7** [comment]
The old components were also completely non-standard in that there were about 6-7 different way these login modules were implemented before instead of one standard way. So now we have a standard methodology for doing Login Scanners, and we know exactly how each one behaves.   These new 'more technical' components also address a lot of gaps that existed in the previous code, and interfaces with a whole new credential model that solves a number of shortcomings of the original approach.

**Comment by wchen-r7** [comment]
> rather than passing all the datastore options into the LoginScanner directly, you for example configure an actual HTTP client object with those options and simply pass the client to the LoginScanner

So if I understand this idea correctly, we leave the implementation to the module developer?

**Comment by hmoore-r7** [comment]
Forcing the module developer to keep up with mixin changes doesn't seem workable. I can take a shot at this and add a mixin method to help configure the LoginScanner with the appropriate options from the mixin's datastore and evasion options. HTTP is the most broken at the moment.

**Comment by wchen-r7** [comment]
@dmaloney-r7 Yeah sorry, I chose my word poorly. LoginScanner is indeed much more powerful than what we had before. Nothing we can't shake off here. I'm gonna let HD take over from here.

**Comment by hmoore-r7** [comment]
@dmaloney-r7 Mixins provide the glue between module datastore options and the Rex protocol layer. No disagreement that there might be better ways to do things, but currently these modules claim to support various options and just ignore them when sent. Tackling this in a PR this weekend.

**Comment by hmoore-r7** [comment]
Many of the HTTP LoginScanner modules were ignoring the SSL, VHOST, and User-Agent options. The rework in #4819 should be good to go for the HTTP modules, but I am still reviewing the non-HTTP modules for similar issues.

**Comment by wchen-r7** [comment]
#4819 will fix #https://github.com/rapid7/metasploit-framework/issues/3960 too. If I merge the PR I'll tag that too.

**Comment by todb-r7** [comment]
So HTTP is done-ish... but it seems like there are several other protocols that may(?) have missing evasions/options. Can we audit for this? I'd love this ticket to be behind us.

**Comment by jvazquez-r7** [comment]
https://github.com/rapid7/metasploit-framework/pull/5995 hopefull fixes the problem for `Metasploit::Framework::LoginScanner::SMB`

**Comment by jvazquez-r7** [comment]
#6014 hopefully fixes the problem for modules missing TCP advanced options.

I'd say it would be the last PR, once #5995 and #6014 are landed it could be closed. 

If I'm missing something, please, feel free to point here and I'll work on it!
