### ISSUE TITLE
improvements to msfvenom semantics 

### ISSUE THREAD

**Issue by oscalation** [rapid7/metasploit-framework#4889]
Just a couple suggestions to help improve the functionality of msfvenom. 

```
-l, --list       [module_type]   List a module type example: payloads, encoders, nops, all
```
The naming of the modules are slightly different than the actual name. encoders vs encoder
so running msfvenom -l encoder  returns an error, msfvenom -l encoders works.

The help page for msfvenom should also include 

```
Msfvenom is the combination of payload generation and encoding. It's a replacement for msfpayload and msfencode.
```

**Comment by kernelsmith** [comment]
Any interest in submitting a pull request and becoming a contributor? Since it's mainly comments it would be pretty easy

**Comment by oscalation** [comment]
Yes! Could you by chance point me to the correct location/folder/area that I would find this code to modify? or how i could attempt to find it?

**Comment by void-in** [comment]
Encoders seem right since that is how the module directory is organized: exploits, payloads, encoders, nops. Only auxiliary and post are singular.

**Comment by wchen-r7** [comment]
@oscalation The file to modify is msfvenom: https://github.com/rapid7/metasploit-framework/blob/master/msfvenom#L69

And here's what you do:

1. Assuming you have your framework development setup like this: https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
2. In your metasploit directory, make sure to ```git pull``` to have the latest everything
3. And do: ```git checkout -b msfvenom_help_menu```
4. Modify msfvenom
5. Do: ```git commit msfvenom```
6. Do: ```git push origin msfvenom_help_menu```
7. Go to https://github.com/rapid7/metasploit-framework, you should see a "Compare & pull request" button with your branch name on it. Kind of like this:

![screen shot 2015-03-07 at 3 40 50 pm](https://cloud.githubusercontent.com/assets/1170914/6543423/707410a2-c4e0-11e4-88cc-32644201a814.png)

8. Write the subject for the pull request
9. Write a description for the pull request (You can use the "Fix #" keyword to tag this issue, and it will automatically close if merged)
10. Submit, and done.

**Comment by kernelsmith** [comment]
Sorry, I started a reply then got distracted. If you're not comfortable with the excellent guidance above, you can, although it's not ideal, click "edit" on the msfvenom link which will automatically do some of what's required and allow you to submit the pull request based on changes you make in an online editor. I only bring this up because the changes are only to msfvenom comments, it's definitely not the preferred approach

**Comment by void-in** [comment]
I might be misunderstanding something but -l option is to list all the modules of a specific type. So msfvenom -l encoders seem more appropriate since it is listing all the encoders and not a single encoder. It reads "list all encoders". Same goes for payloads. The module directory is organized as payloads/, encoders/, nops/ as well.
