### ISSUE TITLE
Generate egghunter as a standalone Metasploit tool

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#4944]
In exploit module you can already use egghunters via the `generate_egghunter` method.

It would be great if msfvenom could also generate egghunter shellcode and encode it if needed.

**Comment by wchen-r7** [comment]
You would have to turn egghunter into a payload module....... but compare to other metasploit payloads, you can't really call egghunter as one. Very interesting idea, but a little tricky to implement.

**Comment by FireFart** [comment]
So what about a new "payload type" `egghunters` like encoders, payloads, nops and so on? I think the nop payloads face the same kind of problem or am I wrong?

**Comment by wchen-r7** [comment]
Thanks for the suggestion! So you mean have another module type like encoders, payloads, nops, etc, yeah?

I think creating another module type is a viable solution, but I imagine this is heavy-duty because you will probably have to work on Framework's module caching, module loader, PayloadGenerator, msfconsole, and maybe components, etc.

How about this, I can create a standalone tool that outputs egghunter in whatever format you want (as long as it's supported by Rex). And then that will allow you to pipe it to msfvenom and do encoding from there? It would be something like this:

```
./egghunter.rb --egg W00T ---format raw | ./msfvenom -p - -a x86 --platform windows -b "\x00" -f c
```

**Comment by FireFart** [comment]
Jeah the egghunter.rb will definitely be easier to implement when thinking of all the components that need to be changed for an egghunter payload.

Is there currently only one egghunter payload available, or are there more types we can choose of?

**Comment by wchen-r7** [comment]
Egghunter comes from Rex::Exploitation::Egghunter, and technically speaking there's two: a Windows one and a Linux one. When you generate an egghunter you get to specify the platform and architecture, and that's about it. Like this:

```ruby
Rex::Exploitation::Egghunter.new(platform, arch)
```

So all I have to do is make sure these two arguments are configurable by the user.

**Comment by wchen-r7** [comment]
Ok, so looks like we're ready to implement this. I'll find the time this week to get it done. Thanks!

**Comment by FireFart** [comment]
Thanks sounds great! Maybe we can also add more egghunter payloads to choose from?

https://www.corelan.be/index.php/2010/01/09/exploit-writing-tutorial-part-8-win32-egg-hunting/
and
https://www.corelan.be/index.php/2011/11/18/wow64-egghunter/
for example

**Comment by wchen-r7** [comment]
We can add more for sure. It will have to be in a new feature request (ticket).

Out of curiosity, is there also a reason why you want more egghunters? Something you're working on? I haven't used or seen egghunter being used since the stack buffer overflow era (also when Windows XP was popular). But most stack buffer overflows are pretty much dead nowadays. And modern memory corruption exploits require very precise control of memory/allocations, so space tends to be not a concern.

**Comment by FireFart** [comment]
@wchen-r7 only playing around with OSCE and thought it might be useful :)

**Comment by wchen-r7** [comment]
Oh ok I see. You know I got my OSCE too. It was some years ago. Very good course.

Yeah please feel free to create another feature request for new egghunters :-)
