### ISSUE TITLE
auxiliary/scanner/smb/smb_version [-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: SMBDirect.

### ISSUE THREAD

**Issue by strasharo** [rapid7/metasploit-framework#4963]
smb_version scanner fails to execute in the default setup and throws the following error:

msf auxiliary(smb_version) > exploit -j -z
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: SMBDirect.

After setting the value manually to "true" it runs as expected.

msf auxiliary(smb_version) > set SMBDirect true
SMBDirect => true
msf auxiliary(smb_version) > exploit -j -z
[*] Auxiliary module running as background job
msf auxiliary(smb_version) >

**Comment by void-in** [comment]
The default value of SMBDirect is true. You must have configured it as false in setg that is why you are getting this error. Do the following:

msf auxiliary(smb_version) > unsetg SMBDirect

Then configure the module option RHOSTS and any additional parameters. Before you run the module, run show options and show advanced and look at all the parameters. 

Also aux modules are not exploits so use run command instead of exploit.
