### ISSUE TITLE
wp_wplms_privilege_escalation Coding Bug

### ISSUE THREAD

**Issue by madmikw** [rapid7/metasploit-framework#5005]
```
[*] mywebsite.com:80 - Authenticating with WordPress using xas234234--:xas234234--ss...
[-] Auxiliary failed: RuntimeError no-access: Failed to authenticate with WordPress
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/msf/core/module.rb:278:in `fail_with'
[-]   /usr/share/metasploit-framework/modules/auxiliary/admin/http/wp_wplms_privilege_escalation.rb:101:in `run'
[*] Auxiliary module execution completed
```

I tried 10s of websites all give the same error even though i can login manually fine

**Comment by FireFart** [comment]
@rastating can you please have a look?

**Comment by FireFart** [comment]
@madmikw do you know the wordpress version of the affected sites? Maybe you can check it by calling `readme.html` in the document root.

**Comment by madmikw** [comment]
Yes, i do know of course :) but i dnt think wordpress version is important as the exploit runs against the theme not the wordpress, but yes the sites i tried on their themes are vulnerable according to there readme they are  1.8.4.2 :) BTW untill now i have been very pleased with your exploits +1 :100:

**Comment by FireFart** [comment]
Hi @madmikw,
The first step in the plugin is to login into wordpress using the wordpress login form: https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/admin/http/wp_wplms_privilege_escalation.rb#L100
This method calls https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/http/wordpress/login.rb#L10 and checks for common wordpress cookies. As you can see, we implemented cookies for various wordpress versions because they change over time so it's possible we missed a version, so i was asking for the wordpress version. You can get it by calling `readme.html` or by logging in into your wordpress installation.
It's also possible for themes and plugins to hook into the login mechanism so i asked @rastating if he can have a look. There are also some security plugins out there which could prevent the login via the module. If you can trace a login request and reponse with burp or another proxy and supply us both, we can have a look at this in detail.

**Comment by rastating** [comment]
@madmikw - if it's failing to authenticate the WordPress version number may be of use as that part of the process communicates directly with WordPress rather than with the plugin. Is there anything unique you can think of about the setup e.g. the wp-login file being located in a non standard place?

**Comment by rastating** [comment]
@FireFart  - doh, you beat me to it :D hehe

**Comment by rastating** [comment]
@madmikw - on a side note - the WPLMS privilege escalation module only works for versions 1.5.2 to 1.8.4.1; version 1.8.4.2 should be patched, as far as I know.

**Comment by madmikw** [comment]
@rastating  yes bro :v i can login manually via wp-login.php so no page is not moved :) and Thank you @FireFart  for the explanation and your time but as i said i have tried on diffrent sites so some where 4.1.1 and some where 3.8.5

**Comment by FireFart** [comment]
@madmikw thanks, so i think we need a request and a response from your login to trace down the error. You can remove all links mentioning the domain, username and password. We are only interested in the request params and the response headers and body.

**Comment by madmikw** [comment]
@FireFart can you please be more specific ?

**Comment by rastating** [comment]
@madmikw - we need to have a look at the data that goes back and forth from your browser to identify what is different on the sites you are testing against. If you check out the proxy @FireFart mentioned (http://portswigger.net/burp/proxy.html) this should let you capture the data and then provide it to us. But as @FireFart mentioned - remove any addresses and credentials before posting it publicly.

You can also do it with Wireshark if you prefer by setting a capture filter up of ```host destination_ip_here and port 80```, however, I've never tried removing destination addresses from a Wireshark capture, so the proxy @FireFart suggested may be the better option if it supports that!

Once you've setup the proxy or monitoring software, just capture the data whilst you navigate to the login page and successfully login, this should then let us see the cookies and form data that go back and forth and should hopefully indicate where the problem is.

Hope that helps

**Comment by FireFart** [comment]
thx @rastating for the explanation :)

Wireshark can only be used when talking to non SSL sites.

You can also set the PROXY option in metasploit to `http:localhost:8080` with burp running to tunnel all traffic through burp. This should also be enough to analyze why this exploit fails on your side

**Comment by madmikw** [comment]
Sure, iam a big lover of wireshark ;) i will sniff the traffic asap and let u know :)

**Comment by wchen-r7** [comment]
Ok so I was assigned to investigate about the RuntimeError exception and the backtrace that fail_with was showing, turns out:

* If it's not an exploit, when you use fail_with, module.rb does raise RuntimeError so that's the expected behavior.
* The backtrace is due to the default verbose level we implemented a while ago, but we ended up reverting all that, so it should not show any backtrace any more.

I tested the module against the latest Wordpress anyway, but I didn't run into any auth probs:

```
[*] 192.168.1.151:80 - Authenticating with WordPress using sinn3r:goodpass...
[+] 192.168.1.151:80 - Authenticated with WordPress
[*] 192.168.1.151:80 - Changing admin e-mail address to mJmQt@JaJiw.com...
[*] 192.168.1.151:80 - Enabling user registrations...
[*] 192.168.1.151:80 - Setting the default user role...
[+] 192.168.1.151:80 - Privilege escalation complete
[+] 192.168.1.151:80 - Create a new account at /wordpress/wp-login.php?action=register to gain admin access.
[*] Auxiliary module execution completed
```

**Comment by bcook-r7** [comment]
This should no longer be a problem. If you encounter further issues, please open a new ticket. Thanks!
