### ISSUE TITLE
nessus-xmlrpc does not return accurate status

### ISSUE THREAD

**Issue by ropdor** [rapid7/metasploit-framework#5217]
Nessus::Client::scan_export_status returns "ready" whenever the server replies with an HTTP 200 response. Documentation says:

200	Returns the status of the file. A status of "ready" indicates the file can be downloaded.

where the status is in the body of the reply. The function should instead return the status so that the caller can keep querying until the export is ready for download.

See https://gist.github.com/ropdor/78296562c74a819aa700 for patch

**Comment by void-in** [comment]
@ropdor Thanks for reporting. So what you want can be achieved through res.code only. Why are you returning the res.body then?

**Comment by ropdor** [comment]
According to documentation, the http code may be 400 indicating an error. My understanding is that unless we see a 200 and "ready" response, the report is either not ready or never will be. I was returning both so the caller may decide how to handle different situations, but just returning a single indicator would be fine for my purposes.

**Comment by void-in** [comment]
@ropdor re: "My understanding is that unless we see a 200 and ready response, the report is either not ready or never will be". During my testing when developing the plugin, the report was getting getting ready immediately after generating the export_status request. That is why 200 or ready was sort of synonymous. Have you experienced a situation where you get a 200 but the status is not ready yet? If yes then I will generate a PR for this. Otherwise, the ready response is more appropriate since the only reason you would call the scan_export_status method is to determine if the scan is ready to be exported and downloaded (because export in isolation doesn't mean anything in the API)

**Comment by ropdor** [comment]
I am seeing this almost every time I query for a report. It may be that the scan reports I am looking at are large and/or load related, but I have a wait loop in my code similar to:

```
 loop do
    code,s = client.scan_export_status(...)
    if code.to_i!=200 or s["status"]=="ready"
      ...
    end
    ...
    <sleep>
  end
  ...
  client.report_download(...)
```

to deal with this and see waits of 3+ seconds on a test report I am grabbing.

**Comment by void-in** [comment]
@ropdor Alright. I will implement the workaround. The loop like you did can make the console completely occupied till the report is not ready that is why a workaround could be to generate the request, if the status is not http 200, perform the operation 5 times. If the status is still not 200, inform the user to check the report after some time. This way the console won't be in an infinite loop state if the report hangs. Is this workaround good enough for you?

**Comment by ropdor** [comment]
Ah, I had not thought about that issue. Your workaround seems workable; I think as long as an accurate indication of report readiness is available (as opposed to the "always ready" assumption previously) we should be good.

**Comment by void-in** [comment]
@ropdor Generated a PR to fix the issue at https://github.com/rapid7/metasploit-framework/pull/5231. If possible, test the PR at your end and update here.

**Comment by ropdor** [comment]
Looks good to me, thanks
