### ISSUE TITLE
failed to unload sqlmap plugin 

### ISSUE THREAD

**Issue by all3g** [rapid7/metasploit-framework#5221]
When sqlmap module is loaded, we could not unload it. **Unload** function is not valid for sqlmap.

    msf > load sqlmap
    [*] Sqlmap plugin loaded
    [*] Successfully loaded plugin: Sqlmap
    msf > unload sqlmap
    msf > load sqlmap
    [-] Failed to load plugin from /home/notfound/sectools/metasploit-framework/plugins/sqlmap: Attempting to load already loaded dispatcher Sqlmap

**Comment by void-in** [comment]
The problem is not with the unload command. The problem is the symbolic name of the loaded plugin. When you load a plugin, run the 'show plugins' command to see a list of plugin names. The symbolic name of sqlmap plugin is Sqlmap (capital S). Hence running the command 'unload sqlmap' doesn't succeed. If you run 'unload Sqlmap', the plugin will be unloaded successfully and you can reload it without any problem.

**Comment by all3g** [comment]
Yeah, I've unloaded **Sqlmap** plugin with command **unload Sqlmap**.   
Thanks. ^.^
