### ISSUE TITLE
Feature Request: Msfmap integration into Meterpreter

### ISSUE THREAD

**Issue by PowerPress** [rapid7/metasploit-framework#5245]
Would it be possible to integrate the msfmap module into meterpreter to allow exponentially increase port scanning via pivoted computers. Instead of port scans having to be routed through the pivot which is slower, this allows meterpreter to run the portscan on the actual pivoted computer which is dramatically faster and not require installing anything on the compromised computer.

see below:
http://blog.securestate.com/new-meterpreter-extension-released-msfmap-beta/

**Comment by rwhitcroft** [comment]
:+1: would use

**Comment by wvu-r7** [comment]
BSD license, too.

**Comment by wvu-r7** [comment]
What do you think, @zeroSteiner?

**Comment by OJ** [comment]
There are elements of the code that concern me a bit. If it was going to be included as a "supported" extension in MSF then there'd need to be some changes.

It's already an extension, it's already built, it's got all the wiring. Why not just let people add it to their own MSF installations if they want to use it? Does it have to be part of the official repo? Perhaps adding something to the README/docs to reference the extension would be enough.

**Comment by wvu-r7** [comment]
@OJ: Not to mention the fact that it's a few years old. With all the refactoring you guys have been doing, I doubt it would merge cleanly.

**Comment by zeroSteiner** [comment]
The extension does do some things that are perhaps not considered best practice which is why I hadn't submitted it in an official capacity. I'd be happy to help get it up to speed though with no small amount of  guidance from @OJ.

**Comment by OJ** [comment]
@zeroSteiner pardon me if that sounded harsh, I certainly didn't intend it to be so! I'm always happy to work on things with you mate, we just need to find the time! :) It's hosted on Google Code as well, which will soon be shutting down, so perhaps it does need a new home. Let's have a chat about it and see if we can come up with a plan/timeline.

**Comment by zeroSteiner** [comment]
@OJ No worries. I wasn't being sarcastic; I'd actually like your thoughts on it. I'll hit you up on IRC and we'll formulate a plan of attack. Until then I'll be sure to pull it off of Google Code for safe keeping.

**Comment by hmoore-r7** [comment]
Does msfmap depend on WinPcap being installed on the target system?

**Comment by hmoore-r7** [comment]
It might make more sense to just upload & run Nmap (in-memory) versus reinventing this

**Comment by zeroSteiner** [comment]
@hmoore-r7 No it does not require WinPcap to be installed. Also because of that SYN scans were never practical due to the Windows limitations.

**Comment by OJ** [comment]
Blog link is dead, new blog link is: https://www.securestate.com/blog/2012/01/06/new-meterpreter-extension-released-msfmap-beta
Source repo is: https://code.google.com/archive/p/msfmap/source/default/source

**Comment by fsacer** [comment]
The above link is also dead. This one seems to be alive http://www2.infosecisland.com/blogview/19231-New-Meterpreter-Extension-Released-MSFMap-Beta.html, repo still exists. Any words on this? The existing methods of portscanning in MSF are so slow, I feel some improvements for portscanning in msf are needed.

**Comment by bcoles** [comment]
The above link which replaces the link which is dead which replaces the link which is dead is also dead.

Here are archive links:

* http://web.archive.org/web/20160328234714/https://www.securestate.com/blog/2012/01/06/new-meterpreter-extension-released-msfmap-beta
* http://web.archive.org/web/20160328234714/https://www.securestate.com/blog/2012/01/06/new-meterpreter-extension-released-msfmap-beta
* http://web.archive.org/web/20200203034243/http://www2.infosecisland.com/blogview/19231-New-Meterpreter-Extension-Released-MSFMap-Beta.html


The Google code archive repo is still alive and was last updated in 2014 - almost 9 years ago.

* https://code.google.com/archive/p/msfmap/source/default/source


This issue is rapidly approaching a non-zero number of decades since it was first created. In 3 days time this issue will celebrate its 8th birthday.

During the past 8 years the issue discussion has barely progressed past "I like this idea" and posting "the URL has changed" every few years.

Adding `attic` label.
