### ISSUE TITLE
auxiliary/scanner/ipmi/ipmi_dumphashes calling report_auth_info

### ISSUE THREAD

**Issue by geoffgarside** [rapid7/metasploit-framework#5269]
I can't see any issues already mentioning this. Apparently the ipmi_dumphashes scanner is still calling `report_auth_info`. Error message below.

```
*** auxiliary/scanner/ipmi/ipmi_dumphashes is still calling the deprecated report_auth_info method! This needs to be updated!
```

**Comment by wchen-r7** [comment]
The related issue is actually this:
https://github.com/rapid7/metasploit-framework/issues/4432

**Comment by void-in** [comment]
@wchen-r7 The issue https://github.com/rapid7/metasploit-framework/issues/4432 you reported was resolved in https://github.com/rapid7/metasploit-framework/pull/4535. The warning is due to missing credential object? Not following the login scanner guide https://github.com/rapid7/metasploit-framework/wiki/Creating-Metasploit-Framework-LoginScanners? Just want to get a clarity why the warning still.

**Comment by wchen-r7** [comment]
Nah the problem was that the #report_auth_info method used to call framework.db.report_auth_info to save credentials, and people couldn't see these creds by using the creds command. So we had to change #report_auth_info to make it use the new credential API.

However if you still rely on #report_auth_info, you're not exactly taking full advantage of the new credential API so that's why these modules should probably need to be updated. And that's why you see that error. I suppose we can change that error to a warning.

**Comment by void-in** [comment]
@wchen-r7 Yup. Thanks as always. Every login scanner should be re-wrote according to the Login Scanner guide.

**Comment by bcook-r7** [comment]
We should annotate existing report_auth_info call sites with a TODO message and a reference to how to convert it to the new API. Perhaps a path to a good module to use as a reference too.

**Comment by jvazquez-r7** [comment]
I'm going to create a new issue for the proposed "workaround"

**Comment by wchen-r7** [comment]
Resolved in https://github.com/rapid7/metasploit-framework/pull/5376
