### ISSUE TITLE
Update default credentials for auxiliary/scanner/http/netgear_sph200d_traversal

### ISSUE THREAD

**Issue by maaaaz** [rapid7/metasploit-framework#5322]
Hello,

Could it be possible to update the default credentials to "service:service" for the `auxiliary/scanner/http/netgear_sph200d_traversal` module ?

The [original advisory](http://www.s3cur1ty.de/m1adv2013-002) make mention about those credentials.

Thanks !

**Comment by void-in** [comment]
That is a simple change. @m-1-k-3 should take a look nevertheless. I think service:service is better than admin:password since the later only works in default case.

**Comment by m-1-k-3** [comment]
I don't know why we have not changed this ... service is the right solution.


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: void-in <notifications@github.com> </div><div>Datum:08.05.2015  12:43  (GMT+01:00) </div><div>An: rapid7/metasploit-framework <metasploit-framework@noreply.github.com> </div><div>Cc: m-1-k-3 <m1k3@s3cur1ty.de> </div><div>Betreff: Re: [metasploit-framework] Update default credz for
  `auxiliary/scanner/http/netgear_sph200d_traversal` (#5322) </div><div>
</div>That is a simple change. @m-1-k-3 should take a look nevertheless. I think service:service is better than admin:password since the later only works in default case.

**Comment by hmoore-r7** [comment]
Looks like the original module got this wrong, it is service:service, not admin:password.

**Comment by maaaaz** [comment]
@hmoore-r7: to be totally right, the original author had already written the module when I found the "service:service" credz and reported it to him. 
He just did not take the time to update his module :)

**Comment by hmoore-r7** [comment]
@maaaaz Ah OK, thanks!

**Comment by void-in** [comment]
@maaaaz Would you be interested in a PR? Just a simple change is required here for which we shouldn't bother either @m-1-k-3 or @hmoore-r7.

**Comment by hmoore-r7** [comment]
@void-in If you have time, go for it!

**Comment by void-in** [comment]
@hmoore-r7 Done

**Comment by maaaaz** [comment]
Well thank you guys.
