### ISSUE TITLE
msfconsole error after upgrade in Kali repo

### ISSUE THREAD

**Issue by theboarteam** [rapid7/metasploit-framework#5553]
someone has the same problem 
https://community.rapid7.com/thread/7388

    root@imlost:~# /usr/bin/msfconsole
    DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at /opt/metasploit/apps/pro/ui/lib/metasploit/pro/ui.rb:16)
    /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:464:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:464:in `block in eager_load!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:462:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:462:in `eager_load!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:347:in `eager_load!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:56:in `each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /usr/share/metasploit-framework/config/environment.rb:5:in `<top (required)>'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:189:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:63:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
    from /opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'

dpkg set the origin msfconsole ( where is /usr/share/metasploit-framework in kali) into msfconsole.framework , use the msfconsole.framewokr will start.

**Comment by dimitrios1988** [comment]
And what about armitage?

**Comment by bcook-r7** [comment]
Thanks, this issue has been reported via various channels already and should be fixed in the next release.

**Comment by ext1** [comment]
there are no  fix  (

**Comment by shuckins-r7** [comment]
Please note: a fix for this issue is in the weekly update build entering testing today. The fixed release should be available on Kali sometime middle of this week, will update here once it's out.

**Comment by todb-r7** [comment]
As @shuckins-r7 said, testing on a set of fixes started yesterday (Monday), and if all goes well, should be released today (Tuesday), at which point the Kali Linux folks ( @offensive-security and friends) will pick it up and distribute it via the usual `apt-get` way.

That said, here's a workaround for the situation right now to get you back in `msfconsole` land.

## Symptom

Running `msfconsole` or other msf commands (msfvenom, msfbinscan, etc) produces a stack trace that starts with, `DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped.`, and exits.

## Solution

Update to the latest Kali Linux distribution of metasploit: `apt-get update && apt-get upgrade metasploit`.

If your installed version is **later** than `4.11.3-2015061001`, this should resolve the issue. You can check the installed version with `dpkg -l metasploit | grep ii`.

## Workaround

If no update is yet available, using the command:

    msfconsole.framework

will correctly start the Metasploit Framework console. Other commands, such as  `msfvenom.framework` and `msfbinscan.framework`, and your usual console command arguments (`-q`, `-r path/to/resource/script.rc`, etc) will also work until update is available.

Note that other workarounds involve symlinking to alternate commands directly. This is not advised without carefully noting the existing linked pathnames first and restoring them before running an update. Otherwise, these symlink-based workaround risk breaking future updates (including the forthcoming solution to this problem).

**Comment by shuckins-r7** [comment]
[An update with a fix for this issue is now available](https://community.rapid7.com/docs/DOC-3075), if you are using a Metasploit Installer. An update will be available to Kali users after the Kali team completes their testing on the update we've provided.

**Comment by m4rc3l** [comment]
Thanks for the fix guys!

**Comment by bcook-r7** [comment]
Sorry for the troubles. I am going to close this for now.

**Comment by offensive-security** [comment]
Updated the fixed metasploit* packages in the Kali repositories.

**Comment by hmoore-r7** [comment]
This is still a problem on master (Pro), when using msfvenom and other utilities:
```
DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at /home/work/pro/ui/lib/metasploit/pro/ui.rb:16)
```

**Comment by Furqanameen** [comment]
There are other problems discussed here: termux/termux-packages#715
For now you can do the following which should work:

apt update
apt -y upgrade
apt -y install git ruby ruby-dev make clang autoconf curl wget ncurses-utils libsqlite-dev postgresql postgresql-dev libpcap-dev libffi-dev libxslt-dev pkg-config
git clone -b termux https://github.com/timwr/metasploit-framework.git
cd metasploit-framework
gem install bundler
gem install nokogiri -- --using-system-libraries
bundle install --gemfile Gemfile.local
./msfconsole
