### ISSUE TITLE
Adding Antivirus disable plugin

### ISSUE THREAD

**Issue by umarfarooq360** [rapid7/metasploit-framework#5620]
Usually it is very inconvenient to disable all anti-virus stuff and then launch metasploit. I thought that it would be nice to have a script that would detect and disable the antivirus. Although the antivirus might classify this as malicious. But this was just an idea?

**Comment by wvu-r7** [comment]
You could shell yourself and run ```killav```.

**Comment by void-in** [comment]
@wvu-r7 The killav is a meterpreter script. Which means he would need a meterpreter shell already on his machine which is not possible since the Metasploit itself wouldn't have started at that stage. I think putting the Metasploit directory in the AV exclusion rule should be good enough.

**Comment by umarfarooq360** [comment]
@void-in Would killav also kill the firewall?

**Comment by void-in** [comment]
@umarfarooq360 No. The purpose of killav is to kill all the AVs on a remote machine where you have got a meterpreter shell and the host AV solution is interfering in the post exploitation. I don't think it applies to your scenario where you want to start Metasploit on your own machine and the AV is detecting it. As I suggested in my previous message, put the Metasploit directory in AV exclusion and it should start correctly.

Tweaking firewall rules for your payloads through a ruby script that runs OS commands for changing the firewall rules based upon the values of LHOST and LPORT shouldn't be too difficult. This ruby script will first put those exceptions in the firewall rules, then start the multi handler for the payload. msfconsle -r option can be used for starting the console and running the script file.

If you have any other questions I would suggest you put it on https://community.rapid7.com and we can discuss there as this issue will be closed anyway since it is not related to a bug in Metasploit.

**Comment by wvu-r7** [comment]
:-)
