### ISSUE TITLE
Api, read result of a module

### ISSUE THREAD

**Issue by DeveloppSoft** [rapid7/metasploit-framework#5723]
Hello everyone,
I am looking at the remote api documentation and I have seen that when we call modules  (post, exploits, auxiliary), it return a job id but we can't see the output of that module.
But... I really need it and if I can do it without calling  console.* methods it could be very great.
How can I do it.
PS1: sorry for my bad english, I am a french student.
PS2: the goal is to developp a python gui like armitage.

**Comment by kernelsmith** [comment]
@DeveloppSoft please use the community page for support-type questions:  https://community.rapid7.com/community/metasploit.
Also, have you seen pymetasploit? https://github.com/allfro/pymetasploit  It's not a gui, but it is a python lib you could use.  Ultimately however you will need to use console methods to see console output.  The reason is that output is specific to the UI (in this case console).  If you always want to show a user the console, then just keep a console open (via RPC).  Otherwise, the expectation is that you will query for what you need.  For example when you run an exploit module, you get the job_id back.  You can then poll to see if that job_id has completed and then check the sessions list to see if a new session has been added.
