### ISSUE TITLE
adobe_flash_hacking_team_uaf crashes IE11 on Win7 x64

### ISSUE THREAD

**Issue by badbob** [rapid7/metasploit-framework#5765]
Looks like this exploit doesn't support any 64-bit payloads, but 32-bit payloads crashes the browser. 
Original Hacking Team Exploit works great. 

Should this exploit support 64-bit payloads?

**Comment by jvazquez-r7** [comment]
sorry @badbob 64 bits payloads aren't supported atm on adobe_flash_hacking_team_uaf. 

So it's expected to not work for example on IE Metro on Windows 8.1 64 bits. Should work still on IE Desktop on Windows 8.1 64 bits. Since in the last case, the broker will run on 64 bits, but the renderers will work on 32 bits!

**Comment by badbob** [comment]
Should I patch an existing exploit or develop separate 64-bit version with different name?

**Comment by jvazquez-r7** [comment]
@badbob new target in the existing exploit.
