### ISSUE TITLE
Problem bruteforcing users/passwords with telnet_login.rb and some devices

### ISSUE THREAD

**Issue by vallejocc** [rapid7/metasploit-framework#5814]
I have been testing telnet_login.rb with a list of users and password (i have set userpass_file option) against some devices and i found a problem. I tested against Comtrend AR-5387un and Comtrend VR-3025un, but i guess the problem could happen with other devices and telnet servers.

When a invalid user+password is sent to the telnet server the communication is like this:

server>  .....!.........BCM96368 Broadband Router
server>  ..!......Login: 
client>   debug
server> debug
server> Password: 
client>  synnet
server> Login incorrect. Try again.
server> Login: 

When invalid credentials are sent, the server shows the login prompt again and the connection is not closed (telnet.rb module seems to be waiting that the server will close the connection). When you try to bruteforce a list of users+passwords, each time that an invalid credentials are sent, a connection is opened and never closed.

In addition, theses devices that i tested don't let you open more than 2 telnet connections at same time. Because of the connections remain open when you try a invalid user+pass, after trying two credentials of the list, it is not possible to continue with the bruteforcing task (because it's not possible to open more connections to the telnet server).

To solve this problem I modified telnet_login.rb to close the connection (scanner.sock.close) when the credentials are invalid and it started to work. I modified telnet_login.rb module in the part where the scanning is done, but Im not sure if scanner.sock member should be accessed from telnet_login.rb module or it is better to modify other more internal module:

    scanner.scan! do |result|
      credential_data = result.to_h
      credential_data.merge!(
          module_fullname: self.fullname,
          workspace_id: myworkspace_id
      )
      if result.success?
        credential_core = create_credential(credential_data)
        credential_data[:core] = credential_core
        create_credential_login(credential_data)
        print_good "#{ip}:#{rport} - LOGIN SUCCESSFUL: #{result.credential}"
        start_telnet_session(ip,rport,result.credential.public,result.credential.private,scanner)
      else
        invalidate_login(credential_data)
        vprint_error "#{ip}:#{rport} - LOGIN FAILED: #{result.credential} (#{result.status}: #{result.proof})"
        scanner.sock.close <--------------------------------------
      end
    end

**Comment by jvazquez-r7** [comment]
Hello @vallejocc,

Since login attempt is opening a new connection I don't think hurts at all closing the connection after every failed login. Even more, I'd say it's a good thing :). And I think the location you're selecting to close the socket is the correct once. It could be closed on the "attempt_login" callback. But in this case, when telnet_login tries to create the session over the socket (when a successful login is generated) it will fail. 

So I'm just modifying your patch to use the `disconnect` method instead of `scanner.sock.close` directly :) See my proposed patch here: https://github.com/rapid7/metasploit-framework/pull/5861

Of course have into account, which when successful logins happen, the socket is still open (because a new session is created over the socket. So if the telnet_login guesses two logins, the bruteforce won't be able to continue (becuase of the limit by the device as far as you're telling us :)).

**Comment by jvazquez-r7** [comment]
btw @vallejocc thanks a lot for the reporting and the proposed fix :) It was helpful. Also, for the future, PR's are welcome if you interested :) Even if you're not 100% sure of some mods, with a good analysis like the one above and a patch we can provide feedback in the PR. I encourage you to make it next time if you would like! Thanks!

**Comment by vallejocc** [comment]
@jvazquez-r7 next time ill create a PR instead of issue. Thank you :)

**Comment by jvazquez-r7** [comment]
@bcook-r7 landed #5861, closing it!
