### ISSUE TITLE
How can we run mfscosole in background

### ISSUE THREAD

**Issue by rajkotraja** [rapid7/metasploit-framework#5848]
mfsconsole instance and session dies when i close my ssh client.
How can i let it run in background and resume when wanted and run commands.
pls help me on this.

**Comment by void-in** [comment]
This is the way SSH works where every session is run in isolation. You can use the Linux screen command in order to connect to a previously connected SSH session. I am going to close this since issues pages are used for reporting bugs/features. Feel free to post it at https://community.rapid7.com if you need generic penetration testing advice from other community users.

**Comment by kernelsmith** [comment]
@rajkotraja this isn't a metasploit issue, it's an OS issue.  SSH always terminates any process it has started, unless that process has been daemonized.  There are ways of daemonizing an arbitrary binary or shell command, however it's much much easier to just run a program like screen or tux instead.  Screen/tux will create a daemonized shell (more or less) to which you can connect and disconnect after SSH'ing in.  Google can tell you more than you could ever want to know about screen or tux.  A simple approach is to:  ssh in to your metasploit box, run `screen -dRR`, and in the resulting shell run `msfconsole`.   Then, in the future, if you disconnect your ssh client and reconnect, just run `screen -dRR` again and you'll be connected back w/your screen session running msfconsole.  The `screen -dRR` command also creates a screen session if one does not exist, which is why it works even when there is no existing screen session.  Note, if you kill msfconsole or screen, then you'll be stuck again, so don't do that.  However, if you need to shutdown your msfconsole session, run the `save` command first to at least preserve your current settings (won't preserve your msf sessions however unless those are configured to reconnect (http/https sessions mainly)).  Once you're in a screen session (like after running `screen -dRR`) you can hit `ctl-a` to enter screen's "command" mode and then `?` to get help.  For example, you can detach from your screen session (w/o destroying it) using `ctl-a`, followed by `d`.  If you'd like to create additional screen sessions, so you can more easily run shell commands etc, do `ctl-a` followed by `c`, and to switch between your sessions, use `ctl-a` followed by `a`.  Use a search engine to learn more, or to use tux instead of screen.

**Comment by OJ** [comment]
My msfconsole lives behind tmux. Many people use screen or byobu. Lots of
options!

**Comment by kernelsmith** [comment]
lol, don't know why I wrote tux

**Comment by all3g** [comment]
**screen** / **tmux** may help you. Screen is installed by default.
