### ISSUE TITLE
auxiliary/scanner/oracle/sid_brute.rb crashes with big dictionaries

### ISSUE THREAD

**Issue by ewilded** [rapid7/metasploit-framework#5854]
When using SID_FILE larger than approximately a thousand entries, the script crashes after reaching that number. The reason for this is probably resource (TCP sockets) exhaustion, as the check function creates new connection every time it is called, but it does not disconnect on failures (e.g. when SID is not found).
I think it would be the best to use use single connection created before the loop with checks and recreated only if needed.

**Comment by jvazquez-r7** [comment]
Thanks for your report @ewilded ! I've added https://github.com/rapid7/metasploit-framework/pull/5886 to try to fix it. 

I preferred to be conservative, and leave the current behavior, one connection by SID. Just ensure disconnecting the sockets after every check, to allow the server to free resources. (Instead of reuse the same connection for every SID check).

It would be helpful to know if https://github.com/rapid7/metasploit-framework/pull/5886 helps in your case :) Thanks!
