### ISSUE TITLE
exiting cleanly from a shell spawned in a meterpreter session

### ISSUE THREAD

**Issue by kernelsmith** [rapid7/metasploit-framework#5922]
I'm not sure this is a bug vs operator error, but thought I would bring it up nonetheless.  It doesn't hurt the active meterpreter session, but the errors seem handleable.  Interestingly, this only happens the first time.  If I drop to a shell again and just run exit, I don't get the errors.  Maybe the errors are actually not related to running exit, but rather the output just woven in there to make it look this way.

Meterp session was created w/an msfvenom-created binary and run from a vmshare drive.  User is an admin, but the payload was not run with "Run as administrator".  Payload is windows/meterpreter/reverse_tcp (x86) and run on Win7_x86

```
meterpreter > shell
Process 3004 created.
Channel 1 created.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\>exit
exit
[-] Failed to spawn shell with thread impersonation. Retrying without it.
Process 2420 created.
Channel 2 created.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\>exit
exit
[-] core_channel_interact: Operation failed: The handle is invalid.
meterpreter >
```

```
msf exploit(handler) > version
Framework: 4.11.4-dev-bde504f8
Console  : 4.11.4-dev-bde504f8.15168
msf exploit(handler) > ruby -v
[*] exec: ruby -v

ruby 2.1.6p336 (2015-04-13 revision 50298)
```

**Comment by OJ** [comment]
I've seen this quite a bit, definitely a known problem. Behind the scenes the `shell` command uses `execute` with the `-t` parameter for thread impersonation. In certain cases, the impersonation can fail, resulting in no shell. Trying again results in no shell. So I added code ages ago that retries the `execute` call without `-t` so that you can at least get a shell _without_ impersonation.

There are times when the shell misbehaves and doesn't exist cleanly, and MSF currently sees this as an impersonation failure, and hence spawns another shell without impersonation. Exiting that shell should be fine.

I've not see the `core_channel_interact` failure before though.

**Comment by kernelsmith** [comment]
Ok cool, thanks @OJ

**Comment by OJ** [comment]
It'd be nice to see a way to clean this up, but I'm not sure how. It might be worth changing the shell command so that it gets another parameter that allows you to avoid the impersonation. If a shell fails, throw a warning to the user to try shell again with this parameter? That'd prevent the auto-spawning of a new one while still giving the ability to get a shell regardless.

Thoughts?

**Comment by kernelsmith** [comment]
Don't worry about it man. I honestly don't give a crap anymore

**Comment by robertjriga** [comment]
Im in powershell module in metasploit ans IDK how to exit from it

**Comment by bcoles** [comment]
> 
> 
> Im in powershell module in metasploit ans IDK how to exit from it

Locate and press the power reset button on your PC.
