### ISSUE TITLE
Failed to encode - Part 2

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#5961]
Much like #5907 and reproduced on multiple systems:
```
msf exploit(ms06_040_netapi) > show options

Module options (exploit/windows/smb/ms06_040_netapi):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOST                     yes       The target address
   RPORT    445              yes       Set the SMB service port
   SMBPIPE  BROWSER          yes       The pipe name to use (BROWSER, SRVSVC)

Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  thread           yes       Exit technique (Accepted: , , seh, thread, process, none)
   LHOST     192.168.92.105   yes       The listen address
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   (wcscpy) Automatic (NT 4.0, 2000 SP0-SP4, XP SP0-SP1)


msf exploit(ms06_040_netapi) > set RhOST 10.55.55.9
RhOST => 10.55.55.9
msf exploit(ms06_040_netapi) > exploit

[-] Exploit failed: No encoders encoded the buffer successfully.
```

Banner:
```
       =[ metasploit v4.11.4-dev-ec3aecbc                 ]
+ -- --=[ 1479 exploits - 859 auxiliary - 254 post        ]
+ -- --=[ 432 payloads - 37 encoders - 8 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]
```

**Comment by bcook-r7** [comment]
Thanks for the note @mubix .

Surprisingly the TCP stager resiliency patch cf8bbbfa3db867b9d6fd3bcfaf03cada93d4eb13 caused this to fail. Is the updated payload unable to be encoded within the badchars constraint? It doesn't appear to be a size problem.

**Comment by mubix** [comment]
@bcook-r7 not sure, is there a way that I can test this?

**Comment by bcook-r7** [comment]
You would need to probably set LogLevel to 1. I went ahead and grepped framework.log for 'Encoder' to do some preliminary investigation. It does appear to be a badchars issue with the new opcodes in the stager:
```
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: iteration 1: Encoder x86/shikata_ga_nai failed: A valid opcode permutation could not be found.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: iteration 1: Encoder generic/none failed: Encoding failed due to a bad character (index=9, char=0x00)
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: iteration 1: Encoder x86/countdown failed: Encoding failed due to a bad character (index=157, char=0x00)
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: iteration 1: Encoder x86/nonalpha failed: Encoding failed due to a bad character (index=45, char=0x00)
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: iteration 1: Encoder x86/nonupper failed: Encoding failed due to a nil character
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/add_sub is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/context_cpuid is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/context_stat is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/context_time is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/bloxor is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/avoid_utf8_tolower is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/opt_sub is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder generic/eicar is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/single_static_bit is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/unicode_mixed is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/avoid_underscore_tolower is manual ranked and was not defined as a preferred encoder.
[09/10/2015 16:20:18] [w(1)] core: windows/meterpreter/reverse_tcp: Encoder x86/unicode_upper is manual ranked and was not defined as a preferred encoder.
```

**Comment by bcook-r7** [comment]
Yeah, something about the reliability bit that is causing it to fail; we may need to either recode that portion to not require encoding a 0 character, or make reliable an explicitly enabled option than implicitly.

A temporary patch like this should get you over the hedge:

```diff
diff --git a/lib/msf/core/payload/windows/reverse_tcp.rb b/lib/msf/core/payload/windows/reverse_tcp.rb
index d11c607..5ca02f9 100644
--- a/lib/msf/core/payload/windows/reverse_tcp.rb
+++ b/lib/msf/core/payload/windows/reverse_tcp.rb
@@ -36,7 +36,6 @@ module Payload::Windows::ReverseTcp
     # Generate the advanced stager if we have space
     unless self.available_space.nil? || required_space > self.available_space
       conf[:exitfunk] = datastore['EXITFUNC']
-      conf[:reliable] = true
     end

     generate_reverse_tcp(conf)
```

**Comment by mubix** [comment]
Awesome! worked like a charm (temp patch)

**Comment by OJ** [comment]
This is strange. The only thing that comes to mind here is size. The "failed to encode" messages also appear when the encode generates code that's too big to fit in the target exploit.

My guess: with reliability turned on, encoding of the stager results in a payload that's too big for the exploit in question. I can't see how it'd be anything else.

If you leave it as is, and encode it with msfvenom from the command line, you don't see the error, which surely implies it's not the payload..
```
./msfvenom -p windows/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 -e x86/shikata_ga_nai -f exe > /dev/null
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 360 (iteration=0)
x86/shikata_ga_nai chosen with final size 360
Payload size: 360 bytes
```

**Comment by mubix** [comment]
I'm sorry, false alarm on my side guys, sorry, I had windows/shell_bind_tcp set has a hard setting when I tried it again...

Current code:
```
  def generate
    conf = {
      port:        datastore['LPORT'],
      host:        datastore['LHOST'],
      retry_count: datastore['ReverseConnectRetries'],
      reliable:    false
    }

    # Generate the advanced stager if we have space
    unless self.available_space.nil? || required_space > self.available_space
      conf[:exitfunk] = datastore['EXITFUNC']
      conf[:reliable] = true
    end
```

Changing this to:
```
      conf[:reliable] = false
```
solved it

**Comment by bcook-r7** [comment]
Note @OJ its the badchars that causes the encoders to bail. If you comment these out from the exploit, the encoding works. Curiously, I could not get the equivalent to fail with msfvenom either.

**Comment by rwhitcroft** [comment]
@OJ asked me to post here as I'm having a similar problem (but @bcook-r7 's diff didn't fix).

```
Module options (exploit/windows/iis/ms02_018_htr):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   RHOST  192.168.20.20   yes       The target address
   RPORT  80              yes       The target port


Exploit target:

   Id  Name
   --  ----
   0   Windows NT 4.0 SP3


msf exploit(ms02_018_htr) > exploit -j

[-] Exploit failed: No encoders encoded the buffer successfully.
msf exploit(ms02_018_htr) >
```

Same behavior with windows/exec and shell/bind.

**Comment by OJ** [comment]
Thanks @rwhitcroft!

I did some investigation into this yesterday. So the reason why both of these are failing is because of payload size. The payload size checks are done prior to encoding, so MSF thinks that the payload can fit, however when encoded they're bigger than the available space and so it fails.

In the case of the IIS exploit, this happens _without_ the stager resiliency changes as well, so that payload was already too big.

Who's up for some shellcode golf? /cc @jlee-r7

**Comment by bcook-r7** [comment]
@bwatters-r7 , I've been staring at this a bit this morning, and I think there are some places where our size check logic is off. I can fill you in on what I was thinking, could you take a look?

**Comment by bwatters-r7** [comment]
I've been poking at this for a bit, and I wish I had more to report, but here's what I have so far....
@bcook-r7 is right on the bad characters.  The exploit has 7 bad characters (\x00\x0A\x0D\x5c\x5f\x2f\x2e) that it forces the encoder to avoid, and that limitation causes framework to die when it tries to generate the code block in ```Rex::Poly::Logicalblock``` Specifically, the code allows it 128 tries to get the permutation right, and it fails all of them, every time.  I was able to reproduce the error in venom with the following command:
```
./msfvenom -p windows/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 -e x86/shikata_ga_nai -f exe -o test.exe --bad-chars '\x00\x0A\x0D\x5c\x5f\x2f\x2e'
```
So this then begs questions about why we succeed in framework when disabling reliability; that cost me time because I did not understand framework and I made a bad assumption.  Disabling reliability does not make  x86/shikata_ga_nai work, it allows the x86/jmp_call_additive encoder to succeed.

Essentially, I have only been able to clarify the question: Why does x86/jmp_call_additive succeed in venom while it fails in framework?  That's where I am headed next.  Venom successfully encodes the payload at 365 bytes, and framework says that it can fit up to 370 in ms06-040, so in theory, it should work.... maybe?

**Comment by bcook-r7** [comment]
Different default value for EXITFUNC maybe? That pushes up to 385

```
./msfvenom -p windows/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 -e x86/jmp_call_additive -f exe -o test.exe --bad-chars '\x00\x0A\x0D\x5c\x5f\x2f\x2e' EXITFUNC=thread
```

**Comment by bwatters-r7** [comment]
Not only does that make sense, but it reflects reality.  If you change the exit function to process in framework, it builds fine.

**Comment by bwatters-r7** [comment]
For the issue reported by @rwhitcroft, there seems to be something else at play.  Many of the encoders fail/bail for predictable reasons like not being a preferred encoder or exceeding size, but specifically, the following exit with exceptions:
```
[06/01/2016 10:07:11] [w(1)] core: windows/shell/bind_tcp: iteration 1: Encoder x86/shikata_ga_nai failed: An encoding exception occurred.
[06/01/2016 10:07:11] [w(1)] core: windows/shell/bind_tcp: iteration 1: Encoder x86/fnstenv_mov failed: A valid encoding key could not be found.
[06/01/2016 10:07:11] [w(1)] core: windows/shell/bind_tcp: iteration 1: Encoder x86/call4_dword_xor failed: A valid encoding key could not be found.
[06/01/2016 10:07:11] [w(1)] core: windows/shell/bind_tcp: iteration 1: Encoder x86/alpha_upper failed: An encoding exception occurred.
[06/01/2016 10:07:11] [w(1)] core: windows/shell/bind_tcp: iteration 1: Encoder x86/alpha_mixed failed: An encoding exception occurred.
```
After digging for a bit into the x86/shikata_ga_nai exception, I found that the culprit was a RunTimeError thrown after rand_perm in block.rb fails to come up with a permutation that does not contain the bad chars.  
So that made me check to see what exactly these bad characters were..... This exploit is listed as having 194 bad characters.  I can see why the encoders are choking on it.  I assume this used to work?  Since it targets NT4, something may have broken it and no one thought to test it or maybe we dropped an encoder that could actually handle it?  Is there a way to determine which encoder used to be able to handle it?
```
Payload information:
  Space: 2048
  Avoid: 194 characters
```

**Comment by egypt** [comment]
@bwatters-r7 I'd guess one of the alpha encoders should have worked. The others can't produce such a restricted character set. I think that's a very different problem from what this ticket was originally created to describe, though.

**Comment by egypt** [comment]
And it looks like the alpha encoders are failing because of the getpc stub. I'm not sure how that exploit ever worked with the current settings because a pure alpha encoder is impossible without knowing the location of the payload buffer. An exploit must provide `BufferRegister` in the encoder options to avoid a non-alpha getpc.

**Comment by egypt** [comment]
Tracked the `ms02_18_htr` bug to datastore differences. Not sure when it was introduced but the `AllowWin32SEH` option apparently used to default to true somehow and now it doesn't. Either way, it's unrelated to the original bug in this ticket, so closing. Thanks, folks!
