### ISSUE TITLE
RHOSTS to RHOST

### ISSUE THREAD

**Issue by ContactLeft** [rapid7/metasploit-framework#5994]
If I run an auxiliary/gather/shodan search on *something (an exploit) supported in the Framework. 

If the results are stored in the database and can be added to RHOSTS via the -R  switch.

which gives RHOSTS => file:/tmp/msf-db-rhosts-date-blah-blah-etc 

however some (or most im trying) of the exploits only support RHOST.

Is there a way to utilise "hosts" in the database ? for specific exploits that are sitting in the database that seem not to support it?

**Comment by void-in** [comment]
The exploit modules are supposed to be run against a single target at a time since every target require specific settings such as the target OS, patch level, etc. I am going to close this since this is the way Metasploit is supposed to work. You can take a look at http://www.infosecisland.com/blogview/7728-Rapid-Fire-PSEXEC-for-Metasploit.html if you want to see how to run an exploit module against multiple targets.
