### ISSUE TITLE
Android Meterpreter: Loading stdapi Extension Fails

### ISSUE THREAD

**Issue by raulsiles** [rapid7/metasploit-framework#6002]
Hi,
I'm using Kali Linux 2.0 and Metasploit Framework Version: 4.11.4-2015090201.

When establishing an Android meterpreter session (using "exploit/multi/handler" and an "android/meterpreter/reverse_tcp"), both the android and stdapi extensions are loaded properly.

However, if from that session I use the "exploit/android/local/futex_requeue" module, the new session obtained (with high privileges) does not load the android (there is an option for it) or, even, the stdapi extensions. If you  try to load the stapi extension manually, the following error appears:

meterpreter > load stdapi
Loading extension stdapi...
[-] Failed to load extension: No response was received to the core_enumextcmd request.

The same attack scenario using a previous Metasploit version works, such as Kali Linux 1.1.0 and Metasploit Framework Version: 4.11.1-2015042001.

**Comment by timwr** [comment]
Hi @raulsides, this is because the session is launched with the ```dalvikvm``` command and I couldn't figure out a way to load the android classes this way. It's definitely fixable, system apps have near root privileges and have these classes loaded. If you've got a root shell you could try playing with the dalvikvm command, the zygote process and libndkstager.so

**Comment by timwr** [comment]
Hi @raulsiles, this is because the session is launched with the ```dalvikvm``` command and I couldn't figure out a way to load the android classes this way. It's definitely fixable, system apps have near root privileges and have these classes loaded. If you've got a root shell you could try playing with the dalvikvm command, the zygote process and libndkstager.so

**Comment by raulsiles** [comment]
Thanks for the details @timwr but, what has specifically changed between the two aforementioned Metasploit versions in order to get the failing behaviour?

BTW, in the most recent version, as I cannot load stdapi, I cannot get a shell from the new session obtained after exploiting "futex_requeue" to elevate privileges.

**Comment by timwr** [comment]
Apologies, you're right, this looks like a regression. load stdapi should work but without the webcam_snap, etc commands.

**Comment by timwr** [comment]
Putting a ```if (context != null)``` check here https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/library/src/com/metasploit/meterpreter/AndroidMeterpreter.java#L113 should fix this. I'll send a pull request tonight.

**Comment by OJ** [comment]
Thanks @timwr, the check for `null` should probably go inside the `IntervalCollectionManager`, rather than being wrapped. At least then we know it's catered for regardless of who/where this is called.
