### ISSUE TITLE
Various problems with meterpreter

### ISSUE THREAD

**Issue by Cotel** [rapid7/metasploit-framework#6101]
Hi,

I'm using **browser_autopwn** and when it comes to post-exploitation everything fails:

* Unknown commands as: migrate, getsystem...
* Fails at loading modules: priv, incognito... ('Failed to load extension: No module of the name ext_server_priv.jar dound')
* Fails at running scripts: most of them really ('This version of Meterpreter is not supported with this Script')

The metasploit version is 4.11.4-201509201 and I'm running Kali linux 2.0 in a virtual machine.

Hope you can help me, Thanks :D

**Comment by void-in** [comment]
Please use https://community.rapid7.com for support queries. What you are seeing is normal since Java meterpreter don't have a getsystem command to privilege escalation directly. It runs in a sandbox. The failed to load extension is the same issue as well if the version of meterpreter is not supporting the module. I am going to close this. If you need further help, post your query on the community site.
