### ISSUE TITLE
windows xp multiple instalation errors

### ISSUE THREAD

**Issue by adamast0r** [rapid7/metasploit-framework#6206]
The last versions (metasploit-4.11.5-windows-installer.exe) does not install in windows XP sp3 anymore, I got multiple errors. I had to install Version 4.1.0 and it seems to be working fine.

There is a problem with the postgresql/bin/ binary's and when the setup try to install them it gives "not valid 32 bits application" error.

Also several *.bat files might have the incorrect path? the use of the linux slash (/) seems to be incorrect but I am not sure if this the problem, some examples:

\script\serviceinstall.bat 

...
""C:\metasploit/postgresql/bin\pg_ctl.exe" register -N "metasploitPostgreSQL" -D "C:\metasploit/postgresql/data"
...
"C:\metasploit/postgresql/bin\pg_ctl.exe" unregister -N "metasploitPostgreSQL"

\apps\pro\ui\scripts : 
...
"C:\metasploit/ruby/bin/ruby.exe" "C:\metasploit\apps\pro\ui\thin_service_install.rb"
.

There are more files with the same issue this is just an example.

**Comment by OJ** [comment]
Why on earth are you using Windows XP?!

**Comment by adamast0r** [comment]
why not?

**Comment by fake-name** [comment]
Because it's been EOL for 2 years?

**Comment by OJ** [comment]
XP isn't supported by anyone, or any thing, including MS themselves. The error your seeing implies that the binaries that need to be run are not supported on XP.

Please update your OS.

**Comment by adamast0r** [comment]
I am fine with that, however it seems that versions not very long time ago indeed support windows XP  (metasploit 4.1.0).

**Comment by OJ** [comment]
I don't think it's Metasploit that's the problem here, it's the "stuff" that Metasploit depends on.

> not valid 32 bits application

^^ This is an indication of binaries compiled for non XP machines.

**Comment by ms-chandra** [comment]
Hi All,

I've   recently tried to install the Metasploit 4.14.2 on Windows 7 Pro by using the Metasploit installer.exe file. After completion of around 99% of the installation process, it suddenly showing an error message on screen by saying that - 
**"Problem running post-install step. Installation may not complete correctly.
Error running C:\metasploit/postgresql/scripts/serviceinstall.bat
INSTALL:'net' is not recognised as an internal or external command, operable program or batch file"**

So, any suggestions on what exactly the problem is.... so that it can help me in resolving the same.

Thanks in Advance...... - Satish
![metasploit issue](https://user-images.githubusercontent.com/34564021/34029036-4b56570a-e18c-11e7-87e0-db97b6b0c168.png)

**Comment by pbarry-r7** [comment]
Hi @ms-chandra.  Please don't comment on unrelated GitHub issues, instead, for support items, please join us on [IRC](https://metasploit.help.rapid7.com/docs/joining-the-metasploit-irc-channel) or visit the [Rapid7 Knowledge Base](https://kb.help.rapid7.com/discuss).  In your instance, it appears the environment that the install process is running in cannot locate the 'net' command, similar to this issue: https://serverfault.com/questions/50173/error-net-is-not-recognized-as-an-internal-or-external-command-operable-pro
