### ISSUE TITLE
Add Wordpress Better-wp-security Plugin Remote Code Execution Module

### ISSUE THREAD

**Issue by madmike33** [rapid7/metasploit-framework#6212]
Hello,if someone is interested it would be great if this vuln had a msf module
Poc: https://cxsecurity.com/issue/WLB-2015090197

**Comment by nashe** [comment]
The link you provided don't give a PoC and seems to copy of https://cxsecurity.com/issue/WLB-2015040018 (described as “Disputed”!), which is the same described vulnerability, but 5 months older. 

This said, I searched for a confirmation of the effective presence of the vulnerability but found nothing. The call to `call_user_func_array()` can be found two times in the file: 
* L723, in `admin_tooltip_ajax`:  `call_user_func_array( $this->tooltip_modules[ sanitize_text_field( $_POST['module'] ) ]['callback'], array() );`. 
* L754, in `admin_tracking_ajax`: `call_user_func_array( $this->tooltip_modules[ sanitize_text_field( $_POST['module'] ) ]['callback'], array() );`.

Since we can control `$_POST['module']` (tell ourselves that the `sanitize_text_field()` call does something that can be bypassed. Why not.), we only can call a function referenced in the `ITSEC_Core::$tooltip_modules` array, containing no user-controller data nor functions that can potentially be used in a malicious way.

I can't guarantee that my analysis is 100% correct and that the vulnerability is not present elsewhere in the source code - but the lack of a PoC, the fact the pseudo-exploit is disputed, the absence of any information in the changelog (nice vendors, sometimes…) and the little research I made let me think I'm right :)

**Comment by nashe** [comment]
I don't think my only advice could be enough to state the plugin is not vulnerable this way, so if someone can have a look…
