### ISSUE TITLE
Web page not available from exploit/android/browser/samsung_knox_smdm_url

### ISSUE THREAD

**Issue by shufan123** [rapid7/metasploit-framework#6379]
Hello,

I tried the exploit/android/browser/samsung_knox_smdm_url and it does `gathering target information` , ` sending HTML ` , `serving exploit` and then on the browser i get webpage not available which means that metasploit didn't share the exploit??!!

Thank you very much.

**Comment by wchen-r7** [comment]
Webpage not found? It means your browser failed to meet the requirements of the exploit. For this exploit, the requirements are pretty simple: It must be an Android, and it must support JavaScript. On your msfconsole, it should say what requirement(s) you failed to meet. Please try to post the console output.

**Comment by shufan123** [comment]
I am on android 4.0.4 on stock browser and it didn't report any unmet requirements

**Comment by wchen-r7** [comment]
@shufan123 Ok I see. Is your Android a Samsung device? It sounds like you don't have the UniversalMDMClient application, so smdm:// registers to nothing.

**Comment by shufan123** [comment]
@wchen-r7 Yes it is ...I thought it was samsung only that had this flaw?

**Comment by wchen-r7** [comment]
Yeah, Samsung was vulnerable. I'm not sure if your device has UniversalMDMClient though (or that it's still vulnerable). We might need to dig into it more.

**Comment by shufan123** [comment]
@wchen-r7 if you are willing to help, i would love to and a million thanks to you.

**Comment by wchen-r7** [comment]
@shufan123 for debugging purposes, it would be nice to know your target environment? Android version, version of Samsung firmware, etc.

**Comment by shufan123** [comment]
@wchen-r7 
 ==========Samsung GT-S7562 ==== 
android-version==>4.0.4
Kernel version==>3.0.8-1218740

**Comment by wchen-r7** [comment]
@shufan123 I actually have a hard time finding the right device that is vulnerable. However, as far as I can tell, if you get a "webpage not available" error, it really means your device does not support ```smdm://```. I was at least able to find a real Samsung Galaxy Note 4 that responds to it (not actually exploitable, but able to respond ```smdm://``` by the exploit). Because of this, "webpage not available" seems to be an expected behavior, so I will go ahead and close this. If you disagree, please let me know and I can reopen. Thanks.

**Comment by science1391ir** [comment]
what is this exploit's job???
