### ISSUE TITLE
register_file_for_cleanup securely

### ISSUE THREAD

**Issue by void-in** [rapid7/metasploit-framework#6452]
The register_file_for_cleanup method (https://github.com/rapid7/metasploit-framework/blob/dea4f35b0e6947c3b96d992c526db348cda36de0/lib/msf/core/exploit/file_dropper.rb#L137) deletes the file through del.exe (Windows) and rm (\*nix). However, in both cases, the deleted file can be recovered forensically. Instead of using the del and rm commands, it should use erase (windows) and shred  (\*nix). Erase is available on all versions of Windows upto Win10 while shred is available on all common flavors of Linux and Unix OSes as well.

Thoughts?

**Comment by wvu-r7** [comment]
Hey, @void-in. :)

I like this idea, but I see a few problems.

First of all, isn't ```ERASE``` an alias for ```DEL```? **[1]** Please correct me if I'm wrong!

Secondly, ```shred``` is far from portable, since it's a GNU coreutils command. **[2]** BSD-like systems have ```rm -P``` instead. **[3]**

Thirdly, even if you wipe a file with something like ```shred```, the data isn't necessarily gone. **[2]** For example, if you're on a flash filesystem, you'll have to deal with the translation layer. **[4]**

Lastly, secure deletion is generally slow.

It would be nice if we could make this optional. A smaller forensic footprint would be lovely!

I've thought about adding a secure deletion method to ```Msf::Post::File```. What do you think?

**[1]** https://technet.microsoft.com/en-us/library/cc770306.aspx
**[2]** https://www.gnu.org/software/coreutils/manual/html_node/shred-invocation.html
**[3]** https://www.freebsd.org/cgi/man.cgi?rm
**[4]** https://www.usenix.org/event/fast11/tech/full_papers/Wei.pdf

**Comment by void-in** [comment]
@wvu-r7 Thanks a lot. It must have been the missing coffee cup due to which I didn't fully understand the erase command description on MSDN :)

I myself wasn't too sure about the shred command. I only had CentOS/RHEL/Ubuntu/Debian around here. I couldn't test it on BSD. I will close this now and start working/researching about a solution. You are right. Whatever the solution is, it needs to be within the framework in order to make it generic and platform independent. Thanks a lot for the wonderful input.

**Comment by wvu-r7** [comment]
Thank you for the suggestion! I think we share the same idea. :)

**Comment by busterb** [comment]
/dev/shm is a good place to put files on most recent linux systems. tmpfs is ram-backed and doesn't survive reboots. I'd feel somewhat confident that unlink actually frees the backing pages back to the vm subsystem, rather than leaving blocks hanging around.

**Comment by wvu-r7** [comment]
Thanks for your input, @bcook-r7! I've been using that trick for years now, and it works great, but sometimes I find mounts that are noexec and/or nosuid, and any good sysadmin worth their salt will look in that directory. We should keep it in mind for FileDropper 2.0, though. :)

**Comment by wvu-r7** [comment]
Thanks for your input, @bcook-r7! I've been using that trick for years now, and it works great, but sometimes I find mounts that are ```noexec``` and/or ```nosuid```, and any good sysadmin worth their salt will look in that directory. We should keep it in mind for ```FileDropper``` 2.0, though. :)
