### ISSUE TITLE
Refreshed documentation for msf-dev on Ubuntu

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#6475]
Unfortunately, we still can't pull request wiki updates, and I'd like to get an opinion on this.

~~~If you check out `rapid7/metasploit-framework.wiki`, you should see a branch there of `new-ubuntu`. This is a recently refreshed, stepped-through version of http://r-7.co/MSF-DEV written for Ubuntu 14.04 Desktop.~~~ Forget that, just see [this page](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment-Ubuntu-14.04).

I don't know if MSF-DEV has been updated for Kali 2.0; from what I can see on the wiki, it's still 1.9 focused, but maybe it all still works the same.

How do you want to handle this? I would be happy with someone maintaining both, and can volunteer to keep the Ubuntu version up to date, but I'd like to rely on someone else to sign off on Kali-centric dev docs.

Assigning to @lsanchez-r7 because I know he loves it when I do, but really anyone is welcome to weigh in on this. We can always merge the two, or have a link farm pointing to different environment setups (thus promoting @darkoperator's version up from a mere footnote), or whatever. I just haven't tested the Kali docs in a while.

**Comment by todb-r7** [comment]
You know what, here you go:

https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment-Ubuntu-14.04

So now the question is just how to best present. I say that http://r-7.co/MSF-DEV should be a link farm pointing at the various operating system build outs. What say you, @tdoan-r7 and friends?

**Comment by todb-r7** [comment]
Also, I saw that @bcook-r7 edited the main MSF-DEV page yesterday, so I'm guessing it's being maintained.

**Comment by FireFart** [comment]
@todb-r7 shouldn't we recommend the official "secure installation" for RVM?
https://rvm.io/rvm/security

It's more work but in the end you will not pass shell scripts to your shell (instead you pass unknown binaries :) )

Also the rvm keyserver part never worked for me I always do the alternative command:
`curl -sSL https://rvm.io/mpapis.asc | gpg --import -` which is also more proxy friendly if you have one in place.

The `bundler config` docs are before the initial `gem install bundler` (it's mentioned in the getting metasploit section). So we should add an `gem install bundler`. If we do an gem install bundler before getting metasploit, bundler will be installed globally instead of the gemset.

**Comment by jlee-r7** [comment]
@todb-r7 I've been looking into solutions for the Pull Requests to wiki pages problem. 

penflip.com has a great interface including a web-based editor and a simple PR-like thing, but there's no content search. We could potentially solve that by embedding a site-specific google search thinger. Also, it doesn't seem to be under active development anymore, so new features might not be forthcoming.

gitbook.com has integration with GitHub for the PR part and the web editor is ok, but doesn't look as easy to collaborate. It's also a bit more focused on writing a book, rather than documentation, so it really wants everything to be linear.

**Comment by FireFart** [comment]
@todb-r7 @jlee-r7 we could also create a new doc branch and use something like jekyll or hugo to create content and push it on a server / use github pages.

**Comment by todb-r7** [comment]
> @todb-r7 shouldn't we recommend the official "secure installation" for RVM? https://rvm.io/rvm/security

Uh YES. Lemme test it real quick.

> Also the rvm keyserver part never worked for me I always do the alternative command:
> `curl -sSL https://rvm.io/mpapis.asc | gpg --import -` which is also more proxy friendly if you have one in place.

Thanks, will test and replace.

> If we do an gem install bundler before getting metasploit, bundler will be installed globally instead of the gemset.

Man, @FireFart you are full of good ideas. Thanks for the proofing!

**Comment by jlee-r7** [comment]
@FireFart I really want non-contributor users to be able to help with docs, though, which doesn't work if they have to have a github account and understand how to use git. An actual wiki makes that a bit easier, but the wikis i've played with all suck in various ways. I'm open to suggestions for streamlining documentation contributions.

**Comment by todb-r7** [comment]
@FireFart, updated https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment-Ubuntu-14.04 with your suggestions. I mentioned the "secure" binary installer for RVM, but ultimately, I suspect it's going to be more problems than what it's worth; it is not currently defaulting to 2.1.8, but only has 2.1.7 as the latest. So, fine suggestion, although I don't know what you get out of it in terms of "security;" it seems faster, though, and I can rvm install 2.1.8 after it's done.

So, link this from the MSF-DEV main site? And keep Kali as the default? I don't mind this too much, given our tight relationship with Kali.

**Comment by FireFart** [comment]
@todb-r7 cool! I never noticed the missing version because I always install RVM and after it my required ruby versions. As I said it's no real gain in security, it's only bad bahaviour passing shellscripts to your shell, but in this case it's just an unknown binary. But if we document both ways, the user can choose on his own.
