### ISSUE TITLE
Linux Kernel local code exec vuln requested (CVE-2016-0728)

### ISSUE THREAD

**Issue by madmike33** [rapid7/metasploit-framework#6486]
http://perception-point.io/2016/01/14/analysis-and-exploitation-of-a-linux-kernel-vulnerability-cve-2016-0728/

**Comment by todb-r7** [comment]
Kernel vulns are notoriously difficult to exploit in any reliable way, especially when you pick your target incorrectly, and we don't usually pursue them in Metasploit. That said, there is purportedly full PoC here:

https://gist.github.com/PerceptionPointTeam/18b1e86d1c0f8531ff8f

...which includes a rousing discussion in the comments.

**Comment by todb-r7** [comment]
btw, next time, @madmike33 , you should consider more verbosity in your request than a straight link. Nobody ain't got time to read.

This shortlink might help: http://r-7.co/MSF-BUGv2

**Comment by todb-r7** [comment]
fuuu updated shortlink

**Comment by wvu-r7** [comment]
And ```WfsDelay``` would need to be bumped up considerably. Best to use the PoC directly, IMHO.

**Comment by void-in** [comment]
FYI I have tried the PoC on a bunch of kernels all within the vulnerable range and none were exploited. In the comments on the gist almost everyone is saying the exploit failed so I am not sure how much it is worth the effort because as @todb-r7 said, the kernel vulns are really difficult to exploit in a reliable way.
