### ISSUE TITLE
duplicate content-length in hp_nnm_nnmrptconfig_nameparams.rb

### ISSUE THREAD

**Issue by Kamlapati** [rapid7/metasploit-framework#6553]
line 124 of the exploit "/modules/exploits/windows/http/**hp_nnm_nnmrptconfig_nameparams**.rb" has content-length defined and send_request_raw() method is adding one more content-length automatically at the end.

 I believe the function send_request_raw() will automatically add the content-length  for the post request so we don't need line 124.   

same problem at line 85 of the exploit "modules/exploits/windows/http/**hp_nnm_nnmrptconfig_schdparams.rb**"
 
Could you please remove this line in the future update because we are testing for the specific conditions.

**Comment by wchen-r7** [comment]
Hmm, this wasn't the case when the exploit was written back then. But at one point we changed the API, and we started enforcing content-length all the time. I'm sure there are more modules affected than just these two. I can make an urgent patch for those two modules since you're in the middle of something, but we might have to go back and fix it from Rex later.

**Comment by Kamlapati** [comment]
Thanks wchen-r7

**Comment by Kamlapati** [comment]
Hi,

I got the same issue in the following file:
https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/unix/webapp/phpmyadmin_config.rb (line:109).

Could u pls check this.

**Comment by wchen-r7** [comment]
OK I'll try to work on a patch in the library.
