### ISSUE TITLE
Add a Steam exploit based on insecure chromium code

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#6570]
Add a Steam exploit based on insecure chromium code:
http://www.ghacks.net/2016/02/08/steam-uses-insecure-out-of-date-chromium-browser/

**Comment by JohnMartinelli** [comment]
This hasn't been patched yet?

**Comment by ekaris** [comment]
Nope, I have reported the problems to then on official github page but they didnt't fix it yet

**Comment by all3g** [comment]
Actually, it effects my chrome browser.
**Chrome Version**: ```Version 48.0.2564.109 (64-bit)```

**Comment by ekaris** [comment]
Reopen due to steam lack of care about securing their browser

**Comment by bcoles** [comment]
This issue is now 6 years old. Whichever Chrome exploit was intended to be used has now long since been patched.

Since then, several exploits for Google Chrome have been added to Metasploit, including exploits for Chrome 87 and 89 as recently as 2020 and 2021 respectively.

```
msf6 > search type:exploit name:chrome -s date

Matching Modules
================

   #  Name                                                                    Disclosure Date  Rank    Check  Description
   -  ----                                                                    ---------------  ----    -----  -----------
   0  exploit/windows/browser/cisco_webex_ext                                 2017-01-21       great   No     Cisco WebEx Chrome Extension RCE (CVE-2017-3823)
   1  exploit/multi/browser/chrome_object_create                              2018-09-25       manual  No     Google Chrome 67, 68 and 69 Object.create exploit
   2  exploit/multi/browser/chrome_array_map                                  2019-03-07       manual  No     Google Chrome 72 and 73 Array.map exploit
   3  exploit/windows/browser/chrome_filereader_uaf                           2019-03-21       manual  No     Chrome 72.0.3626.119 FileReader UaF exploit for Windows 7 x86
   4  exploit/multi/browser/chrome_jscreate_sideeffect                        2020-02-19       manual  No     Google Chrome 80 JSCreate side-effect type confusion exploit
   5  exploit/multi/browser/chrome_simplifiedlowering_overflow                2020-11-19       manual  No     Google Chrome versions before 87.0.4280.88 integer overflow during SimplfiedLowering phase
   6  exploit/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation  2021-04-13       manual  No     Google Chrome versions before 89.0.4389.128 V8 XOR Typer Out-Of-Bounds Access RCE
```

Most if not all of these exploits require Chrome to be running with the sandbox disabled.

Apparently Steam continued to ship with the `--no-sandbox` flag for at least a year after this issue. It is unlikely that this is still the case; however, various sources suggest disabling the sandbox when troubleshooting issues with Steam:

* https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1649918058727436495/
* https://www.reddit.com/r/Steam/comments/9b36wd/steam_client_update_for_82818/
* https://websetnet.net/steam-browser-not-working-heres-how-to-fix-it/

It is possible that users will continue to launch Steam with this flag.

A quick look at the latest version of Steam shows `libcef` version 84 is in use.

![libcef](https://user-images.githubusercontent.com/434827/151659690-cae83df8-9b5f-461b-89ea-6a9ee8869c82.png)

Presuming a one-to-one mapping of Chrome Browser and CEF versions (not sure if this is the case) then this version of CEF may be vulnerable to the exploits for Chrome 87 and 89. However, neither of these exploits bypass the Chrome sandbox.

Closing this issue.
