### ISSUE TITLE
Multi/Handler dies after a while

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#6653]
Not sure how to repeat this one, but it's happened for both reverse_https and reverse_tcp. 

Symptoms are that the port is still open and accepts connections (SYN/ACK) but then stalls, no other information is sent from the handler

cc: @OJ @bcook-r7 @jlee-r7

**Comment by bcook-r7** [comment]
Hi @mubix - does the version you are running include this diff? https://github.com/rapid7/metasploit-framework/commit/a587975

The effect before that bug was fixed was if you ran an nmap scan of the reverse_tcp handler, it would catch an exception and break in the the accept thread, leaving the worker thread all alone:

When things are working, you should see 2 threads for a multi/handler:
```
   7   sleep   False     ReverseTcpHandlerListener-4444   2016-03-08 04:27:03 -0600
   8   sleep   False     ReverseTcpHandlerWorker-4444     2016-03-08 04:27:03 -0600
```

When you get into this state, you will likely only see one thread. Could you share your framework.log when in this state and the output of the threads command?

**Comment by bcook-r7** [comment]
Hey @mubix , when you see this again, could you please paste the results of the threads command?

**Comment by bcook-r7** [comment]
I'm going to close this since https://github.com/rapid7/rex-socket/pull/1 landed. Originally, anyone connecting on an SSL rex-socket could cause a DoS of a service simply by not continuing the handshake. Now it kicks stale connections after 3.5 seconds.
