### ISSUE TITLE
Interact with Active session over SSH [PuTTy]

### ISSUE THREAD

**Issue by honeyfairy** [rapid7/metasploit-framework#6664]
The payload handler is running in a terminal on my VPS. Once the Meterpreter session is opened I wish to interact with the session via SSH using Putty from my Windows desktop.

How do I interact with active sessions over SSH which are already opened in the Terminal?

Reference Screenshot [Top window is the Putty SSH connection to the same server that the VNC viewer is connected to showing the Terminal]

![met](https://cloud.githubusercontent.com/assets/17691989/13703970/6cbdf48a-e7aa-11e5-9991-0eae3936a870.PNG)

**Comment by vysec** [comment]
If you run it in screen, then on your ssh session you can attach to the screen and see the same msfconsole instance being run?

**Comment by wchen-r7** [comment]
@honeyfairy  Hmm I don't think you can at that point. All sessions objects are stored in a framework instance, which is in memory. When you SSH in and start msfconsole, you are getting another framework instance, so that's why you cannot see the sessions. I think you are basically asking a [hook](https://en.wikipedia.org/wiki/Hooking) or something like that.

The only thing that is shared between instances is the database. But this isn't what you're looking for.

However, here's a trick you can do to be able to interact w/ the Meterpreter session. If you are on the latest Metasploit Framework, first you can go ahead and type ```exit``` to exit the Meterpreter session. The ```exit``` command actually won't terminate the TCP session like it used to, only the ```sessions -K``` command will.

And then you can SSH in to your box, start msfconsole, set up the same handler, and then the payload should automatically connect back to you again. At that point, you should be interacting w/ the session in your SSH shell.

Again, this is a new feature in Metasploit. Make sure you are up to date. This feature is also described in our wiki here:
https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Reliable-Network-Communication#important-note-about-resilient-transports

BTW, since we use Github for bug tracking, and your issue sounds more like a support question. Next time please ask on the [Rapid7 Community website](https://community.rapid7.com/community/metasploit/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D) :-)

**Comment by wvu-r7** [comment]
@honeyfairy: Yes, use ```screen```, ```tmux```, or, in the worst case, something like ```reptyr```. Cheers.

**Comment by honeyfairy** [comment]
Thank you all for the replies, that's really a cool idea, to use screen. 
Wow, I didn't know [exit] doesn't kill the session, that is really informative.  
And please accept my apologies, I'm so sorry for the support related issue here...

**Comment by vysec** [comment]
I didn't know about [exit] either :) Thanks guys.
