### ISSUE TITLE
Feature request: a module to compress a folder on a remote system

### ISSUE THREAD

**Issue by Viss** [rapid7/metasploit-framework#7155]
Let's say you need to download a folder, 200+ megs of various office documents, there are several hundred of them. It's a lot faster to download one zip than it is 700 files.

Possibly add a flag to meterpreters 'download' function to compress files into c:\temp or elsewhere first, before downloading? Or a postexploit module to compress a folder? There 

using download -r works, but it takes a substantially longer time with the overhead of having to deal with a huge directory tree.

**Comment by wchen-r7** [comment]
I discussed with @bcook-r7 about this problem a little bit. It turns out meterpreter does compress the data while it is sent (at least with the Windows one and Linux), but the smaller block size for read might not be good enough for downloading large files: https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/channel.rb#L180

It is possible to write a post module to compress a folder, probably even more versatile than a Meterpreter command, but on Windows this kind of sucks. On a higher level, this is all the possible options I have found for Windows:

* **Powershell**. Only works for newer versions of PS, or I think starting Windows 8)
* **makecab**. Not really a zip, and it doesn't look like you can compress a directory with it?)
* **JAR**. Assuming there is a jar command, it can be used to zip, but it does this with absolute paths)
* **JSZIP**. Upload this library and use IE (in background) to compress the directory, that is the idea.
* **VBScript**. This seems to be the most ideal one I have found, because it should work for older versions of Windows. I'm currently trying this route.

On unix systems, I guess this is pretty straight forward, there is the ```zip``` command.

**Comment by void-in** [comment]
@wchen-r7 Why not Rex::Zip::Archive?

**Comment by wvu-r7** [comment]
@void-in: How does that work on the target?

**Comment by void-in** [comment]
@wvu-r7 https://github.com/void-in/metasploit-framework/blob/7009682100c698122d7444d2173422bd28be4906/lib/rex/zip/samples/recursive.rb

**Comment by wvu-r7** [comment]
@void-in: No, I'm asking how ```Rex::Zip::Archive``` works on a remote system.

**Comment by wchen-r7** [comment]
@void-in I don't think I can use Rex::Zip::Archive because the compression has to be done on the target, not on the attacker's side.

**Comment by wchen-r7** [comment]
Powershell doesn't look so great so I removed the option. Too high on requirements and the API only allows zipping a directory and not a file.
