### ISSUE TITLE
meterpreter android commands missing

### ISSUE THREAD

**Issue by kofs** [rapid7/metasploit-framework#7226]
today after i update and upgrade kali android commands in meterpreter session are missing .
what i have to do ?
is this a bug?
how can i fix it?

**Comment by busterb** [comment]
did you try 'load android' ?

**Comment by kofs** [comment]
no 
where i have to run this?

**Comment by busterb** [comment]
from the meterpreter> prompt

**Comment by busterb** [comment]
will check to see if there is something that's preventing automatic loading of the extension on android sessions

**Comment by kofs** [comment]
thank you so much 
its works
how can i set it on automatic loading?

**Comment by bcook-r7** [comment]
auto-loading is now resolved with @timwr 's fix above. Thanks a lot!

**Comment by ayoubbtt** [comment]
it does not work
i get this error :
error: running command load: loaderror cannot load such file --rex/post/meterpreter/extensions/android/android

**Comment by busterb** [comment]
Since this issue was raised, we got rid of the extension altogether. In other words, there's no need to run 'load android' at all (I'm assuming that's what you typed, since that part is edited out above).

**Comment by googlinaweb** [comment]
Hi Im stuck on this problem please help me to set autoload android

**Comment by h00die** [comment]
This issue is closed.  Please do the following:
Ensure you have a metasploit version that contains #7231 .  Re-exploit the device (including generating a new .app or mterpreter or whatever).
If you still have the issue give us as much details as possible.  metasploit version, how you generated the payload, details of the target, and the commands and output you typed.
DO NOT RESPOND HERE.  if you still have an issue either make a new ticket, or go to the IRC chat room for support. this issue was resolved and confirmed resolved by the reporter.

**Comment by manikantaraavi** [comment]
please help me with metasploit andriod commands missing 
version v5.0.2-dev please help
thank in advance

**Comment by manikantaraavi** [comment]
please help me with metasploit andriod commands missing 
version v5.0.2-dev please help
thank in advance
