### ISSUE TITLE
sugarcrm_rest_unserialize_exec does not work for a larger payload

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#7318]
User may experience the following outcome when using sugarcrm_rest_unserialize_exec with a larger payload such as php/meterpreter_reverse_tcp:

```
msf exploit(sugarcrm_rest_unserialize_exec) > run

[*] Started reverse TCP handler on 192.168.3.167:4444 
[*] 192.168.3.104:80 - Exploiting the unserialize() to upload PHP code
[*] 192.168.3.104:80 - Executing the payload /custom/FUsGkUGabk.php
[-] 192.168.3.104:80 - Payload execution failed: 400
[!] This exploit may require manual cleanup of 'FUsGkUGabk.php' on the target
[*] Exploit completed, but no session was created.
```

A smaller payload such as php/meterpreter/reverse_tcp does not have this issue.

Problem was first mentioned in: https://github.com/rapid7/metasploit-framework/pull/7284#discussion-diff-77943645a

Related to pull request #7284

**Comment by OJ** [comment]
@wchen-r7 so what do you think the preferred method will be? Clearly the executed payload needs to be sent to the target via the `POST` body. My current vote would be to see it baked into the file that is written to disk, rather than having an execution cradle written. The main reason is OPSEC related: instead of having a general runner that could be abused by another person to execute _any_ payload they want, the uploaded file serves just one purpose, and that's to invoke the payload that you had intended in the first place.

So I say include the payload in the first `POST`, then invoke it with a second request (`GET` or `POST`) that requires a key of some kind (this could perhaps be in a custom head or request variable).
