### ISSUE TITLE
Auxiliary failed: NoMethodError

### ISSUE THREAD

**Issue by FusionPyro** [rapid7/metasploit-framework#7406]
Hello, when ever i try to SYN flood i always get this error:
Auxiliary failed: NoMethodError undefined method `<=' for nil:NilClass
Did you mean?  <=>
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/dos/tcp/synflood.rb:57:in `run'
How can i fix this?

**Comment by void-in** [comment]
This is a dup of https://github.com/rapid7/metasploit-framework/issues/7264. Please follow the advise there. It totally go off my radar. If no one generated a PR, I will do it tomorrow morning (it is quite late here and I am away from my dev machine). Will keep it open so that I don't forget about it. Thanks

**Comment by wvu-r7** [comment]
I'll fix it.

**Comment by wvu-r7** [comment]
Leo is going to fix it. :P
