### ISSUE TITLE
FATAL:  password authentication failed for user "msfdev"  | HELP!!!

### ISSUE THREAD

**Issue by AMAN1312** [rapid7/metasploit-framework#7425]
# HELP!!!

I installed the Metasploit-framework (dev) from-
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

After entering 'msfconsole' in the terminal, it says-
FATAL:  password authentication failed for user "msfdev"

## Expected behavior

according to the guide it will not show any error and connect with the database "msfdev"

## Current behavior

Terminal window shows-

[-] Failed to connect to the database: FATAL:  password authentication failed for user "msfdev"
FATAL:  password authentication failed for user "msfdev"

Metasploit Info-
Framework: 4.12.33-dev-adb6f31
Console  : 4.12.33-dev-adb6f31

### OS

I am Using Ubuntu 15.10
![screenshot from 2016-10-10 12-55-14](https://cloud.githubusercontent.com/assets/16210791/19229132/d64eb2f0-8ee8-11e6-9b9d-2de2c24853d2.png)

**Comment by bcook-r7** [comment]
Looks like exactly what it's telling you - the password in your database.yml file doesn't match the password for the msfdev user.

Carefully examine your setup again, and perhaps look at the 'Vagrantfile' for hints on the commands you would run to set up a development environment and configure a matching password for your database user. I'd also recommend posting support questions like this on https://community.rapid7.com/community/metasploit rather than the github project.

**Comment by void-in** [comment]
In addition to the @bcook-r7 answer, I would recommend that if you just want to use msf and not into the dev side, then use a binary/omnibus installer or use the built-in Metasploit package that comes with the Kali Linux. Those are easy to setup compared to the development environment setup.

**Comment by myhashs** [comment]
guys you could spent alot of times with that problem but u need Create same user same database and same password in postres apt first !@
