### ISSUE TITLE
Request: Add some unit tests for Msf::Payload::Apk

### ISSUE THREAD

**Issue by timwr** [rapid7/metasploit-framework#7571]
It was mentioned in https://github.com/rapid7/metasploit-framework/pull/7567 that we don't currently have any tests for Android, specifically lib/msf/core/payload/apk.rb
I'm raising this issue for visibility.
Perhaps we could have some tests that assume that a device is connected with adb, that are skipped if the device is not present?
In theory we could download the android sdk, fire up an emulator, and run the tests, then kill the emulator, but last time I tried this it was extremely slow and flakey.

**Comment by itsbriany** [comment]
@timwr Thanks for accepting #7567!

I was thinking something more amongst the lines of unit testing (i.e. testing individual functions for generating Android APKs) such that we can expect a properly formatted payload APK.

For example, while debugging https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/apk.rb#L69, I was loading up `msfvenom` every time to test my changes. By testing the logic for each public method in `Msf::Payload::Apk`, I think we can mitigate bugs and make future debugging and maintenance much easier (since we can simply test the individual function immediately instead of loading up the whole `msfvenom` application).

I think this would be much easier than running a more integration-style test since generating an APK and loading up an Android emulator takes a while.

If you are happy with having unit tests for https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/apk.rb, I would like to take on this task :)

**Comment by timwr** [comment]
@itsbriany that would be awesome. Unit tests would be ideal and run much more quickly and without an emulator. Many thanks for your help with this!

**Comment by Tomy0498** [comment]
https://github.com/rapid7/metasploit-framework/issues/7571
exelent!!
