### ISSUE TITLE
Metasploıt bad character error

### ISSUE THREAD

**Issue by bayp1p0** [rapid7/metasploit-framework#7619]
http://i.hizliresim.com/VPlXoq.jpg

How can ı solve this error help pls. S

**Comment by pbarry-r7** [comment]
Hi, this has been raised (and the fix committed recently) in #7613.  If you are running off a clone of master, you can try it out.  Otherwise, it will get picked up in the build this coming Friday.

**Comment by bayp1p0** [comment]
I cant understand bro can you tell us on here ?

**Comment by void-in** [comment]
@bayp1p0 What @pbarry-r7 said is that the fix for the problem you mentioned is already committed to the github branch. However, depending on how you have installed Metasploit, the fix might or might not be available for you to apply. If you have cloned the Metasploit framework from Github, running git pull is going to get you the fix. If you are running it off of Kali, then you will have to wait till Friday unless the next version of Metasploit is tagged and then available for the Kali Linux users.

**Comment by busterb** [comment]
I went ahead and put out metasploit-framework 4.13.2 with this fix in it, since it seems like more users will be impacted by it.

Usually Kali picks up releases on Friday when we release automatically, but I'll drop them a line to see if they want to grab this sooner than that. Thanks all.
