### ISSUE TITLE
Webcam not working failing with "Operation failed: 2147943850"

### ISSUE THREAD

**Issue by invious** [rapid7/metasploit-framework#7621]
Have a session on victim, webcam was working, then stopped Using non-persistent Kali Live USB, rebooted, same issue.

`metasploit-framework/scripts/meterpreter/webcam.rb`

```ruby
meterpreter > run webcam -p /var/www/
[*] Starting webcam 1: USB2.0 HD UVC WebCam
[-] Error: Rex::Post::Meterpreter::RequestError webcam_start: Operation failed: 2147943850
["/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/webcam/webcam.rb:41:in `webcam_start'",
"/usr/share/metasploit-framework/lib/rex/script/base.rb:119:in `run'",
"/usr/share/metasploit-framework/lib/rex/script/base.rb:43:in `eval'",
"/usr/share/metasploit-framework/lib/rex/script/base.rb:43:in `run'",
"/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:227:in `execute_file'",
"/usr/share/metasploit-framework/lib/msf/base/sessions/scriptable.rb:123:in `execute_script'",
"/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1124:in `cmd_run'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:428:in `run_command'",
"/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:390:in `block in run_single'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `each'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `run_single'",
"/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'",
"/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:193:in `run'",
"/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'",
"/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:473:in `_interact'",
"/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'",
"/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1968:in `cmd_sessions'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:428:in `run_command'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:390:in `block in run_single'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `each'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `run_single'",
"/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/exploit.rb:140:in `cmd_exploit'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:428:in `run_command'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:390:in `block in run_single'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `each'",
"/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `run_single'",
"/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'",
"/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'",
"/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'",
"/usr/bin/msfconsole:48:in `<main>'"]
```
`webcam_start: Operation failed:2147943850`

**Comment by OJ** [comment]
This sounds environment specific to me. The error code shown maps to `ERROR_NO_SYSTEM_RESOURCES`, and the reason the stack trace appears would be due to the script incorrectly handling error cases.

Why that error happens, I don't know. It could happen for many reasons. We do use DirectShow behind the scenes, and it's not uncommon for this error to happen if the webcam is already in use.

Rebooting your local machine will not fix issues on a remote machine.

Also, scripts are basically obsolete, and I don't think they are actively maintained. If you want to take a snap from the webcam, just use the `webcam_snap` function in Meterpreter.

**Comment by busterb** [comment]
Doesn't seem like much we can do here.

**Comment by thecarpetjasp** [comment]
The reason this has happened is because the session was abruptly ended whilst you were streaming the webcam. This happens all the time and there isn't any way to avoid this - sometimes we just lose our connections unexpectedly. 

So the reason you are running into this error is because their camera is still streaming. The unfortunate part is, you no longer have the session that is controlling that stream, therefore you're unable to access the camera until their camera stops being used. There are some obvious ways to do this of course, like restarting their machine. But this is unnecessary. 

Fortunately, I figured out a way which I've tested myself that works. You need to kill the process you was running on when you were streaming before it stopped working. If you didn't migrate, then you need to kill the meterpreter malware `pkill -N <your application name.exe>`. Make sure to migrate to a different process beforehand obviously, then restart the meterpreter malware again whilst you're still connected to their machine so you can get back on in case of a timeout (you should have a backdoor though...). 

If you were running on 'explorer.exe' when you had your timeout and the camera stopped working, then you would need to restart 'explorer.exe' by killing it and executing it again. You get the picture. Hope this helps.
