### ISSUE TITLE
module "scanner/http/concrete5_member_list" should use lesser aggression in regular expression

### ISSUE THREAD

**Issue by jinq102030** [rapid7/metasploit-framework#7628]
## Steps to reproduce

How'd you do it?

1. `use auxiliary/scanner/http/concrete5_member_list`
2. `set RHOSTS 127.0.0.1`
3. `run`
and notice the username in the output could be garbled.

```
msf auxiliary(concrete5_member_list) > run

[+] 127.0.0.1:80          Extracted 1 entries

Concrete5 members
=================

   UserID  Username                                                                                      Profile
   ------  --------                                                                                      -------
   123     john</a></div><div class="ccm-profile-member-username">/view/345/<a href="profiles/345">mary  profiles/123">john</a></div><div class="ccm-profile-member-username">/view/345/<a href="profiles/345


[*] Scanned 1 of 1 hosts (100% complete)
```

### Metasploit version

```
msf auxiliary(concrete5_member_list) > version
Framework: 4.13.3-dev-19bcef0
Console  : 4.13.3-dev-19bcef0

```

### OS

Ubuntu 14.04

**Comment by wchen-r7** [comment]
@jinq102030 Could you please give me a test box?

**Comment by Chiggins** [comment]
I actually use concrete5 at work so I figured I'd look at this. 

It looks like @jinq102030 might've already fixed this with commit https://github.com/rapid7/metasploit-framework/commit/1beeb99d44f57064767139091ff601e9f3f38b6e. Though with the current version of concrete5, I'm not sure this is actually valid anymore as it didn't work for me. The last module-specific work done on this was back in November 2012 here https://github.com/rapid7/metasploit-framework/commit/f88ec5cbc80919df90885609f30677c563345575.

If I go to `/index.php/members` on my fresh install, I get a 404 page. Maybe it'd be a half decent idea to add some sort of check to see if this module would work with the target. In the current version at least there's a HTML line that will provide the concrete5 version, `<meta name="generator" content="concrete5 - 5.7.5.9"/>`, so that could be very helpful.

Anyway, that's my two cents on it. Maybe that'll provide some more insight.

**Comment by jinq102030** [comment]
@Chiggins Totally agree with you that it needs to be updated whenever possible.  Since you have access to the software, would be nice to identify whether the problem is still there (but with a different URL due to configuration) or the vulernability is fixed.

 I don't have the concrete5 software, instead, I just had an emulator.

**Comment by Chiggins** [comment]
@jinq102030 It's actually a free software that you can download and run yourself, just set up your own test VM with Apache, PHP, and MySQL running. https://www.concrete5.org/download

**Comment by jinq102030** [comment]
Thanks @Chiggins for the link!

**Comment by busterb** [comment]
Something good to add to module documentation.

**Comment by Chiggins** [comment]
@jinq102030 What's the version of concrete5 that you're testing against?

**Comment by jinq102030** [comment]
@Chiggins I was testing with an emulator that emulates the old version (the version based on which the module was created originally).

**Comment by Chiggins** [comment]
@jinq102030 Well I was hoping you could provide the actual version number so I could install it on my own dev server and kind of look into this a little bit more.

**Comment by wchen-r7** [comment]
@Chiggins I tried to look into this bug too, and yeah it doesn't work against the latest version of Concrete5. The module needs an upgrade.

I also don't see when the original module was created, lost some of that history there. But the first commit is from 2012, and the first release of Concrete was this: https://www.concrete5.org/download_file/-/view/33453/8497/

I should be able to patch the module soon to resolve this ticket, but again, this module needs an upgrade.
