### ISSUE TITLE
my devices not supported? :О

### ISSUE THREAD

**Issue by xxxcrow** [rapid7/metasploit-framework#7696]
i've check this vulnerable on my device, critical:9 :)
but i can't exploit this :С 
(i've tested on 2 devices)(version of android: 4.1.2)
```
msf exploit(stagefright_mp4_tx3g_64bit) > exploit -j
[*] Exploit running as background job.

[*] Started reverse TCP handler on 10.0.0.10:4444 
[*] Using URL: http://10.0.0.10:8080/11
[*] Server started.
[-] 10.0.0.11        stagefright_mp4_tx3g_64bit - 10.0.0.11:56579 - Requested /11 - Unknown user-agent: "Mozilla/5.0 (Linux; Android 4.1.2; JY-G2 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36"
```

i use msf on kali

**Comment by h00die** [comment]
what devices?

**Comment by h00die** [comment]
This is for reporting bugs, if this is a support issue Please ask on IRC (#metasploit on freenode) or the Rapid7 Community site (https://community.rapid7.com/). GitHub is for bugs and feature requests. Thanks.

**Comment by xxxcrow** [comment]
device: (china) Jiayu JY-G2 (4.1.2 custom:MAUI)

**Comment by h00die** [comment]
This is expected behavior https://github.com/rapid7/metasploit-framework/blob/d8f59a9d622ff37db9392bbd104d7456f2ff8c7e/modules/exploits/android/browser/stagefright_mp4_tx3g_64bit.rb#L991
If this is a support request to add additional devices, see my previous comment. https://github.com/rapid7/metasploit-framework/issues/7696#issuecomment-266208996
