### ISSUE TITLE
can't connect to msfdb

### ISSUE THREAD

**Issue by chris2lamb** [rapid7/metasploit-framework#7957]
I am running Linux kali 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux

I installed the Metasploit framework as indicated in the metasploit doc pdf (page 6). 
After having completed the installation (metasploit v4.13.23), I can't connect to the db and can't have access to msfdb commands:

msf > db_status
[*] postgresql selected, no connection
msf > msfdb
[*] exec: msfdb

Please run msfdb as a non-root user
msf > 

note that postgresql service is up

TIA

**Comment by h00die** [comment]
This sounds more like a support issue than a bug.  For support, please join #metasploit on IRC

**Comment by busterb** [comment]
This is actually a common problem for Kali Linux users specifically when running as root using the omnibus package, rather than Kali's own Linux package. Kali manages the database differently, preferring to use the system rather than user database.

I put a PR on the omnibus package to fallback to Kali's method if root user is detected: https://github.com/rapid7/metasploit-omnibus/pull/46

**Comment by busterb** [comment]
Also, note that 'msfdb' is a standalone program, not something you need to run from metasploit itself. Generally, unless you can't wait a week or so for Kali to grab the latest metasploit tag, you might as well just use the builtin package. But, with the above PR, the experience should be effectively the same as using Kali's native package, if you're running as root. I left the original behavior for non-root users however.
