### ISSUE TITLE
Request: Running in Memory

### ISSUE THREAD

**Issue by zero77** [rapid7/metasploit-framework#8017]
I appreciate there’s lots of work that needs to be dune and that has been requested. 
But in the future when time is available can you look at adding the option for, support of complete memory integration of exploits and modules.

 For example, can you get obfuscated exploits and modules to load and run completely in memory and not right anything to disk.

As this would greatly help to evade detection, by creating less of a footprint and have less for the AV to scan additionally, lots of AV don’t scan memory or registry.

Thanks

**Comment by void-in** [comment]
So exploits are always run against a running process in memory and payload is injected and run from the memory as well. Obfuscation is a different thing. Most of the time obfuscating the payload will increase its size which won't fit into the space available for the shellcode.

If you encountered a specific issue which you want to address, please update. Otherwise I am not sure exactly what is requested here.

**Comment by zero77** [comment]
I knew that exploits where run against a running process but, I didn’t know that happen completely in memory without touching the disk. Also, is the exploit code that is run in memory obfuscated or plain text.
Is this the same process for post exploit modules i.e. loading and running completely from memory without touching the disk.

**Comment by void-in** [comment]
Exploit code can't be obfuscated due to the fact that the running process which you are targeting won't be able to de-obfuscate that code. De-obfuscation require the ability to run arbitrary code which you don't have when you send the exploit code to the target process, You are merely interacting with the process (albeit in an interesting way). This is true for the classic memory corruption exploits. For exploits such as Office macros or tricking the user into running a file, you can obfuscate the code as much as you want and still have a de-obfuscating stub to run the code successfully.

Depending upon the purpose of the post module, it might or might not touch the disk. For example, a post module which migrate the process from one process to another won't touch the disk. A post module for extracting credentials from a file will definitely touch the disk.

**Comment by h00die** [comment]
Many of the local privilege escalations also write files to disk. All the Linux ones I've written definitely do

**Comment by busterb** [comment]
The plan I have in mind for implementing this is two-fold, at least on the Linux/Unix side, since there are already ways to do this with Windows, e.g. reflective DLL injection. What I want to do is add two possibilities to the new posix meterpreter / mettle:

 1. The ability to spawn a new child process entirely in-memory and run the code there. This would basically follow the same loader mechanism we use to load mettle on Linux systems today.
 2. Embedding a scripting language that can call syscalls, such that we can either do something like railgun, or load generic code into mettle's main process for platforms and environments where dlopen / fork are not available.

I think a combination of these two should cover the problems we've encountered so far on Linux/Unix platforms.

**Comment by h00die** [comment]
Most LPE that write to disk are doing so with 1mb, what about some mettle way that would allocate a ram disk to load the files into.
Not only would this prevent writing to the real disk, but would alleviate having to check if a file exists ahead of time.
That being said I'm not volunteering and have no clue how complicated that would be.

**Comment by h00die** [comment]
1mb or less...

**Comment by wchen-r7** [comment]
Some vuln types will simply write to disk. For example: if you load a browser exploit, the malicious page will be on disk. If you exploit an arbitrary write/upload, it will write to disk, etc.

I think the main objective is more focus on AV evasion, and maybe anti-forensics. In-memory is one technique but does not always apply.

**Comment by zero77** [comment]
@wchen-r7  `Yes, the objectives I had in mind were, AV evasion, and anti-forensics although arguably they can sometimes be part and parcel, but specifically for exploits and modules as Veil-Evasion works more with payloads. 
I think avoiding disk and righting to volatile memory instead is a good way to go although, that said I am interested in the other methods you had in mind.`


@busterb `Yes, DLL injection is a good method to use for windows and would your Linux/Unix suggestion also feasible for mac OS as well.`

**Comment by busterb** [comment]
There's nothing really specific for us to do here. It'll always be an ongoing effort. So, I'm going to close this as an issue; we'll keep moving this direction.
