### ISSUE TITLE
CVE-2016-5195 - dirtycow + Android 6.01 -- Does metasploit have any cool tools?

### ISSUE THREAD

**Issue by droidvoider** [rapid7/metasploit-framework#8122]
The only way I know to use metasploit is when someone puts up a tutorial and I have no knowledge of a list or index of Android + metasploit exploits. Can someone help me with the right things to Google?

I'm trying to root Android 6.01 phones with locked bootloaders. Any tools that would help me gather information or gain root + context would likely give me ideas. I'm currently working with farm-root from github.com which does get root + system_server and root + install_recovery. But what all to replace becomes the question.

**Comment by wwebb-r7** [comment]
There was a lot of buzz regarding dirtycow when it was new; however, nothing more than some PoC's that barely worked were produced.  I haven't kept up with it enough to know if anyone, regardless of association with Metasploit, has published a working exploit for it.  Someone else will chime in I'm sure.

Outside of the fabulously wealthy and other corner cases, an individual would have to be very much insane to put in the work required to find a quality Android vulnerability, write a robust exploit for it, and give it to us for free.  For the most part, we depend on the charity of those individuals, so it's no surprise that the exploit selection is sparse.  If you really need some exploits, there are places that can set you up.  It'll require a very serious looking NDA, proof of financial assets, and payment up front.

Other than that, there's ongoing work on the payload and post-exploitation side of things.  I'll let @bcook-r7 @timwr or someone more up to speed fill you in on that.

**Comment by timwr** [comment]
Hi @droidvoider 
We had https://github.com/rapid7/metasploit-framework/pull/7478 up for a while. Feel free to test it. If there is interest I'll see if I can improve it.
It's unclear what the best method on Android is. On 64bit devices with vdso we can replace gettimeofday in the vdso table with shellcode. What do you recommend for 32bit devices with selinux?

**Comment by jbreed** [comment]
@timwr I'd be interested in getting this refined. 

When the phone locks up it continues to maintain the root shell? Upon reboot I imagine you lose the shell, but have you tried chaining this to something for persistence?

In the coming weeks I will see what I can find. My Samsung still shows an old patch level (even though it is updated) so this exploit still has validity. I imagine for older Androids it may be valid for a while.

**Comment by timwr** [comment]
@jbreed if I remember correctly the shell still worked for a while after the phone locked up, but it eventually died (I think because certain core services were not starting), so persistence would definitely help here.
I suspect it's going to be increasingly hard to do depending on the version of Android. I think @freddierice and @jcadduono have some repositories that achieve this but I'm not sure how generic they are.

**Comment by freddierice** [comment]
> I think @freddierice and @jcadduono have some repositories that achieve this but I'm not sure how generic they are.

Not very. However @hyln9 packaged it up a fairly portable version in https://github.com/hyln9/VIKIROOT.

**Comment by timwr** [comment]
The vdso approach in VIKIROOT is perfect for 64bit phones, but not 32bit :(
@hyln9 can we borrow some of your code for the metasploit project? credit to you of course.
p.s In VIKIROOT I always get stuck on `Waiting for reverse connect shell`, but I'm sure it's fixable.

**Comment by freddierice** [comment]
I'm pretty sure we could make this work for 32 bit phones as well. Looking at the linux source, linux/arch/arm/vdso implements gettimeofday. I'm not sure how many manufacturers have enabled 'CONFIG_VDSO' while configuring the kernel, but it's worth looking into.

**Comment by hyln9** [comment]
@droidvoider 
Well, I believe without another kernel exploit, dirtycow-based exploits need patched sepolicy to gain root plus unrestricted context for Android 6, so do VIKIROOT, which usually requires a unlocked bootloader.

@freddierice 
As you can see, vdso for arm linux was added on 26 Mar 2015, maybe too late.

@timwr 
Sure. Btw, since my code is currently licensed under GPLv3, I'd like to change it to a permissive one if required.

**Comment by wvu-r7** [comment]
We are beyond the scope of OP's question. If Dirty COW development resumes, we'll create a new ticket. Thanks!

**Comment by timwr** [comment]
I made an attempt here:
It's a bit buggy because it replaces app_process, and can crash half way through (I can't work out whether that's better or worse than dirtycowing libc).
https://github.com/rapid7/metasploit-framework/compare/master...timwr:dirtycow_rebase
Replacing app_process gives you system_server uid 0, but the SELinux context doesn't allow execmem (so no staging), there isn't space in /system/bin for stageless mettle, and you can't execve(/system/bin/sh) because of SELinux.
In theory we could put stageless mettle in /system/lib/hw/bluetooth.so, but it's segfaulting for me currently:
https://github.com/rapid7/metasploit-framework/compare/master...timwr:linux_so_template?expand=1
In theory we could also hook a function in app_process (or within /system/lib/) for the same context, without crashing the UI, but the above problems remain.

**Comment by busterb** [comment]
Hmm, we could probably track down the segfault. Probably due to environment assumptions.
