### ISSUE TITLE
Rex::RuntimeError The core_loadlib request failed with result: 1

### ISSUE THREAD

**Issue by m4hmoud** [rapid7/metasploit-framework#8222]
## Steps to reproduce

1. Downloaded the [put_user exploit](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/android/local/put_user_vroot.rb)
2. Added the file to ~/.msf4/modules/exploits/android/local
3. Created a session on an Android 4.2.2 device
4. Set the options (LHOST, ...)
5. Run the exploit

## Expected behavior

I expected the exploit to run successfully as the device was vulnerable. 

## Current behavior

It shows this error:
```

[*] Loading exploit library /data/data/com.metasploit.stage/files/gvwxi
[-] Exploit failed: Rex::RuntimeError The core_loadlib request failed with result: 1.
[*] Exploit completed, but no session was created.
```

### Metasploit version

4.14.7-dev

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali

**Comment by timwr** [comment]
hi @m4hmoud 
Can you follow the instructions here: https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/android/local/put_user_vroot.md
You don't need to download the file and put it in ~/.msf4/ because it's already there, you can simply use it with:
`use exploit/android/local/put_user_vroot`
After than can you post the full log (including `sessions -v`) and `show options`? Does the device reboot?
If you want more verbose logging of the exploit you can also try attaching the device with usb, `cd metasploit-framework/external/source/exploits/CVE-2013-6282` and run `make test`?

**Comment by m4hmoud** [comment]
thanks for the reply @timwr 

At first I tried using it directly, but it wasn't in the list of exploits! Even after upgrading the metasploit (with `msfupgrade`), it still couldn't load the module and it the only `android/local` exploit in the list was `futex_requeue`.

So, my only option was adding it manually to the mentioned folder.

--------------------------------------------------------------------------------------------

OK, now strangely it works fine and doesn't give me the previous error (maybe it was because of giving a different port than the session port)

Now, the device reboots the moment the new sessions is created and meterpreter prompt is shown.

**Comment by timwr** [comment]
> At first I tried using it directly, but it wasn't in the list of exploits! Even after upgrading the metasploit (with msfupgrade), it still couldn't load the module and the only android/local exploit in the list was futex_requeue.

Do you have a broken install of metasploit? Can you try a fresh install?
```
$ msfconsole -q
msf > use exploit/android/local/put_user_vroot
msf exploit(put_user_vroot) >
```
