### ISSUE TITLE
is_known_pipename.rb can't be used on msfconsole

### ISSUE THREAD

**Issue by anwareset** [rapid7/metasploit-framework#8524]
msf > use exploit/linux/samba/is_known_pipename 
[-] The supplied module name is ambiguous: uninitialized constant Msf::Modules::Mod6578706c6f69742f6c696e75782f73616d62612f69735f6b6e6f776e5f706970656e616d65::MetasploitModule::ARCH_MIPS64LE.

**Comment by busterb** [comment]
Hi - are you actually running the latest version of metasploit, or did you slip this exploit file into your own, older copy? You need to actually be running the latest version of metasploit to use this module, just copying that one file won't work, as you observed, because it needs some library additions.

**Comment by wvu-r7** [comment]
Someone asked the same thing on IRC. It was most definitely that.

**Comment by busterb** [comment]
Roger

**Comment by anwareset** [comment]
Solved by using the first release version.
