### ISSUE TITLE
WebCam error

### ISSUE THREAD

**Issue by umerov1999** [rapid7/metasploit-framework#8646]
webcam_start: Operation failed: 731 on Windows 10 build 14393

**Comment by jvoisin** [comment]
Please give us more information about what you're trying to do, what setup are you using, what machines, OS, module, …

**Comment by DominikSchlecht** [comment]
Hey, I get the same error.

Using Windows 10 Pro x64 10.0.16299 on VMWare-Workstation 12.5.9. Payload is windows/meterpreter/reverse_https. Metasploit is a 5.0.16-dev (Kali).

I tried using a logitech C920 Webcam (wiedly spred) and the camera also works in windows (for example via the camera-app) but I also receive the 731-Error when tried to take a snap.

If I can assist somehow, please point me in the right direction :)

**Comment by DominikSchlecht** [comment]
Short Update:
I think that this issue is caused by VMWare + Meterpreter. Running the same meterpreter agains a physical W10 (up-to-date) results in success while running agains an W10-VM does result in the error. I also tried different webcams with the same result.

Yet the strange thing is, that these webcams are always useabel in the VM (for example via the camera-app) but not by meterpreter.

I am using VMWare-Workstation 12 in USB3-Mode (tested the case on both W10 and Arch as Host) - I will play with the settings a bit to figure out if this can be solved be reconfiguring the vm.
