### ISSUE TITLE
Meterpreter scripts don't take args in run command

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#8703]
Details pending.

**Comment by wvu-r7** [comment]
cc @Viss

**Comment by xiaohuanshu** [comment]
same here

**Comment by bcoles** [comment]
@Viss @wvu-r7 

Possibly the same issue - pepelegal on IRC mentioned an issue with `multi_console_command` which I've confirmed exists in master.

The [fix](https://community.rapid7.com/thread/10121) is trivial:

```diff
diff --git a/scripts/meterpreter/multi_console_command.rb b/scripts/meterpreter/multi_console_command.rb
index d456741..62434a0 100644
--- a/scripts/meterpreter/multi_console_command.rb
+++ b/scripts/meterpreter/multi_console_command.rb
@@ -34,6 +34,7 @@ def usage
 end
 
 @@exec_opts.parse(args) { |opt, idx, val|
+  opt = args[0]
   case opt
 
   when "-cl"
```

**Comment by sn0wfa11** [comment]
This issue is also mentioned in Issue #8773. PR #8622 was to remove multi-char arguments due to changes in the way the argument parser works for Meterpreter. It is the multi-char arguments that are causing the problem. That PR did not address Meterpreter scripts. I'll put in a PR shortly to single char all of the Meterpreter scripts. Not sure if R7 will land it since they have stopped supporting Meterpreter scripts. However, much of the functionality of multi_console_command can be replicated using `post/multi/manage/multi_post`.

**Comment by OJ** [comment]
Ah bummer. I knew this was going to bite us somewhere else too :(

**Comment by bcoles** [comment]
Was this closed by #8802 ?

**Comment by sn0wfa11** [comment]
Yes, it was.

**Comment by wvu-r7** [comment]
This might have been a different bug. I haven't posted details yet. Sorry for dropping the ball. I'll close this if it's resolved.

**Comment by wvu-r7** [comment]
Scripts are deprecated, anyway.
