### ISSUE TITLE
I Have  added Netripper to metasploit but not loaded 

### ISSUE THREAD

**Issue by activenew** [rapid7/metasploit-framework#8996]
Hi All,

This first post for me , i am also very new in this field, i am facing issue with NetRipper ,i used the below steps to add Netripper module to metasploit.

```
mkdir /usr/share/metasploit-framework/modules/post/windows/gather/netripper
cp netripper.rb /usr/share/metasploit-framework/modules/post/windows/gather/netripper.rb
g++ -Wall netripper.cpp -o netripper
cp netripper /usr/share/metasploit-framework/modules/post/windows/gather/netripper/netripper
cd ../Release
cp DLL.dll /usr/share/metasploit-framework/modules/post/windows/gather/netripper/DLL.dll
```

its appear with module but i can't select it.

Note:i did not found (Release folder) after download the module, so i made it manually and added (DLL.dll) file on it

please advise me.

thanks

**Comment by h00die** [comment]
I'm assuming you were following a guide, care to link it?

**Comment by activenew** [comment]
yes , i am followed this 
https://github.com/NytroRST/NetRipper

**Comment by h00die** [comment]
There is no Release folder in the git repo, so my assumption is the directions are wrong.
If you put the file in `modules/post/windows/gather/netripper/netripper.rb` then you would do `use post/windows/gather/netripper/netripper` (notice the double since you put it in its own folder).
I would suggest instead of opening an issue here, open an issue in NetRipper since your issues is actually with their instructions, not metasploit.

**Comment by activenew** [comment]
Thanks  for advice.
I will open in Netripper
