### ISSUE TITLE
The command record_mic -d errors out very often on Android reverse tcp connection

### ISSUE THREAD

**Issue by mahmoudissam** [rapid7/metasploit-framework#9113]
## Steps to reproduce
Run the command: "record_mic -d 20" on a reverse TCP connection, give you the error:
[-] Error running command record_mic: Rex::TimeoutError Operation timed out.
It works sometimes If you reduce the length, but there should be a way to avoid the timeout error.

## Expected behavior
To create the wav file. 

## Current behavior
Sometimes errors out:
[-] Error running command record_mic: Rex::TimeoutError Operation timed out.

## System stuff
Tested on : Android 6.0.1 - Linux 3.10.61-8299335 (armv8l) - Samsung J7 dual sim 3g.

### Metasploit version
metasploit v4.16.11-dev

### I installed Metasploit with:
Kali package via apt

### OS
Kali Linux 2017.2

**Comment by gnu-like** [comment]
@mahmoudissam as you said it works when reduce time,ethier it 's related internet speed 's victim I use 15 it usually works well when I receive error I decrease to 10

**Comment by HitmanBobina47** [comment]
I doubt the issue is related to internet speed, because record_mic -d 30 doesn't work but webcam_stream -d 1800 does, at least for me

**Comment by Noirtas** [comment]
Have same issue. Any fixes one might know of would be much appreciated!

**Comment by RoseDeSable** [comment]
I ran metaploit with the Kali package and also use the payload from this. I ran hostapd on my kali and connect a samsung tablet with android 8.0 directly with it. I'm using an android-https-reverse-meterpreter on the tablet.  Using the camera on the tab is no problem, but I receive a timeout, if the duration time of record_mic is over 15 secs. Could it be, that the video is transferred in mjpeg to the browser on my kali, so that no problems can exist, because the pictures are sended in separated https-connections ? In the case of the audio-data of the micro, I think, that after 15 secs the http-packet is full, so that meterpreter send it to me. After this action, the payload-handler on kali receives the end of the receive_mic command. Go I wrong ?

**Comment by RoseDeSable** [comment]
Hello, 
 I wrote a bash procedure, that plays wav-files in a directory in the order of their creation time. So I can set any duration time for record_mic. If I manually repeat the record_mic in the meterpreter I can continually play (with breakings) the downloaded wav-files. Additionally all the files are written into a single (big) file in their order of time. The procedure works in a loop, that must be finished by Ctrl-C. Optionally I only can write to the file without playing. 
 Now I must call a procedure in meterpreter, that calls record_mic in a loop. I want to write such a procedure and upload it into the memory for running. But I have no experience. Can someone give me an example ?

**Comment by gnu-like** [comment]
@RoseDeSable I use a script like you:
```
#!/bin/bash
ls -rt > lst.txt &&
dir=`pwd`/
sed -i "s/^/ ${dir//\//\\/}/" lst.txt &&
sed -i 's/^/file /' lst.txt &&
#name= echo "${PWD##*/}"
ffmpeg -f concat -safe 0 -i lst.txt -c copy output`echo ${PWD##*/}`.wav &&
#rm !(output`echo ${PWD##*/}`.wav) 
find . ! -name output`echo ${PWD##*/}`.wav -delete &&
find . -name output`echo ${PWD##*/}`.wav -exec mv {} /root/Music/wav/final \; &&
echo 'done'

```
I want to run automaticaly meterpreter command such as ```webcam_snap ```&```record_mic```&```rexploit``` #11582

**Comment by RoseDeSable** [comment]
Hello,
 the function "client.webcam.record_mic" in webcam.rb of stdapi seems to give no signs of live, when it runs. Correctly ? In the past some ftp-clients showed the same behaviour, when they downloaded large files through a dmz. The dmz gathered the data about minutes, but sent no heart-beats to the client. So the client expired with a timeout. 
 I believe, that the problem could be solved, if the function "client.webcam.record_mic" runs as a threat. The parent sends dummy signals in the time, when it waits of the end of the threat.

**Comment by Qarun-Qadir-Bissoondial** [comment]
Can confirm that once the recording time is set to 500 seconds or above, it immediately returns `webcam_audio_record: Operation failed: 1` but anything below 500, it starts recording and then times out with `Error running command record_mic: Rex::TimeoutError Operation timed out.`

Also on Android reverse_tcp connection

**Comment by RoseDeSable** [comment]
Hello,
 it doesn't only seem to be a problem with Android. Under Windows 10 I have the same problem. I'm using in both cases a reverse_https connection with meterpreter. The webcam_stream works together with the webbrowser. Here the program seems to read single photos (mjpeg) from the device like a webapp for cameras. For each photo a separate http-connection ! This functions. But reading a continuous stream from the microphone seems to be a problem. Because you can look a rtsp stream by vlc player through a vpn-tunnel, that is build by https over a http-proxy, I believe that the record-program must do something further for stream-handling.

Bye
Rose
