### ISSUE TITLE
Mozilla Caching

### ISSUE THREAD

**Issue by RootUp** [rapid7/metasploit-framework#9168]
Just taught if this is possible by any chance can we have module for the below issue which exists in mozilla, tried by best but couldn't do it, could some one please advise.

Steps to reproduce:
-Login to Gmail
-Logout of Gmail
-View the Gmail source, and you can see all mails in the last <script>-part
 (view-source:https://mail.google.com/mail/u/0)

Actual results:
You can see the Mails of the last out-logged person.

https://bugzilla.mozilla.org/show_bug.cgi?id=1318234
https://datarift.blogspot.in/2017/01/firefox-is-not-respecting-caching.html
Bug was officially reported by : Sebastian Grünwald, Dhiraj Mishra, Japz Divino.

Thnx!

**Comment by wwebb-r7** [comment]
The nature of this bug is a pretty poor fit for Metasploit, or any other exploitation framework for that matter.  There are also much more productive routes for accomplishing the same thing assuming you have access to the target's PC.  But we'd be talking about breaking into an online service, so we won't go there.
