### ISSUE TITLE
AutoRunScript hangs at processing

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#9266]
These should be simple use cases and should not require writing a custom script:

1. run a list of post modules upon new session
2. upgrade shell sessions to meterpreter, then run a list of post modules, upon new session

The obvious and traditional answer was to use `AutoRunScript` to load a resource file containing a list of new-line delimetered Metasploit commands to execute, such as `run post/multi/gather/env`.

`AutoRunScript` now appears to do not much of anything.

```
msf exploit(multi/handler) > set AutoRunScript asdf.rc
autorunscript => asdf.rc
msf exploit(multi/handler) > run
[*] Started reverse TCP handler on 10.1.1.197:1337 
[*] Transmitting intermediate stager...(106 bytes)
[*] Sending stage (849108 bytes) to 10.1.1.197
[*] Meterpreter session 13 opened (10.1.1.197:1337 -> 10.1.1.197:36665) at 2017-12-01 05:17:28 -0500
[*] Session ID 13 (10.1.1.197:1337 -> 10.1.1.197:36665) processing AutoRunScript 'asdf.rc'
^C
```

```
msf exploit(multi/handler) > cat asdf.rc
[*] exec: cat asdf.rc

run post/multi/gather/env
run post/linux/gather/checkvm
```

**Comment by busterb** [comment]
It seems that the root cause of this is Metasploit interprets anything with a name that doesn't match a post module or a builtin meterpreter script as an external meterpreter script, implying that it should be valid Ruby without <ruby> tags. That you don't get any useful output from this is an unfortunate side-effect of how meterpreter scripts work (which I _think_ is one reason why we deprecated them in the first place).

To make the intuitive thing of 'just running an RC script' work, we need to teach the code that executes AutoRunScript to tell the difference between these two things. My first thought is to have options that are not so vague that we have to guess what they are:

   AutoRunResourceScripts
   AutoRunMeterpreterScripts

Another approach could be that we only interpret these as old-school meterpreter scripts if they end in .rb. Otherwise they are interpreted as resource scripts in the context of the session. This prevents the 'if you change anything, it breaks 10+ years of documentation that says otherwise' issue we have with this sort of thing in general. Or, we could always interpret ".rc" files as resource scripts instead.

Open to ideas, I'll try to put up a PR for us to bikeshed on in a bit.

**Comment by wvu-r7** [comment]
And we should give it the option of running resource scripts, too.

#8704

**Comment by wvu-r7** [comment]
Oh, you literally said that. Tagged the issue. :P
