### ISSUE TITLE
Docker-Compose up not functionally starting the application container

### ISSUE THREAD

**Issue by silver0a1** [rapid7/metasploit-framework#9287]
Using docker-compose, this error shows up for the metasploit application container and the container dies. The db container stays up and able to connect.

`ms_1  | Rails Error: Unable to access log file. Please ensure that /home/msf/.msf4/logs/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /home/msf/.msf4/logs/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
/usr/local/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': Permission denied @ dir_s_mkdir - /home/msf/.msf4/logs (Errno::EACCES)
ms_1  | 	from /usr/local/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
ms_1  | 	from /usr/local/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
ms_1  | 	from /usr/local/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
ms_1  | 	from /usr/local/lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
ms_1  | 	from /usr/local/lib/ruby/2.4.0/fileutils.rb:191:in `each'
ms_1  | 	from /usr/local/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
ms_1  | 	from /usr/src/metasploit-framework/lib/msf/base/config.rb:367:in `init'
ms_1  | 	from /usr/src/metasploit-framework/lib/msf/base/config.rb:205:in `init'
ms_1  | 	from /usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:110:in `simplify'
ms_1  | 	from /usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:73:in `create'
ms_1  | 	from /usr/src/metasploit-framework/lib/msf/ui/console/driver.rb:74:in `initialize'
ms_1  | 	from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
ms_1  | 	from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
ms_1  | 	from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
ms_1  | 	from /usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
ms_1  | 	from ./msfconsole:48:in `<main>'
metasploitframework_ms_1 exited with code 1
`

**Comment by jmartin-r7** [comment]
As noted in the error, it looks like you already executed `msfconsole` with another user context that restricted access right for `~/.msf4/*` for the user that is starting the container. `~/.msf4/` gets mounted into the docker instance to allow users to persist configuration.

**Comment by FireFart** [comment]
@silver0a1 the folder `~/.msf4/` from your host is mounted inside the container on start and needs to be write bei UID 1000. So if you run docker-compose for example as root, this will fail because the container does not run as root

**Comment by FireFart** [comment]
BTW: I'm currently writing on the docker wiki page where I want to mention all this stuff but it's not ready yet

**Comment by FireFart** [comment]
If you run as a different user you can try the `--user UID` command line switch to docker-compose

**Comment by idan89** [comment]
I'm having the same problem as stated above. 
Everytime I try to run `./docker/bin/msfconsole` or `docker-compose run --rm --service-ports ms` I get:

`Rails Error: Unable to access log file. Please ensure that /home/msf/.msf4/logs/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /home/msf/.msf4/logs/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
/usr/local/lib/ruby/2.4.0/fileutils.rb:230:in 'mkdir': Permission denied @ dir_s_mkdir - /home/msf/.msf4/logs (Errno::EACCES)`

I have tried with a root user and a non root user. The result is the same.
Anyone?

Thanks!

**Comment by FireFart** [comment]
Whats your user id on the host system? Unfortunately it has to match the userid in the image (1000) because we are mounting ~/.msf4 inside and the image runs as a seperate user.

You can try to run `docker-compose run --rm -u root --service-ports ms`. This will start metasploit inside the container as root and thus should be able to modify whe mounted directory

**Comment by idan89** [comment]
That did the trick. Thank you.

**Comment by FireFart** [comment]
@idan89 @silver0a1 we did some changes to the latest docker image (https://github.com/rapid7/metasploit-framework/pull/9568). It should now work without the `--root` flag (just use the binstub)
