### ISSUE TITLE
win32-sshserver does not work any more

### ISSUE THREAD

**Issue by UMRnInside** [rapid7/metasploit-framework#9535]
## Steps to reproduce

How'd you do it?

1. Simply establish a meterpreter session
2. `run win32-sshserver`

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior

An OpenSSH Server should be deployed

## Current behavior

`[-] Could not execute win32-sshserver: Rex::Post::Meterpreter::RequestError stdapi_registry_open_key: Operation failed: The system cannot find the file specified.`

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

```
Framework: 4.16.36-dev
Console  : 4.16.36-dev
```

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [x] Kali package via apt

### OS

What OS are you running Metasploit on?

* Kali
* Debian GNU/Linux "buster"

**Comment by bcook-r7** [comment]
Note the line at the top of this script:

```
##
# WARNING: Metasploit no longer maintains or accepts meterpreter scripts.
# If you'd like to imporve this script, please try to port it as a post
# module instead. Thank you.
##
```

If you would like to convert this script to a post exploitation module, feel free.

This script looks like it could uses a lot of updates anyway, since it downloads an ancient OpenSSH installer . from http://updates.metasploit.com/data/win32-ssh/openssh.sfx, without using HTTPS. There are also probably better / more up-to-date ways to install openssh. In fact, that upstream file is gone entirely.

The issue you're probably hitting is this sanity check code:

```
root_key, base_key = client.sys.registry.splitkey("HKLM\\Software\\Cygnus\ Solutions")
open_key = client.sys.registry.open_key(root_key, base_key)
```

But since the openssh installer this script references doesn't even exist, I'd say our best course of action in the short term is to delete this script. It just can't work any more.

**Comment by busterb** [comment]
For a future module that does this in an up-to-date way, might look at https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

Now that Microsoft has a native OpenSSH port for Windows, some of the previous kludges hopefully go away.
