### ISSUE TITLE
Cpu usage increased 

### ISSUE THREAD

**Issue by gnu-like** [rapid7/metasploit-framework#9540]
after upgrading metasploit framework in kali the **cpu usage of ruby** increased

**Comment by bcook-r7** [comment]
There is no information provided to actually address anything here. Upgraded from what to what? What's normal?

Metasploit 4.x does rebuild the module cache on each restart, so that could be the issue you see. Metasploit 5 (not in Kali yet) removes the need for the in-memory module cache building altogether.
