### ISSUE TITLE
Can't load ms17_010_psexec.rb SOLVED

### ISSUE THREAD

**Issue by shuntawolf** [rapid7/metasploit-framework#9569]
## Steps to reproduce
You want to run the MS17_010_psexec.rb and your system won't do it, showing an error of "NameError uninitialized constant Msf::Exploit::Remote::SMB::Client::Psexec_MS17_010" 

How'd you do it?

1. You copy/place the ms17_010_psexec.rb into /root/.msf4/modules/exploits/windows/remote/ or some other /.msf4 location (.../windows/smb/ etc)
2. You launch msfconsole, and see the error listed above

## Expected behavior

Expect it to work with USE pathtofile/ms17_010_psexec  (eg: use windows/remote/ms17.... or windows/smb/ms17....)

## Current behavior

error shows up saying cant find the file, and immediately after launching msfconsole, you see the error fly by prior to the banner.

### Metasploit version

       =[ metasploit v4.16.34-dev                         ]
+ -- --=[ 1734 exploits - 992 auxiliary - 300 post        ]
+ -- --=[ 509 payloads - 40 encoders - 10 nops

### I installed Metasploit with:
Parrot distro with it installed

### OS
Linux parrot 4.14.0-parrot13-amd64 #1 SMP Parrot 4.14.13-1parrot13 (2018-01-21) x86_64 GNU/Linux

******************
I am an EXTREME newby with Linux, but a fast learner.  This worked for ME with my system.

To solve the issue, 
1) create/place the files ms17_010_psexec.rb into /root/.msf4/modules/exploits/windows/smb
2) create/place the file psexec_ms17_010.rb into /usr/share/metasploit-framework/lib/msf/core/exploit/smb/client
3) (as root) modify lib/msf/core/exploit/mixins.rb as shown:
require 'msf/core/exploit/smb/client/authenticated'
require 'msf/core/exploit/smb/client/local_paths'
require 'msf/core/exploit/smb/client/psexec'
require 'msf/core/exploit/smb/client/psexec_ms17_010' ##<<<< ADD THIS LINE
require 'msf/core/exploit/smb/client/remote_paths'
require 'msf/core/exploit/smb/server'
require 'msf/core/exploit/smb/server/share'

#9508 and #9523 both referenced this issue, and #9499 folks seemed to have an attitude about how to fix it when it is very obviously working for me.

Somewhere in all my adding and hunting I found ms17_010_command.rb as well, and at one point used same type of procedure to make it work as well.  It goes into /root/.msf4/modules/auxiliary/admin/smb 

msf > use auxiliary/admin/smb/ms17_010_command
msf auxiliary(admin/smb/ms17_010_command) > use windows/smb/ms17_010_psexec
msf exploit(windows/smb/ms17_010_psexec) > 

Attached is the psexec_ms17_010.rb file in .txt form, rename so you drop the .txt and place as instructed above and it SHOULD all work for you.

Hope this helps
[psexec_ms17_010.rb.txt](https://github.com/rapid7/metasploit-framework/files/1732553/psexec_ms17_010.rb.txt)

**Comment by busterb** [comment]
Or just grab the latest nightly build:

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

**Comment by busterb** [comment]
Some modules work standalone. Sometimes they require additional library support from metasploit-framework, and cannot run standalone. This is one of those cases.

While these instructions might work specifically for you and the version of Metasploit that Parrot happened to have last shipped, the files that would need to be patched might be completely different for another OS, version, installation method, etc.

So, we recommend if you want the latest code, just run the latest code as a whole. We provide an easy way to do this specifically because people always want the latest exploits. If you can't do that yourself, ask your distro maintainer to update their Metasploit package. Kali Linux updates once a week. Rapid7 builds new packages daily. Your distro may have a different schedule.

Patching together a mixture of code from different versions of Metasploit might work sometimes, but it's not something we would recommend, especially for a newbie.
