### ISSUE TITLE
Metasploit got stuck ParrotSec OS

### ISSUE THREAD

**Issue by JohnEric100** [rapid7/metasploit-framework#9597]
I'm using ParrotSec OS on my laptop and when i run metasploit its just take a long time approximately 30mins and sometimes not open..
Just > Starting  Metasploit Framework console...\
# Screenshot
![screenshot from 2018-02-21 09-30-03](https://user-images.githubusercontent.com/25101476/36463172-e67eae70-16e9-11e8-8ecc-9874b3f69b50.png)

Please guide me how to fix it?
I will appreciate for any help.
Thanks

**Comment by busterb** [comment]
Try https://community.parrotsec.org/c/support

ParrotSec maintains its own Metasploit package, so they are probably the best to ask for help with it. If you want further help (e.g. the ParrotSec folks aren't able to figure it out), please answer the questions that were in the 'New Issue' template, since a screenshot of the console obviously won't help us debug it.

**Comment by busterb** [comment]
It would be interesting to know if the nightly installer packages work on ParrotSec though: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
