### ISSUE TITLE
Feature request: add meta-shell commands

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#9630]
> Shell sessions typically expose a direct connection to a remote shell, but are lacking a number of nice features such as the ability to stop a remote command, background a job, or to even lock the session. This project would implement some pre-processing hooks to shell sessions so that job control could be added by default (allowing backgrounding of commands), meta-commands like 'background' and 'sessions' could be added as well.

https://github.com/rapid7/metasploit-framework/wiki/GSoC-2018-Project-Ideas#add-meta-shell-commands

The idea here is to abstract advanced functionality away from the payload and place it in the console, providing the user with an "enriched" shell with a mostly seamless experience.

**Comment by sempervictus** [comment]
@kernelsmith: any chance some of your old Great Shell Overhaul Effort might see the light of day for this feature?

**Comment by kernelsmith** [comment]
@sempervictus I haven't been involved with this issue, but I was reminded of this work after seeing "Metasploit without Metasploit" presentation at BSides by Adam and Jonathan and thought I should restart my "MESH" efforts

**Comment by kernelsmith** [comment]
FWIW, my concept for a similar idea that I called `MESH` (aka Metasploit-Extended SHell) (tm) kernelsmith LOL, on which I got reasonably far, was the following:

<img width="823" alt="mesh_arch" src="https://user-images.githubusercontent.com/620129/37636307-5dbe09a0-2bcf-11e8-8846-d69065efb5f6.png">

1. Shell aliases relay all known (or supported) msfconsole commands to a ruby "binary" called mesh.
2. Simple config/rc file to decide how to handle msfconsole commands that collide with existing shell commands, on a global basis, like all msfconsole commands take precedence over shell, or the opposite, with exceptions to the global listed individually
3. If msfrpcd isn't running the first time mesh is called, it would start it w/default (or specified options).  Mesh could also be called stand-alone like:

```Ruby
class OptsMesh
	#
	# Return a hash describing the options.
	#
	def self.parse(args)
		options = {
			'DeferModuleLoads' => true
		}

		opts = OptionParser.new do |opts|
			opts.banner = "Usage: mesh [start|stop|start]"

			opts.separator ""
			opts.separator "Specific options:"

			opts.on("start", "start [opts]", "Start mesh w/default or specified options") do |o|
				options['Start'] ||= []
				options['Start'] << o
			end

			opts.on("stop", "stop", "Stop mesh and optionally, maybe, unhook shell aliases") do
				options['Stop'] = true
			end

			opts.on("status", "status", "Display mesh status") do
				options['Status'] = true
			end
        # ...

# it would have a method like the following:
def start_msfrpcd(opts = {})
	require 'rex/parser/arguments'
	require 'rex/text'
	require 'timeout'

	default_opts = {
		'ServerHost' => "127.0.0.1",
		'ServerPort' => 55552, # use 55552 so we don't conflict with other msfrpc instances
		'ServerType' => 'Msg',
		'User'       => 'msf',
		'SSL'        => true,
		'URI'        => '', #todo
		'DisableDatabase' => false,
	}
	foreground = false
        # ...

# And later, something like:

# when no password is specified, we generate our own to avoid a passwordless msfrpcd instance
def generate_random_password(min = 25, max = 30)
	Rex::Text.rand_text_alphanumeric(rand(max-min)+min)
end

# instantiate msfrpcd if it's not already running
status = @msfrpcd_thread ? @msfrpcd_thread.status : "none" # status can return a string, nil, or false

# @todo, the msfrpcd instance may not be from this code, we should also check if we can connect
unless (status.to_s =~ /^(run|sleep)$/) # run/sleep is good, otherwise need new msfrpcd
	# let's make sure the old thread is dead dead as we are reusing the port
	@msfrpcd_thread.kill if status # pretty much this just affects the "aborting" status
	Timeout::timeout(10) do
		begin
			while @msfrpcd_thread.status {true} # just wait
		rescue Timeout::Error
			puts "[!]  The old msfrpcd instance is unresponsive and won't die."
			puts "[!]  You need to forcibly kill it, wait for it to die, or restart on a new port"
			raise
		end
	end
	# if the thread doesn't exist, or is peacefully dead, let's start another (or for the first time)
	@msfrpcd_thread, token = start_msfrpcd(opts)
end
```
4.  Originally, talking with HD about this a long time ago, the best option for communication amongst the parts seemed to be a FIFO, so we could talk directly to msfconsole.  I just did a `mknod -p` kinda thing.  It mostly worked, had some kinks with reusing them between runs that I never had a chance to work on, they didn't seem like they would be hard to solve.  This obviously meant that Windows was not supported, which didn't bother me, especially since Windows doesn't have fork either, plus aliasing the shell is doable but painful etc.  However, it also seemed like using msfrpcd would scale better, tho it's more work translating msfconsole-like commands into msfrpc api calls and back again, and make it easier to get status and share state etc.
5.  Aliases would look like `alias sessions=mesh sessions` effectively
6.  Mesh would translate `sessions` into the appropriate msfrpc API call(s) (assuming you go the msfrpcd route)
7.  Mesh would format the returned info and display it

It would look something like:

```Shell
root@kali:~# sessions -l

Active sessions
===============

No active sessions.

root@kali:~# use windows/smb/psexec

# Nice touch here would be to add to the PS1 prompt like we often do w/git branch info like:
root@kali:~ (exploit/windows/smb/psexec)#
# so a default, mesh enabled PS1 might look like:
root@kali:~ (msf)# 
# or
root@kali:~ (mesh)# 
# I started writing a zsh plugin for this and tab completing mesh/msf commands, but didn't get far

# back to the point
root@kali:~# show options
Module options (exploit/windows/smb/psexec):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   RHOST                                  yes       The target address
   # ...SNIP...
   SMBUser                                no        The username to authenticate as

Exploit target:

   Id  Name
   --  ----
   0   Automatic
```

Anyways, that's about all I can remember/drag up at the moment.

**Comment by kernelsmith** [comment]
I also had a quick script I would run to yank out all the `def cmd_*` lines and parse them so I could check if new commands had been added that I didn't have coverage for etc.  Wherever that script is now, is where the rest of my code/notes are.  I know it's around, so if you want me to find it, let me know, or if this whole scheme is crap/outdated now, just say so.

**Comment by busterb** [comment]
Thanks @kernelsmith! This is a little different than the feature being described in this ticket, which is around making interaction with shell sessions better. There is definitely room for both ideas, and what you are proposing here sounds great.

**Comment by kernelsmith** [comment]
Ack @busterb. I blame @sempervictus for dragging me into this ;)  Upside, at least I finally documented it somewhere besides my one random google slides presentation.

**Comment by sempervictus** [comment]
That diagram is worth the blame.
The idea seems similar in that its an overlay shell atop the local or remote context. Precedence and env jump out as potential hurdles, but at least in the local version that seems to have a formative architecture addressing those.
Just call it the one ring and turn MSF into a giant mux terminal for all the things ;-).

**Comment by wvu-r7** [comment]
#9630
