### ISSUE TITLE
windows/x64/shell_reverse_tcp DOESN'T RUN AUTORUNSCRIPT

### ISSUE THREAD

**Issue by PentesterMalwareAnalizsing** [rapid7/metasploit-framework#9680]
## Steps to reproduce

Hi Everyon, Im trying to Run a Script from "shell_reverse_tcp", But Apparently every time that the console pups Up the script doesnt run, this is what I have.

Expected behavior

Script  (simple but it doesnt work) (the problema still happening Even if I change the extension of the script to sh)

![image](https://user-images.githubusercontent.com/18033928/37077207-ed84e194-21a7-11e8-907e-55a2244744b8.png)

Configuration of the multi/handler

![image](https://user-images.githubusercontent.com/18033928/37077696-103f71f2-21aa-11e8-9746-3fd4fd928d60.png)

This is what I get

![image](https://user-images.githubusercontent.com/18033928/37077287-522bf47a-21a8-11e8-9858-509993a4efbe.png)
![image](https://user-images.githubusercontent.com/18033928/37077797-83a2734c-21aa-11e8-8733-39c2f513a874.png)

whats over the sessions is created but the script is not executed, So  I did the same but using a meterpreter shell  And this is what i get

configuration of multi/handler

![image](https://user-images.githubusercontent.com/18033928/37077833-b0412560-21aa-11e8-9054-3cfa2ce0e145.png)

exploit -j

![image](https://user-images.githubusercontent.com/18033928/37077498-4795b018-21a9-11e8-96a9-3056ed254822.png)

so it works fine, script executed

so Why this AutorunScript Cant run on  windows/x64/shell_reverse_tcp but it works fine on a meterpreter shell.

is it just work with meterperter shell? if is not , what am I doing wrong?
Ty cheese

Environment:

Kali Linux running on VMWARE 

OS windows10 pro 
windows 10 pro (victim) (AVs Down)

**Comment by OmarCuadrado** [comment]
@roccomuso

**Comment by void-in** [comment]
That is expected. The first command mkdir was successfully executed on the target machine. The second command (and subsequent command) failed because there is no nano editor on the Windows machine so no users file was created. I fail to understand what the problem is. AutoRunScript run the commands on the meterpreter session opened on the target machine.

**Comment by jmartin-r7** [comment]
Agree with @void-in closing as learning opportunity.

**Comment by wvu-r7** [comment]
It has come to my attention that the user's question was not actually answered. This isn't a problem with the script not doing what it's supposed to do. This is a problem with the script not being found when it supposedly should be.

The script *isn't* found because the user is using it under the wrong session type. Meterpreter scripts (deprecated) can't be used with normal shells. That much is a usage error. If the user had used a script designed for normal shells, it would have worked in the first test case.

I'll fix this to raise a better error. Reopening for now. Thanks for the comments, everyone.

**Comment by wvu-r7** [comment]
As @void-in has already stated, even if the script runs, it won't succeed, since the commands are incorrect for the platform. That is a secondary problem and not what the user originally asked.

**Comment by wvu-r7** [comment]
@OmarCuadrado:

```
wvu@hiigara:~/metasploit-framework:bug/script$ search multi_console_command
./scripts/meterpreter/multi_console_command.rb
wvu@hiigara:~/metasploit-framework:bug/script$
```

As you can see, it's a Meterpreter script. The output you've shown is expected behavior, but it's certainly not clear why.

1. You will have to use the script with Meterpreter only
2. You need to change the commands in your resource script to be Windows-appropriate

Thanks. I'll close this when I've fixed the error.

**Comment by wvu-r7** [comment]
Oh, and I think if there's any confusion here, it's because there are two kinds of scripts: "session" scripts and resource scripts (also simply called files).

A session script is usually either `shell` or `meterpreter` in type. A resource script is for automating the console (`msfconsole`).

The Meterpreter session script is failing for the shell but working for Meterpreter - expected. The resource script is failing for Meterpreter because Unix commands don't work on Windows (some do!).
