### ISSUE TITLE
find: unkown predicate '-y'

### ISSUE THREAD

**Issue by 0cx23** [rapid7/metasploit-framework#9725]
I am using kali-linux 2018.1 x64 I recently updated metasploit-framework from ver 4.16.43 to 4.16.45 and i got this message (find: unkown predicate '-y') when i start (msfconsole)

**Comment by busterb** [comment]
can you show exactly how you launched msfconsole and the exact output?

**Comment by busterb** [comment]
Also, are you using the stock Kali package, or the omnibus package?

**Comment by 0cx23** [comment]
[<a href="https://ibb.co/dorDpc"><img src="https://preview.ibb.co/k8f69c/1.png" alt="1" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload image</a><br />
I am sorry bro I am newbie on kali-linux , can you tell me how I check if i am using stock Kali package, or the omnibus package ?

**Comment by kernelsmith** [comment]
@0cx23 if you didn't install the omnibus, and are just using stock Kali, then you're using the Kali package

**Comment by kernelsmith** [comment]
@0cx23 I don't think msfconsole calls the `find` shell command (as indicated by your error), so I would run `which msfconsole` and `alias msfconsole` and `msfconsole -v` and put the outputs in here (they should each have one line of output)

**Comment by busterb** [comment]
Just to be sure, type 'dpkg -l |grep metasploit' and show the output. I agree this doesn't look like an actual issue with msfconsole but something with Kali perhaps, so I'm going to close this issue.

You may just need to actually do a full update on Kali, e.g. 'apt update; apt dist-upgrade' since this is possibly a side-effect of other packages being out of date.
