### ISSUE TITLE
Better handling of RHOSTS validation, experience and messaging

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#9764]
Today when you specify multiple targets in `RHOSTS`, by any method including `file://`, if any of the targets provided in there are invalid, the end user is not informed which target is invalid or why.  Furthermore, all of the targets provided in `RHOSTS` must "validate" before any module will run, but it could be argued that there are use cases where it is ok if a subset don't validate, and that the module should run on the targets that *do* validate and warn/error on the ones that don't.

```
msf5 auxiliary(scanner/http/http_version) > echo this.does.not.exist > /tmp/hosts
[*] exec: echo this.does.not.exist > /tmp/hosts

msf5 auxiliary(scanner/http/http_version) > echo www.google.com  >> /tmp/hosts
[*] exec: echo www.google.com  >> /tmp/hosts

msf5 auxiliary(scanner/http/http_version) > cat /tmp/hosts
[*] exec: cat /tmp/hosts

this.does.not.exist
www.google.com
msf5 auxiliary(scanner/http/http_version) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.
msf5 auxiliary(scanner/http/http_version) > set RHOSTS www.google.cm this.does.not.exist
RHOSTS => www.google.cm this.does.not.exist
msf5 auxiliary(scanner/http/http_version) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.
echo 1.2.3.4.5 > /tmp/hosts
[*] exec: echo 1.2.3.4.5 > /tmp/hosts

msf5 auxiliary(scanner/http/http_version) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.
```

Particularly when targeting a large number of hosts, it would be excellent if it was made more obvious which targets were invalid and why, and, perhaps optionally, allow the module to run against any targets that were validated and skip those that didn't.

**Comment by kkirsche** [comment]
This looks like it may need adjustments to rex-socket's RangeWalker, since that's where the next_ip and validation is occurring. It returns a boolean `false` if the next address is not valid, but doesn't provide what the address was. 

So the validation error seems to be coming from, in this POC at least, https://github.com/rapid7/rex-socket/blob/master/lib/rex/socket/range_walker.rb#L145

Not sure where the raise `OptionValidateError` is coming from based on that failure though since this doesn't give any stack trace during the validation failure
